Repository zooniverse/front-end-monorepo, pull requests merged in 2018-12, with the labels that each got.

#307 Updating several packages
  packages/app-project/package-lock.json
  packages/app-project/package.json
  packages/lib-auth/package-lock.json
  packages/lib-auth/package.json
  packages/lib-classifier/package-lock.json
  packages/lib-classifier/package.json
  packages/lib-grommet-theme/.babelrc
  packages/lib-grommet-theme/package-lock.json
  packages/lib-grommet-theme/package.json
  packages/lib-grommet-theme/src/index.js
  packages/lib-react-components/package-lock.json
  packages/lib-react-components/package.json
Labels: dependencies

#306 Update input styles
  packages/lib-classifier/package-lock.json
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskInputField/TaskInputField.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskInputField/TaskInputField.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.js
Labels: enhancement

#289 Clear user project preferences on logout
  packages/lib-auth/src/controllers/oauth/createOAuthClient.js
  packages/lib-auth/src/models/oauth/UserStore.js
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore.js
  packages/lib-classifier/src/store/utils/getBearerToken.js
  packages/lib-classifier/src/store/utils/index.js
Labels: enhancement

#328 Add support for jsonb default for steps
  packages/lib-classifier/src/store/Workflow.js
Labels: bug

#330 Use `id` prop instead of autogenerating ids (which leads to SSR errors)
  packages/lib-react-components/src/ZooFooter/ZooFooter.js
  packages/lib-react-components/src/ZooFooter/components/ZooniverseLogotype/README.md
  packages/lib-react-components/src/ZooFooter/components/ZooniverseLogotype/SVGContent.js
  packages/lib-react-components/src/ZooFooter/components/ZooniverseLogotype/ZooniverseLogotype.js
  packages/lib-react-components/src/ZooFooter/components/ZooniverseLogotype/ZooniverseLogotype.spec.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
  packages/lib-react-components/src/ZooHeader/components/ZooniverseLogo/README.md
  packages/lib-react-components/src/ZooHeader/components/ZooniverseLogo/ZooniverseLogo.js
  packages/lib-react-components/src/ZooHeader/components/ZooniverseLogo/ZooniverseLogo.spec.js
Labels: bug
