Repository zooniverse/front-end-monorepo, pull requests merged in 2018-11, with the labels that each got.

#235 Fix auth classifier
  packages/lib-auth/package-lock.json
  packages/lib-auth/package.json
  packages/lib-classifier/.babelrc
  packages/lib-classifier/package-lock.json
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/Layout/Layout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/Layout.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
  packages/lib-classifier/test/mocha.opts
  packages/lib-classifier/webpack.dev.js
Labels: dependencies

#250 Fix LCV not loading next subject
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/DrawingTask.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/helpers/getTaskComponent.js
Labels: bug

#252 [WIP] Classifier auth
  packages/lib-auth/dev/components/App/App.js
  packages/lib-auth/package-lock.json
  packages/lib-auth/package.json
  packages/lib-auth/src/controllers/oauth/createOAuthClient.js
  packages/lib-auth/src/models/oauth/CredentialsStore.js
  packages/lib-auth/src/models/oauth/CredentialsStore.spec.js
  packages/lib-auth/src/models/oauth/OAuthStore.js
  packages/lib-auth/src/models/oauth/UserResource.js
  packages/lib-auth/src/models/oauth/UserResource.spec.js
  packages/lib-auth/src/models/oauth/UserStore.js
  packages/lib-auth/src/models/oauth/UserStore.spec.js
  packages/lib-auth/src/models/oauth/helpers/clearTimer.js
  packages/lib-auth/src/models/oauth/helpers/setTimer.js
  packages/lib-auth/src/views/oauth/components/shared/Countdown/Countdown.js
  packages/lib-auth/test/enzyme-setup.js
  packages/lib-auth/test/mocha.opts
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/store/ResourceStore.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/UserProjectPreferences.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore.js
  packages/lib-classifier/src/store/Workflow.js
  packages/lib-classifier/src/store/WorkflowStore.js
Labels: enhancement

#219 Classifier - TESS Light Curve Viewer - Axis Scales and Single-Axis Zoom/Pan
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setPointStyle.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setPointStyle.spec.js
Labels: enhancement

#232 Add "Finished for the day" component to project app
  packages/app-project/.babelrc
  packages/app-project/components/ClassifyPage/ClassifyPage.js
  packages/app-project/components/ClassifyPage/ClassifyPage.spec.js
  packages/app-project/components/ClassifyPage/components/ClassifyBox/ClassifyBox.js
  packages/app-project/components/ClassifyPage/components/ClassifyBox/ClassifyBox.spec.js
  packages/app-project/components/ClassifyPage/components/ClassifyBox/README.md
  packages/app-project/components/ClassifyPage/components/ClassifyBox/index.js
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.js
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.spec.js
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.js
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.spec.js
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/components/Placeholder/Placeholder.js
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/components/Placeholder/Placeholder.spec.js
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/components/Placeholder/index.js
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/index.js
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/locales/en.json
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/index.js
  packages/app-project/components/ClassifyPage/components/FinishedForTheDay/locales/en.json
  packages/app-project/components/ClassifyPage/index.js
  packages/app-project/components/Head/Head.spec.js
  packages/app-project/components/Navigation/Navigation.spec.js
  packages/app-project/package-lock.json
  packages/app-project/package.json
  packages/app-project/pages/Classify.js
  packages/app-project/pages/_app.js
  packages/app-project/server/server.js
  packages/app-project/stores/Project.js
  packages/app-project/stores/Project.spec.js
  packages/app-project/stores/initStore.spec.js
  packages/app-project/test/mocha.opts
Labels: enhancement

#248 Add Statistics box to project app
  packages/app-project/components/ClassifyPage/ClassifyPage.js
  packages/app-project/components/ClassifyPage/ClassifyPage.spec.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/ProjectStatistics.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/ProjectStatistics.spec.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/ProjectStatisticsContainer.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/ProjectStatisticsContainer.spec.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/CompletionBar.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/CompletionBar.spec.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/CompletionBarContainer.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/CompletionBarContainer.spec.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/d3/addBackgroundLayer.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/d3/createBar.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/d3/createLabel.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/CompletionBar/index.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/MainGrid/MainGrid.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/MainGrid/MainGrid.spec.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/MainGrid/index.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/Stat.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/Stat.spec.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/components/AnimatedNumber/AnimatedNumber.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/components/AnimatedNumber/AnimatedNumber.spec.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/components/AnimatedNumber/index.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Stat/index.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Subtitle/Subtitle.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Subtitle/Subtitle.spec.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/components/Subtitle/index.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/index.js
  packages/app-project/components/ClassifyPage/components/ProjectStatistics/locales/en.json
  packages/app-project/package.json
  packages/app-project/stores/Project.js
Labels: enhancement

#273 Bootstrap script, new component generators
  README.md
  bin/bootstrap.sh
  plop/generators/component.js
  plop/templates/component/Component.spec.js.hbs
  plop/templates/component/Container.spec.js.hbs
  plop/templates/component/MSTContainer.js.hbs
  plop/templates/component/MSTContainer.spec.js.hbs
Labels: bug, enhancement

#268 Auth environment fix and login/logout callback support
  packages/lib-auth/dev/components/App/App.js
  packages/lib-auth/package.json
  packages/lib-auth/src/controllers/oauth/createOAuthClient.js
  packages/lib-auth/src/models/oauth/CredentialsStore.js
  packages/lib-auth/src/models/oauth/CredentialsStore.spec.js
  packages/lib-auth/src/models/oauth/UserResource.js
  packages/lib-auth/src/models/oauth/UserStore.js
  packages/lib-auth/webpack.dev.js
  packages/lib-auth/webpack.dist.js
Labels: enhancement

#275 Finished header
  packages/app-project/pages/_app.js
  packages/lib-react-components/.storybook/addons.js
  packages/lib-react-components/.storybook/config.js
  packages/lib-react-components/package-lock.json
  packages/lib-react-components/package.json
  packages/lib-react-components/src/ZooHeader/README.md
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.spec.js
  packages/lib-react-components/src/ZooHeader/ZooHeaderContainer.js
  packages/lib-react-components/src/ZooHeader/ZooHeaderContainer.spec.js
  packages/lib-react-components/src/ZooHeader/components/MainNavList/MainNavList.js
  packages/lib-react-components/src/ZooHeader/components/MainNavList/MainNavList.spec.js
  packages/lib-react-components/src/ZooHeader/components/MainNavList/index.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMainNavMenu/NarrowMainNavMenu.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMainNavMenu/NarrowMainNavMenu.spec.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMainNavMenu/index.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenu/NarrowMenu.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenu/NarrowMenu.spec.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenu/index.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenuNavListItem/NarrowMenuNavListItem.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenuNavListItem/NarrowMenuNavListItem.spec.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenuNavListItem/index.js
  packages/lib-react-components/src/ZooHeader/components/NavListItem/NavListItem.js
  packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.spec.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/SignedOutUserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/SignedOutUserNavigation.spec.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/components/NavButton/NavButton.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/components/NavButton/NavButton.spec.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/components/NavButton/index.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/index.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/locales/en.json
  packages/lib-react-components/src/ZooHeader/components/UserMenu/UserMenu.js
  packages/lib-react-components/src/ZooHeader/components/UserMenu/components/UserNavListItem/UserNavListItem.spec.js
  packages/lib-react-components/src/ZooHeader/components/UserMenu/components/UserNavListItem/index.js
  packages/lib-react-components/src/ZooHeader/helpers/getHost.js
  packages/lib-react-components/src/ZooHeader/helpers/index.js
  packages/lib-react-components/src/ZooHeader/helpers/navListItems.js
  packages/lib-react-components/src/ZooHeader/index.js
  packages/lib-react-components/src/ZooHeader/locales/en.json
  packages/lib-react-components/stories/AdminCheckbox.stories.js
  packages/lib-react-components/stories/Modal.stories.js
  packages/lib-react-components/stories/SpacedText.stories.js
  packages/lib-react-components/stories/Tooltip.stories.js
  packages/lib-react-components/stories/ZooFooter.stories.js
  packages/lib-react-components/stories/ZooHeader.stories.js
  packages/lib-react-components/stories/lib/backgrounds.js
Labels: enhancement
