Repository zooniverse/front-end-monorepo, pull requests merged in 2018-10, with the labels that each got.

#131 Add jenkinsfile for tests
  .dockerignore
  Dockerfile
  Jenkinsfile
  README.md
Labels: enhancement

#170 Add Rxjs and an interaction layer
  packages/lib-classifier/package-lock.json
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/index.js
  packages/lib-classifier/src/helpers/asyncStates/asyncStates.js
  packages/lib-classifier/src/helpers/asyncStates/asyncStates.spec.js
  packages/lib-classifier/src/helpers/asyncStates/index.js
  packages/lib-classifier/src/store/DrawingStore.js
  packages/lib-classifier/src/store/DrawingStore.spec.js
  packages/lib-classifier/src/store/ResourceStore.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/RootStore.spec.js
  packages/lib-classifier/src/store/SubjectStore.js
Labels: enhancement

#195 Update grommet, grommet-icons, and styled-components
  packages/app-project/package-lock.json
  packages/app-project/package.json
  packages/lib-auth/dev/components/App/App.js
  packages/lib-auth/package-lock.json
  packages/lib-auth/package.json
  packages/lib-classifier/package-lock.json
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.js
  packages/lib-grommet-theme/package.json
  packages/lib-grommet-theme/src/index.js
  packages/lib-grommet-theme/src/light.js
  packages/lib-react-components/.storybook/config.js
  packages/lib-react-components/dist/main.js
  packages/lib-react-components/package-lock.json
  packages/lib-react-components/package.json
  packages/lib-react-components/src/Modal/Modal.js
  packages/lib-react-components/src/Modal/WithLayer.js
  packages/lib-react-components/src/Modal/components/CloseIcon/CloseIcon.js
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js
  packages/lib-react-components/src/SpacedText/__snapshots__/SpacedText.spec.js.mocha-snapshot
  packages/lib-react-components/src/ZooFooter/ZooFooter.js
  packages/lib-react-components/src/ZooFooter/components/AdminCheckbox/AdminCheckbox.js
  packages/lib-react-components/src/ZooFooter/components/AdminCheckbox/__snapshots__/AdminCheckbox.spec.js.mocha-snapshot
  packages/lib-react-components/src/ZooFooter/components/NavListItem/__snapshots__/NavListItem.spec.js.mocha-snapshot
  packages/lib-react-components/stories/AdminCheckbox.stories.js
  packages/lib-react-components/stories/Modal.stories.js
  packages/lib-react-components/stories/SpacedText.stories.js
  packages/lib-react-components/stories/ZooFooter.stories.js
Labels: dependencies

#199 Submit classification
  packages/lib-async-states/src/async-states.js
  packages/lib-async-states/src/async-states.spec.js
  packages/lib-classifier/package-lock.json
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskInputField/TaskInputField.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.js
  packages/lib-classifier/src/store/Classification.js
  packages/lib-classifier/src/store/Classification.spec.js
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/Project.js
  packages/lib-classifier/src/store/ProjectStore.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/Subject.js
  packages/lib-classifier/src/store/SubjectStore.js
  packages/lib-classifier/src/store/Workflow.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStore.js
  packages/lib-classifier/src/store/utils/convertMapToArray.js
  packages/lib-classifier/src/store/utils/convertMapToArray.spec.js
  packages/lib-classifier/src/store/utils/index.js
  packages/lib-classifier/src/store/utils/session.js
  packages/lib-classifier/src/store/utils/session.spec.js
  packages/lib-classifier/test/enzyme-setup.js
Labels: enhancement

#134 Add proposed adr-7
  docs/arch/README.md
  docs/arch/adr-7.md
Labels: documentation, question

#206 Use `nock` instead of `superagent-mock`
  packages/lib-panoptes-js/package-lock.json
  packages/lib-panoptes-js/package.json
  packages/lib-panoptes-js/src/panoptes.spec.js
  packages/lib-panoptes-js/src/resources/projects/commonRequests.spec.js
  packages/lib-panoptes-js/src/resources/projects/rest.spec.js
  packages/lib-panoptes-js/src/resources/subjects/commonRequests.spec.js
  packages/lib-panoptes-js/src/resources/subjects/rest.spec.js
  packages/lib-panoptes-js/src/resources/tutorials/commonRequests.js
  packages/lib-panoptes-js/src/resources/tutorials/commonRequests.spec.js
  packages/lib-panoptes-js/src/resources/tutorials/rest.spec.js
  packages/lib-panoptes-js/test/mocha.opts
Labels: bug

#183 Add troubleshooting guide for devs
  README.md
  docs/troubleshooting-guide.md
Labels: documentation

#208 Add footer
  packages/app-project/package.json
  packages/app-project/pages/_app.js
  packages/lib-react-components/src/ZooFooter/components/NavListItem/NavListItem.js
Labels: enhancement
