Repository zooniverse/front-end-monorepo, pull requests merged in 2019-10, with the labels that each got.

#1131 Add recently classified subjects to the Classify page
  packages/app-project/package.json
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.spec.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.stories.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjectsContainer.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjectsContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/index.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/locales/en.json
  packages/app-project/src/shared/components/CollectionsModal/CollectionsModal.js
  packages/app-project/src/shared/components/CollectionsModal/CollectionsModal.spec.js
  packages/app-project/src/shared/components/CollectionsModal/CollectionsModalContainer.js
  packages/app-project/src/shared/components/CollectionsModal/CollectionsModalContainer.spec.js
  packages/app-project/src/shared/components/CollectionsModal/components/CreateCollection/CreateCollection.js
  packages/app-project/src/shared/components/CollectionsModal/components/CreateCollection/CreateCollection.spec.js
  packages/app-project/src/shared/components/CollectionsModal/components/CreateCollection/index.js
  packages/app-project/src/shared/components/CollectionsModal/components/CreateCollection/locales/en.json
  packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.js
  packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.spec.js
  packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/index.js
  packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/locales/en.json
  packages/app-project/src/shared/components/CollectionsModal/index.js
  packages/app-project/src/shared/components/CollectionsModal/locales/en.json
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.spec.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.stories.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsIcon.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsIcon.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/index.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/locales/en.json
  packages/app-project/src/shared/components/SubjectPreview/components/FavouritesButton/FavouritesButton.js
  packages/app-project/src/shared/components/SubjectPreview/components/FavouritesButton/FavouritesButton.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/FavouritesButton/HeartIcon.js
  packages/app-project/src/shared/components/SubjectPreview/components/FavouritesButton/HeartIcon.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/FavouritesButton/index.js
  packages/app-project/src/shared/components/SubjectPreview/components/FavouritesButton/locales/en-GB.json
  packages/app-project/src/shared/components/SubjectPreview/components/FavouritesButton/locales/en-US.json
  packages/app-project/src/shared/components/SubjectPreview/components/MetaToolsButton/MetaToolsButton.js
  packages/app-project/src/shared/components/SubjectPreview/components/MetaToolsButton/MetaToolsButton.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/MetaToolsButton/index.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkIcon.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkIcon.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkLink.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkLink.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/index.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/locales/en.json
  packages/app-project/src/shared/components/SubjectPreview/components/index.js
  packages/app-project/src/shared/components/SubjectPreview/index.js
  packages/app-project/src/shared/components/SubjectPreview/locales/en.json
  packages/app-project/static/subject-placeholder.png
  packages/app-project/stores/Recents.js
Labels: enhancement

#1188 Add focus and hover styles to workflow links
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/theme.js
Labels: accessibility, design

#1189 Make lower footer responsive
  packages/lib-react-components/src/ZooFooter/components/PolicyLinkSection/PolicyLinkSection.js
Labels: bug, design

#1186 Page-level layout fixes
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.js
Labels: design

#1109 Add a multi-stage Docker build for production apps
  .dockerignore
  Dockerfile
  Jenkinsfile
  README.md
  bin/bootstrap.sh
  docker-compose.yml
  packages/app-content-pages/Dockerfile
  packages/app-content-pages/README.md
  packages/app-content-pages/docker-compose.yml
  packages/app-project/Dockerfile
  packages/app-project/docker-compose.yml
  packages/lib-classifier/docker-compose.yml
Labels: dx

#1205 Update SubjectPreview stories
  packages/app-project/.storybook/lib/backgrounds.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.stories.js
Labels: enhancement

#1184 Add a story for the recent subjects carousel
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjects.stories.js
Labels: design, dx

#1201 CloseButton
  packages/lib-react-components/src/CloseButton/CloseButton.js
  packages/lib-react-components/src/CloseButton/CloseButton.spec.js
  packages/lib-react-components/src/CloseButton/CloseButton.stories.js
  packages/lib-react-components/src/CloseButton/README.md
  packages/lib-react-components/src/CloseButton/components/CloseIcon/CloseIcon.js
  packages/lib-react-components/src/CloseButton/components/CloseIcon/index.js
  packages/lib-react-components/src/CloseButton/index.js
  packages/lib-react-components/src/CloseButton/locales/en.json
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js
  packages/lib-react-components/src/index.js
Labels: enhancement

#1204 Add a gradient background to workflow links
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/locales/en.json
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/theme.js
Labels: design, enhancement

#1056 React vx bars
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/mockData.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/Background.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/Background.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Chart/Chart.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Chart/Chart.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Chart/index.js
  yarn.lock
Labels: discussion, enhancement, experiment

#1210 Add the storysource addon to the app-project storybook
  packages/app-project/.storybook/addons.js
  packages/app-project/.storybook/webpack.config.js
  packages/app-project/package.json
  yarn.lock
Labels: dx

#1211 Add project hero stories
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
Labels: design, dx

#1202 Package up the collections button
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.stories.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/README.md
Labels: refactor

#1220 Lint the classifier
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/mockData.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/Background.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/Background.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Chart/Chart.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Chart/Chart.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Chart/index.js
Labels: refactor

#1217 Bump next to 9.1.1
  packages/app-project/package.json
  yarn.lock
Labels: dependencies

#1225 Move assetPrefix to runtime config
  packages/app-project/next.config.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js
Labels: bug

#1218 Move favourites button to shared react components
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/FavouritesButton/FavouritesButton.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkLink.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkLink.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/index.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/CollectionsButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/CollectionsButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/FavouritesButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/HeartIcon.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/HeartIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/index.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetaToolsButton/MetaToolsButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetaToolsButton/MetaToolsButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetaToolsButton/index.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/MetadataButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/MetadataButton.spec.js
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.js
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.spec.js
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.stories.js
  packages/lib-react-components/src/FavouritesButton/HeartIcon.js
  packages/lib-react-components/src/FavouritesButton/HeartIcon.spec.js
  packages/lib-react-components/src/FavouritesButton/README.md
  packages/lib-react-components/src/FavouritesButton/index.js
  packages/lib-react-components/src/FavouritesButton/locales/en-GB.json
  packages/lib-react-components/src/FavouritesButton/locales/en-US.json
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.js
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.spec.js
  packages/lib-react-components/src/MetaToolsButton/index.js
  packages/lib-react-components/src/index.js
Labels: dx

#1229 Move linting related packages to dev deps for panoptes.js
  packages/lib-panoptes-js/docs/CHANGELOG.md
  packages/lib-panoptes-js/package.json
  packages/lib-panoptes-js/src/panoptes.js
  packages/lib-panoptes-js/src/panoptes.spec.js
Labels: bug, dependencies

#1227 Remove deprecated container
  packages/app-project/pages/_app.js
Labels: refactor

#1230 Bump panoptes.js to v0.1.1
  packages/lib-panoptes-js/docs/CHANGELOG.md
  packages/lib-panoptes-js/package.json
Labels: dependencies

#1233 Add ProjectAnnouncement to all pages
  packages/app-project/pages/_app.js
  packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncement.js
  packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncement.spec.js
  packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncement.stories.js
  packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncementContainer.js
  packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncementContainer.spec.js
  packages/app-project/src/components/ProjectAnnouncement/README.md
  packages/app-project/src/components/ProjectAnnouncement/index.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
Labels: design

#1234 Ensure ProjectAnnouncement takes the width of its container
  packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncement.js
  packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncement.spec.js
Labels: bug

#1238 Fix undefined theme in the favourites button
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.spec.js
  packages/lib-react-components/src/CloseButton/CloseButton.js
  packages/lib-react-components/src/CloseButton/index.js
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.js
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.spec.js
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.stories.js
  packages/lib-react-components/src/FavouritesButton/HeartIcon.js
Labels: bug

#1199 Add GoldButton to react components, update text color
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/theme.js
  packages/lib-react-components/.storybook/lib/backgrounds.js
  packages/lib-react-components/package.json
  packages/lib-react-components/src/GoldButton/GoldButton.js
  packages/lib-react-components/src/GoldButton/GoldButton.spec.js
  packages/lib-react-components/src/GoldButton/GoldButton.stories.js
  packages/lib-react-components/src/GoldButton/README.md
  packages/lib-react-components/src/GoldButton/index.js
  packages/lib-react-components/src/GoldButton/theme.js
  packages/lib-react-components/src/index.js
Labels: bug

#1215 Add stories for the subject viewer banners
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBannerContainer.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/RetiredBanner/RetiredBannerContainer.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/RetiredBanner/RetiredBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/UserHasFinishedWorkflowBanner/UserHasFinishedWorkflowBannerContainer.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/UserHasFinishedWorkflowBanner/UserHasFinishedWorkflowBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/WorkflowIsFinishedBanner/WorkflowIsFinishedBannerContainer.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/WorkflowIsFinishedBanner/WorkflowIsFinishedBannerContainer.stories.js
Labels: dx

#1228 Add a default annotation to tasks
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/tasks/DataVisAnnotationTask.js
  packages/lib-classifier/src/store/tasks/DrawingTask.js
  packages/lib-classifier/src/store/tasks/MultipleChoiceTask.js
  packages/lib-classifier/src/store/tasks/SingleChoiceTask.js
  packages/lib-classifier/src/store/tasks/SingleChoiceTask.spec.js
  packages/lib-classifier/src/store/tasks/Task.js
  packages/lib-classifier/src/store/tasks/Task.spec.js
Labels: enhancement

#1236 Preload images for the single image viewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
Labels: bug

#1246 Refactor TutorialStore
  packages/lib-classifier/src/store/TutorialStore.js
  packages/lib-classifier/src/store/TutorialStore.spec.js
Labels: refactor

#1235 Make project announcement dismissible
  packages/app-project/package.json
  packages/app-project/pages/_app.js
  packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncement.js
  packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncement.spec.js
  packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncementContainer.js
  packages/app-project/src/components/ProjectAnnouncement/ProjectAnnouncementContainer.spec.js
  packages/app-project/src/components/ProjectAnnouncement/components/NarrowProjectAnnouncement/NarrowProjectAnnouncement.js
  packages/app-project/src/components/ProjectAnnouncement/components/NarrowProjectAnnouncement/NarrowProjectAnnouncement.spec.js
  packages/app-project/src/components/ProjectAnnouncement/components/NarrowProjectAnnouncement/index.js
  packages/app-project/src/components/ProjectAnnouncement/components/WideProjectAnnouncement/WideProjectAnnouncement.js
  packages/app-project/src/components/ProjectAnnouncement/components/WideProjectAnnouncement/WideProjectAnnouncement.spec.js
  packages/app-project/src/components/ProjectAnnouncement/components/WideProjectAnnouncement/index.js
  packages/app-project/src/components/ProjectAnnouncement/helpers/markdownzComponents/index.js
  packages/app-project/src/components/ProjectAnnouncement/helpers/markdownzComponents/markdownzComponents.js
  packages/app-project/stores/UI.js
  packages/app-project/stores/UI.spec.js
  packages/app-project/test/create-global-document.js
Labels: design, discussion, enhancement

#1250 Update next.js for content pages app
  packages/app-content-pages/package.json
  packages/app-content-pages/pages/_app.js
  packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.js
  yarn.lock
Labels: dependencies

#1251 Actually call to create a default annotation on next or on done
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
  packages/lib-classifier/src/store/ClassificationStore.js
Labels: bug

#1232 Add a text input task
  packages/lib-classifier/.babelrc
  packages/lib-classifier/.storybook/webpack.config.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/helpers/getTaskComponent.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/index.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/locales/en.json
  packages/lib-classifier/src/plugins/tasks/TextTask/index.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextAnnotation.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.spec.js
  packages/lib-classifier/src/store/Classification.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/webpack.dev.js
  packages/lib-classifier/webpack.dist.js
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/src/index.js
Labels: enhancement

#1222 VX ScatterPlotViewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/Axes.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/Axes.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/Axis/Axis.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/Axis/Axis.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/Axis/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/InnerTickAxis/InnerTickAxis.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/InnerTickAxis/InnerTickAxis.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/InnerTickAxis/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/constants.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/mockData.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/utils.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/utils.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/index.js
Labels: enhancement

#1252 Alias test/ to @test in dev
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/RetiredBanner/RetiredBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/UserHasFinishedWorkflowBanner/UserHasFinishedWorkflowBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/WorkflowIsFinishedBanner/WorkflowIsFinishedBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuide.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemIcon/FieldGuideItemIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItemAnchor.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItems.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.stories.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonContainer.spec.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/FeedbackStore.spec.js
  packages/lib-classifier/src/store/FieldGuideStore.spec.js
  packages/lib-classifier/src/store/Subject.spec.js
  packages/lib-classifier/src/store/SubjectStore.spec.js
  packages/lib-classifier/src/store/TutorialStore.spec.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
  packages/lib-classifier/src/store/WorkflowStore.spec.js
  packages/lib-classifier/webpack.dev.js
Labels: dx
