Repository zooniverse/front-end-monorepo, pull requests merged in 2019-02, with the labels that each got.

#388 Add tutorial
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/index.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/index.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tabs/Tab.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tabs/Tabs.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Graph2dRangeXTask/Graph2dRangeXTask.js
  packages/lib-classifier/src/store/Medium.js
  packages/lib-classifier/src/store/Medium.spec.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/RootStore.spec.js
  packages/lib-classifier/src/store/Tutorial.js
  packages/lib-classifier/src/store/Tutorial.spec.js
  packages/lib-classifier/src/store/TutorialStore.js
  packages/lib-classifier/src/store/TutorialStore.spec.js
  packages/lib-classifier/test/factories/MediumFactory.js
  packages/lib-classifier/test/factories/TutorialFactory.js
  packages/lib-classifier/test/factories/index.js
  packages/lib-classifier/test/mocha.opts
  packages/lib-classifier/test/setup.js
  packages/lib-react-components/src/Media/components/Audio/Audio.js
  packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js
  packages/lib-react-components/src/Media/components/Video/Video.js
  packages/lib-react-components/src/Media/helpers/mediaPropTypes.js
Labels: enhancement

#432 Do not define custom npm install script
  packages/app-project/package.json
  packages/lib-async-states/package.json
  packages/lib-auth/package.json
Labels: bug

#400 Classifier - TESS Light Curve Viewer - Feedback Response (29 Jan Demo)
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLabel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBackgroundLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBorderLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setDataPointStyle.js
Labels: enhancement

#435 Rebuild ZooFooter
  packages/lib-grommet-theme/src/dark.js
  packages/lib-grommet-theme/src/index.js
  packages/lib-grommet-theme/src/light.js
  packages/lib-react-components/src/AdminCheckbox/AdminCheckbox.js
  packages/lib-react-components/src/SpacedText/SpacedText.js
  packages/lib-react-components/src/ZooFooter/README.md
  packages/lib-react-components/src/ZooFooter/ZooFooter.js
  packages/lib-react-components/src/ZooFooter/ZooFooter.spec.js
  packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.js
  packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.spec.js
  packages/lib-react-components/src/ZooFooter/components/LinkList/index.js
  packages/lib-react-components/src/ZooFooter/components/LogoAndTagline/LogoAndTagline.js
  packages/lib-react-components/src/ZooFooter/components/LogoAndTagline/LogoAndTagline.spec.js
  packages/lib-react-components/src/ZooFooter/components/LogoAndTagline/index.js
  packages/lib-react-components/src/ZooFooter/components/NavListItem/NavListItem.js
  packages/lib-react-components/src/ZooFooter/components/NavListItem/NavListItem.spec.js
  packages/lib-react-components/src/ZooFooter/components/NavListItem/index.js
  packages/lib-react-components/src/ZooFooter/components/PolicyLinkSection/PolicyLinkSection.js
  packages/lib-react-components/src/ZooFooter/components/PolicyLinkSection/PolicyLinkSection.spec.js
  packages/lib-react-components/src/ZooFooter/components/PolicyLinkSection/index.js
  packages/lib-react-components/src/ZooFooter/components/SocialAnchor/SocialAnchor.js
  packages/lib-react-components/src/ZooFooter/helpers/zipLabelsAndUrls/index.js
  packages/lib-react-components/src/ZooFooter/helpers/zipLabelsAndUrls/zipLabelsAndUrls.js
  packages/lib-react-components/src/ZooFooter/helpers/zipLabelsAndUrls/zipLabelsAndUrls.spec.js
  packages/lib-react-components/src/ZooFooter/lib/index.js
  packages/lib-react-components/src/ZooFooter/lib/whichTealColorForTheme.js
  packages/lib-react-components/src/ZooniverseLogotype/README.md
  packages/lib-react-components/src/ZooniverseLogotype/SVGContent.js
  packages/lib-react-components/src/ZooniverseLogotype/ZooniverseLogotype.js
  packages/lib-react-components/src/ZooniverseLogotype/ZooniverseLogotype.spec.js
  packages/lib-react-components/src/ZooniverseLogotype/index.js
Labels: bug

#436 Fix a couple of bugs in Subject Metadata modal
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/MetadataModal.js
  packages/lib-classifier/webpack.dist.js
Labels: bug

#430 Add collections to the API client
  packages/lib-panoptes-js/src/index.js
  packages/lib-panoptes-js/src/resources/collections/commonRequests.js
  packages/lib-panoptes-js/src/resources/collections/helpers.js
  packages/lib-panoptes-js/src/resources/collections/index.js
  packages/lib-panoptes-js/src/resources/collections/mocks.js
  packages/lib-panoptes-js/src/resources/collections/rest.js
  packages/lib-panoptes-js/src/resources/collections/rest.spec.js
Labels: enhancement

#437 Add user collections to a project
  packages/app-project/package-lock.json
  packages/app-project/package.json
  packages/app-project/stores/Collections.js
  packages/app-project/stores/Collections.spec.js
  packages/app-project/stores/Store.js
  packages/app-project/stores/User.js
  packages/app-project/stores/initStore.js
  packages/app-project/test/chai-config.js
  packages/app-project/test/mocha.opts
Labels: enhancement

#385 Classifier - TESS Light Curve Viewer - Introduce D3 multiple brushes for annotations
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLabel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBackgroundLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBorderLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addRemoveAnnotationButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addRemoveAnnotationButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setDataPointStyle.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setUserAnnotationAttr.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setUserAnnotationAttr.spec.js
Labels: enhancement

#460 Classifier tests
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/MetadataModal.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.spec.js
  packages/lib-classifier/src/store/utils/getBearerToken.spec.js
Labels: enhancement

#459 Add error boundary to `ClassifierWrapper`
  packages/app-project/components/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
  packages/app-project/components/ClassifyPage/components/ClassifierWrapper/components/ErrorMessage/ErrorMessage.js
  packages/app-project/components/ClassifyPage/components/ClassifierWrapper/components/ErrorMessage/ErrorMessage.spec.js
  packages/app-project/components/ClassifyPage/components/ClassifierWrapper/components/ErrorMessage/index.js
  packages/app-project/components/ClassifyPage/components/ClassifierWrapper/components/ErrorMessage/locales/en.json
Labels: enhancement

#465 Prevent unnecessary project calls
  packages/app-project/pages/_app.js
Labels: bug

#467 Populate <head />
  packages/app-project/components/Head/Head.js
  packages/app-project/components/Head/Head.spec.js
  packages/app-project/components/Head/HeadContainer.js
  packages/app-project/components/Head/HeadContainer.spec.js
  packages/app-project/components/Head/index.js
  packages/app-project/components/Head/locales/en.json
  packages/app-project/pages/_app.js
  packages/app-project/stores/Project.js
Labels: enhancement

#461 Fix create new favourites test
  packages/app-project/stores/Collections.spec.js
Labels: bug

#466 UPP store tests
  packages/lib-classifier/src/store/UserProjectPreferences.spec.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js
  packages/lib-classifier/test/factories/UPPFactory.js
  packages/lib-classifier/test/factories/UserFactory.js
  packages/lib-classifier/test/factories/index.js
  packages/lib-classifier/test/stubPanoptesJs/stubPanoptesJs.js
Labels: enhancement

#472 Move HeadContainer
  packages/app-project/src/components/Head/HeadContainer.js
  packages/app-project/src/components/Head/HeadContainer.spec.js
  packages/app-project/src/components/Head/locales/en.json
Labels: bug

#469 Start project header component
  packages/app-project/pages/_app.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js
  packages/app-project/src/components/ProjectHeader/index.js
  packages/app-project/src/components/ProjectHeader/locales/en.json
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
Labels: enhancement

#482 Bump to Next 8, fix environment mismatch
  packages/app-project/next.config.js
  packages/app-project/package-lock.json
  packages/app-project/package.json
Labels: bug, enhancement

#487 Setup Travis
  .travis.yml
  README.md
  bin/bootstrap.sh
  bin/travis-bootstrap.sh
  bin/travis-test.sh
  package-lock.json
  package.json
  packages/app-project/.babelrc
  packages/app-project/package.json
  packages/lib-async-states/package.json
  packages/lib-classifier/package.json
  packages/lib-panoptes-js/package.json
  packages/lib-react-components/package.json
  packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.spec.js
  packages/lib-react-components/src/ZooniverseLogotype/ZooniverseLogotype.js
Labels: enhancement

#501 Add MST inspector
  packages/app-project/package-lock.json
  packages/app-project/package.json
  packages/app-project/pages/_app.js
Labels: enhancement

#489 Tutorial store tests
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBackgroundLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setDataPointStyle.spec.js
  packages/lib-classifier/src/store/Classification.js
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/TutorialStore.js
  packages/lib-classifier/src/store/TutorialStore.spec.js
Labels: enhancement

#505 Track seen date for tutorial during session
  packages/lib-classifier/src/store/TutorialStore.js
  packages/lib-classifier/src/store/TutorialStore.spec.js
Labels: enhancement

#510 Unregister workers
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/workers/index.js
  packages/lib-classifier/src/workers/unregisterWorkers.js
Labels: bug
