Repository zooniverse/front-end-monorepo, pull requests merged in 2019-07, with the labels that each got.

#962 Add logging for sentry
  kubernetes/deployment.tmpl
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package-lock.json
  packages/app-content-pages/package.json
  packages/app-content-pages/pages/_app.js
  packages/app-content-pages/pages/_document.js
  packages/app-content-pages/src/helpers/logger/README.md
  packages/app-content-pages/src/helpers/logger/index.js
  packages/app-content-pages/src/helpers/logger/initializeSentry.js
  packages/app-content-pages/src/helpers/logger/logNodeError.js
  packages/app-content-pages/src/helpers/logger/logReactError.js
  packages/app-project/next.config.js
  packages/app-project/package-lock.json
  packages/app-project/package.json
  packages/app-project/pages/_app.js
  packages/app-project/pages/_document.js
  packages/app-project/src/helpers/logger/README.md
  packages/app-project/src/helpers/logger/index.js
  packages/app-project/src/helpers/logger/initializeSentry.js
  packages/app-project/src/helpers/logger/logNodeError.js
  packages/app-project/src/helpers/logger/logReactError.js
Labels: ops

#973 @zooniverse/async-states fixes
  bin/bootstrap.sh
  bin/travis-bootstrap.sh
  packages/lib-async-states/package-lock.json
  packages/lib-async-states/package.json
  packages/lib-async-states/src/async-states.spec.js
  packages/lib-async-states/test/mocha.opts
Labels: dependencies

#972 Fix @zooniverse/standard
  packages/tools-standard/bin/cmd.js
  packages/tools-standard/package-lock.json
  packages/tools-standard/package.json
Labels: bug, dependencies

#974 Improvements to @zooniverse/grommet-theme
  bin/bootstrap.sh
  bin/travis-bootstrap.sh
  packages/lib-grommet-theme/.babelrc
  packages/lib-grommet-theme/.gitignore
  packages/lib-grommet-theme/README.md
  packages/lib-grommet-theme/package-lock.json
  packages/lib-grommet-theme/package.json
  packages/lib-grommet-theme/src/index.js
Labels: dependencies

#975 Update panoptes-js
  packages/lib-panoptes-js/package-lock.json
  packages/lib-panoptes-js/package.json
  packages/lib-panoptes-js/src/panoptes.js
  packages/lib-panoptes-js/src/resources/collections/rest.spec.js
  packages/lib-panoptes-js/src/resources/projects/commonRequests.spec.js
  packages/lib-panoptes-js/src/resources/tutorials/commonRequests.spec.js
Labels: dependencies

#986 app-project housekeeping
  packages/app-project/.storybook/addons.js
  packages/app-project/.storybook/config.js
  packages/app-project/.storybook/lib/backgrounds.js
  packages/app-project/.storybook/lib/index.js
  packages/app-project/package-lock.json
  packages/app-project/package.json
Labels: dependencies

#988 Move cookie helper outside `pages`
  packages/app-project/pages/_app.js
  packages/app-project/src/helpers/getCookie/getCookie.js
  packages/app-project/src/helpers/getCookie/getCookie.spec.js
  packages/app-project/src/helpers/getCookie/index.js
Labels: bug

#998 Add story for ContentBox
  packages/app-project/src/shared/components/ContentBox/ContentBox.js
  packages/app-project/src/shared/components/ContentBox/ContentBox.stories.js
  packages/app-project/src/shared/components/Stat/Stat.stories.js
Labels: enhancement

#996 Hook up AboutProject component
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/shared/components/AboutProject/AboutProject.js
  packages/app-project/src/shared/components/AboutProject/AboutProject.spec.js
  packages/app-project/src/shared/components/AboutProject/AboutProjectContainer.js
  packages/app-project/src/shared/components/AboutProject/AboutProjectContainer.spec.js
  packages/app-project/stores/Project.js
Labels: enhancement

#990 First pass at ADR 16: Monorepo Tooling
  docs/arch/README.md
  docs/arch/adr-16.md
Labels: documentation

#935 Add ADR 15
  docs/arch/README.md
  docs/arch/adr-15.md
Labels: discussion, documentation

#945 Move withCustomFormik to shared lib
  packages/app-project/package.json
  packages/app-project/src/components/AuthModal/components/LoginForm/LoginForm.js
  packages/app-project/src/components/AuthModal/components/LoginForm/LoginFormContainer.js
  packages/app-project/src/components/AuthModal/components/LoginForm/LoginFormContainer.spec.js
  packages/app-project/src/components/AuthModal/components/LoginForm/components/Form/Form.js
  packages/app-project/src/components/AuthModal/components/LoginForm/components/Form/Form.spec.js
  packages/app-project/src/components/AuthModal/components/LoginForm/components/Form/index.js
  packages/app-project/src/components/AuthModal/components/LoginForm/locales/en.json
  packages/app-project/src/components/AuthModal/components/RegisterForm/components/Form/Form.js
  packages/app-project/src/components/AuthModal/components/RegisterForm/components/Form/Form.spec.js
  packages/lib-react-components/package.json
  packages/lib-react-components/src/helpers/withCustomFormik/README.md
  packages/lib-react-components/src/helpers/withCustomFormik/index.js
  packages/lib-react-components/src/helpers/withCustomFormik/withCustomFormik.js
  packages/lib-react-components/src/helpers/withCustomFormik/withCustomFormik.spec.js
  packages/lib-react-components/src/index.js
Labels: enhancement

#878 Use contentful category titles
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Publications/locales/en.json
  packages/app-content-pages/src/shared/stores/Publications/Publications.js
Labels: bug

#741 Start related projects API
  packages/app-related-projects-experiment/README.md
  packages/app-related-projects-experiment/package.json
  packages/app-related-projects-experiment/src/controllers/index.js
  packages/app-related-projects-experiment/src/controllers/relatedProjects.js
  packages/app-related-projects-experiment/src/db.js
  packages/app-related-projects-experiment/src/helpers/cleanTag.js
  packages/app-related-projects-experiment/src/helpers/generateRelatedProjects.js
  packages/app-related-projects-experiment/src/helpers/getProjectProperties.js
  packages/app-related-projects-experiment/src/helpers/getTargetProject.js
  packages/app-related-projects-experiment/src/helpers/panoptesClient.js
  packages/app-related-projects-experiment/src/helpers/populateDb.js
  packages/app-related-projects-experiment/src/helpers/sortByMatchingTags.js
  packages/app-related-projects-experiment/src/index.js
  packages/app-related-projects-experiment/src/logger.js
  packages/app-related-projects-experiment/src/models/projects.js
  packages/app-related-projects-experiment/src/models/relatedProjects.js
  packages/app-related-projects-experiment/test/chai-config.js
  packages/app-related-projects-experiment/test/mocha.opts
  yarn.lock
Labels: enhancement

#1016 Hook up Researcher Message widget
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcher.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcher.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcherContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcherContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/index.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/locales/en.json
  packages/app-project/src/shared/components/AboutProject/AboutProject.js
  packages/app-project/src/shared/components/MessageFromResearcher/MessageFromResearcher.js
  packages/app-project/src/shared/components/MessageFromResearcher/MessageFromResearcher.spec.js
  packages/app-project/src/shared/components/MessageFromResearcher/MessageFromResearcherContainer.js
  packages/app-project/src/shared/components/MessageFromResearcher/MessageFromResearcherContainer.spec.js
  packages/app-project/src/shared/components/MessageFromResearcher/locales/en.json
  packages/app-project/stores/Project.js
  packages/app-project/stores/Project.spec.js
Labels: enhancement

#1022 [MST Upgrade] Update UPP store
  packages/lib-classifier/src/store/UserProjectPreferencesStore.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js
Labels: bug, dependencies

#1021 [MST Upgrade] Update WorkflowStore
  packages/lib-classifier/src/store/WorkflowStore.js
  packages/lib-classifier/src/store/WorkflowStore.spec.js
Labels: bug, dependencies

#1029 Add storybook to classifier library
  packages/lib-classifier/.storybook/addons.js
  packages/lib-classifier/.storybook/config.js
  packages/lib-classifier/.storybook/lib/backgrounds.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/webpack.dist.js
  yarn.lock
Labels: dependencies, enhancement

#1033 Add support to restricted names list
  packages/lib-react-components/src/Markdownz/Markdownz.js
  packages/lib-react-components/src/Markdownz/Markdownz.spec.js
Labels: enhancement

#1034 Perform a build during tests
  .travis.yml
Labels: ops

#1038 Fix client-side routing
  packages/app-project/next.config.js
  packages/app-project/pages/_app.js
  packages/app-project/pages/about/faq.js
  packages/app-project/pages/about/index.js
  packages/app-project/pages/about/research.js
  packages/app-project/pages/about/results.js
  packages/app-project/pages/about/team.js
  packages/app-project/server/helpers/getCommonParams.js
  packages/app-project/server/server.js
  packages/app-project/src/components/AuthModal/components/LoginForm/LoginForm.js
  packages/app-project/src/components/AuthModal/components/LoginForm/LoginForm.spec.js
  packages/app-project/src/components/AuthModal/components/LoginForm/components/Form/Form.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
  packages/app-project/src/components/ProjectHeader/components/Nav/components/NavLink/NavLink.js
  packages/app-project/src/components/ProjectHeader/components/Nav/components/NavLink/NavLink.spec.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.spec.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitleContainer.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitleContainer.spec.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/index.js
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.js
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.spec.js
  packages/app-project/src/helpers/getCookie/getCookie.spec.js
  packages/app-project/src/helpers/logger/logReactError.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcher.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcherContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcherContainer.spec.js
  packages/app-project/src/shared/components/AboutProject/AboutProject.js
  packages/app-project/stores/Project.js
Labels: bug, enhancement

#968 Add axis layer test
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addAxisLayer.spec.js
Labels: refactor

#969 Test for clip-path
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addDataLayer.spec.js
Labels: refactor

#970 Add unit tests for addDataMask
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addDataMask.spec.js
Labels: refactor

#1046 [MST Upgrade] FeedbackStore updates
  packages/lib-classifier/src/store/FeedbackStore.js
  packages/lib-classifier/src/store/FeedbackStore.spec.js
  packages/lib-classifier/src/store/Workflow.js
  packages/lib-classifier/test/factories/FeedbackFactory.js
  packages/lib-classifier/test/factories/ProjectFactory.js
  packages/lib-classifier/test/factories/WorkflowFactory.js
  packages/lib-classifier/test/factories/index.js
Labels: bug, dependencies

#1004 [MST Upgrade] Update FieldGuideStore
  packages/lib-classifier/src/store/FieldGuideStore.js
  packages/lib-classifier/src/store/FieldGuideStore.spec.js
Labels: bug, dependencies

#913 Add drawing task inputs
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/DrawingTask.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/DrawingTask.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/AnchoredEllipse.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/Bezier.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/Circle.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/Column.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/Ellipse.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/Fan.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/FreehandLine.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/FreehandSegmentLine.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/FreehandSegmentShape.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/FreehandShape.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/FullHeightLine.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/FullWidthLine.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/Grid.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/Line.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/Point.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/PointGrid.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/Polygon.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/Rectangle.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/RotateRectangle.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/Triangle.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/components/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/helpers/getIcon.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/helpers/getIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/helpers/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/InputIcon/InputIcon.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/InputStatus/InputStatus.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/InputStatus/InputStatus.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/InputStatus/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskInputField/components/TaskInputLabel/TaskInputLabel.js
  packages/lib-classifier/src/store/DrawingStore.js
  packages/lib-classifier/src/store/DrawingStore.spec.js
Labels: enhancement
