Repository zooniverse/front-end-monorepo, pull requests merged in 2019-04, with the labels that each got.

#614 FieldGuide store
  packages/lib-classifier/src/store/FieldGuide.js
  packages/lib-classifier/src/store/FieldGuide.spec.js
  packages/lib-classifier/src/store/FieldGuideStore.js
  packages/lib-classifier/src/store/FieldGuideStore.spec.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/test/factories/FieldGuideFactory.js
  packages/lib-classifier/test/factories/MediumFactory.js
  packages/lib-classifier/test/factories/index.js
Labels: enhancement

#635 Adjust paddings/margins in theme to match design
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
  packages/app-project/src/shared/components/ContentBox/ContentBox.js
  packages/app-project/src/shared/components/ProjectStatistics/ProjectStatistics.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js
  packages/lib-grommet-theme/src/index.js
  packages/lib-react-components/src/ZooFooter/ZooFooter.js
  packages/lib-react-components/src/ZooFooter/components/SocialAnchor/SocialAnchor.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
Labels: bug

#640 Use zooniverse markdown instead of grommet
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DrawingTask/DrawingTask.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/SingleChoiceTask/SingleChoiceTask.js
Labels: enhancement

#641 Make subject metadata modal scrollable
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/MetadataModal.js
Labels: bug

#622 Add already seen and retired banners
  packages/lib-classifier/package-lock.json
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.js
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/README.md
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBannerContainer.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBannerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/index.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/components/TooltipText/TooltipText.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/components/TooltipText/TooltipText.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/components/TooltipText/index.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/components/Triangle/Triangle.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/components/Triangle/Triangle.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/components/Triangle/index.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/index.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/Banners/components/RetiredBanner/RetiredBannerContainer.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/RetiredBanner/RetiredBannerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/RetiredBanner/index.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/RetiredBanner/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/Banners/components/UserHasFinishedWorkflowBanner/UserHasFinishedWorkflowBannerContainer.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/UserHasFinishedWorkflowBanner/UserHasFinishedWorkflowBannerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/UserHasFinishedWorkflowBanner/index.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/UserHasFinishedWorkflowBanner/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/Banners/components/WorkflowIsFinishedBanner/WorkflowIsFinishedBannerContainer.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/WorkflowIsFinishedBanner/WorkflowIsFinishedBannerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/WorkflowIsFinishedBanner/index.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/WorkflowIsFinishedBanner/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/Banners/index.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
Labels: enhancement

#615 Focus accessibility for tutorial navigation
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.spec.js
Labels: bug

#646 Set tabs active state
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tabs/Tab.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tabs/Tabs.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tabs/index.js
Labels: bug, enhancement

#644 Remove the default transparent background for drop from theme
  packages/app-project/src/screens/ClassifyPage/components/CollectionsModal/components/SelectCollection/SelectCollection.js
  packages/lib-grommet-theme/src/index.js
Labels: bug

#655 Render modal title as an h2
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.spec.js
Labels: accessibility, bug

#656 Enable reset zoom button
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
Labels: enhancement

#652 Narrow project header
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js
  packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/ApprovedIcon.js
  packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/ApprovedIconContainer.js
  packages/app-project/src/components/ProjectHeader/components/Avatar/AvatarContainer.js
  packages/app-project/src/components/ProjectHeader/components/Avatar/AvatarContainer.spec.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.spec.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/index.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.spec.js
  packages/app-project/src/components/ProjectHeader/components/Nav/NavContainer.js
  packages/app-project/src/components/ProjectHeader/components/Nav/NavContainer.spec.js
  packages/app-project/src/components/ProjectHeader/components/Nav/index.js
  packages/app-project/src/components/ProjectHeader/components/Nav/locales/en.json
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.spec.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/index.js
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.js
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.spec.js
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/index.js
  packages/app-project/src/components/ProjectHeader/locales/en.json
Labels: enhancement

#664 Ensure toolbar buttons have an aria-label
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.spec.js
Labels: accessibility, bug

#645 Fix styling issues with the tutorial
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/CollectionsButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/index.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/index.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tabs/Tabs.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DataVisAnnotationTask/DataVisAnnotationTask.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DataVisAnnotationTask/DataVisAnnotationTask.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DataVisAnnotationTask/components/Graph2dRangeXIcon.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/DataVisAnnotationTask/components/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/InputIcon/InputIcon.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/InputIcon/InputIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/InputIcon/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/InputStatus/InputStatus.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/InputStatus/InputStatus.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/InputStatus/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskInputField/components/TaskInputLabel/TaskInputLabel.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js
  packages/lib-classifier/src/store/Classification.spec.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/DataVisAnnotatingStore.js
  packages/lib-classifier/src/store/FieldGuideStore.js
  packages/lib-classifier/src/store/FieldGuideStore.spec.js
  packages/lib-classifier/src/store/Project.spec.js
  packages/lib-classifier/src/store/TutorialStore.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
  packages/lib-classifier/src/store/annotations/DataVisAnnotation.js
  packages/lib-classifier/src/store/annotations/DataVisToolAnnotations/index.js
  packages/lib-classifier/src/store/tasks/DataVisAnnotationTask.js
  packages/lib-classifier/src/store/tasks/DataVisAnnotationTask.spec.js
  packages/lib-classifier/src/store/tasks/dataVisTools/index.js
  packages/lib-classifier/test/factories/FieldGuideFactory.js
  packages/lib-grommet-theme/src/index.js
  packages/lib-react-components/.storybook/lib/example.md
  packages/lib-react-components/src/Markdownz/Markdownz.js
Labels: bug

#637 Field guide modal
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideContainer.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuide.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuide.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/index.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemIcon/FieldGuideItemIcon.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemIcon/FieldGuideItemIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemIcon/index.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItemAnchor.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItemAnchor.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItems.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItems.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/index.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/index.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/HelpIcon.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/HelpIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/index.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/index.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FieldGuideButton/FieldGuideButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FieldGuideButton/FieldGuideButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FieldGuideButton/index.js
  packages/lib-classifier/src/store/FieldGuideStore.js
  packages/lib-classifier/src/store/FieldGuideStore.spec.js
  packages/lib-react-components/src/Modal/Modal.js
  packages/lib-react-components/src/Modal/README.md
  packages/lib-react-components/src/Modal/components/ModalBody/ModalBody.js
Labels: enhancement

#659 Remove banners from DOM when inactive
  packages/lib-classifier/package-lock.json
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.js
Labels: accessibility, bug

#670 Render link lists as ul in footer
  packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.js
  packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.spec.js
Labels: accessibility

#674 Add Contributing.md
  README.md
  docs/CONTRIBUTING.md
  docs/arch/adr-13.md
  packages/app-project/README.md
  packages/lib-async-states/README.md
  packages/lib-classifier/README.md
  packages/lib-grommet-theme/README.md
  packages/lib-panoptes-js/README.md
  packages/lib-react-components/README.md
Labels: documentation, enhancement

#665 Subject metadata modal fixes
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/MetadataModal.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/filterByLabel.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/filterByLabel.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/index.js
  packages/lib-classifier/src/store/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore.spec.js
  packages/lib-classifier/test/factories/SubjectFactory.js
Labels: bug

#672 Field guide style fixes
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideContainer.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemIcon/FieldGuideItemIcon.js
  packages/lib-grommet-theme/src/index.js
  packages/lib-react-components/src/Media/components/Audio/Audio.js
  packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js
  packages/lib-react-components/src/Media/components/Video/Video.js
  packages/lib-react-components/src/Modal/WithLayer.js
Labels: bug

#701 Use default theme sizes for paragraphs
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
  packages/app-project/src/shared/components/ProjectStatistics/ProjectStatistics.js
Labels: bug

#702 Add Google Tag Manager in production
  packages/app-project/pages/_document.js
Labels: enhancement

#703 Fix typo in line-height
  packages/lib-grommet-theme/src/index.js
Labels: bug

#705 Update background color for LCV
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
Labels: enhancement

#699 Add components for related projects modal
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/RelatedProjectsContainer.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/RelatedProjectsContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsButton/RelatedProjectsButton.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsButton/RelatedProjectsButton.spec.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsButton/index.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsButton/locales/en.json
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/RelatedProjectsModal.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/RelatedProjectsModal.spec.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/RelatedProjectsModalContainer.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/RelatedProjectsModalContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/components/ProjectCard/ProjectCard.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/components/ProjectCard/ProjectCard.spec.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/components/ProjectCard/index.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/components/ProjectCard/locales/en.json
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/index.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/locales/en.json
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/index.js
Labels: enhancement

#706 Move collections modal into classify container
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
Labels: bug

#708 Pass auth headers with collections delete requests
  packages/lib-panoptes-js/src/resources/collections/commonRequests.js
  packages/lib-panoptes-js/src/resources/collections/rest.spec.js
Labels: bug

#711 Fix Next.js document so it correctly renders <Head>
  packages/app-project/pages/_document.js
Labels: bug

#712 Make sure field guide item icons stay the same size. Consistent padding.
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideContainer.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItemAnchor.js
Labels: bug

#713 Fix undefined error with metadata button
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/CollectionsButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/FavouritesButton/FavouritesButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataButton/MetadataButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataButton/MetadataButton.spec.js
Labels: bug

#704 Additional tutorial style fixes
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.js
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js
Labels: bug

#716 Add link for user stats only if logged in
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsButton/RelatedProjectsButton.js
Labels: enhancement

#720 Add a key to the subject viewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
Labels: bug

#724 Tab design fixes
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tabs/Tabs.js
Labels: bug

#742 Add dark theme toggle icon
  packages/app-project/src/components/ThemeModeToggle/ThemeModeToggle.js
Labels: enhancement

#745 Fix elevations
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
  packages/app-project/src/shared/components/ContentBox/ContentBox.js
  packages/lib-grommet-theme/src/index.js
Labels: enhancement

#765 Fix font sizes and theme in ZooFooter
  packages/lib-react-components/package.json
  packages/lib-react-components/src/ZooFooter/README.md
  packages/lib-react-components/src/ZooFooter/ZooFooter.js
  packages/lib-react-components/src/ZooFooter/ZooFooter.spec.js
  packages/lib-react-components/src/ZooFooter/ZooFooter.stories.js
  packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.js
  packages/lib-react-components/src/ZooFooter/components/LogoAndTagline/LogoAndTagline.js
  packages/lib-react-components/src/ZooFooter/components/LogoAndTagline/LogoAndTagline.spec.js
  packages/lib-react-components/src/ZooFooter/components/SocialAnchor/SocialAnchor.js
  packages/lib-react-components/src/ZooFooter/components/SocialAnchor/SocialAnchor.spec.js
Labels: bug, enhancement

#743 Set theme via cookie and SSR correct theme mode
  packages/app-project/package-lock.json
  packages/app-project/package.json
  packages/app-project/pages/_app.js
  packages/app-project/stores/UI.js
Labels: enhancement

#770 Update node version in README
  README.md
Labels: documentation

#767 Tutorial get started button
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.js
  packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.js
  packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideContainer.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuide.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuide.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/index.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemIcon/FieldGuideItemIcon.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemIcon/FieldGuideItemIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemIcon/index.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItemAnchor.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItemAnchor.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItems.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItems.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/index.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/index.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/HelpIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/index.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataButton/MetadataButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/filterByLabel.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/filterByLabel.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/MetadataModal/index.js
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.spec.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js
  packages/lib-classifier/src/store/FieldGuideStore.spec.js
  packages/lib-classifier/src/store/SubjectStore.spec.js
  packages/lib-classifier/src/store/TutorialStore.js
  packages/lib-classifier/src/store/TutorialStore.spec.js
  packages/lib-classifier/test/factories/SubjectFactory.js
Labels: enhancement

#769 Style `Next` button in Classifier
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/theme.js
Labels: bug

#780 Update theme for the radio buttons
  packages/lib-grommet-theme/src/index.js
Labels: bug

#779 Refactor metadata modal to be contained in a fragment container class
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/Metadata.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/Metadata.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/InfoIcon.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/InfoIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/MetadataButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/MetadataButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/index.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/filterByLabel.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/filterByLabel.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/index.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/theme.js
  packages/lib-classifier/src/store/SubjectStore.js
Labels: bug

#785 Alias react for dev environment
  packages/lib-classifier/webpack.dev.js
Labels: bug

#784 Set default padding for button in the theme
  packages/lib-grommet-theme/src/index.js
Labels: bug

#788 Add a defined height for the FFTD project image
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.js
Labels: bug
