Repository zooniverse/front-end-monorepo, pull requests merged in 2019-08, with the labels that each got.

#1062 Allow feedback rules with falsy values
  packages/lib-classifier/src/store/feedback/helpers/generate-rules.spec.js
  packages/lib-classifier/src/store/feedback/helpers/metadata-to-rules.js
  packages/lib-classifier/src/store/feedback/helpers/metadata-to-rules.spec.js
Labels: bug

#1069 Bump Next.js to v9 in app-project
  packages/app-project/package.json
  yarn.lock
Labels: dependencies, enhancement

#1065 Add ADR 17
  docs/arch/README.md
  docs/arch/adr-17.md
Labels: documentation, ops, question

#1064 [MST Upgrade] Update workflow step store
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
Labels: dependencies, refactor

#1060 [MST Upgrade] Update classification store
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/FeedbackStore.js
  packages/lib-classifier/src/store/SubjectStore.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
  packages/lib-classifier/test/factories/annotations/SingleChoiceAnnotationFactory.js
  packages/lib-classifier/test/factories/index.js
Labels: dependencies, refactor

#1053 [MST Upgrade] Update subject viewer store
  packages/lib-classifier/src/store/SubjectViewerStore.js
  packages/lib-classifier/src/store/SubjectViewerStore.spec.js
Labels: dependencies, refactor

#1081 Preparation for publishing @zooniverse/grommet-theme
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/README.md
  packages/lib-grommet-theme/package.json
Labels: dependencies

#1084 Theme: Update changelog. Add postversion script
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/package.json
Labels: dependencies

#1087 Bump theme version across packages
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: bug

#1086 [MST Upgrade] Update FieldGuideStore and tests
  packages/lib-classifier/src/store/FieldGuideStore.js
  packages/lib-classifier/src/store/FieldGuideStore.spec.js
Labels: refactor

#1085 [MST Upgrade] Update WorkflowStore and tests
  packages/lib-classifier/src/store/WorkflowStore.js
  packages/lib-classifier/src/store/WorkflowStore.spec.js
Labels: refactor

#1095 Feedback bug fixes
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/FeedbackStore.js
  packages/lib-classifier/src/store/FeedbackStore.spec.js
Labels: bug

#1003 [MST Upgrade] Update Stores
  .travis.yml
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/DataVisAnnotatingStore.js
  packages/lib-classifier/src/store/FeedbackStore.js
  packages/lib-classifier/src/store/FeedbackStore.spec.js
  packages/lib-classifier/src/store/FieldGuideStore.js
  packages/lib-classifier/src/store/FieldGuideStore.spec.js
  packages/lib-classifier/src/store/ProjectStore.js
  packages/lib-classifier/src/store/ProjectStore.spec.js
  packages/lib-classifier/src/store/ResourceStore.js
  packages/lib-classifier/src/store/ResourceStore.spec.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/RootStore.spec.js
  packages/lib-classifier/src/store/Subject.js
  packages/lib-classifier/src/store/Subject.spec.js
  packages/lib-classifier/src/store/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore.spec.js
  packages/lib-classifier/src/store/SubjectViewerStore.js
  packages/lib-classifier/src/store/SubjectViewerStore.spec.js
  packages/lib-classifier/src/store/TutorialStore.js
  packages/lib-classifier/src/store/TutorialStore.spec.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js
  packages/lib-classifier/src/store/Workflow.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
  packages/lib-classifier/src/store/WorkflowStore.js
  packages/lib-classifier/src/store/WorkflowStore.spec.js
  packages/lib-classifier/test/factories/FeedbackFactory.js
  packages/lib-classifier/test/factories/ProjectFactory.js
  packages/lib-classifier/test/factories/SubjectFactory.js
  packages/lib-classifier/test/factories/WorkflowFactory.js
  packages/lib-classifier/test/factories/annotations/SingleChoiceAnnotationFactory.js
  packages/lib-classifier/test/factories/index.js
  packages/lib-classifier/test/stubPanoptesJs/stubPanoptesJs.js
Labels: bug, dependencies
