Repository zooniverse/front-end-monorepo, pull requests merged in 2020-10, with the labels that each got.

#1825 Fix color regression in scatter plot
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/HighlightSeriesCheckBoxes/HighlightSeriesCheckBoxes.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/HighlightSeriesCheckBoxes/HighlightSeriesCheckBoxes.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/HighlightSeriesCheckBoxes/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/Label/Label.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/VisibilitySeriesCheckBoxes/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesHighlighted/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesHighlighted/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesHighlighted/isDataSeriesHighlighted.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesHighlighted/isDataSeriesHighlighted.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesVisible/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesVisible/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesVisible/isDataSeriesVisible.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesVisible/isDataSeriesVisible.spec.js
Labels: approved, bug

#1831 [VSLCV] Responsive grid
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
Labels: approved, design

#1840 Revert "Upgrade to mobx-react 6 (#1820)"
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js
  yarn.lock
Labels: approved, bug, dependencies

#1844 Classifier: add a console message when loading Subjects
  packages/lib-classifier/src/store/SubjectStore.js
Labels: approved, dx

#1849 [VSLCV] Fix the missed renamed prop for the checkbox on change handler
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
Labels: approved, bug

#1850 [VSLCV] Updated phased bar chart calculation
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/helpers/constants.js
Labels: approved, refactor

#1842 Classifier: Test default annotations for tasks
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotationTask.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Task.spec.js
Labels: approved, enhancement

#1854 Add visual indicators that project is in beta aka under review
  packages/app-project/pages/_app.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/components/UnderReviewLabel/UnderReviewLabel.js
  packages/app-project/src/components/ProjectHeader/components/UnderReviewLabel/UnderReviewLabel.spec.js
  packages/app-project/src/components/ProjectHeader/components/UnderReviewLabel/index.js
  packages/app-project/src/components/ProjectHeader/components/UnderReviewLabel/locales/en.json
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.spec.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePageContainer.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePageContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/index.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayout.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayoutContainer.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayoutContainer.spec.js
  packages/app-project/src/shared/components/StandardLayout/index.js
  packages/app-project/stores/Project.js
  packages/app-project/stores/Project.spec.js
Labels: approved, design, enhancement

#1858 Allow text mime type fallback for variable star LCV
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.spec.js
Labels: approved, bug

#1830 Classifier: Simple dropdown task adapter
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/helpers/index.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/helpers/panoptesAdapter/index.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/helpers/panoptesAdapter/panoptesAdapter.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/helpers/panoptesAdapter/panoptesAdapter.spec.js
  packages/lib-classifier/src/store/Step.js
Labels: approved, experiment

#1772 Classifier Dropdown Task (v3) - Simple Dropdown
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/README.md
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/SimpleDropdownTask.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/SimpleDropdownTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/SimpleDropdownTask.stories.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/index.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/locales/en.json
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/index.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownAnnotation.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/helpers/index.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/helpers/panoptesAdapter/index.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/helpers/panoptesAdapter/panoptesAdapter.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/helpers/panoptesAdapter/panoptesAdapter.spec.js
  packages/lib-classifier/src/plugins/tasks/index.js
  packages/lib-classifier/src/store/Step.js
Labels: approved

#1799 Add subtask required UI
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopupContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ConfirmModal/ConfirmModal.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ConfirmModal/ConfirmModal.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ConfirmModal/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ConfirmModal/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/TaskInput.js
Labels: approved, design, enhancement

#1865 switch pdb to percent of available replicas
  kubernetes/deployment-production.tmpl
Labels: approved

#1824 Upgrade vx to 0.0.199
  packages/app-project/package.json
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/mockData.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VXZoom/VXZoom.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/Axis/Axis.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/InnerTickAxis/InnerTickAxis.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/utils.js
  yarn.lock
Labels: dependencies

#1867 [DataImageViewer] refactor image rendering and finding subject locations
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.spec.js
  packages/lib-classifier/src/helpers/constants/constants.js
  packages/lib-classifier/src/helpers/constants/index.js
  packages/lib-classifier/src/helpers/findLocationsByMediaType/findLocationsByMediaType.js
  packages/lib-classifier/src/helpers/findLocationsByMediaType/findLocationsByMediaType.spec.js
  packages/lib-classifier/src/helpers/findLocationsByMediaType/index.js
  packages/lib-classifier/src/helpers/index.js
  packages/lib-classifier/src/helpers/validateMimeType/validateMimeType.js
Labels: approved, enhancement, refactor

#1861 Classifier: validate simple dropdown options
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.spec.js
Labels: approved, enhancement
