Repository zooniverse/front-end-monorepo, pull requests merged in 2020-08, with the labels that each got.

#1727 Set up new classifier routes for workflows and subject sets
  packages/app-project/pages/projects/[owner]/[project]/classify/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
Labels: approved

#1728 Initial DataImageViewer setup
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/index.js
Labels: approved, enhancement

#1732 Add a story about a text task with suggestions
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.stories.js
Labels: approved, dx

#1737 Fix arrow positioning for Tooltip
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/Tooltip/components/Label/Label.js
  packages/lib-react-components/src/Tooltip/components/Label/Label.spec.js
Labels: approved, bug

#1724 ADR 28 about data as a subject viewers
  docs/arch/README.md
  docs/arch/adr-28.md
Labels: approved, documentation

#1726 Classifier: Upgrade and document the withKeyZoom decorator
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/README.md
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js
  packages/lib-classifier/src/store/SubjectViewerStore/Readme.md
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.spec.js
  packages/lib-classifier/src/store/SubjectViewerStore/index.js
Labels: approved, enhancement, refactor

#1741 Upgrade storybook-deployer
  package.json
  yarn.lock
Labels: approved, dependencies

#1743 Add transients samples
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/mockLightCurves/transients/subject-1/ZTF20abqdkne.jpeg
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/mockLightCurves/transients/subject-1/zoo_subject_ZTF20abqdkne.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/mockLightCurves/transients/subject-2/ZTF20abqfmcr.jpeg
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/mockLightCurves/transients/subject-2/zoo_subject_ZTF20abqfmcr.json
Labels: approved, dx

#1740 SVGZoom: fix horizontal panning
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
Labels: approved, bug

#1753 Only calculate period bar chart
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/mockLightCurves/variableStar.json
Labels: approved, bug

#1738 Make mark UX consistent and fix associated keyboard events
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.js
  packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.spec.js
Labels: approved, bug, design

#1754 Upgrade styled-components
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.stories.js
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  packages/lib-react-components/src/AdminCheckbox/AdminCheckbox.stories.js
  packages/lib-react-components/src/CloseButton/CloseButton.stories.js
  packages/lib-react-components/src/PlainButton/PlainButton.stories.js
  packages/lib-react-components/src/Tabs/Tabs.stories.js
  packages/lib-react-components/src/ZooFooter/ZooFooter.stories.js
  yarn.lock
Labels: approved, dependencies, dx

#1755 Added a check for active tool
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
Labels: approved

#1744 ScatterPlotViewer options
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/Axis/Axis.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
Labels: approved, enhancement

#1756 Implement dark theme and other style fixes for ScatterPlotViewer, BarChartViewer, and VSLCV
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/Axis/Axis.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/theme.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/theme.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/FlipIcon/FlipIcon.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/ZoomEnableButton/ZoomEnableButton.js
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/README.md
Labels: approved, bug, design

#1749 Fix keyboard panning with VXZoom
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VXZoom/VXZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VXZoom/VXZoom.spec.js
Labels: approved, bug

#1759 Remove focus from previous transcription when a new line is created
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
Labels: approved, bug

#1735 Fix Bug when Placing Transcription Lines on Touchscreen
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/TranscriptionLineTool/TranscriptionLineTool.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/TranscriptionLineTool/TranscriptionLineTool.spec.js
Labels: approved, bug, discussion

#1771 Fix TESS LCV direction for left and right arrow panning
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
Labels: approved, bug

#1769 Refactor VSLCV to use connector component
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/index.js
Labels: approved, refactor

#1775 Allow for configuration of several more viewers
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.spec.js
  packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.js
  packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.spec.js
  packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
Labels: approved, enhancement

#1765 Get zoom control working with DataImageViewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomControlButton/ZoomControlButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomControlButton/ZoomControlButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomControlButton/locales/en.json
Labels: approved, enhancement
