Repository zooniverse/front-end-monorepo, pull requests merged in 2020-11, with the labels that each got.

#1872 Add readme for DataImageViewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/README.md
Labels: approved, documentation

#1871 [DataImageViewer] Toggleable zoom for the single image
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/HidePreviousTranscriptionsButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ZoomControlButton/ZoomControlButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ZoomControlButton/ZoomControlButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ZoomControlButton/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ZoomControlButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getZoomBackgroundColor/getZoomBackgroundColor.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getZoomBackgroundColor/getZoomBackgroundColor.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getZoomBackgroundColor/index.js
  packages/lib-classifier/src/helpers/constants/constants.js
  packages/lib-classifier/src/helpers/constants/index.js
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.js
Labels: approved, enhancement, refactor, storybook

#1873 Get DataImageViewer functional for subject demo
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.spec.js
Labels: approved, bug

#1828 Upgrade to visx
  packages/app-project/package.json
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.spec.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/components/Bars/Bars.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/components/Bars/Bars.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/mockData.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VXZoom/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/Axis/Axis.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/Axis/Axis.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/InnerTickAxis/InnerTickAxis.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/InnerTickAxis/InnerTickAxis.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/mockData.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/utils.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/glyphComponents.js
  yarn.lock
Labels: approved, dependencies

#1888 docker-compose: add an interactive shell
  README.md
  docker-compose.yml
Labels: approved

#1868 Add isComplete to textAnnotation model
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextAnnotation.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextAnnotation.spec.js
Labels: approved

#1891 Fix VSLCV style regression introduced from grommet upgrade
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/PeriodMultipleControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/theme.js
Labels: approved, bug

#1892 Fix style regression from #1871
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsIcon.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkIcon.js
  packages/lib-react-components/CHANGELOG.md
Labels: approved, bug

#1883 Update Grommet to 2.15.2
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/MetadataButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/PeriodMultipleControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/theme.js
  packages/lib-classifier/src/components/Classifier/components/shared/Triangle/Triangle.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-react-components/package.json
  yarn.lock
Labels: approved, dependencies

#1896 Add storybook story for MetaToolsButton
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.stories.js
  packages/lib-react-components/src/MetaToolsButton/README.md
Labels: approved, storybook

#1720 Add TranscribedLines tests for callback and ref per event
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.js
Labels: approved, refactor

#1898 [DataImageViewer] Hard code margin and label offset for workshop
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
Labels: approved, bug, design

#1897 DataImageViewer responsive layout
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js
Labels: approved, design

#1862 Classifier: add Required to dropdown stories
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/SimpleDropdownTask.stories.js
Labels: approved, dx, enhancement, storybook

#1841 Task models: remove unused actions and use tryReference to access annotations
  packages/lib-classifier/src/plugins/drawingTools/README.md
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.stories.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Task.js
  packages/lib-classifier/src/plugins/tasks/readme.md
  packages/lib-classifier/src/store/Step.spec.js
Labels: refactor

#1907 Fix layout issues for transcription projects
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
Labels: approved, design

#1638 Subject Group Annotations
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.spec.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/components/SubjectGroupComparisonTask.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/components/SubjectGroupComparisonTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/components/index.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/index.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonAnnotation.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonTask.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonTask.spec.js
  packages/lib-classifier/src/plugins/tasks/index.js
Labels: approved, enhancement

#1909 Demo mode by query param
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptions.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptions.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptionsContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptionsContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/DemoModeToggle.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/DemoModeToggle.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/DemoModeToggleContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/DemoModeToggleContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/locales/en.json
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/TranscriptionReductions/TranscriptionReductions.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/src/index.js
Labels: approved, enhancement

#1908 Add observers to the classifier task stories
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.stories.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/SimpleDropdownTask.stories.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.stories.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.stories.js
Labels: approved, bug

#1855 Classifier: Add an id parameter to task default annotations
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotationTask.js
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotationTask.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Task.js
  packages/lib-classifier/src/plugins/tasks/models/Task.spec.js
  packages/lib-classifier/src/plugins/tasks/readme.md
  packages/lib-classifier/src/store/Step.spec.js
Labels: approved, enhancement

#1887 Remove the multistage Docker build
  .travis.yml
  Dockerfile
  Jenkinsfile
  README.md
  bin/bootstrap.sh
  docker-compose.yml
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
  packages/app-content-pages/Dockerfile
  packages/app-content-pages/README.md
  packages/app-content-pages/docker-compose-prod.yml
  packages/app-content-pages/docker-compose.yml
  packages/app-content-pages/next.config.js
  packages/app-content-pages/src/helpers/logger/initializeSentry.js
  packages/app-content-pages/src/helpers/logger/logNodeError.js
  packages/app-content-pages/src/helpers/logger/logReactError.js
  packages/app-project/Dockerfile
  packages/app-project/README.md
  packages/app-project/docker-compose-prod.yml
  packages/app-project/docker-compose.yml
  packages/app-project/next.config.js
  packages/app-project/src/helpers/logger/initializeSentry.js
  packages/app-project/src/helpers/logger/logNodeError.js
  packages/app-project/src/helpers/logger/logReactError.js
  packages/lib-classifier/docker-compose.yml
Labels: approved, enhancement

#1911 Fix broken Jenkins builds
  Jenkinsfile
Labels: approved

#1914 Add missing ID parameter to Simple Dropdown and Subject Group Comparison Tasks
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/SimpleDropdownTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/components/SubjectGroupComparisonTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonTask.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonTask.spec.js
Labels: approved, bug
