Repository zooniverse/front-end-monorepo, pull requests merged in 2020-02, with the labels that each got.

#1467 Project app: add source maps to the NextJS build
  packages/app-project/next.config.js
  packages/app-project/package.json
  yarn.lock
Labels: dependencies, dx

#1396 Multi frame viewer view components
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
Labels: enhancement

#1479 Update storybook
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies

#1474 Drawing new marks: fix pointer capture
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
Labels: bug

#1478 Update babel
  packages/app-content-pages/.babelrc
  packages/app-content-pages/package.json
  packages/app-project/.babelrc
  packages/app-project/package.json
  packages/lib-classifier/.babelrc
  packages/lib-classifier/package.json
  packages/lib-react-components/.babelrc
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies

#1434 Decouple task models from classifications
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
  packages/lib-classifier/src/plugins/drawingTools/README.md
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotationTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Annotation.js
  packages/lib-classifier/src/plugins/tasks/models/Annotation.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Task.js
  packages/lib-classifier/src/plugins/tasks/models/Task.spec.js
  packages/lib-classifier/src/store/AnnotationsStore.js
  packages/lib-classifier/src/store/AnnotationsStore.spec.js
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/Step.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
  packages/lib-classifier/test/factories/annotations/SingleChoiceAnnotationFactory.js
Labels: enhancement

#1473 Containers and exports to prepare for VSLCV composite viewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/index.js
Labels: enhancement

#1481 Add white to theme
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/README.md
  packages/lib-grommet-theme/src/index.js
Labels: enhancement

#1488 Make InteractionLayer configurable for SingleImageViewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
Labels: enhancement

#1447 Add SVGContext to the draggable story
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.stories.js
Labels: dx, refactor

#1497 Fix rebase mistake
  packages/app-project/package.json
  packages/lib-classifier/package.json
  yarn.lock
Labels: dependencies

#1496 Add CSS helper for styled-components
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Team/Team.js
  packages/app-content-pages/src/screens/Team/components/Person/components/TwitterLink/TwitterLink.js
  packages/app-content-pages/src/shared/components/AboutHeader/theme.js
  packages/app-project/src/components/AuthModal/AuthModal.js
  packages/app-project/src/components/AuthModal/theme.js
  packages/app-project/src/components/ProjectHeader/components/Avatar/Avatar.js
  packages/app-project/src/components/ProjectHeader/components/Background/Background.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.js
  packages/app-project/src/components/ThemeModeToggle/ThemeModeToggle.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Background/Background.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/theme.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/components/SubjectThumbnail/SubjectThumbnail.js
  packages/app-project/src/shared/components/NavLink/NavLink.js
  packages/app-project/src/shared/components/ProjectStatistics/components/Subtitle/Subtitle.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/ZoomEventLayer/ZoomEventLayer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/theme.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/theme.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/theme.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/theme.js
  packages/lib-classifier/src/components/Classifier/components/shared/Triangle/Triangle.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/index.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
  packages/lib-classifier/src/plugins/tasks/components/InputIcon/InputIcon.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/TaskInput.js
  packages/lib-react-components/src/FavouritesButton/HeartIcon.js
  packages/lib-react-components/src/GoldButton/theme.js
  packages/lib-react-components/src/Media/components/Audio/Audio.js
  packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js
  packages/lib-react-components/src/Media/components/Video/Video.js
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.js
  packages/lib-react-components/src/PrimaryButton/themes/blue.js
  packages/lib-react-components/src/PrimaryButton/themes/gold.js
  packages/lib-react-components/src/PrimaryButton/themes/green.js
  packages/lib-react-components/src/PrimaryButton/themes/teal.js
  packages/lib-react-components/src/SpacedText/SpacedText.js
  packages/lib-react-components/src/Tabs/theme.js
  packages/lib-react-components/src/ZooHeader/components/NavListItem/NavListItem.js
  packages/lib-react-components/src/ZooHeader/components/NavListItem/NavListItem.spec.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/components/NavButton/NavButton.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/components/NavButton/NavButton.spec.js
Labels: bug, performance

#1500 Remove types.maybe from safe references
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotationTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.js
  packages/lib-classifier/src/plugins/tasks/models/Task.js
Labels: refactor

#1501 Classifier: delete annotations by task key
  packages/lib-classifier/src/store/AnnotationsStore.js
  packages/lib-classifier/src/store/AnnotationsStore.spec.js
  packages/lib-classifier/src/store/ClassificationStore.js
Labels: bug

#1504 Drawing: fix evergreen subtask tests
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js
Labels: bug

#1495 Reset action for wherever annotations are stored
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/store/AnnotationsStore.js
  packages/lib-classifier/src/store/AnnotationsStore.spec.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/ResourceStore.js
  packages/lib-classifier/src/store/ResourceStore.spec.js
  packages/lib-classifier/test/factories/ClassificationFactory.js
  packages/lib-classifier/test/factories/tasks/SingleChoiceTaskFactory.js
Labels: refactor

#1503 Publications page: sort publications by year
  packages/app-content-pages/src/api/publications/publications.js
Labels: bug

#1510 Fix 1507 - allow MultipleChoiceTask component to observe changes again
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.js
Labels: bug

#1475 Drawing: Add classification snapshot processors
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Annotation.js
  packages/lib-classifier/src/plugins/tasks/models/Annotation.spec.js
  packages/lib-classifier/src/store/Classification.js
  packages/lib-classifier/src/store/Classification.spec.js
  packages/lib-classifier/src/store/ClassificationStore.js
Labels: enhancement

#1512 VSLCV grid layout and scaffolding for functionality
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/theme.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/FlipIcon/FlipIcon.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/FlipIcon/FlipIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/FlipIcon/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/mocks/temperature.png
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.js
Labels: enhancement

#1490 Use an uncontrolled textarea for text transcription
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
Labels: bug

#1524 Add drawing tool colors and highlighter tool colors to the theme
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/README.md
  packages/lib-grommet-theme/src/index.js
Labels: enhancement

#1494 Add build and default ENV vars for app dockerfiles
  Jenkinsfile
  README.md
  docker-compose.yml
  packages/app-content-pages/Dockerfile
  packages/app-content-pages/README.md
  packages/app-content-pages/docker-compose-prod.yml
  packages/app-content-pages/docker-compose.yml
  packages/app-content-pages/package.json
  packages/app-project/Dockerfile
  packages/app-project/README.md
  packages/app-project/docker-compose-prod.yml
  packages/app-project/docker-compose.yml
  packages/app-project/next.config.js
  packages/app-project/package.json
  packages/app-project/src/helpers/logger/initializeSentry.js
Labels: ops, refactor

#1531 Add babel-loader to app-project dev deps
  packages/app-project/package.json
Labels: bug, dependencies

#1526 Color and glyph picker utility helpers
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/constants.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/helpers/mocks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/getDataSeriesSymbol.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/getDataSeriesSymbol.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/glyphComponents.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/mockLightCurves/variableStar.json
Labels: refactor

#1493 Single Image viewer: add SVGPanZoom component
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
Labels: refactor

#1518 Add frame to subject viewer store, update multi-frame viewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js
  packages/lib-classifier/src/store/SubjectViewerStore.js
  packages/lib-classifier/src/store/SubjectViewerStore.spec.js
Labels: enhancement

#1535 Drawing: generate subtasks from tool details
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
Labels: enhancement

#1527 [VSLCV] Add in basic specs for getting JSON subject
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
Labels: enhancement

#1540 Transcription line updates
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js
Labels: enhancement

#1534 Drawing tools: draggable updates
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js
Labels: enhancement

#1525 Add frame viewer previous and next button functionality
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.spec.js
Labels: enhancement

#1520 Classifier: Add TranscriptionReductions
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/store/Subject.js
  packages/lib-classifier/src/store/Subject.spec.js
  packages/lib-classifier/src/store/SubjectStore.js
  packages/lib-classifier/src/store/TranscriptionReductions/TranscriptionReductions.js
  packages/lib-classifier/src/store/TranscriptionReductions/TranscriptionReductions.spec.js
  packages/lib-classifier/src/store/TranscriptionReductions/index.js
  packages/lib-classifier/src/store/TranscriptionReductions/mocks/index.js
  packages/lib-classifier/src/store/TranscriptionReductions/mocks/reducedEmptySubject.js
  packages/lib-classifier/src/store/TranscriptionReductions/mocks/reducedSubject.js
  packages/lib-classifier/src/store/Workflow.js
  packages/lib-classifier/src/store/Workflow.spec.js
  packages/lib-classifier/test/factories/WorkflowFactory.js
Labels: enhancement

#1545 Fix transcription line appearance
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/TranscriptionLine/TranscriptionLine.js
Labels: bug, design
