Repository zooniverse/front-end-monorepo, pull requests merged in 2020-07, with the labels that each got.

#1697 Sentry 5.18.1
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: approved, enhancement

#1683 Consensus UI
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/helpers/constants.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/helpers/setupMock.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/locales/en.json
  packages/lib-react-components/src/Modal/Modal.js
  packages/lib-react-components/src/Modal/Modal.spec.js
  packages/lib-react-components/src/Modal/README.md
  packages/lib-react-components/src/Modal/components/ModalBody/ModalBody.js
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.spec.js
  packages/lib-react-components/src/MovableModal/MovableModal.js
  packages/lib-react-components/src/MovableModal/MovableModal.spec.js
  packages/lib-react-components/src/MovableModal/README.md
Labels: approved, enhancement

#1700 [VSLCV] HR Diagram
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/locales/en.json
Labels: approved, enhancement

#1686 New classifications from previous transcriptions
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopupContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopupContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/index.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextPreviousAnnotationValues.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextPreviousAnnotationValues.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.spec.js
Labels: approved, enhancement, experiment, refactor

#1704 Rename all the variables related to the focus to visibility
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/FocusSeriesCheckBoxes/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/VisibilitySeriesCheckBoxes/VisibilitySeriesCheckBoxes.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/VisibilitySeriesCheckBoxes/VisibilitySeriesCheckBoxes.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/VisibilitySeriesCheckBoxes/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.spec.js
Labels: approved, bug, design

#1710 ZRC: export ZooniverseLogotype
  packages/lib-react-components/src/index.js
Labels: approved, bug

#1707 Add activeMark subTaskVisibility check to SubTaskPopup render
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopupContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopupContainer.spec.js
Labels: approved, bug

#1712 Patch React Components
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: approved

#1714 Update react components build
  README.md
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: approved

#1709 VSLCV phased focus
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/Label/Label.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/Label/Label.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/Label/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/PeriodMultipleControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/PeriodMultipleControls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/theme.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/VisibilitySeriesCheckBoxes/VisibilitySeriesCheckBoxes.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/VisibilitySeriesCheckBoxes/VisibilitySeriesCheckBoxes.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/theme.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/FlipIcon/FlipIcon.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/locales/en.json
Labels: approved, enhancement, refactor

#1711 Refactor transcribed lines ref for subtask positioning
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
Labels: approved, bug

#1725 Add https: true setting for the dev classifier
  packages/lib-classifier/webpack.dev.js
Labels: approved, dx

#1722 Refactor TranscribedLinesContainer for frame and shownMarks
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesContainer.spec.js
Labels: approved, bug

#1723 Refactor InteractionLayerContainer to filter previous annotation values per frame
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
Labels: approved, bug

#1691 Add ADR 27 Subject Viewer Config
  docs/arch/README.md
  docs/arch/adr-27.md
Labels: approved, discussion, documentation

#1721 VSLCV zoom controls for individual scatter plot modules
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Chart/Chart.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VXZoom/VXZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VXZoom/VXZoom.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/ZoomEventLayer/ZoomEventLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/ZoomEventLayer/ZoomEventLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/ZoomEnableButton/ZoomEnableButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/ZoomEnableButton/ZoomEnableButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/ZoomEnableButton/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js
  packages/lib-classifier/src/store/SubjectViewerStore.js
  packages/lib-classifier/test/setup.js
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/README.md
  packages/lib-grommet-theme/src/index.js
Labels: approved, enhancement

#1734 Update information on expected location files for VSLCV
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/README.md
Labels: approved, documentation
