Repository zooniverse/front-end-monorepo, pull requests merged in 2020-04, with the labels that each got.

#1589 Set sentry environment during the Jenkins build
  Jenkinsfile
  packages/app-content-pages/Dockerfile
  packages/app-content-pages/src/helpers/logger/initializeSentry.js
  packages/app-project/Dockerfile
Labels: approved, bug

#1598 app-project: Remove invalid divs from project nav
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
Labels: accessibility, approved, bug

#1574 Classifier: WorkflowConfiguration model
  packages/lib-classifier/src/store/FeedbackStore.spec.js
  packages/lib-classifier/src/store/SingleImageSubject/SingleImageSubject.js
  packages/lib-classifier/src/store/SingleImageSubject/SingleImageSubject.spec.js
  packages/lib-classifier/src/store/Subject/Subject.js
  packages/lib-classifier/src/store/Subject/Subject.spec.js
  packages/lib-classifier/src/store/SubjectGroup/SubjectGroup.js
  packages/lib-classifier/src/store/SubjectViewerStore.js
  packages/lib-classifier/src/store/Workflow/Workflow.js
  packages/lib-classifier/src/store/Workflow/Workflow.spec.js
  packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
  packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.spec.js
  packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/index.js
  packages/lib-classifier/src/store/Workflow/index.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
  packages/lib-classifier/webpack.dev.js
  packages/lib-classifier/webpack.dist.js
Labels: approved, enhancement, refactor

#1599 Create Sentry releases on push to master
  .github/workflows/main.yml
  packages/app-content-pages/src/helpers/logger/initializeSentry.js
  packages/app-project/src/helpers/logger/initializeSentry.js
Labels: dx

#1601 Split up workflow action files
  .github/workflows/main.yml
  .github/workflows/sentry-production-releases.yml
  .github/workflows/sentry-staging-releases.yml
Labels: approved

#1568 Content Pages: delete MyApp.getInitialProps
  packages/app-content-pages/pages/_app.js
Labels: approved, refactor

#1575 Classifier: Validate locations before creating subjects
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
  packages/lib-classifier/src/helpers/createLocationCounts/createLocationCounts.spec.js
  packages/lib-classifier/src/helpers/index.js
  packages/lib-classifier/src/helpers/validateMimeType/validateMimeType.js
  packages/lib-classifier/src/helpers/validateMimeType/validateMimeType.spec.js
  packages/lib-classifier/src/helpers/validateSubjectLocations/index.js
  packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.js
  packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.spec.js
  packages/lib-classifier/src/store/Subject/Subject.js
  packages/lib-classifier/src/store/Subject/Subject.spec.js
  packages/lib-classifier/src/store/SubjectStore.js
Labels: enhancement, experiment

#1608 Add the TranscriptionLine icon
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/helpers/getIcon.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/icons/TranscriptionLine.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/icons/index.js
  packages/lib-classifier/src/plugins/tasks/components/InputIcon/InputIcon.js
  packages/lib-classifier/src/plugins/tasks/components/InputStatus/InputStatus.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/components/TaskInputLabel/TaskInputLabel.js
Labels: approved, enhancement

#1609 Revert "Add the TranscriptionLine icon"
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/helpers/getIcon.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/icons/TranscriptionLine.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/icons/index.js
  packages/lib-classifier/src/plugins/tasks/components/InputIcon/InputIcon.js
  packages/lib-classifier/src/plugins/tasks/components/InputStatus/InputStatus.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/components/TaskInputLabel/TaskInputLabel.js
Labels: approved, bug, design

#1600 Refactor text task default, with suggestions, and tags
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/index.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTagButtons/TextTagButtons.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTagButtons/TextTagButtons.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTagButtons/index.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTagButtons/locales/en.json
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/index.js
Labels: approved, enhancement, refactor

#1605 Upgrade Sentry
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: approved, dx

#1607 ADR 26: Tracking errors with Sentry releases
  docs/arch/README.md
  docs/arch/adr-26.md
Labels: approved, documentation

#1614 Suggested changes for #1611
  packages/lib-classifier/src/components/Classifier/components/SubTaskPopup/SubTaskPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/SaveButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/SaveButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/theme.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/index.js
Labels: refactor

#1613 Add build environment to Docker image names
  Jenkinsfile
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
Labels: approved, dx

#1611 Move SubTaskPopup to InteractionLayerContainer
  packages/lib-classifier/src/components/Classifier/components/SubTaskPopup/SubTaskPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/SaveButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/SaveButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/theme.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
Labels: approved, refactor

#1612 Update Sentry production on release edit
  .github/workflows/sentry-production-releases.yml
Labels: approved, dx

#1622 Update Sentry production on tag push
  .github/workflows/sentry-production-releases.yml
Labels: approved

#1617 Transcription Line Icon
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/components/DataVisAnnotationTask.js
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/components/components/Graph2dRangeXIcon.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/helpers/getIcon.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/icons/TranscriptionLine.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/icons/index.js
  packages/lib-classifier/src/plugins/tasks/components/InputIcon/InputIcon.js
  packages/lib-classifier/src/plugins/tasks/components/InputStatus/InputStatus.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/TaskInput.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/components/TaskInputLabel/TaskInputLabel.js
Labels: approved, enhancement

#1615 Fix primary button
  packages/lib-react-components/src/PrimaryButton/PrimaryButton.stories.js
  packages/lib-react-components/src/PrimaryButton/themes/blue.js
  packages/lib-react-components/src/PrimaryButton/themes/gold.js
  packages/lib-react-components/src/PrimaryButton/themes/green.js
  packages/lib-react-components/src/PrimaryButton/themes/teal.js
  packages/lib-react-components/src/index.js
Labels: approved, bug

#1619 Update deployment Readme
  README.md
Labels: approved, documentation

#1624 Fix transcription task when there are other steps
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionAnnotation.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.spec.js
Labels: approved, bug

#1610 Create HidePreviousMarksButton
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/HidePreviousMarksButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/HidePreviousMarksButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/index.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
Labels: approved, enhancement

#1628 Fix a couple of React warnings
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/icons/TranscriptionLine.js
Labels: approved, refactor

#1629 Sub-task styles
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ResizeIcon/ResizeIcon.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ResizeIcon/ResizeIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ResizeIcon/index.js
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/src/index.js
Labels: approved, design
