Repository zooniverse/front-end-monorepo, pull requests merged in 2020-05, with the labels that each got.

#1632 Update ADR 25 with information about aggregation
  docs/arch/adr-25.md
Labels: approved, documentation

#1626 Add check for subtasks before setSubTaskVisibility
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
Labels: approved, bug

#1627 Classifier: add `subject_viewer_config` to `workflow.configuration`
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.js
  packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
Labels: approved, enhancement

#1641 Check for element type when keydown happens
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js
Labels: approved, bug

#1639 NextJS apps: Update NextJS, React and MobX State Tree
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: approved, enhancement

#1634 Content pages: remove next/link
  packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.js
Labels: approved, bug

#1649 Add k8s resource limits to production template
  kubernetes/deployment-production.tmpl
Labels: approved

#1647 Add frame to InteractionLayer mark creation
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
Labels: approved, bug

#1642 Refactor multi-frame viewer container with SVGPanZoom
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
Labels: approved, refactor

#1643 Refactor to reset pan, zoom, or rotate on new frame
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
  packages/lib-classifier/src/store/SubjectViewerStore.js
  packages/lib-classifier/src/store/SubjectViewerStore.spec.js
Labels: approved, refactor

#1646 Classifier: Remove updateClassificationMetadata
  packages/lib-classifier/src/store/Classification/Classification.js
  packages/lib-classifier/src/store/Classification/Classification.spec.js
  packages/lib-classifier/src/store/Classification/ClassificationMetadata.js
  packages/lib-classifier/src/store/Classification/ClassificationMetadata.spec.js
  packages/lib-classifier/src/store/Classification/index.js
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
Labels: approved, refactor

#1654 Add k8s limits for staging
  kubernetes/deployment-staging.tmpl
Labels: approved

#1655 Upgrade NextJS to 9.4.1
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/ProjectLink.js
  yarn.lock
Labels: approved, enhancement

#1653 When transcription task, use the hard coded colors for transcription line
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.spec.js
  packages/lib-classifier/src/store/TranscriptionReductions/TranscriptionReductions.js
  packages/lib-classifier/src/store/TranscriptionReductions/mocks/index.js
  packages/lib-classifier/src/store/TranscriptionReductions/mocks/reducedASMSubject.json
Labels: approved, refactor

#1635 Content pages: remove getInitialProps and the content API
  packages/app-content-pages/pages/about/publications.js
  packages/app-content-pages/pages/about/team.js
  packages/app-content-pages/pages/api/publications.js
  packages/app-content-pages/pages/api/team.js
  packages/app-content-pages/src/api/publications/publications.js
  packages/app-content-pages/src/api/shared/contentfulClient/contentfulClient.js
  packages/app-content-pages/src/api/team/team.js
  packages/app-content-pages/src/screens/Publications/PublicationsContainer.js
  packages/app-content-pages/src/screens/Publications/PublicationsContainer.spec.js
  packages/app-content-pages/src/screens/Publications/getServerSideProps.js
  packages/app-content-pages/src/screens/Publications/getServerSideProps.spec.js
  packages/app-content-pages/src/screens/Publications/index.js
  packages/app-content-pages/src/screens/Team/TeamContainer.js
  packages/app-content-pages/src/screens/Team/TeamContainer.spec.js
  packages/app-content-pages/src/screens/Team/getServerSideProps.js
  packages/app-content-pages/src/screens/Team/getServerSideProps.spec.js
  packages/app-content-pages/src/screens/Team/index.js
Labels: approved, refactor

#1658 Observe and react to subject advance
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/FeedbackStore.spec.js
  packages/lib-classifier/src/store/FieldGuideStore.js
  packages/lib-classifier/src/store/FieldGuideStore.spec.js
  packages/lib-classifier/src/store/ResourceStore.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/RootStore.spec.js
  packages/lib-classifier/src/store/SingleImageSubject/SingleImageSubject.spec.js
  packages/lib-classifier/src/store/Subject/Subject.spec.js
  packages/lib-classifier/src/store/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore.spec.js
  packages/lib-classifier/src/store/TutorialStore.spec.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
  packages/lib-classifier/src/store/WorkflowStore.spec.js
Labels: approved, bug, refactor
