Repository zooniverse/front-end-monorepo, pull requests merged in 2020-09, with the labels that each got.

#1779 Get real data to display in the VSLCV
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/mockData.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/Label/Label.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/VisibilitySeriesCheckBoxes/VisibilitySeriesCheckBoxes.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/mockLightCurves/variableStar.json
Labels: approved, bug

#1758 Refactor Step and WorkflowStepStore for branching
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
  packages/lib-classifier/src/store/Step.js
  packages/lib-classifier/src/store/Step.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
Labels: approved, refactor

#1768 Refactor task required property, Step and WorkflowStepStore for branching
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
  packages/lib-classifier/src/plugins/drawingTools/README.md
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.stories.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.stories.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Task.js
  packages/lib-classifier/src/store/AnnotationsStore.spec.js
  packages/lib-classifier/src/store/Step.js
  packages/lib-classifier/src/store/Step.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
  packages/lib-classifier/test/factories/tasks/MultipleChoiceTaskFactory.js
  packages/lib-classifier/test/factories/tasks/SingleChoiceTaskFactory.js
Labels: approved, bug, refactor

#1773 Allow PlainButton to set the label color prop
  packages/lib-react-components/src/PlainButton/PlainButton.js
  packages/lib-react-components/src/PlainButton/PlainButton.stories.js
  packages/lib-react-components/src/PlainButton/README.md
Labels: approved

#1774 Added instruction to run locally
  packages/lib-react-components/README.md
Labels: approved, documentation

#1784 [VSLCV] Use series option label and hardcoded string as fallback
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/mockLightCurves/variableStar.json
Labels: approved, bug

#1786 ZRC: Fix modal default colours
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.spec.js
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/CloseButton/CloseButton.js
  packages/lib-react-components/src/CloseButton/CloseButton.spec.js
  packages/lib-react-components/src/CloseButton/CloseButton.stories.js
  packages/lib-react-components/src/CloseButton/README.md
  packages/lib-react-components/src/Modal/Modal.js
  packages/lib-react-components/src/Modal/components/ModalBody/ModalBody.js
  packages/lib-react-components/src/Modal/components/ModalBody/ModalBody.spec.js
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.spec.js
  packages/lib-react-components/src/MovableModal/MovableModal.js
  packages/lib-react-components/src/MovableModal/MovableModal.stories.js
Labels: approved, bug

#1796 [VSLCV] Configurable bar chart y-axis domain
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
Labels: approved, enhancement

#1794 increase the request CPU
  kubernetes/deployment-staging.tmpl
Labels: approved

#1731 Project app: Subject set picker
  packages/app-project/src/screens/ProjectHomePage/components/Hero/HeroContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/SubjectSetPicker.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/SubjectSetPicker.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/SubjectSetPicker.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/components/SubjectSetCard/index.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/helpers/index.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/helpers/mockWorkflow.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/index.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/locales/en.json
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
Labels: approved

#1802 Project: Fix the workflows helper when all workflows are complete
  packages/app-project/src/screens/ProjectHomePage/components/Hero/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
Labels: approved, bug

#1800 Add nice to scaleLinear utility functions
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/utils.js
Labels: approved, enhancement

#1806 increase the app pods cpu request for k8s HPA targets
  kubernetes/deployment-production.tmpl
Labels: approved

#1793 Classifier: load specific workflows and subject sets
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/dev/index.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/store/ResourceStore/ResourceStore.js
  packages/lib-classifier/src/store/ResourceStore/ResourceStore.spec.js
  packages/lib-classifier/src/store/ResourceStore/index.js
  packages/lib-classifier/src/store/Workflow/SubjectSet/SubjectSet.js
  packages/lib-classifier/src/store/Workflow/SubjectSet/SubjectSet.spec.js
  packages/lib-classifier/src/store/Workflow/SubjectSet/index.js
  packages/lib-classifier/src/store/Workflow/SubjectSetStore/SubjectSetStore.js
  packages/lib-classifier/src/store/Workflow/SubjectSetStore/SubjectSetStore.spec.js
  packages/lib-classifier/src/store/Workflow/SubjectSetStore/index.js
  packages/lib-classifier/src/store/Workflow/Workflow.js
  packages/lib-classifier/src/store/Workflow/Workflow.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
  packages/lib-classifier/src/store/WorkflowStore.js
  packages/lib-classifier/src/store/WorkflowStore.spec.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.spec.js
  packages/lib-classifier/src/store/WorkflowStore/index.js
  packages/lib-classifier/test/factories/SubjectSetFactory.js
  packages/lib-classifier/test/factories/WorkflowFactory.js
  packages/lib-classifier/test/factories/index.js
Labels: approved, enhancement

#1815 modify HPA scaling metrics
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
Labels: approved

#1811 [VSLCV] Dynamically determine the bar charts domain
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
Labels: approved, enhancement

#1818 turn on app cache headers
  kubernetes/deployment-staging.tmpl
Labels: approved, ops

#1821 enable cache headers on production services
  kubernetes/deployment-production.tmpl
Labels: approved

#1814 add prod service pod disruption budgets
  kubernetes/deployment-production.tmpl
Labels: approved

#1816 Refactor to use connector component with the store
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/index.js
Labels: approved, refactor

#1801 [VSLCV] Make glyph less visible when toggled off
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/Label/Label.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/VisibilitySeriesCheckBoxes/VisibilitySeriesCheckBoxes.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesVisible/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesVisible/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesVisible/isDataSeriesVisible.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesVisible/isDataSeriesVisible.spec.js
Labels: approved, design

#1820 Upgrade to mobx-react 6
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js
  yarn.lock
Labels: approved, dependencies

#1817 Restore workflowStore observers
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
Labels: approved

#1795 [VSLCV] Increase row sizes and image area size
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
Labels: approved, bug, design

#1822 notify ops when job succeeds
  Jenkinsfile
Labels: approved

#1819 [VSLCV] dynamic image size
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/locales/en.json
Labels: approved, refactor
