Repository zooniverse/front-end-monorepo, pull requests merged in 2020-03, with the labels that each got.

#1541 [VSLCV] Y-axis inversion control
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/Axis/Axis.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/InnerTickAxis/InnerTickAxis.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/utils.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/utils.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.spec.js
Labels: enhancement

#1533 [VSLCV] Series focus control
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/FocusSeriesCheckBoxes/FocusSeriesCheckBoxes.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/FocusSeriesCheckBoxes/FocusSeriesCheckBoxes.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/FocusSeriesCheckBoxes/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.js
Labels: enhancement

#1549 Classifier: remove inject/observer from individual task components
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/components/DataVisAnnotationTask.js
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/components/DataVisAnnotationTask.spec.js
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotationTask.js
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotationTask.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/DrawingTask.js
  packages/lib-classifier/src/store/DataVisAnnotatingStore.js
  packages/lib-classifier/src/store/DataVisAnnotatingStore.spec.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/RootStore.spec.js
Labels: bug

#1517 Drawing SubTasks - Popup UI component (v2)
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubTaskPopup/SubTaskPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubTaskPopup/components/SaveButton/SaveButton.js
  packages/lib-classifier/src/components/Classifier/components/SubTaskPopup/components/SaveButton/SaveButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubTaskPopup/components/SaveButton/index.js
  packages/lib-classifier/src/components/Classifier/components/SubTaskPopup/components/SaveButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubTaskPopup/components/SaveButton/theme.js
  packages/lib-classifier/src/components/Classifier/components/SubTaskPopup/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
  yarn.lock
Labels: enhancement

#1553 Classifier: Tasks: Test all registered task models
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/store/Subject.js
Labels: enhancement

#1551 Classifier: Pass the theme prop to task components
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuide.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.js
Labels: bug

#1552 Add frame scroll handler
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js
Labels: enhancement

#1547 [VSLCV] Calculating phased JSON scatter plot data
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/Background.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/Background.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/theme.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/mockLightCurves/variableStar.json
Labels: enhancement

#1561 add approved labels to pull requests
  .github/workflows/main.yml
Labels: approved, dx

#1555 Classifier: Consolidate store subject observers
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/store/AnnotationsStore.js
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/FeedbackStore.js
  packages/lib-classifier/src/store/FeedbackStore.spec.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/RootStore.spec.js
  packages/lib-classifier/src/store/Subject.spec.js
  packages/lib-classifier/src/store/TutorialStore.spec.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
  packages/lib-classifier/src/store/WorkflowStore.spec.js
Labels: approved, bug

#1563 Update Grommet to 2.11
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-project/pages/_app.js
  packages/app-project/src/components/AuthModal/components/LoginForm/components/Form/Form.spec.js
  packages/app-project/src/components/AuthModal/components/RegisterForm/components/Form/Form.spec.js
  packages/app-project/src/helpers/GrommetWrapper/GrommetWrapperContainer.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
  packages/app-project/src/shared/components/CollectionsModal/components/CreateCollection/CreateCollection.spec.js
  packages/app-project/stores/UI.js
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-panoptes-js/package.json
  packages/lib-react-components/package.json
  packages/lib-react-components/src/Markdownz/Markdownz.spec.js
  packages/lib-react-components/src/helpers/withCustomFormik/withCustomFormik.spec.js
  yarn.lock
Labels: approved, dependencies, refactor

#1560 [VSLCV] Phased bar charts
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/components/Bars/Bars.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/mockData.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/utils.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/FocusSeriesCheckBoxes/FocusSeriesCheckBoxes.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/mockLightCurves/variableStar.json
Labels: approved, enhancement, refactor

#1559 Classifier: test stubPanoptesJs
  packages/lib-classifier/test/mocha.opts
  packages/lib-classifier/test/stubPanoptesJs/stubPanoptesJs.js
  packages/lib-classifier/test/stubPanoptesJs/stubPanoptesJs.spec.js
Labels: approved, enhancement

#1564 Transcription task
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/README.md
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/index.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionAnnotation.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.js
  packages/lib-classifier/src/plugins/tasks/index.js
  packages/lib-classifier/src/store/Subject.js
  packages/lib-classifier/src/store/Subject.spec.js
  packages/lib-classifier/src/store/Workflow.js
  packages/lib-classifier/src/store/Workflow.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
Labels: approved, enhancement

#1562 Validate subject mimetypes
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/helpers/createLocationCounts/createLocationCounts.js
  packages/lib-classifier/src/helpers/createLocationCounts/createLocationCounts.spec.js
  packages/lib-classifier/src/helpers/validateMimeType/index.js
  packages/lib-classifier/src/helpers/validateMimeType/validateMimeType.js
  packages/lib-classifier/src/helpers/validateMimeType/validateMimeType.spec.js
  packages/lib-classifier/src/helpers/validateSubjectLocations/index.js
  packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.js
  packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.spec.js
  packages/lib-classifier/src/store/Subject.spec.js
Labels: approved, enhancement

#1550 Classifier: Add the move cursor to draggable subjects
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
Labels: approved, enhancement

#1570 Project hero stories
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
Labels: approved, bug, storybook

#1569 Upgrade NextJS to 9.3
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: approved, dependencies

#1360 Drawing: add the ellipse tool
  packages/lib-classifier/src/plugins/drawingTools/components/DragHandle/DragHandle.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.js
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/index.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Ellipse/Ellipse.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Ellipse/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/EllipseTool/EllipseTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/EllipseTool/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/index.js
Labels: approved, enhancement, experiment

#1565 Classifier: Refactor types.union with references
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/store/Step.js
Labels: approved, refactor

#1577 Classifier: fix Tasks storybook errors
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStore.js
Labels: approved, bug

#1579 Fix background, Grommet props for Task stories
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.js
Labels: approved, storybook

#1573 Classifier: Subject model: use tryReference
  packages/lib-classifier/src/store/Subject/Subject.js
Labels: approved, refactor

#1580 Classifier: fix pointer not found errors
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
Labels: approved, bug

#1582 Classifier: fix zoom button key handlers
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
Labels: approved, bug

#1539 Transcription: show transcribed lines
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/Tooltip/Tooltip.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/Tooltip/Tooltip.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/Tooltip/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/locales/en.json
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/TranscriptionLine/TranscriptionLine.js
  packages/lib-classifier/src/store/SubjectStore.js
  packages/lib-classifier/src/store/TranscriptionReductions/TranscriptionReductions.js
Labels: approved, enhancement

#1572 Classifier: subjects.append: test that order is preserved
  packages/lib-classifier/src/store/SubjectStore.spec.js
Labels: approved, enhancement

#1587 Add withSourceMaps to app-content-pages
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
Labels: approved, dx

#1590 Tag sentry releases with git commit hashes
  Jenkinsfile
  packages/app-content-pages/Dockerfile
  packages/app-content-pages/next.config.js
  packages/app-content-pages/src/helpers/logger/initializeSentry.js
  packages/app-project/Dockerfile
  packages/app-project/next.config.js
  packages/app-project/src/helpers/logger/initializeSentry.js
Labels: approved

#1578 Multi-frame viewer styling clean-up
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js
Labels: approved, enhancement

#1593 Remove shared environment from Jenkins builds
  Jenkinsfile
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
  packages/app-project/src/helpers/logger/initializeSentry.js
Labels: approved

#1556 Subject Group Viewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.js
  packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.js
  packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.spec.js
  packages/lib-classifier/src/store/Subject/Subject.js
Labels: approved, experiment
