Repository zooniverse/front-end-monorepo, pull requests merged in 2020-12, with the labels that each got.

#1889 Video Data Model
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.js
  packages/lib-classifier/src/helpers/createLocationCounts/createLocationCounts.js
  packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.js
  packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.spec.js
  packages/lib-classifier/src/store/SingleVideoSubject/SingleVideoSubject.js
  packages/lib-classifier/src/store/SingleVideoSubject/SingleVideoSubject.spec.js
  packages/lib-classifier/src/store/SingleVideoSubject/index.js
  packages/lib-classifier/src/store/Subject/Subject.js
  packages/lib-classifier/src/store/SubjectStore.js
Labels: approved

#1864 Default to hide summaries and fix associated bugs
  packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
  packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
Labels: approved, bug

#1918 Update the docs that got missed from #1887
  README.md
  docs/arch/adr-12.md
  packages/app-content-pages/README.md
  packages/app-project/README.md
Labels: approved, documentation

#1923 Add top-level storybook script
  package.json
  packages/app-content-pages/docker-compose.yml
  packages/app-content-pages/package.json
  packages/lib-react-components/package.json
Labels: approved

#1924 Remove hardcoded cancel value from MovableModal
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/MovableModal/MovableModal.js
Labels: approved, bug

#1913 [Security] Upgrade storybook to 6.1
  package.json
  packages/app-content-pages/.storybook/addons.js
  packages/app-content-pages/.storybook/config.js
  packages/app-content-pages/.storybook/main.js
  packages/app-content-pages/.storybook/manager.js
  packages/app-content-pages/package.json
  packages/app-project/.storybook/addons.js
  packages/app-project/.storybook/config.js
  packages/app-project/.storybook/lib/backgrounds.js
  packages/app-project/.storybook/main.js
  packages/app-project/.storybook/manager.js
  packages/app-project/.storybook/preview.js
  packages/app-project/package.json
  packages/lib-classifier/.babelrc
  packages/lib-classifier/.storybook/addons.js
  packages/lib-classifier/.storybook/config.js
  packages/lib-classifier/.storybook/lib/backgrounds.js
  packages/lib-classifier/.storybook/main.js
  packages/lib-classifier/.storybook/manager.js
  packages/lib-classifier/.storybook/preview.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/RetiredBanner/RetiredBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/UserHasFinishedWorkflowBanner/UserHasFinishedWorkflowBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/WorkflowIsFinishedBanner/WorkflowIsFinishedBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.stories.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/components/DataVisAnnotationTask.stories.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/DrawingTask.stories.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.stories.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/SimpleDropdownTask.stories.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.stories.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.stories.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/TranscriptionTask.stories.js
  packages/lib-react-components/.babelrc
  packages/lib-react-components/.storybook/addons.js
  packages/lib-react-components/.storybook/config.js
  packages/lib-react-components/.storybook/lib/backgrounds.js
  packages/lib-react-components/.storybook/main.js
  packages/lib-react-components/.storybook/manager.js
  packages/lib-react-components/.storybook/preview.js
  packages/lib-react-components/package.json
  yarn.lock
Labels: approved, enhancement, security

#1926 Add a GitHub action to run the CI tests
  .github/workflows/ci-tests.yml
  .travis.yml
  package.json
Labels: approved

#1933 increase ram limits for staging apps
  kubernetes/deployment-staging.tmpl
Labels: approved

#1885 Classifier: WorkflowStep type
  packages/lib-classifier/src/store/Workflow/Workflow.js
  packages/lib-classifier/src/store/Workflow/Workflow.spec.js
Labels: approved, enhancement

#1941 Remove react-rnd dependency from the classifier.
  packages/lib-classifier/package.json
  yarn.lock
Labels: approved, dependencies

#1942 [Security] Remove storybook/addon-notes
  packages/app-content-pages/.storybook/main.js
  packages/app-content-pages/package.json
  packages/app-project/.storybook/main.js
  packages/app-project/package.json
  packages/lib-classifier/.storybook/main.js
  packages/lib-classifier/package.json
  packages/lib-react-components/.storybook/main.js
  packages/lib-react-components/package.json
  packages/lib-react-components/src/Markdownz/Markdownz.stories.js
  yarn.lock
Labels: security

#1921 Drawing tasks: add createMark(event) to the drawing canvas
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
Labels: approved, refactor

#1932 Classifier: Convert drawing stories to CSF
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.stories.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js
Labels: approved, storybook

#1922 Drawing tools: add actions to handle events during mark creation
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/plugins/drawingTools/README.md
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/TranscriptionLine/TranscriptionLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/TranscriptionLineTool/TranscriptionLineTool.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/TranscriptionLineTool/TranscriptionLineTool.spec.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
Labels: approved, bug, refactor

#1946 Fix mobx warning about accessing an undefined index in an array
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
Labels: approved, bug

#1950 Fix subtask positioning
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
Labels: approved, bug

#1917 Add survey task annotation model
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyAnnotation.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyAnnotation.spec.js
Labels: approved, enhancement

#1935 Add survey task model
  packages/lib-classifier/src/plugins/tasks/SurveyTask/index.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyTask.spec.js
Labels: approved, enhancement

#1916 Refactor multi-frame viewer with Media component, thumbnail service
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
Labels: approved
