Repository zooniverse/front-end-monorepo, pull requests merged in 2020-01, with the labels that each got.

#1392 Update handlebars
  package.json
  yarn.lock
Labels: dependencies, dx, security

#1373 Add bs-local.com to allowedHosts webpack config
  packages/lib-classifier/webpack.dev.js
Labels: dx

#1384 Drawing: Add delete button specs
  packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.js
  packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.spec.js
Labels: enhancement

#1393 Drawing: Replace svg props with SVGContext
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/DrawingToolRoot.js
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.js
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.spec.js
  packages/lib-classifier/src/plugins/drawingTools/shared/SVGContext.js
Labels: enhancement

#1388 Add subject image rotation
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
  packages/lib-classifier/src/store/SubjectViewerStore.js
  packages/lib-classifier/src/store/SubjectViewerStore.spec.js
Labels: enhancement

#1389 Subject image pan and zoom
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/DrawingToolRoot.js
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js
Labels: enhancement

#1372 Drawing: Use the state tree to get a mark's tool
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/DrawingToolRoot.js
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.spec.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Line/Line.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Point/Point.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/index.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
Labels: enhancement

#1390 Drawing annotation model ADR
  docs/arch/README.md
  docs/arch/adr-24.md
Labels: documentation

#1403 Tasks: add task.reset() and step.reset()
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Task.js
  packages/lib-classifier/src/plugins/tasks/readme.md
  packages/lib-classifier/src/store/Step.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
Labels: refactor

#1405 Update to node 12
  .travis.yml
  Dockerfile
  README.md
  package.json
  packages/app-content-pages/src/api/publications/buildResponse.js
  packages/app-content-pages/src/api/publications/buildResponse.spec.js
Labels: dependencies

#1409 Remove useState from tasks
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
Labels: bug

#1415 Drawing: Add marks prop to InteractionLayer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
Labels: bug

#1399 Refactor banner to not block being able to delete TESS annotations
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/RetiredBanner/RetiredBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/UserHasFinishedWorkflowBanner/UserHasFinishedWorkflowBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/WorkflowIsFinishedBanner/WorkflowIsFinishedBannerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  yarn.lock
Labels: bug, design

#1401 Use a relative scale for SVG zooming
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
Labels: bug

#1413 Add Line and Point stories
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.js
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.stories.js
Labels: dx

#1421 Drawing: Add angle and distance helpers to marks
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
Labels: enhancement

#1414 Make mark.tool generic
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
Labels: enhancement

#1379 [VSLCV] Multiple series support for scatter plot
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/constants.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/mockData.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/utils.js
Labels: enhancement

#1422 Drawing: Add x, y, angle to drawing tool root
  packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/DrawingToolRoot.js
  packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/DrawingToolRoot.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Point/Point.js
Labels: enhancement

#1431 Drawing: Add toolType to marks
  packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/DrawingToolRoot.spec.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/LineTool/LineTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/PointTool/PointTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.spec.js
Labels: enhancement

#1375 [VSLCV] Individual bar focus
  packages/lib-classifier/.storybook/webpack.config.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/components/Triangle/Triangle.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/components/Bars/Bars.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/components/Bars/Bars.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/components/Bars/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/mockData.js
  packages/lib-classifier/src/components/Classifier/components/shared/Triangle/Triangle.js
  packages/lib-classifier/src/components/Classifier/components/shared/Triangle/Triangle.spec.js
  packages/lib-classifier/src/components/Classifier/components/shared/Triangle/index.js
  packages/lib-classifier/test/mocha.opts
  packages/lib-classifier/webpack.dev.js
  packages/lib-classifier/webpack.dist.js
  yarn.lock
Labels: accessibility, enhancement

#1420 Drawing: Add pointer capture to mark creation
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
Labels: enhancement

#1419 Drawing: Rename DrawingToolRoot to Mark
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/DrawingToolRoot/index.js
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/index.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/index.js
Labels: refactor

#1433 Scatter plot styles
  packages/lib-classifier/.babelrc
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/Background.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/Background.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/Axes.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/Axes.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/Axis/Axis.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/Axis/Axis.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  yarn.lock
Labels: design, enhancement

#1417 Classifier: add Rectangle drawing tool
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/index.js
  packages/lib-classifier/src/plugins/drawingTools/components/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Line/Line.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Point/Point.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Rectangle/Rectangle.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Rectangle/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/RectangleTool/RectangleTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/RectangleTool/RectangleTool.spec.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/RectangleTool/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/index.js
Labels: enhancement, experiment

#1430 Add taskType to annotations
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotationTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.js
  packages/lib-classifier/src/plugins/tasks/models/Annotation.js
  packages/lib-classifier/src/plugins/tasks/models/Annotation.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Task.js
  packages/lib-classifier/src/plugins/tasks/models/Task.spec.js
  packages/lib-classifier/src/plugins/tasks/readme.md
  packages/lib-classifier/src/store/AnnotationsStore.spec.js
  packages/lib-classifier/test/factories/annotations/SingleChoiceAnnotationFactory.js
Labels: enhancement

#1376 Drawing: add drawing tool subtasks to the models
  packages/lib-classifier/src/plugins/drawingTools/README.md
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
Labels: enhancement

#1397 Add ADR 25 about drawing sub-tasks
  docs/arch/adr-25.md
Labels: documentation, dx

#1432 Decouple Task components from classifications
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/components/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/components/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Annotation.js
  packages/lib-classifier/src/plugins/tasks/models/Task.js
  packages/lib-classifier/src/store/Step.spec.js
Labels: enhancement

#1449 [VSLCV] Scatter bar viewer support for error bars
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/mockData.js
Labels: enhancement

#1453 Project app: catch errors in initial page render
  packages/app-project/next.config.js
  packages/app-project/pages/_document.js
Labels: bug, dx
