Repository zooniverse/front-end-monorepo, pull requests merged in 2021-01, with the labels that each got.

#1947 Remove Travis CI
  .travis.yml
Labels: approved, dx

#1958 Upgrade outdated packages
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-panoptes-js/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: approved, dependencies, security

#1959 [Security] Patch outdated dependencies
  yarn.lock
Labels: approved, security

#1823 Project app: use getServerSideProps on all project pages
  packages/app-project/pages/_app.js
  packages/app-project/pages/projects/[owner]/[project]/classify/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/index.js
  packages/app-project/src/helpers/getCookie/getCookie.js
  packages/app-project/src/helpers/getCookie/getCookie.spec.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js
  packages/app-project/src/helpers/getDefaultPageProps/index.js
  packages/app-project/stores/Project.js
  packages/app-project/stores/Project.spec.js
  packages/app-project/stores/UI.js
  packages/app-project/stores/UI.spec.js
Labels: approved, enhancement, refactor

#1962 Fix initStore args
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js
Labels: approved, bug

#1961 Classifier: Project default workflow
  packages/lib-classifier/src/store/Project.js
  packages/lib-classifier/src/store/Project.spec.js
  packages/lib-classifier/src/store/Project/Project.js
  packages/lib-classifier/src/store/Project/Project.spec.js
  packages/lib-classifier/src/store/Project/index.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
Labels: approved, refactor

#1809 Render project workflows on the server
  packages/app-project/pages/projects/[owner]/[project]/classify/index.js
  packages/app-project/pages/projects/[owner]/[project]/index.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/index.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePageContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/HeroContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/HeroContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelectorContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelectorContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/index.js
  packages/app-project/src/screens/ProjectHomePage/index.js
Labels: approved, enhancement

#1930 ADR: Video Player
  docs/arch/README.md
  docs/arch/adr-29.md
Labels: approved, documentation, dx

#1886 Upgrade NextJS to 9.5
  packages/app-content-pages/package.json
  packages/app-content-pages/src/screens/Publications/getStaticProps.js
  packages/app-content-pages/src/screens/Team/getStaticProps.js
  packages/app-project/package.json
  yarn.lock
Labels: enhancement

#1927 Video viewer
  .gitignore
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/index.js
  yarn.lock
Labels: approved, enhancement

#1943 Restrict the Jenkins builds
  Jenkinsfile
Labels: approved

#1944 Add a production test build to CI Tests
  .github/workflows/ci-tests.yml
  README.md
  packages/app-content-pages/server/set-logging.spec.js
  packages/app-project/server/set-logging.spec.js
  packages/app-project/stores/UI.spec.js
  packages/lib-react-components/src/helpers/withCustomFormik/withCustomFormik.spec.js
Labels: approved, dx, ops

#1957 Project: Convert workflow selector stories to CSF
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/WorkflowSelector.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/SubjectSetPicker.stories.js
Labels: approved, dx, refactor

#1967 Create general field guide story
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuide.stories.js
Labels: approved, storybook

#1969 ZRC: Add Readme docs to React Components stories
  packages/lib-react-components/src/AdminCheckbox/AdminCheckbox.stories.js
  packages/lib-react-components/src/CloseButton/CloseButton.stories.js
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.stories.js
  packages/lib-react-components/src/GoldButton/GoldButton.stories.js
  packages/lib-react-components/src/Media/Media.stories.js
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.stories.js
  packages/lib-react-components/src/Modal/Modal.stories.js
  packages/lib-react-components/src/MovableModal/MovableModal.stories.js
  packages/lib-react-components/src/PlainButton/PlainButton.stories.js
  packages/lib-react-components/src/PrimaryButton/PrimaryButton.stories.js
  packages/lib-react-components/src/SpacedHeading/SpacedHeading.stories.js
  packages/lib-react-components/src/SpacedText/SpacedText.stories.js
  packages/lib-react-components/src/Tabs/Tabs.stories.js
  packages/lib-react-components/src/Tooltip/Tooltip.stories.js
  packages/lib-react-components/src/Tooltip/components/Label/Label.stories.js
  packages/lib-react-components/src/Tooltip/components/Triangle/Triangle.stories.js
  packages/lib-react-components/src/ZooFooter/ZooFooter.stories.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.stories.js
Labels: approved, dx, enhancement

#1977 Update newrelic to version 7 in preparation of node 14 update
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: approved, dependencies

#1953 Add an annotation prop to text tasks
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.js
Labels: approved, bug

#1960 Project app: Rewrite project model tests
  packages/app-project/stores/Project.spec.js
Labels: approved, bug

#1963 Remove /classify as the route for a project's default workflow
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.js
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
  packages/app-project/stores/Project.js
  packages/app-project/stores/Project.spec.js
  packages/lib-classifier/src/store/Project/Project.js
  packages/lib-classifier/src/store/Project/Project.spec.js
Labels: approved, enhancement

#1988 Refactor suggestions task
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.spec.js
Labels: approved, bug

#1985 Classifier: use mark.isComplete for subtask validation
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
Labels: approved, bug, refactor

#1966 Project: Add workflow selection to the Classify page
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/NarrowLayout/NarrowLayout.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/NarrowLayout/NarrowLayout.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WideLayout/WideLayout.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WideLayout/WideLayout.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.stories.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorContainer.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorContainer.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/SubjectSetPicker/SubjectSetPicker.js
  packages/app-project/src/shared/components/WorkflowSelector/components/SubjectSetPicker/SubjectSetPicker.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/SubjectSetPicker/SubjectSetPicker.stories.js
  packages/app-project/src/shared/components/WorkflowSelector/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js
  packages/app-project/src/shared/components/WorkflowSelector/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/SubjectSetPicker/components/SubjectSetCard/index.js
  packages/app-project/src/shared/components/WorkflowSelector/components/SubjectSetPicker/helpers/index.js
  packages/app-project/src/shared/components/WorkflowSelector/components/SubjectSetPicker/helpers/mockWorkflow.js
  packages/app-project/src/shared/components/WorkflowSelector/components/SubjectSetPicker/index.js
  packages/app-project/src/shared/components/WorkflowSelector/components/SubjectSetPicker/locales/en.json
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/index.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/locales/en.json
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/theme.js
  packages/app-project/src/shared/components/WorkflowSelector/components/index.js
  packages/app-project/src/shared/components/WorkflowSelector/index.js
  packages/app-project/src/shared/components/WorkflowSelector/locales/en.json
  packages/app-project/stores/Project.spec.js
Labels: approved, enhancement

#1767 Add ADR 29: Simple Dropdown Task
  docs/arch/README.md
  docs/arch/adr-29.md
  docs/arch/adr-30.md
Labels: approved, documentation

#1965 Add a 301 redirect to /classify
  packages/app-project/pages/projects/[owner]/[project]/classify/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/index.js
Labels: approved

#2001 Fix previous marks from caesar render for transcription task
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarksConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarksConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesContainer.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/DragHandle/DragHandle.js
  packages/lib-classifier/src/store/Classification/Classification.js
  packages/lib-classifier/src/store/Classification/Classification.spec.js
  packages/lib-classifier/src/store/Workflow/Workflow.js
  packages/lib-classifier/src/store/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore.spec.js
  packages/lib-classifier/test/factories/index.js
Labels: approved, bug

#1995 Accessible headings for issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request--data-store--ops--etc.md
  .github/ISSUE_TEMPLATE/feature-request--ux--ui--accessibility--design--etc.md
Labels: accessibility, approved, bug

#1975 Field guide refactoring
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideConnector.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideContainer.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuide.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuide.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/components/SpacedHeading/SpacedHeading.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/components/SpacedHeading/SpacedHeading.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/components/SpacedHeading/index.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/index.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItems.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItems.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/index.js
Labels: approved, refactor

#2006 Style PreviousMarks with pointer-events: none
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.spec.js
Labels: approved, bug

#1983 ZRC: allow for modals that can't be closed
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/Modal/Modal.js
  packages/lib-react-components/src/Modal/Modal.spec.js
  packages/lib-react-components/src/Modal/Modal.stories.js
  packages/lib-react-components/src/Modal/README.md
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.spec.js
  packages/lib-react-components/src/MovableModal/MovableModal.js
  packages/lib-react-components/src/MovableModal/MovableModal.stories.js
  packages/lib-react-components/src/helpers/withLayer/withLayer.js
  packages/lib-react-components/src/helpers/withLayer/withLayer.spec.js
Labels: approved

#1980 Video controller
  .gitignore
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/VideoController.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/components/FormattedTime/FormattedTime.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/components/FormattedTime/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/components/Slider/Slider.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/components/Slider/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/locales/en.json
Labels: approved, design, enhancement

#1937 Add survey task characteristics property validation
  packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyTask.spec.js
Labels: approved, enhancement

#1974 Add SubjectGroup end point to Classifier
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.spec.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonAnnotation.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonTask.spec.js
  packages/lib-classifier/src/store/SubjectGroup/SubjectGroup.js
  packages/lib-classifier/src/store/SubjectGroup/SubjectGroup.spec.js
  packages/lib-classifier/src/store/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore.spec.js
Labels: approved, enhancement

#2008 Engaging Crowds: Subject set selection fixes
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.stories.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/index.js
  packages/app-project/src/shared/components/SubjectSetPicker/locales/en.json
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/locales/en.json
Labels: approved
