Repository zooniverse/front-end-monorepo, pull requests merged in 2021-04, with the labels that each got.

#2077 Upgrade to node 14
  .github/workflows/ci-tests.yml
  Dockerfile
  README.md
  package.json
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-async-states/package.json
  packages/lib-classifier/package.json
  packages/lib-grommet-theme/package.json
  packages/lib-panoptes-js/package.json
  packages/lib-react-components/package.json
Labels: approved, dependencies

#2071 Add SurveyTaskContainer to connect survey task components to annotation
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTaskContainer.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTaskContainer.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/Chooser.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/helpers/getFilteredChoiceIds.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/helpers/getFilteredChoiceIds.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/index.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/index.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/mock-data/task.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyTask.js
Labels: approved, enhancement

#2085 Update grommet and grommet-icons
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-project/src/components/ThemeModeToggle/ThemeModeToggle.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkLink.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkLink.spec.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/CollectionsButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/CollectionsButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/MetadataButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/MetadataButton.spec.js
  packages/lib-react-components/package.json
  packages/lib-react-components/src/CloseButton/CloseButton.js
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.js
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.spec.js
  yarn.lock
Labels: approved, dependencies

#2089 Update test dependencies
  package.json
  packages/app-content-pages/package.json
  packages/app-content-pages/test/.mocharc.json
  packages/app-content-pages/test/mocha.opts
  packages/app-project/package.json
  packages/app-project/test/.mocharc.json
  packages/app-project/test/mocha.opts
  packages/lib-async-states/package.json
  packages/lib-async-states/test/.mocharc.json
  packages/lib-async-states/test/mocha.opts
  packages/lib-classifier/package.json
  packages/lib-classifier/test/.mocharc.json
  packages/lib-panoptes-js/package.json
  packages/lib-panoptes-js/test/.mocharc.json
  packages/lib-panoptes-js/test/mocha.opts
  packages/lib-react-components/package.json
  packages/lib-react-components/test/.mocharc.json
  packages/lib-react-components/test/mocha.opts
  yarn.lock
Labels: dependencies

#2092 Build dependency updates
  package.json
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-async-states/package.json
  packages/lib-classifier/package.json
  packages/lib-classifier/webpack.dev.js
  packages/lib-grommet-theme/package.json
  packages/lib-panoptes-js/package.json
  packages/lib-react-components/package.json
  packages/lib-react-components/webpack.dist.js
  packages/tools-standard/package.json
  yarn.lock
Labels: dependencies

#2080 Classifier drawing tools: fix focus and window scroll position for new marks
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
Labels: approved, bug, refactor

#2091 Project app: Add set_member_subjects to API mocks for page props
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.spec.js
Labels: approved

#2097 Fix Done & Talk for single answer tasks
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js
Labels: approved, bug

#2095 Refactor survey task component PropTypes
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.js
Labels: approved

#2096 Remove mocha opts file missed during upgrade
  packages/lib-classifier/test/mocha.opts
Labels: approved, refactor

#2094 Add survey task FilterIcon
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterIcon.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterIcon.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
Labels: approved

#2104 Classifier: Set step.next for transcription tasks
  packages/lib-classifier/src/store/Workflow/Workflow.js
  packages/lib-classifier/src/store/helpers/convertWorkflowToUseSteps/convertWorkflowToUseSteps.js
  packages/lib-classifier/src/store/helpers/convertWorkflowToUseSteps/convertWorkflowToUseSteps.spec.js
Labels: approved

#2062 Refactor task navigation
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/index.js
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.js
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.spec.js
Labels: approved, refactor

#2109 Fix broken stories by making setStepsAndTasks available again
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
Labels: approved, bug, storybook

#2101 Classifier: add the subjectID prop
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/dev/index.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/store/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore.spec.js
  packages/lib-classifier/src/store/Workflow/Workflow.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.spec.js
  packages/lib-classifier/test/stubPanoptesJs/stubPanoptesJs.js
Labels: approved

#2112 Update visx related packages
  packages/app-project/package.json
  packages/lib-classifier/package.json
  yarn.lock
Labels: approved, dependencies

#2124 Classifier: Fix task stories
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.js
  packages/lib-classifier/src/stories/components/MockTask/MockTask.js
Labels: approved

#2083 Transcription task: Allow one transcription line for each previously transcribed line
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesContainer.js
Labels: approved, experiment

#2114 Upgrade NextJS to 10.1
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: approved

#1925 Engaging Crowds: Subject picker tool
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowMenu/WorkflowMenu.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.stories.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/columns.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/columns.spec.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchRows.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchSubjects.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/index.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/searchParams.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/searchParams.spec.js
  packages/app-project/src/shared/components/SubjectPicker/index.js
  packages/app-project/src/shared/components/SubjectPicker/locales/en.json
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.js
Labels: approved

#2000 Made SubjectViewer props viewBox and src optional
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
Labels: approved, bug

#2125 Upgrade storybook to 6.2.9
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: approved, dependencies, dx

#2115 Redirect from projects/:owner/:name/about
  packages/app-project/pages/projects/[owner]/[project]/about/index.js
Labels: approved

#2137 Add string transform output to passed down props
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js
Labels: approved, enhancement

#2139 Update app-project to use redirect and notFound
  packages/app-project/pages/projects/[owner]/[project]/about/education.js
  packages/app-project/pages/projects/[owner]/[project]/about/faq.js
  packages/app-project/pages/projects/[owner]/[project]/about/index.js
  packages/app-project/pages/projects/[owner]/[project]/about/research.js
  packages/app-project/pages/projects/[owner]/[project]/about/results.js
  packages/app-project/pages/projects/[owner]/[project]/about/team.js
  packages/app-project/pages/projects/[owner]/[project]/classify/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject/[subjectID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/index.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
  packages/app-project/src/helpers/notFoundError/notFoundError.js
  packages/app-project/src/helpers/notFoundError/notFoundError.spec.js
Labels: approved, refactor

#2126 Classifier: support subject priority metadata
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.js
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.spec.js
  packages/lib-classifier/src/store/Subject/Subject.js
Labels: approved, bug
