Repository zooniverse/front-end-monorepo, pull requests merged in 2021-09, with the labels that each got.

#2402 Track already seen subjects during session
  packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js
  packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.spec.js
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/README.md
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBanner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBanner.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBanner.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.stories.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.spec.js
  packages/lib-classifier/src/helpers/index.js
  packages/lib-classifier/src/helpers/subjectsSeenThisSession/index.js
  packages/lib-classifier/src/helpers/subjectsSeenThisSession/subjectsSeenThisSession.js
  packages/lib-classifier/src/helpers/subjectsSeenThisSession/subjectsSeenThisSession.spec.js
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/Subject/Subject.js
  packages/lib-classifier/src/store/Subject/Subject.spec.js
  packages/lib-classifier/test/mockStore/mockStore.js
Labels: enhancement, approved

#2404 Project: Set default pageTitle as null
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject/[subjectID]/index.js
Labels: bug, approved

#2302 Engaging Crowds: fetch multiple queued subjects for Next Available Subject
  packages/lib-classifier/src/store/SubjectStore/AvailableSubjects/AvailableSubjects.js
  packages/lib-classifier/src/store/SubjectStore/AvailableSubjects/index.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
Labels: enhancement, approved

#2372 Add subcomponents to SubjectSetPicker stories
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.stories.js
  packages/app-project/src/shared/components/SubjectSetPicker/components/index.js
Labels: storybook, approved

#2358 Expand WorkflowMenuModal stories
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.stories.js
Labels: storybook, approved

#2379 Engaging Crowds: Show the subject set name for grouped workflows
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/locales/en.json
Labels: enhancement, approved

#2385 Use async/await in UPPStore tests
  packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js
Labels: bug, approved

#2401 Move workflow status message on workflow buttons
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/locales/en.json
Labels: approved

#2359 Use UTC for daily stats calculations
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.stories.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartConnector.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/index.js
  packages/app-project/stores/YourStats.js
Labels: bug, approved

#2407 Temporarily move about pages to preview route
  packages/app-project/pages/projects/[owner]/[project]/preview/about/education.js
  packages/app-project/pages/projects/[owner]/[project]/preview/about/faq.js
  packages/app-project/pages/projects/[owner]/[project]/preview/about/index.js
  packages/app-project/pages/projects/[owner]/[project]/preview/about/research.js
  packages/app-project/pages/projects/[owner]/[project]/preview/about/results.js
  packages/app-project/pages/projects/[owner]/[project]/preview/about/team.js
  packages/app-project/pages/projects/[owner]/[project]/preview/index.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.js
Labels: approved

#2376 Project: Tidy up WorkflowSelector stories
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.stories.js
  packages/app-project/src/shared/components/WorkflowSelector/components/index.js
Labels: enhancement, storybook

#2398 Dev inspect project app
  packages/app-project/README.md
  packages/app-project/package.json
Labels: dx, approved

#2408 Classifier loading state
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.spec.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.spec.js
  packages/app-project/stores/Store.js
  packages/app-project/stores/Store.spec.js
  packages/app-project/stores/User.js
Labels: enhancement, approved

#2374 Refactor survey task Question inputs
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/Questions.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/CheckBoxInputs.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/CheckBoxInputs.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/CheckBoxInputs.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/components/CheckBoxInput.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/components/CheckBoxInput.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/index.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/InputGroup/InputGroup.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/InputGroup/InputGroup.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/InputGroup/components/QuestionInput.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/InputGroup/components/QuestionInput.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/InputGroup/index.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/index.js
Labels: refactor, approved

#2409 Reset personalization
  packages/app-project/stores/Store.js
  packages/app-project/stores/Store.spec.js
  packages/app-project/stores/User.js
  packages/app-project/stores/UserPersonalization.js
  packages/app-project/stores/UserPersonalization.spec.js
  packages/app-project/stores/YourStats.js
  packages/app-project/stores/YourStats.spec.js
Labels: bug

#2403 Add survey task feedback
  docs/arch/README.md
  docs/arch/adr-33.md
  packages/lib-classifier/src/store/feedback/strategies/index.js
  packages/lib-classifier/src/store/feedback/strategies/survey/simple/README.md
  packages/lib-classifier/src/store/feedback/strategies/survey/simple/create-rule.js
  packages/lib-classifier/src/store/feedback/strategies/survey/simple/create-rule.spec.js
  packages/lib-classifier/src/store/feedback/strategies/survey/simple/index.js
  packages/lib-classifier/src/store/feedback/strategies/survey/simple/index.spec.js
  packages/lib-classifier/src/store/feedback/strategies/survey/simple/reducer.js
  packages/lib-classifier/src/store/feedback/strategies/survey/simple/reducer.spec.js
Labels: enhancement, approved

#2413 Classifier: improvements to the Finished popup
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/DisabledTaskPopup/DisabledTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/DisabledTaskPopup/DisabledTaskPopup.spec.js
Labels: bug, approved

#2414 Classifier: Priority subject fixes
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.spec.js
  packages/lib-classifier/src/store/Subject/Subject.js
  packages/lib-classifier/src/store/Subject/Subject.spec.js
  packages/lib-classifier/src/store/Workflow/Workflow.js
  packages/lib-classifier/src/store/Workflow/Workflow.spec.js
Labels: bug, approved

#2417 Revert "Temporarily move about pages to preview route"
  packages/app-project/pages/projects/[owner]/[project]/about/education.js
  packages/app-project/pages/projects/[owner]/[project]/about/faq.js
  packages/app-project/pages/projects/[owner]/[project]/about/index.js
  packages/app-project/pages/projects/[owner]/[project]/about/research.js
  packages/app-project/pages/projects/[owner]/[project]/about/results.js
  packages/app-project/pages/projects/[owner]/[project]/about/team.js
  packages/app-project/pages/projects/[owner]/[project]/preview/index.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.js
Labels: refactor, approved

#2324 Talk in Classify (aka QuickTalk)
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.spec.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.stories.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/README.md
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/Comment.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/PostForm.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/UserAvatar.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/UserRole.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/index.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/locales/en.json
Labels: approved

#2418 Workflow assignment filter
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.spec.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageConnector.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/index.js
Labels: enhancement, approved

#2419 Existential check for workflow from the url
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
Labels: bug, approved

#2412 Project: include all props with notFound errors
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
Labels: bug, approved

#2416 Default to true when demo mode is loaded
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptionsConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptionsContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptionsContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/DemoModeToggleConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/DemoModeToggleConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/index.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/index.js
  packages/lib-classifier/src/store/ClassificationStore.js
Labels: enhancement, approved

#2388 Add storing of client sizes for DataImageViewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.spec.js
Labels: enhancement, approved

#2392 Engaging Crowds: Next/Previous subject navigation
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.js
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
  packages/lib-classifier/src/store/SubjectStore/helpers/getIndexedSubjects/getIndexedSubjects.js
  packages/lib-classifier/src/store/SubjectStore/helpers/getIndexedSubjects/getIndexedSubjects.spec.js
  packages/lib-classifier/src/store/SubjectStore/helpers/subjectSelectionStrategy/subjectSelectionStrategy.js
  packages/lib-classifier/src/store/SubjectStore/helpers/subjectSelectionStrategy/subjectSelectionStrategy.spec.js
Labels: enhancement, approved

#2451 Store docs
  packages/lib-classifier/src/store/README.md
Labels: documentation, dx, approved

#2453 Feedback docs
  packages/lib-classifier/src/store/feedback/README.md
  packages/lib-classifier/src/store/feedback/strategies/drawing/column/README.md
Labels: documentation, approved

#2415 Classifier: Refactor drawing task annotations
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.spec.js
Labels: refactor, approved

#2444 Classifier: Clarify getNextStep
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
Labels: refactor, approved

#2411 Engaging Crowds: Add annotation._inProgress
  packages/lib-classifier/src/plugins/tasks/index.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Annotation.js
Labels: enhancement, approved

#2410 Classifier: Remove mocks from global test setup
  packages/lib-classifier/src/helpers/useStores/useStores.spec.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
Labels: enhancement

#2454 Remove absolute link used for project about pages
  packages/app-project/src/shared/components/NavLink/NavLink.js
  packages/app-project/src/shared/components/NavLink/NavLink.spec.js
Labels: approved

#2465 Refactor ClassifyPage canClassify per workflowID
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
Labels: bug, approved

#2466 ensure datatable UI can use desc sort order at subject-set-search API
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchSubjects.js
  packages/app-project/src/shared/components/SubjectPicker/locales/en.json
Labels: approved

#2468 Add user existence check before UPP refresh in increment action of UserPersonalization store
  packages/app-project/stores/UserPersonalization.js
  packages/app-project/stores/UserPersonalization.spec.js
Labels: bug, approved
