Repository zooniverse/front-end-monorepo, pull requests merged in 2021-07, with the labels that each got.

#2287 Classifier: observe active subject set for changes
  packages/lib-classifier/src/store/SubjectStore.js
Labels: approved, bug

#2282 Engaging Crowds: Refactor subject set completeness
  packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
  packages/app-project/src/shared/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js
  packages/app-project/src/shared/components/SubjectSetPicker/helpers/mockWorkflow.js
Labels: approved, refactor

#2285 Upgrade to storybook 6.3.2
  package.json
  packages/app-content-pages/.storybook/main.js
  packages/app-content-pages/package.json
  packages/app-project/.storybook/main.js
  packages/app-project/.storybook/webpack.config.js
  packages/app-project/package.json
  packages/lib-classifier/.storybook/main.js
  packages/lib-classifier/.storybook/webpack.config.js
  packages/lib-classifier/package.json
  packages/lib-react-components/.storybook/main.js
  packages/lib-react-components/package.json
  yarn.lock
Labels: approved, enhancement

#2286 Upgrade Sentry to 6.8
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: approved, enhancement

#2277 Classifier: use DOMPointReadOnly for drawing
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.js
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.spec.js
Labels: approved, refactor

#2256 Add onKeyDown functionality and refactor grid for survey task choices
  packages/lib-classifier/package.json
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTaskContainer.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/Chooser.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.stories.js
  yarn.lock
Labels: approved, enhancement

#2293 Fix loading of image in complex composite subject viewers.
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
Labels: approved, bug

#2193 Engaging Crowds: Subject Picker: add Already Seen status
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.spec.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchRows.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchRows.spec.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchSubjects.js
  packages/app-project/src/shared/components/SubjectPicker/locales/en.json
Labels: approved, enhancement

#2271 App-project: Modify document title for About pages
  packages/app-project/pages/_app.js
  packages/app-project/pages/projects/[owner]/[project]/about/education.js
  packages/app-project/pages/projects/[owner]/[project]/about/faq.js
  packages/app-project/pages/projects/[owner]/[project]/about/research.js
  packages/app-project/pages/projects/[owner]/[project]/about/results.js
  packages/app-project/pages/projects/[owner]/[project]/about/team.js
  packages/app-project/src/components/Head/Head.js
  packages/app-project/src/components/Head/HeadContainer.js
Labels: approved

#2295 Disable previous transcription marks when there is an transcription mark unfinished and invalid.
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/index.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.spec.js
Labels: approved, bug

#2290 Upgrade @artsy/fresnel
  packages/app-project/package.json
  yarn.lock
Labels: approved, dependencies

#2304 Refactor selector stories
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/index.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.stories.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/index.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowMenu/WorkflowMenu.stories.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.stories.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.stories.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.stories.js
Labels: approved, refactor, storybook

#2305 Add key controls for survey task choice questions radio inputs
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.spec.js
Labels: approved, enhancement

#2303 Update pjc lib
  packages/app-project/package.json
  packages/lib-classifier/package.json
  yarn.lock
Labels: approved, dependencies

#2308 Add disabled functionality to survey task ChoiceButton and FilterStatus
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/Chooser.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.stories.js
Labels: approved, enhancement

#2310 Add devcert to deal with SSL in browsers for local dev (particularly Chrome)
  packages/app-project/README.md
  packages/app-project/package.json
  packages/app-project/server/dev-server.js
  yarn.lock
Labels: approved, dx

#2313 Rotate rectangle resize
  packages/lib-classifier/src/plugins/drawingTools/components/RotateRectangle/RotateRectangle.js
  packages/lib-classifier/src/plugins/drawingTools/components/RotateRectangle/RotateRectangle.spec.js
Labels: approved, bug

#2311 Add react-testing-library
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: approved, dependencies

#2316 Remove console.log from WorkflowSelectorConnector
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorConnector.js
Labels: approved

#2306 Add dark theme styling to Project About pages
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutMarkdownz/theme.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember.js
Labels: approved, enhancement

#2307 Use as prop to render a span when href is defined and disabled is true
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/CloseButton/CloseButton.js
  packages/lib-react-components/src/CloseButton/CloseButton.spec.js
  packages/lib-react-components/src/CloseButton/README.md
  packages/lib-react-components/src/PlainButton/PlainButton.js
  packages/lib-react-components/src/PlainButton/PlainButton.spec.js
  packages/lib-react-components/src/PlainButton/PlainButton.stories.js
  packages/lib-react-components/src/PrimaryButton/PrimaryButton.js
  packages/lib-react-components/src/PrimaryButton/PrimaryButton.spec.js
  packages/lib-react-components/src/PrimaryButton/PrimaryButton.stories.js
Labels: approved, enhancement

#2318 Added videoViewer ref back to svg element
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
Labels: approved, bug

#2314 Refactor survey task Choices styling for Safari
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/Chooser.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/ClearFilters/ClearFilters.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.stories.js
Labels: approved

#2320 Install the scoped latest version of the testing-library
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: approved, dependencies

#2229 Add ADR-32: Subject Viewer Layouts (aka subject viewer sizing/fitting behaviour)
  docs/arch/README.md
  docs/arch/adr-32.md
Labels: approved

#2315 Add hover styling to survey task FilterButton
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/components/FilterButton.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/components/FilterButton.spec.js
Labels: approved, enhancement

#2321 Disable workflows
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
  packages/app-project/src/shared/components/NavLink/NavLink.js
  packages/app-project/src/shared/components/NavLink/NavLink.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.stories.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorConnector.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorConnector.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/theme.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/index.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/locales/en.json
  packages/app-project/stores/UserPersonalization.js
  packages/app-project/stores/UserPersonalization.spec.js
  packages/app-project/stores/UserProjectPreferences.js
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/PlainButton/PlainButton.js
  packages/lib-react-components/src/PrimaryButton/PrimaryButton.js
  packages/lib-react-components/src/PrimaryButton/themes/blue.js
  packages/lib-react-components/src/PrimaryButton/themes/gold.js
  packages/lib-react-components/src/PrimaryButton/themes/green.js
  packages/lib-react-components/src/PrimaryButton/themes/teal.js
Labels: approved, enhancement, refactor

#2325 Fix tutorial
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.spec.js
Labels: approved, bug
