Repository zooniverse/front-end-monorepo, pull requests merged in 2021-11, with the labels that each got.

#2510 Add page_size to subject set queries
  packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
Labels: approved

#2509 Refactor user collections and recents
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.spec.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjectsConnector.js
  packages/app-project/src/shared/components/CollectionsModal/CollectionsModalContainer.js
  packages/app-project/stores/Store.js
  packages/app-project/stores/User/Collections/Collections.js
  packages/app-project/stores/User/Collections/Collections.spec.js
  packages/app-project/stores/User/Collections/index.js
  packages/app-project/stores/User/Recents/Recents.js
  packages/app-project/stores/User/Recents/Recents.spec.js
  packages/app-project/stores/User/Recents/index.js
  packages/app-project/stores/User/User.js
Labels: refactor, approved

#2513 Fix Your Recent Classifications
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjectsConnector.js
Labels: bug, approved

#2497 Freehand line tool
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.js
  packages/lib-classifier/src/plugins/drawingTools/components/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/FreehandLineTool/FreehandLineTool.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/FreehandLineTool/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Line/Line.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/LineTool/LineTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/index.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/icons/FreehandLine.js
Labels: enhancement, approved

#2515 Refactor UPP data-fetching
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.js
  packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.js
  packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.spec.js
Labels: bug, approved

#2484 Bump NextJS
  yarn.lock
Labels: dependencies, approved

#2491 Disable the task area while subjects load
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.spec.js
Labels: bug, approved

#2506 Fix OpenGraph preview URLs
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js
Labels: bug, approved

#2523 Refactor workflow promotion prompt
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalContainer.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalContainer.spec.js
Labels: enhancement, approved

#2479 Fix SubjectSetProgressBanner stories
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.stories.js
Labels: bug, storybook, approved

#2527 Upgrade webpack build tools
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: bug, dependencies, approved

#2528 Fix UserPersonalisation on Sundays
  packages/app-project/stores/Store.spec.js
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.js
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.spec.js
  packages/app-project/stores/User/UserPersonalization/YourStats/YourStats.js
  packages/app-project/stores/User/UserPersonalization/YourStats/YourStats.spec.js
Labels: bug, approved

#2521 [Security] Upgrade trim and node-fetch
  package.json
  yarn.lock
Labels: dependencies, security, approved

#2517 Freehand Line: Continue and Undo
  packages/lib-classifier/src/plugins/drawingTools/components/DragHandle/DragHandle.js
  packages/lib-classifier/src/plugins/drawingTools/components/UndoButton/UndoButton.js
  packages/lib-classifier/src/plugins/drawingTools/components/UndoButton/index.js
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js
  packages/lib-classifier/src/plugins/drawingTools/components/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/README.md
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
Labels: enhancement, approved

#2519 NextJS: add /about and /projects base paths
  docker-compose.yml
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
  packages/app-content-pages/next.config.js
  packages/app-content-pages/pages/about/publications.js
  packages/app-content-pages/pages/about/team.js
  packages/app-content-pages/pages/publications.js
  packages/app-content-pages/pages/team.js
  packages/app-project/next.config.js
  packages/app-project/pages/[owner]/[project]/about/education.js
  packages/app-project/pages/[owner]/[project]/about/faq.js
  packages/app-project/pages/[owner]/[project]/about/index.js
  packages/app-project/pages/[owner]/[project]/about/research.js
  packages/app-project/pages/[owner]/[project]/about/results.js
  packages/app-project/pages/[owner]/[project]/about/team.js
  packages/app-project/pages/[owner]/[project]/classify/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject/[subjectID]/index.js
  packages/app-project/pages/[owner]/[project]/index.js
  packages/app-project/pages/[owner]/[project]/logger.js
Labels: enhancement, ops, approved

#2530 Fix liveness probe paths
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
Labels: approved

#2529 Projects: Remove /projects from internal links
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButtonContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButtonContainer.spec.js
  packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.js
  packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.spec.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
  packages/app-project/stores/Project.js
  packages/app-project/stores/UI.js
Labels: approved

#2533 Fix About page redirects
  packages/app-project/pages/[owner]/[project]/about/index.js
Labels: bug, approved

#2539 Remove /projects from /classify redirects
  packages/app-project/pages/[owner]/[project]/classify/index.js
Labels: bug, approved

#2524 ADR35: adding undo/redo to workflow steps
  docs/arch/README.md
  docs/arch/adr-35.md
Labels: documentation, approved

#2535 Drawing tools models cleanup
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/TranscriptionLine/TranscriptionLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/TranscriptionLineTool/TranscriptionLineTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Circle/Circle.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Ellipse/Ellipse.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Point/Point.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Rectangle/Rectangle.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/RotateRectangle/RotateRectangle.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/TemporalPoint/TemporalPoint.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/TemporalRotateRectangle/TemporalRotateRectangle.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/CircleTool/CircleTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/EllipseTool/EllipseTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/PointTool/PointTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/RectangleTool/RectangleTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/RotateRectangleTool/RotateRectangleTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/TemporalPointTool/TemporalPointTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/TemporalRotateRectangleTool/TemporalRotateRectangleTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
Labels: refactor, approved

#2520 Refactor annotatedSteps as subject.stepHistory
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/helpers/setupMock.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/TasksConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.js
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.spec.js
  packages/lib-classifier/src/store/AnnotatedSteps/index.js
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/SubjectStore/AvailableSubjects/AvailableSubjects.js
  packages/lib-classifier/src/store/SubjectStore/SingleImageSubject/SingleImageSubject.js
  packages/lib-classifier/src/store/SubjectStore/SingleImageSubject/SingleImageSubject.spec.js
  packages/lib-classifier/src/store/SubjectStore/SingleImageSubject/index.js
  packages/lib-classifier/src/store/SubjectStore/SingleVideoSubject/SingleVideoSubject.js
  packages/lib-classifier/src/store/SubjectStore/SingleVideoSubject/SingleVideoSubject.spec.js
  packages/lib-classifier/src/store/SubjectStore/SingleVideoSubject/index.js
  packages/lib-classifier/src/store/SubjectStore/Subject/StepHistory/AnnotatedStep/AnnotatedStep.js
  packages/lib-classifier/src/store/SubjectStore/Subject/StepHistory/AnnotatedStep/index.js
  packages/lib-classifier/src/store/SubjectStore/Subject/StepHistory/StepHistory.js
  packages/lib-classifier/src/store/SubjectStore/Subject/StepHistory/StepHistory.spec.js
  packages/lib-classifier/src/store/SubjectStore/Subject/StepHistory/index.js
  packages/lib-classifier/src/store/SubjectStore/Subject/Subject.js
  packages/lib-classifier/src/store/SubjectStore/Subject/Subject.spec.js
  packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/TranscriptionReductions.js
  packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/TranscriptionReductions.spec.js
  packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/index.js
  packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/mocks/index.js
  packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/mocks/reducedASMSubject.json
  packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/mocks/reducedEmptySubject.js
  packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/mocks/reducedSubject.js
  packages/lib-classifier/src/store/SubjectStore/Subject/index.js
  packages/lib-classifier/src/store/SubjectStore/SubjectGroup/README.md
  packages/lib-classifier/src/store/SubjectStore/SubjectGroup/SubjectGroup.js
  packages/lib-classifier/src/store/SubjectStore/SubjectGroup/SubjectGroup.spec.js
  packages/lib-classifier/src/store/SubjectStore/SubjectGroup/index.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
  packages/lib-classifier/src/stories/components/MockTask/MockTask.js
Labels: refactor, approved

#2541 Use CDN domains for asset prefixes
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
  packages/app-content-pages/public/robots.txt
  packages/app-project/public/assets/simple-avatar.png
  packages/app-project/public/assets/subject-placeholder.png
  packages/app-project/public/robots.txt
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.js
  packages/app-project/src/shared/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js
Labels: ops, approved

#2538 Add minZoom to SingleImageViewerContainer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
Labels: enhancement, approved

#2546 Classifier: Refactor SubjectStore createClassificationObserver
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
Labels: bug, approved

#2545 Fix favicon URLs
  packages/app-content-pages/src/shared/components/Head/Head.js
  packages/app-project/src/components/Head/Head.js
Labels: bug, approved

#2543 ADR 36: NextJS App base paths
  docs/arch/README.md
  docs/arch/adr-36.md
Labels: documentation, approved

#2552 Engaging Crowds: Warn volunteers about unsaved work
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/TranscriptionReductions.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js
  packages/lib-classifier/src/store/locales/en.json
Labels: enhancement, approved

#2548 Classifier: Run addMiddleware, onAction and onPatch outside of autorun
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/FeedbackStore.js
  packages/lib-classifier/src/store/FeedbackStore.spec.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
Labels: bug, refactor

#2557 Add subject optional chaining to task nav button containers
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.js
Labels: bug, approved

#2560 Engaging Crowds: Ignore active subjects when selecting a subject
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.spec.js
Labels: bug, approved

#2562 Classifier: Refactor the beforeunload warning
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/SubjectStore/Subject/StepHistory/StepHistory.js
  packages/lib-classifier/src/store/SubjectStore/Subject/StepHistory/locales/en.json
Labels: bug, refactor, approved

#2559 LightCurveViewer: fix "invisible annotations" when returning to Classify page
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
Labels: approved

#2547 Upgrade to Next 12
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: dependencies, ops, approved

#2551 Support project slugs in the dev classifier
  packages/lib-classifier/dev/components/App/App.js
Labels: enhancement, dx, approved

#2558 Refactor task nav buttons to use withStores
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.spec.js
  packages/lib-classifier/src/helpers/withStores/README.md
  packages/lib-classifier/src/helpers/withStores/withStores.js
Labels: refactor, approved

#2568 Bump mime-types and panoptes-client
  yarn.lock
Labels: bug, approved

#2549 Engaging Crowds: track classifier subject changes in the page URL
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/store/RootStore.js
Labels: enhancement, approved

#2570 Engaging Crowds: Mark subjects as seen on subjects.advance()
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.js
  packages/lib-classifier/src/store/SubjectStore/Subject/Subject.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
Labels: bug, approved
