Repository zooniverse/front-end-monorepo, pull requests merged in 2021-08, with the labels that each got.

#2332 Classifier: Fix Finished modal button alignment
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/DisabledTaskPopup/DisabledTaskPopup.js
Labels: approved, bug

#2322 Project App: Add Stories for About Page components
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/index.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink/AboutNavLink.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink/AboutNavLink.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink/AboutNavLink.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink/index.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/index.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/index.js
Labels: approved

#2333 Add testing-library user-event and dom packages
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: approved, dependencies, dx

#2329 Fix broken Tasks imports
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
  packages/lib-classifier/src/stories/components/MockTask/MockTask.js
Labels: approved, bug, storybook

#2334 Render inside the it statement so it doesn't pollute other tests
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskAreaConnector.spec.js
Labels: approved, bug

#2291 NextJS apps: fix linter errors
  packages/app-content-pages/pages/Index.js
  packages/app-project/pages/Index.js
  packages/app-project/pages/_app.js
  packages/app-project/pages/projects/[owner]/[project]/logger.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/helpers/markdownzComponents/markdownzComponents.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js
  packages/app-project/src/shared/components/withRequireUser/withRequireUser.js
Labels: bug, refactor, approved

#2339 Project: WorkflowSelectButtons: fix list structure
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.js
Labels: bug, accessibility, approved

#2343 Add chai-dom package
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-classifier/test/setup.js
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies, dx, approved

#2309 Docker build and compose improvements
  Dockerfile
  docker-compose.yml
Labels: experiment, approved

#2326 Fix survey task characteristics filters
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.spec.js
Labels: bug, approved

#2344 Update grommet and grommet-icons
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies, approved

#2342 Refactor ZoomingScatterPlot tests with react-testing-library
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Chart/Chart.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/ZoomEventLayer/ZoomEventLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js
Labels: refactor, approved

#2348 Add unmount to FieldGuideWrapper tests
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideWrapper.spec.js
Labels: dx

#2337 Project: Fix broken Hero and WorkflowMenuModal stories
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
Labels: bug, storybook, approved

#2347 Fix survey task Choices component focus after choice selection
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.spec.js
Labels: bug, approved

#2281 [Security] Upgrade to Next 11.1 and React 17
  packages/app-content-pages/.eslintrc
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-content-pages/test/create-enzyme-adapter.js
  packages/app-project/.eslintrc
  packages/app-project/next.config.js
  packages/app-project/package.json
  packages/app-project/test/create-enzyme-adapter.js
  packages/lib-classifier/package.json
  packages/lib-classifier/test/enzyme-config.js
  packages/lib-react-components/package.json
  packages/lib-react-components/test/setup.js
  yarn.lock
Labels: enhancement, security, approved

#2351 reinstate PR 2309 - Docker build and compose improvements
  Dockerfile
  Jenkinsfile
  docker-compose.yml
Labels: approved

#2335 Engaging Crowds: Use links for workflow and subject set selection
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js
  packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
  packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.spec.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/NarrowLayout/NarrowLayout.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/NarrowLayout/NarrowLayout.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WideLayout/WideLayout.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WideLayout/WideLayout.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowMenu/WorkflowMenu.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowMenu/WorkflowMenu.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowMenu/WorkflowMenu.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowMenu/index.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowMenu/locales/en.json
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.spec.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.stories.js
  packages/app-project/src/shared/components/SubjectPicker/locales/en.json
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.spec.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.stories.js
  packages/app-project/src/shared/components/SubjectSetPicker/locales/en.json
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
Labels: refactor, approved

#2319 Add ADR-33 for survey task feedback
  docs/arch/README.md
  docs/arch/adr-33.md
Labels: documentation, approved

#2352 Engaging Crowds: fix SubjectPicker header styles
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
Labels: bug, approved

#2349 Refresh user project preferences
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.stories.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalContainer.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalContainer.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.spec.js
  packages/app-project/stores/UserPersonalization.js
  packages/app-project/stores/UserPersonalization.spec.js
  packages/app-project/stores/UserProjectPreferences.js
  packages/app-project/stores/UserProjectPreferences.spec.js
Labels: enhancement, approved

#2357 Refactor testing of About Pages components with react-testing-library
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPageConnector.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutMarkdownz/AboutMarkdownz.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink/AboutNavLink.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.stories.js
Labels: refactor, approved

#2369 Refactor glyph assignment
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/HighlightSeriesCheckBoxes/HighlightSeriesCheckBoxes.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/Label/Label.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/Label/Label.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/getDataSeriesSymbol.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/getDataSeriesSymbol.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesSymbol/glyphComponents.js
Labels: refactor, approved

#2364 Add persist_annotations to workflow config
  packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
  packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.spec.js
Labels: bug, approved

#2365 Always hide workflow summaries
  packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
  packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js
Labels: refactor, approved

#2375 Remove `plop`
  .dockerignore
  README.md
  package.json
  plop/generators/app.js
  plop/generators/component.js
  plop/plopfile.js
  plop/templates/app/.babelrc
  plop/templates/app/next.config.js
  plop/templates/app/package.json
  plop/templates/app/pages/Index.js
  plop/templates/app/pages/Index.spec.js
  plop/templates/app/pages/Public.js
  plop/templates/app/pages/Public.spec.js
  plop/templates/app/pages/_app.js
  plop/templates/app/pages/_document.js
  plop/templates/app/server/server.js
  plop/templates/app/test/create-enzyme-adapter.js
  plop/templates/app/test/create-global-document.js
  plop/templates/app/test/mocha.opts
  plop/templates/component/Component.js.hbs
  plop/templates/component/Component.spec.js.hbs
  plop/templates/component/Container.js.hbs
  plop/templates/component/Container.spec.js.hbs
  plop/templates/component/MSTContainer.js.hbs
  plop/templates/component/MSTContainer.spec.js.hbs
  plop/templates/component/Readme.md.hbs
  plop/templates/component/Stories.js.hbs
  plop/templates/component/index.js.hbs
  plop/templates/component/locales/en.json.hbs
  plopfile.js
  yarn.lock
Labels: approved

#2366 Simplify highlight state
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/HighlightSeriesCheckBoxes/HighlightSeriesCheckBoxes.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/HighlightSeriesCheckBoxes/HighlightSeriesCheckBoxes.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/Label/Label.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getDataSeriesColor/getDataSeriesColor.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesHighlighted/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesHighlighted/isDataSeriesHighlighted.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/isDataSeriesHighlighted/isDataSeriesHighlighted.spec.js
Labels: refactor, approved

#2373 Reorder data points by highlight state
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/sortDataPointsByHighlight/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/sortDataPointsByHighlight/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/sortDataPointsByHighlight/sortDataPointsByHighlight.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/sortDataPointsByHighlight/sortDataPointsByHighlight.spec.js
Labels: bug, design, approved

#2360 Refactor survey task Choice component tests with react-testing-library
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/ConfusedWith.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/ConfusedWith.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/components/Confusion.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/components/Confusion.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/Questions.spec.js
Labels: refactor, approved

#2377 Refactor FeedbackModal to not render null FeedbackViewer
  packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.js
  packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.spec.js
Labels: bug, approved

#2361 Mock the API in SubjectPicker tests
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.spec.js
Labels: approved

#2386 Classifier: Refactor drawing Tool tests
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js
Labels: bug, refactor, approved

#2383 VariableStarViewer client sizes for classification metadata
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
Labels: enhancement, approved

#2391 Refactor survey task Choice and Questions RTL tests
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/Questions.spec.js
Labels: refactor, approved

#2380 Projects: Add page titles for workflows and subject sets
  packages/app-project/pages/projects/[owner]/[project]/classify/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject/[subjectID]/index.js
  packages/app-project/src/components/Head/Head.js
  packages/app-project/src/components/Head/HeadContainer.js
Labels: enhancement, approved

#2384 Classifier: add 'Literal Insertion' text tags
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.stories.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.spec.js
Labels: approved

#2387 Add storing of client sizes for ScatterPlotViewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.spec.js
Labels: enhancement, approved

#2367 Fix broken images in Recent Subjects stories
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.stories.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjectsConnector.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjectsContainer.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjectsContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/index.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjects.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjects.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsCarousel.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.stories.js
Labels: bug, storybook, approved

#2350 Classifier: remove Ellipse component's unused `.children`
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.js
Labels: approved

#2397 Loader component
  packages/app-project/src/shared/components/Loader/Loader.js
  packages/app-project/src/shared/components/Loader/Loader.spec.js
  packages/app-project/src/shared/components/Loader/Loader.stories.js
  packages/app-project/src/shared/components/Loader/README.md
  packages/app-project/src/shared/components/Loader/index.js
  packages/app-project/src/shared/components/Loader/locales/en.json
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.spec.js
Labels: enhancement, approved
