Repository zooniverse/front-end-monorepo, pull requests merged in 2021-05, with the labels that each got.

#2113 NextJS: Enable webpack 5 in next.config
  packages/app-content-pages/next.config.js
  packages/app-project/next.config.js
Labels: approved

#2122 Classifier: Explicitly define taskType for annotation models
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/models/DataVisAnnotation.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingAnnotation.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceAnnotation.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownAnnotation.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceAnnotation.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonAnnotation.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyAnnotation.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextAnnotation.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionAnnotation.js
  packages/lib-classifier/src/plugins/tasks/models/Annotation.js
Labels: approved, bug

#2149 Remove Becky from the issue and PR template
  .github/ISSUE_TEMPLATE/feature-request--ux--ui--accessibility--design--etc.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: approved, dx

#2099 Video annotation: Extending the Point Tool
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getFixedNumber/getFixedNumber.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getFixedNumber/index.js
  packages/lib-classifier/src/plugins/drawingTools/README.md
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.js
  packages/lib-classifier/src/plugins/drawingTools/components/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Point/Point.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/TemporalPoint/TemporalPoint.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/TemporalPoint/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/TemporalPointTool/TemporalPointTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/TemporalPointTool/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/index.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/components/helpers/getIcon.js
Labels: approved, enhancement

#2116 Provide default content for blank project About pages (research, faq, etc...)
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPageConnector.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPageConnector.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutMarkdownz/AboutMarkdownz.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember.js
Labels: approved, enhancement

#2135 Engaging Crowds: Fallback to workflow.links when Cellect fails
  packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
Labels: approved, bug

#2141 Classifier: fix store re-renders
  packages/lib-classifier/src/components/Classifier/Classifier.js
Labels: approved, bug

#2144 Add modal for workflow assignment
  packages/lib-classifier/src/components/Classifier/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
  packages/lib-classifier/src/components/Classifier/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js
  packages/lib-classifier/src/components/Classifier/components/WorkflowAssignmentModal/WorkflowAssignmentModal.stories.js
  packages/lib-classifier/src/components/Classifier/components/WorkflowAssignmentModal/index.js
  packages/lib-classifier/src/components/Classifier/components/WorkflowAssignmentModal/locales/en.json
Labels: approved, enhancement

#2123 Classifier: Add git commit to classifications
  README.md
  packages/lib-classifier/src/store/Classification/ClassificationMetadata.js
  packages/lib-classifier/webpack.dev.js
  packages/lib-classifier/webpack.dist.js
Labels: approved, enhancement

#2129 Classifier: set multi-frame thumbnail dimensions
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
Labels: approved, bug

#2103 Remove git commit history from the Docker build
  .dockerignore
  Dockerfile
  packages/app-content-pages/next.config.js
  packages/app-project/next.config.js
Labels: approved, dx, security

#2155 Classifier: check classification and step before rendering Tasks
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
Labels: approved, bug

#2160 Classifier: catch git errors during builds
  packages/lib-classifier/webpack.dev.js
  packages/lib-classifier/webpack.dist.js
Labels: approved

#2163 Upgrade Sentry to 6.3
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: approved, enhancement

#2132 Engaging Crowds: switch to Datasette for subject browse & search
  packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowMenu/WorkflowMenu.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.spec.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.spec.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchRows.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchRows.spec.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchSubjects.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/searchParams.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/searchParams.spec.js
Labels: approved, enhancement

#2171 Add spec files and tests for About Pages components
  packages/app-project/src/screens/ProjectAboutPage/components/AboutMarkdownz/AboutMarkdownz.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember.spec.js
Labels: approved

#2175 Update url-parse to 1.5.1
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-panoptes-js/package.json
  yarn.lock
Labels: approved, bug

#2170 Update SubjectGroupViewer README (May 2021)
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/README.md
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/README.md
  packages/lib-classifier/src/store/SubjectGroup/README.md
Labels: approved

#2142 Zoom configuration
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js
  packages/lib-classifier/src/store/Subject/Subject.js
  packages/lib-classifier/src/store/Subject/Subject.spec.js
  packages/lib-classifier/src/store/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
Labels: approved, enhancement

#2146 Disable mark and update tests
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
Labels: approved, enhancement

#2167 Add TranscriptionLine mark validation
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/TranscriptionLine/TranscriptionLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/TranscriptionLine/TranscriptionLine.spec.js
Labels: approved, bug

#2148 Engaging Crowds: enable indexed subject selection
  packages/lib-classifier/src/store/SubjectSet/SubjectSet.js
  packages/lib-classifier/src/store/SubjectSet/SubjectSet.spec.js
  packages/lib-classifier/src/store/SubjectStore.js
  packages/lib-classifier/src/store/Workflow/Workflow.js
  packages/lib-classifier/src/store/Workflow/Workflow.spec.js
  packages/lib-classifier/src/store/helpers/getIndexedSubjects/getIndexedSubjects.js
  packages/lib-classifier/src/store/helpers/getIndexedSubjects/getIndexedSubjects.spec.js
  packages/lib-classifier/src/store/helpers/getIndexedSubjects/index.js
  packages/lib-classifier/src/store/helpers/index.js
  packages/lib-classifier/src/store/helpers/subjectSelectionStrategy/index.js
  packages/lib-classifier/src/store/helpers/subjectSelectionStrategy/subjectSelectionStrategy.js
  packages/lib-classifier/src/store/helpers/subjectSelectionStrategy/subjectSelectionStrategy.spec.js
  packages/lib-classifier/test/factories/SubjectSetFactory.js
Labels: approved, enhancement

#2159 Transcription tooltips
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/TooltipIcon/TooltipIcon.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/TooltipIcon/TooltipIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/TooltipIcon/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/TooltipLabel/TooltipLabel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/TooltipLabel/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.spec.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TooltipIcon/TooltipIcon.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TooltipIcon/TooltipIcon.spec.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TooltipIcon/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TranscriptionLineMark/TranscriptionLineMark.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TranscriptionLineMark/TranscriptionLineMark.spec.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TranscriptionLineMark/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/helpers/constants.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/locales/en.json
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/index.js
Labels: approved, enhancement

#2185 Remove seven-ten
  packages/lib-classifier/package.json
  packages/lib-classifier/src/store/ClassificationStore.js
  yarn.lock
Labels: approved

#2181 Observe TranscriptionLineMark
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TranscriptionLineMark/TranscriptionLineMark.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TranscriptionLineMark/TranscriptionLineMark.spec.js
Labels: approved, bug

#2182 Freeze the lockfile during CI builds
  .github/workflows/ci-tests.yml
Labels: approved, ops, security

#2153 Markdownz: Provide backwards compatibility for rendering images with sizes in source string
  packages/lib-react-components/.storybook/lib/example.md
  packages/lib-react-components/src/Markdownz/Markdownz.js
  packages/lib-react-components/src/Markdownz/Markdownz.spec.js
Labels: approved

#2190 Project: Use @sentry/browser in storybook builds
  packages/app-project/.storybook/webpack.config.js
Labels: approved, bug

#2188 Post to #deploys instead of #ops
  Jenkinsfile
Labels: approved

#2187 Classifier: Observe drawing marks
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.js
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.js
Labels: approved, bug

#2134 Classifier: Add a test case for a single step combo task
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.js
  packages/lib-classifier/src/store/helpers/convertWorkflowToUseSteps/convertWorkflowToUseSteps.js
  packages/lib-classifier/src/store/helpers/convertWorkflowToUseSteps/convertWorkflowToUseSteps.spec.js
  packages/lib-classifier/test/factories/index.js
  packages/lib-classifier/test/factories/tasks/TextTaskFactory.js
Labels: approved, bug

#2199 Classifier: track annotation changes on step change
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.js
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.spec.js
Labels: approved, bug

#2172 Classifier: Add autofocus to Tasks
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js
Labels: accessibility, approved

#2194 Add deselect functionality to survey task question radio input
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/Questions.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/components/CheckBoxInput.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.spec.js
Labels: approved, enhancement

#2208 Version theme and component library
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/package.json
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: approved, dependencies

#2209 Update readme on publishing
  README.md
Labels: approved, documentation, dx

#2202 Move WorkflowAssignmentModal to project app
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.stories.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/index.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/locales/en.json
Labels: approved, refactor

#2195 Refactor banner connections
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncement.stories.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.spec.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementContainer.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/index.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncement.stories.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncementConnector.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncementConnector.spec.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncementContainer.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncementContainer.spec.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/index.js
Labels: approved, refactor

#2174 Add survey task ClearFilters component to Chooser
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/ConfusedWith.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/components/CheckBoxInput.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/components/CheckBoxInput.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/Chooser.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/ClearFilters/ClearFilters.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/ClearFilters/ClearFilters.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/ClearFilters/ClearFilters.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/ClearFilters/index.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/locales/en.json
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.js
Labels: approved, enhancement

#2164 ADR 31
  docs/arch/README.md
  docs/arch/adr-31.md
Labels: approved, discussion, documentation
