Repository zooniverse/front-end-monorepo, pull requests merged in 2021-06, with the labels that each got.

#2179 Delete invalid marks on next or done
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/TranscriptionLineTool/TranscriptionLineTool.spec.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Task.js
  packages/lib-classifier/src/plugins/tasks/models/Task.spec.js
  packages/lib-classifier/src/plugins/tasks/readme.md
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.js
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.spec.js
Labels: approved, bug

#2222 Fix extra space that Safari renders below footer
  packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.js
Labels: approved

#2224 Clean up team array
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember.js
Labels: approved

#2227 Build with node:14-alpine
  Dockerfile
  docker-compose.yml
Labels: approved

#2207 Isolate mobx globals so classifier is a true plugin.
  packages/lib-classifier/src/store/RootStore.js
Labels: approved, dependencies, enhancement

#2206 Add basic UPP model
  packages/app-project/stores/UserProjectPreferences.js
  packages/app-project/stores/UserProjectPreferences.spec.js
Labels: approved, enhancement

#2228 Update lib-react-components Changelog
  packages/lib-react-components/CHANGELOG.md
Labels: approved

#2217 Publish /commit_id.txt during builds
  Dockerfile
  packages/app-project/next.config.js
Labels: approved

#2226 Refactor Step isComplete
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.spec.js
Labels: approved

#2236 Team Page: Pass env param when fetching team members data
  packages/app-project/pages/projects/[owner]/[project]/about/team.js
Labels: approved, bug

#2176 Project: remove inject from the classifier wrapper
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.spec.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.spec.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/index.js
Labels: approved, refactor

#2237 Project About Pages: Use counterpart for page titles
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
  packages/app-project/src/screens/ProjectAboutPage/locales/en.json
Labels: approved, enhancement

#2232 Upgrade all the things.
  yarn.lock
Labels: approved, dependencies

#2184 Classifier: Updated focus management for modal popups
  packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ConfirmModal/ConfirmModal.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.js
Labels: accessibility, approved, bug

#2238 Integrate UPP store in project app
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.spec.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStatsContainer.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js
  packages/app-project/stores/Store.js
  packages/app-project/stores/User.js
  packages/app-project/stores/UserPersonalization.js
  packages/app-project/stores/UserPersonalization.spec.js
  packages/app-project/stores/UserProjectPreferences.js
  packages/app-project/stores/UserProjectPreferences.spec.js
  packages/app-project/stores/YourStats.js
  packages/app-project/stores/YourStats.spec.js
Labels: enhancement, refactor

#2243 Refactor SurveyTask Choice render, from Drop, to Stack
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.js
Labels: approved

#2231 Subject Group Viewer: set optional max grid width/height
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.js
Labels: approved, enhancement

#2211 Rotating rectangle tool
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/RotateHandle/RotateHandle.js
  packages/lib-classifier/src/plugins/drawingTools/components/RotateHandle/index.js
  packages/lib-classifier/src/plugins/drawingTools/components/RotateRectangle/RotateRectangle.js
  packages/lib-classifier/src/plugins/drawingTools/components/RotateRectangle/RotateRectangle.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/RotateRectangle/index.js
  packages/lib-classifier/src/plugins/drawingTools/components/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Rectangle/Rectangle.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/RotateRectangle/RotateRectangle.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/RotateRectangle/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/RectangleTool/RectangleTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/RotateRectangleTool/RotateRectangleTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/RotateRectangleTool/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/index.js
Labels: approved, enhancement

#2245 Add delete choice functionality
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTaskContainer.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js
Labels: approved

#2239 Markdownz: avoid creating username-links with ping in email addresses
  packages/lib-react-components/.storybook/lib/example.md
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/Markdownz/Markdownz.js
  packages/lib-react-components/src/Markdownz/lib/ping.js
  packages/lib-react-components/src/Markdownz/lib/ping.spec.js
Labels: approved, bug

#2240 Bump Grommet to 2.17.3
  yarn.lock
Labels: approved, dependencies

#2186 Zoom configuration docs for ScatterPlotViewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/README.md
Labels: approved, documentation

#2241 Classifier: add image placeholder for Single Image Viewer (Fix 2221)
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
Labels: approved, bug

#2254 Classifier: add image placeholder for Multi Frame Viewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js
Labels: approved, bug

#2257 Update store connection to reflect recent refactor for UPP.
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitation.stories.js
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.js
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.spec.js
Labels: approved, bug

#2259 Use next.js dynamic import to not SSR auth invite banner.
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.js
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.spec.js
Labels: approved, bug

#2248 Prompt workflow assignment
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.stories.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalContainer.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/index.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/locales/en.json
  packages/app-project/stores/Project.js
  packages/app-project/stores/UserProjectPreferences.js
  packages/app-project/stores/UserProjectPreferences.spec.js
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/src/index.js
Labels: approved, enhancement

#2169 Engaging Crowds: Add URL workflow and subject set to WorkflowMenu
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.spec.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.js
  packages/app-project/src/shared/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js
Labels: approved, enhancement

#2260 Project: Cache subject sets across workflows
  packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
Labels: approved, bug

#2261 modify cpu and memory resource requests and limits
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
Labels: approved

#2230 Remove dev dependencies and src from Docker builds
  Dockerfile
  README.md
Labels: approved

#2255 Classifier drawing tools: simplify SVGContext
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
Labels: approved

#2262 Reset cpu requests to ensure the HPA pod scaling is correct
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
Labels: approved

#2223 Fix Subject Group Viewer (aka Grid Viewer) zoom on Safari
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.spec.js
Labels: approved

#2253 Use Markdownz to render text task instructions.
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/DefaultTextTask/DefaultTextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.spec.js
Labels: approved, bug

#2263 Link to workflow in assignment prompt
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.stories.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalContainer.js
Labels: approved, enhancement

#2264 Add reordering logic to workflow fetch in project app
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
Labels: approved, bug

#2250 Add conditional focus to survey task Choice components
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/ConfusedWith.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/ConfusedWith.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/Questions.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/Questions.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/CheckBoxInputs.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/CheckBoxInputs.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/components/CheckBoxInput.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/CheckBoxInputs/components/CheckBoxInput.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/RadioInputs.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/components/RadioInputs/components/RadioInput.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/mock-data/task.js
Labels: approved, enhancement

#2266 App-project: correct old 'Research Case' page title for translations
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPageConnector.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPageConnector.spec.js
Labels: approved, bug

#2267 Refactor store connection for WorkflowSelector
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenu/WorkflowMenu.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowMenu/WorkflowMenu.stories.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorConnector.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorConnector.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorContainer.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorContainer.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/index.js
Labels: approved, enhancement, refactor

#2276 Classifier: fix "Reset Image/View" action (fix 2274)
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
Labels: approved
