Repository zooniverse/front-end-monorepo, pull requests merged in 2021-03, with the labels that each got.

#2049 Remove PEP
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  yarn.lock
Labels: approved, bug, dependencies

#2043 Engaging Crowds: subject banners
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.js
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/index.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/locales/en.json
Labels: approved, enhancement

#1875 Projects: Add subject index pages
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js
  packages/app-project/pages/projects/[owner]/[project]/classify/workflow/[workflowID]/subject/[subjectID]/index.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
Labels: approved, enhancement

#2052 Project: fetch project data on the server
  packages/app-project/src/helpers/fetchProjectData/fetchProjectData.js
  packages/app-project/src/helpers/fetchProjectData/fetchProjectData.spec.js
  packages/app-project/src/helpers/fetchProjectData/index.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
  packages/app-project/stores/Project.js
  packages/app-project/stores/Project.spec.js
Labels: approved, refactor

#2053 Project: cast null properties to undefined
  packages/app-project/src/helpers/fetchProjectData/fetchProjectData.js
Labels: approved, bug

#2054 Project: test null project properties
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
Labels: approved, enhancement

#2044 Project: Install @sentry/node
  packages/app-project/.babelrc
  packages/app-project/next.config.js
  packages/app-project/package.json
  packages/app-project/pages/_app.js
  packages/app-project/pages/_document.js
  packages/app-project/src/helpers/logger/index.js
  packages/app-project/src/helpers/logger/initializeSentry.js
  packages/app-project/src/helpers/logger/logNodeError.js
  packages/app-project/src/helpers/logger/logToSentry.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperContainer.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/components/ErrorMessage/ErrorMessage.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/components/ErrorMessage/ErrorMessage.spec.js
  packages/app-project/stores/Store.js
  packages/app-project/webpack.config.test.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
  yarn.lock
Labels: approved, dx, enhancement

#2055 Update color names
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.stories.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.spec.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/README.md
  packages/lib-grommet-theme/src/index.js
Labels: approved, refactor

#1989 Add survey task characteristics filter components
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/Chooser.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/Chooser.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/FilterButton.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/FilterButton.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/FilterButton.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/index.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/index.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/locales/en.json
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilterLabel/CharacteristicsFilterLabel.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilterLabel/CharacteristicsFilterLabel.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilterLabel/index.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilterLabel/locales/en.json
Labels: approved, enhancement

#2057 Subject Group Viewer - Mar 2020 UI update
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.js
Labels: approved

#2050 Classifier: add support for recursive, branching workflows
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtonsContainer.spec.js
  packages/lib-classifier/src/plugins/drawingTools/README.md
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/MultipleChoiceTask/models/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/models/SimpleDropdownTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SingleChoiceTask/models/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SubjectGroupComparisonTask/models/SubjectGroupComparisonTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/Chooser.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/models/SurveyTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/models/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/TranscriptionTask/models/TranscriptionTask.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Task.js
  packages/lib-classifier/src/plugins/tasks/models/Task.spec.js
  packages/lib-classifier/src/plugins/tasks/readme.md
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedStep/AnnotatedStep.js
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedStep/index.js
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.js
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.spec.js
  packages/lib-classifier/src/store/AnnotatedSteps/index.js
  packages/lib-classifier/src/store/AnnotationsStore.js
  packages/lib-classifier/src/store/AnnotationsStore.spec.js
  packages/lib-classifier/src/store/Classification/Classification.spec.js
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/ResourceStore/ResourceStore.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/index.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore/index.js
  packages/lib-classifier/src/stories/components/MockTask/MockTask.js
  packages/lib-classifier/test/mockStore/branchingWorkflow.js
  packages/lib-classifier/test/mockStore/index.js
  packages/lib-classifier/test/mockStore/mockStore.js
  yarn.lock
Labels: approved, enhancement, experiment

#2041 New project about pages
  packages/app-project/pages/projects/[owner]/[project]/about/education.js
  packages/app-project/pages/projects/[owner]/[project]/about/faq.js
  packages/app-project/pages/projects/[owner]/[project]/about/index.js
  packages/app-project/pages/projects/[owner]/[project]/about/research.js
  packages/app-project/pages/projects/[owner]/[project]/about/results.js
  packages/app-project/pages/projects/[owner]/[project]/about/team.js
  packages/app-project/src/helpers/fetchProjectData/fetchProjectData.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPageConnector.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPageConnector.spec.js
  packages/app-project/src/screens/ProjectAboutPage/index.js
  packages/app-project/stores/Project.js
  packages/app-project/stores/Project.spec.js
Labels: approved, enhancement

#2056 New project about pages styling
  packages/app-project/public/simple-avatar.png
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPageConnector.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutMarkdownz/AboutMarkdownz.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutMarkdownz/theme.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember.js
Labels: approved

#2065 Update getNavLink helper for about page routing
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.js
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.spec.js
Labels: approved, enhancement

#2066 Use standard anchor for about page link for now
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/Introduction.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/Introduction.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.spec.js
Labels: approved, bug

#2067 Project: Restore external link behaviour for nav links
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.js
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/Introduction.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/Introduction.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/IntroductionContainer.spec.js
  packages/app-project/src/shared/components/NavLink/NavLink.js
  packages/app-project/src/shared/components/NavLink/NavLink.spec.js
Labels: approved, bug

#2028 Add survey task choice components
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.stories.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/helpers/allowIdentification.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/helpers/allowIdentification.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/helpers/getQuestionIds.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/helpers/getQuestionIds.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/index.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/locales/en.json
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/Chooser.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/components/ChoiceButton.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/mock-data/task.js
Labels: approved, enhancement

#2016 Engaging Crowds: Subject set completeness
  packages/app-project/package.json
  packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
  packages/app-project/src/helpers/fetchSubjectSets/index.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
  packages/app-project/src/shared/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js
  yarn.lock
Labels: approved

#2076 Remove mouse wheel zoom from SVGPanZoom
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
Labels: approved, bug, refactor

#1972 Upgrade Next to version 10
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: approved, dependencies

#2064 Classifier: refactor convertWorkflowToUseSteps
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.js
  packages/lib-classifier/src/store/Workflow/Workflow.js
  packages/lib-classifier/src/store/Workflow/Workflow.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js
  packages/lib-classifier/src/store/helpers/convertWorkflowToUseSteps/convertWorkflowToUseSteps.js
  packages/lib-classifier/src/store/helpers/convertWorkflowToUseSteps/convertWorkflowToUseSteps.spec.js
  packages/lib-classifier/src/store/helpers/convertWorkflowToUseSteps/index.js
  packages/lib-classifier/src/store/helpers/index.js
  packages/lib-classifier/test/factories/tasks/SingleChoiceTaskFactory.js
Labels: approved, bug, refactor

#2079 Classifier: Clean up step annotations history
  packages/lib-classifier/src/store/AnnotatedSteps/AnnotatedSteps.js
Labels: approved, refactor

#2084 Test suggestions for #2071
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/SurveyTask.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/Choices/Choices.spec.js
Labels: approved, refactor
