Repository zooniverse/front-end-monorepo, pull requests merged in 2021-12, with the labels that each got.

#2542 Vertical layout for Project Announcements
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/components/NarrowGenericAnnouncement/NarrowGenericAnnouncement.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/components/WideGenericAnnouncement/WideGenericAnnouncement.js
Labels: bug, design, approved

#2563 Classifier: Check bearer token on annotation update
  packages/lib-classifier/src/plugins/tasks/models/Annotation.js
Labels: approved

#2565 Add a warning for unsaved work from the transcription task
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.spec.js
Labels: bug, refactor, approved

#2526 Clean up classifier workflows
  packages/lib-classifier/src/store/README.md
  packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.spec.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/WorkflowConfiguration/WorkflowConfiguration.spec.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/WorkflowConfiguration/index.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/index.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.spec.js
Labels: refactor, approved

#2576 Add mobile app nav item
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.js
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.spec.js
Labels: approved

#2567 Classifier: Refactor classification queue promises
  packages/lib-classifier/src/store/utils/ClassificationQueue.js
Labels: refactor, approved

#2581 Consolidate build workflows
  .github/workflows/ci-storybook.yml
  .github/workflows/ci-tests.yml
Labels: ops, approved

#2580 Engaging Crowds: Allow completed workflows to be fetched by ID
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
Labels: enhancement, approved

#2572 Engaging Crowds: ADRs for selecting a subject
  docs/arch/README.md
  docs/arch/adr-37.md
  docs/arch/adr-38.md
Labels: documentation, ops, approved

#2582 CI: Use built-in Node package caching
  .github/workflows/ci-tests.yml
Labels: ops, approved

#2585 Upgrade testing libraries
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-async-states/package.json
  packages/lib-classifier/package.json
  packages/lib-panoptes-js/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies, approved

#2583 Classifier: Refactor store connectors for image subject viewers
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerConnector.js
Labels: refactor, approved
