Repository zooniverse/front-end-monorepo, pull requests merged in 2022-09, with the labels that each got.

#3592 Documentation: remove out-of-date troubleshooting guide
  docs/troubleshooting-guide.md
Labels: documentation, approved

#3559 Freehand line: cancel edits on deselect
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
Labels: bug, experiment, approved

#3571 NextJS Upgrade to 12.2.5
  packages/app-content-pages/package.json
  packages/app-content-pages/src/screens/Team/components/Person/Person.js
  packages/app-content-pages/src/screens/Team/components/Team/Team.js
  packages/app-project/package.json
  packages/app-project/pages/_middleware.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStatsContainer.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStatsContainer.spec.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePageConnector.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePageConnector.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProject.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProjectContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProjectContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcher.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/ZooniverseTalk.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.spec.js
  packages/app-project/src/shared/components/ContentBox/ContentBox.js
  packages/app-project/src/shared/components/ContentBox/ContentBox.stories.js
  packages/app-project/src/shared/components/NavLink/NavLink.js
  packages/app-project/src/shared/components/StubComponent/StubComponent.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchStatuses.js
  packages/app-project/src/shared/components/WidgetHeading/WidgetHeading.js
  packages/app-project/src/shared/components/WidgetHeading/WidgetHeading.spec.js
  packages/app-project/src/shared/components/withRequireUser/withRequireUser.js
  packages/app-project/src/shared/components/withRequireUser/withRequireUser.spec.js
  yarn.lock
Labels: approved

#3615 Update Japanese Dictionaries
  packages/app-project/public/locales/ja/components.json
  packages/app-project/public/locales/ja/screens.json
  packages/lib-classifier/src/translations/ja/components.json
  packages/lib-classifier/src/translations/ja/plugins.json
  packages/lib-react-components/src/translations/ja.json
Labels: approved, translations

#3616 Project App: Refactor naming of mockStore when it's injected as a component prop
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.js
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.spec.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.spec.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncementConnector.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncementConnector.spec.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorConnector.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelectorConnector.spec.js
Labels: refactor, dx, approved, tests

#3607 Project: only render user recents in the browser
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js
Labels: bug, approved

#3609 Project: clear stored User on log out
  packages/app-project/stores/User/User.js
Labels: bug, approved

#3601 NextJS apps: enable Strict Mode
  packages/app-content-pages/next.config.js
  packages/app-project/next.config.js
Labels: dx, approved

#3646 Refactor LightCurveViewer height with defined value before d3 svg defined
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
Labels: bug, high priority, approved

#3652 Revert "Refactor LightCurveViewer height with defined value before d3 svg defined"
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
Labels: bug, approved

#3661 Classifier: Refactor LightCurveViewer to use Chart component
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/index.js
  yarn.lock
Labels: refactor, approved

#3662 Edit LightCurveViewer saveBrushesToAnnotations props reference
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
Labels: bug, approved

#3598 Freehand line: adjust segments before editing
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
Labels: enhancement, experiment, approved

#3666 Projects: add Admin Mode
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/components/AdminContainer/AdminContainer.js
  packages/app-project/src/components/AdminContainer/AdminContainer.spec.js
  packages/app-project/src/components/AdminContainer/index.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js
  packages/app-project/src/components/index.js
  packages/app-project/src/hooks/index.js
  packages/app-project/src/hooks/useAdminMode.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.spec.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayout.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayout.spec.js
  packages/app-project/stores/User/User.js
Labels: enhancement, approved

#3669 Project admin: fix typo
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
Labels: bug, dx, approved

#3600 Consolidate NextJS app configs
  .github/workflows/ci-build.yml
  .github/workflows/deploy_branch.yml
  .github/workflows/deploy_staging.yml
  Dockerfile
  Jenkinsfile
  README.md
  kubernetes/deployment-branch.tmpl
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-content-pages/src/helpers/logger/initializeSentry.js
  packages/app-project/next.config.js
  packages/app-project/package.json
Labels: ops, approved

#3678 Markdownz: catch parsing errors
  packages/lib-react-components/src/Markdownz/Markdownz.js
Labels: bug, approved

#3641 Classifier tasks: Copy task.required for legacy dropdowns
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/helpers/legacyDropdownAdapter/legacyDropdownAdapter.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/helpers/legacyDropdownAdapter/legacyDropdownAdapter.spec.js
Labels: bug, approved

#3671 Replace url-parse with URL
  packages/app-content-pages/package.json
  packages/app-content-pages/src/shared/components/AuthModal/AuthModalContainer.js
  packages/app-content-pages/src/shared/components/AuthModal/AuthModalContainer.spec.js
  packages/app-content-pages/src/shared/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js
  packages/app-content-pages/test/create-global-document.js
  packages/app-project/package.json
  packages/app-project/src/components/AuthModal/AuthModalContainer.js
  packages/app-project/src/components/AuthModal/AuthModalContainer.spec.js
  packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js
  packages/lib-panoptes-js/package.json
  packages/lib-panoptes-js/src/resources/projects/helpers.js
  yarn.lock
Labels: refactor, approved

#3645 Classifier: Refactor Video Subject Viewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getFixedNumber/README.md
  packages/lib-classifier/src/translations/en/components.json
Labels: refactor, storybook, approved, tests, video subject

#3623 yarn clean-install
  bin/bootstrap.sh
  bin/clean-install.sh
  package.json
Labels: ops, dx, approved

#3625 Drawing tool tests: wrap marks in <svg>
  packages/lib-classifier/src/plugins/drawingTools/components/Circle/Circle.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/DeleteButton/DeleteButton.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.spec.js
Labels: bug, approved

#3599 Improve Publications and Team page content accessibility
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Publications/PublicationsContainer.js
  packages/app-content-pages/src/screens/Publications/components/Category/Category.js
  packages/app-content-pages/src/screens/Team/Team.js
  packages/app-content-pages/src/screens/Team/TeamContainer.js
  packages/app-content-pages/src/screens/Team/components/Team/Team.js
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.js
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.spec.js
  packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.js
  packages/app-content-pages/src/shared/components/TwoColumnLayout/TwoColumnLayout.js
Labels: accessibility, approved

#3632 Video subjects: Add touch styles
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
Labels: bug, approved

#3699 Zooniverse-React-Components: Remove Enzyme from ZooFooter
  packages/lib-react-components/src/ZooFooter/ZooFooter.js
  packages/lib-react-components/src/ZooFooter/ZooFooter.spec.js
  packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.js
  packages/lib-react-components/src/ZooFooter/components/PolicyLinkSection/PolicyLinkSection.js
  packages/lib-react-components/src/ZooFooter/components/index.js
  packages/lib-react-components/src/translations/en.json
Labels: refactor, approved

#3700 Zooniverse-React-Components: Remove Enzyme from ZooHeader
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.spec.js
  packages/lib-react-components/src/ZooHeader/components/MainNavList/MainNavList.js
  packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/SignedOutUserNavigation.js
Labels: refactor, approved

#3685 Refactor Markdownz as a functional component
  packages/lib-react-components/src/Markdownz/Markdownz.js
  packages/lib-react-components/src/Markdownz/Markdownz.spec.js
  packages/lib-react-components/test/setup.js
Labels: refactor, approved

#3702 Remove Choice conditional input focus, fix accessibility and scroll issues
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.spec.js
Labels: approved

#3680 Freehand lines: optimise annotation size
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/README.md
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
Labels: refactor, approved

#3704 Maintenance: replace deprecated Grommet 'tag' prop with 'as'
  packages/app-project/src/shared/components/Stat/Stat.js
  packages/lib-classifier/src/plugins/tasks/dataVisAnnotation/components/DataVisAnnotationTask.js
  packages/lib-classifier/src/plugins/tasks/drawing/components/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.js
  packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/subjectGroupComparison/components/SubjectGroupComparisonTask.js
  packages/lib-react-components/src/ZooFooter/ZooFooter.js
  packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
Labels: approved

#3711 Add project page-level headers
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/shared/components/ContentBox/ContentBox.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayout.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
Labels: bug, accessibility, approved, degraded-ux
