Repository zooniverse/front-end-monorepo, pull requests merged in 2022-07, with the labels that each got.

#3372 UI Fix: allow `<Tabs>` to have more than 2 `<Tab>`s in a row
  packages/lib-react-components/src/Tabs/Tabs.stories.js
  packages/lib-react-components/src/Tabs/theme.js
Labels: bug, approved

#3257 Refactor ImageAndTextViewer and SingleTextViewer with minimum height from subject image
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerContainer.js
Labels: refactor, approved

#3383 Classifier: Use red for Already Seen banner
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBanner.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBanner.spec.js
Labels: bug, approved

#3345 Use internal API service names for SSR
  packages/app-project/pages/[owner]/[project]/about/team.js
  packages/app-project/src/helpers/fetchProjectData/fetchProjectData.js
  packages/app-project/src/helpers/fetchProjectData/fetchProjectData.spec.js
  packages/app-project/src/helpers/fetchProjectPage/fetchProjectPage.js
  packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
  packages/app-project/src/helpers/fetchTranslations/fetchTranslations.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/helpers/getServerSideAPIHost/getServerSideAPIHost.js
  packages/app-project/src/helpers/getServerSideAPIHost/index.js
  packages/lib-panoptes-js/src/panoptes.js
  packages/lib-panoptes-js/src/panoptes.spec.js
  packages/lib-panoptes-js/src/resources/projects/commonRequests.js
Labels: ops, performance, approved

#3351 QuickTalk: Improve UI
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/PostForm.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/PostForm.spec.js
  packages/lib-classifier/src/translations/en/components.json
Labels: approved

#3400 getServerSideAPIHost: set default API env
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/helpers/getServerSideAPIHost/getServerSideAPIHost.js
Labels: ops, approved

#3402 remove master branch from jenkins
  Jenkinsfile
Labels: approved

#3395 App-project: Add translation keys for TeamMember roles
  packages/app-project/public/locales/en/screens.json
  packages/app-project/public/locales/test/screens.json
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.spec.js
Labels: refactor, approved, translations

#3337 Classifier: scale subject width to page zoom
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
Labels: bug, accessibility, approved

#3403 Project: Refactor Team page
  packages/app-project/pages/[owner]/[project]/about/team.js
  packages/app-project/src/helpers/fetchTeam/fetchTeam.js
  packages/app-project/src/helpers/fetchTeam/index.js
Labels: bug, refactor, performance, approved

#3389 Classifier: refactor polygon tool
  packages/lib-classifier/src/plugins/drawingTools/components/DragHandle/DragHandle.js
  packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.js
  packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.stories.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Polygon/Polygon.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/PolygonTool/PolygonTool.js
  packages/lib-classifier/src/plugins/drawingTools/types/FixedNumber.js
  packages/lib-classifier/src/plugins/drawingTools/types/FixedNumber.spec.js
  packages/lib-classifier/src/plugins/drawingTools/types/index.js
Labels: refactor, approved

#3416 Classifier: Adjust FieldGuideButton text styling
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.js
Labels: bug, approved

#3393 Classifier: refactor freehand line tool
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.stories.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
Labels: refactor, approved

#3432 Branch deploy k8s setup
  .github/workflows/deploy_branch.yml
  kubernetes/deployment-branch.tmpl
Labels: approved

#3415 Classifier: responsive layout for tablets
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
Labels: bug, accessibility, design, approved

#3347 Refactor Notifications with panoptes-js talkAPI
  packages/app-project/stores/User/UserPersonalization/Notifications/Notifications.js
  packages/app-project/stores/User/UserPersonalization/Notifications/Notifications.spec.js
  packages/app-project/stores/User/UserPersonalization/Notifications/helpers/getTalkUnreadNotificationsCount.js
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.spec.js
  packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.spec.js
  packages/app-project/stores/User/UserPersonalization/YourStats/YourStats.spec.js
Labels: refactor, approved

#3439 Project: Refactor /classify redirects
  packages/app-project/pages/[owner]/[project]/classify/index.js
Labels: refactor, approved

#3424 Classifier: validate drawn marks on tool change
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopupContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopupContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/plugins/drawingTools/README.md
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
  packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingTask.js
Labels: bug, approved, degraded-ux

#3388 Bump storybook to 6.5.9
  yarn.lock
Labels: storybook

#3409 Project: Refactor About pages
  packages/app-project/pages/[owner]/[project]/about/education.js
  packages/app-project/pages/[owner]/[project]/about/faq.js
  packages/app-project/pages/[owner]/[project]/about/research.js
  packages/app-project/pages/[owner]/[project]/about/results.js
  packages/app-project/pages/[owner]/[project]/about/team.js
  packages/app-project/src/helpers/fetchProjectData/fetchProjectData.js
  packages/app-project/src/helpers/fetchProjectPageTitles/fetchProjectPageTitles.js
  packages/app-project/src/helpers/fetchProjectPageTitles/fetchProjectPageTitles.spec.js
  packages/app-project/src/helpers/fetchProjectPageTitles/index.js
  packages/app-project/src/helpers/fetchTeam/fetchTeam.spec.js
  packages/lib-panoptes-js/src/resources/projects/commonRequests.js
Labels: refactor, performance, approved

#3431 Classifier: remove default drawing tool gestures
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/FreehandLineTool/FreehandLineTool.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/TranscriptionLineTool/TranscriptionLineTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Ellipse/Ellipse.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/CircleTool/CircleTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/EllipseTool/EllipseTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/LineTool/LineTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/PointTool/PointTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/RectangleTool/RectangleTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/RotateRectangleTool/RotateRectangleTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/TemporalPointTool/TemporalPointTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/TemporalRotateRectangleTool/TemporalRotateRectangleTool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
Labels: refactor, approved

#3464 Daily Classifications Chart: fix locale
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartConnector.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.spec.js
Labels: bug, refactor, approved

#3447 App-project: Refactor ProjectHeader styling
  packages/app-project/package.json
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/ApprovedIcon.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.js
  packages/app-project/src/components/ProjectHeader/components/LocaleSwitcher/LocaleSwitcher.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js
  yarn.lock
Labels: refactor, design, approved

#3469 App-project: Enable locale switcher for live site
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js
Labels: approved, translations

#3387 Content pages: log SSR errors with @sentry/node
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-content-pages/src/helpers/logger/initializeSentry.js
  packages/app-content-pages/src/helpers/logger/logNodeError.js
  packages/app-content-pages/src/helpers/logger/logReactError.js
Labels: refactor, ops, approved

#3476 Revert "Bump lerna from 5.1.8 to 5.2.0"
  package.json
  yarn.lock
Labels: approved

#3475 Allow manual staging deploys via workflow dispatch
  .github/workflows/deploy_staging.yml
Labels: approved

#3478 Update Translations docs with link to Translations Guidebook
  packages/app-project/public/locales/README.md
  packages/lib-classifier/src/translations/README.md
  packages/lib-react-components/src/translations/README.md
Labels: documentation, approved, translations

#3479 Add dotenv dependency to app-content-pages and app-project
  packages/app-content-pages/package.json
  yarn.lock
Labels: dependencies, ops, approved

#3487 Project: remove dotenv
  packages/app-project/next.config.js
  packages/app-project/package.json
Labels: refactor, ops, approved

#3484 Refactor CI test builds
  .github/workflows/ci-build.yml
Labels: ops, approved

#2979 App-project: Persist user sessions in session storage
  packages/app-project/package.json
  packages/app-project/pages/_app.js
  packages/app-project/src/hooks/index.js
  packages/app-project/src/hooks/usePanoptesUser.js
  packages/app-project/stores/User/User.js
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.js
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.spec.js
  packages/app-project/stores/initStore.js
  packages/app-project/stores/initStore.spec.js
  packages/app-project/webpack.config.js
Labels: enhancement, refactor, performance, approved
