Repository zooniverse/front-end-monorepo, pull requests merged in 2022-02, with the labels that each got.

#2732 Classifier: remove @inject from Layout
  packages/lib-classifier/src/components/Classifier/components/Layout/Layout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/Layout.spec.js
Labels: refactor, approved

#2704 app-project: Refactor ProjectAboutPages' components to use next-i18next
  packages/app-project/.storybook/i18n.js
  packages/app-project/.storybook/main.js
  packages/app-project/.storybook/preview.js
  packages/app-project/package.json
  packages/app-project/pages/[owner]/[project]/about/education.js
  packages/app-project/pages/[owner]/[project]/about/faq.js
  packages/app-project/pages/[owner]/[project]/about/research.js
  packages/app-project/pages/[owner]/[project]/about/results.js
  packages/app-project/pages/[owner]/[project]/about/team.js
  packages/app-project/public/locales/README.md
  packages/app-project/public/locales/en/common.json
  packages/app-project/public/locales/en/screens.json
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPageConnector.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.spec.js
  packages/app-project/src/screens/ProjectAboutPage/locales/en.json
  packages/app-project/test/i18n-for-tests.js
  packages/app-project/webpack.config.js
  yarn.lock
Labels: refactor, approved

#2731 Classifier: Remove @inject from ImageToolbar
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.spec.js
Labels: refactor, approved

#2669 lib-react-components: Remove counterpart and use react-i18next
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/README.md
  packages/lib-react-components/package.json
  packages/lib-react-components/src/AdminCheckbox/AdminCheckbox.js
  packages/lib-react-components/src/AdminCheckbox/locales/en.json
  packages/lib-react-components/src/CloseButton/CloseButton.js
  packages/lib-react-components/src/CloseButton/locales/en.json
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.js
  packages/lib-react-components/src/FavouritesButton/locales/en-GB.json
  packages/lib-react-components/src/FavouritesButton/locales/en-US.json
  packages/lib-react-components/src/ZooFooter/ZooFooter.js
  packages/lib-react-components/src/ZooFooter/locales/en.json
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
  packages/lib-react-components/src/ZooHeader/components/MainNavList/MainNavList.spec.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMainNavMenu/NarrowMainNavMenu.spec.js
  packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/locales/en.json
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/SignedOutUserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/locales/en.json
  packages/lib-react-components/src/ZooHeader/components/UserMenu/UserMenu.js
  packages/lib-react-components/src/ZooHeader/components/UserMenu/locales/en.json
  packages/lib-react-components/src/ZooHeader/helpers/index.js
  packages/lib-react-components/src/ZooHeader/helpers/navListItems.js
  packages/lib-react-components/src/ZooHeader/locales/en.json
  packages/lib-react-components/src/translations/README.md
  packages/lib-react-components/src/translations/en.json
  packages/lib-react-components/src/translations/i18n.js
Labels: refactor, approved, translations

#2657 Classifier: Persist the subjects store in session storage
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/components/Classifier/index.js
  packages/lib-classifier/src/store/SubjectStore/Subject/Subject.spec.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.spec.js
  packages/lib-classifier/test/mockStore/mockStore.js
Labels: bug, enhancement, experiment, approved

#2684 Patch @babel/core and @babel/preset-env
  yarn.lock
Labels: dependencies, approved

#2740 app-project: Remove @inject from ProjectHomePage > RecentSubjects and translate it with next-i18next
  packages/app-project/pages/[owner]/[project]/index.js
  packages/app-project/public/locales/en/screens.json
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/ZooniverseTalk.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/ZooniverseTalk.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButton.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjects.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjects.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/components/SubjectThumbnail/SubjectThumbnail.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/components/SubjectThumbnail/locales/en.json
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/locales/en.json
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/locales/en.json
Labels: refactor, approved, translations

#2748 Classifier: react to workflow version changes
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
Labels: bug, approved

#2750 Remove log from ProjectHomePage > RecentSubjectsContainer
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.js
Labels: approved

#2755 Classifier: persist selected subject set ID
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
Labels: bug, high priority, approved

#2767 lib-classifier: Refactor FieldGuide components to use react-i18next
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuideContainer.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuideContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/locales/en.json
  packages/lib-classifier/src/translations/en/components.json
Labels: refactor, approved, translations

#2784 app-project: Refactor ClassifyPage components to use next-i18next
  packages/app-project/pages/[owner]/[project]/classify/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject/[subjectID]/index.js
  packages/app-project/public/locales/en/screens.json
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/components/ErrorMessage/ErrorMessage.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/components/ErrorMessage/locales/en.json
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/locales/en.json
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsButton/RelatedProjectsButton.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsButton/locales/en.json
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/RelatedProjectsModal.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/components/ProjectCard/ProjectCard.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/components/ProjectCard/locales/en.json
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/RelatedProjects/components/RelatedProjectsModal/locales/en.json
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/locales/en.json
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/locales/en.json
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/locales/en.json
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/locales/en.json
  packages/app-project/src/screens/ClassifyPage/components/YourStats/locales/en.json
Labels: refactor, approved, translations

#2772 lib-classifier: ImageToolbar stories and refactor its component translations
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/locales/en.json
  packages/lib-classifier/src/translations/en/components.json
Labels: refactor, storybook, approved, translations

#2791 Enable session storage for projects with ordered subjects
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
Labels: bug, approved

#2733 Classifier: fix dev classifier OAuth redirect
  packages/lib-classifier/dev/components/App/App.js
Labels: bug, dx, approved

#2738 app-project: Translate Hero and MessageFromResearcher components with next-i18next
  packages/app-project/public/locales/en/screens.json
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/Introduction.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Introduction/locales/en.json
  packages/app-project/src/screens/ProjectHomePage/components/Hero/helpers/README.md
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcher.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcher.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/locales/en.json
Labels: refactor, approved, translations

#2718 Content pages: remove node-cache
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  yarn.lock
Labels: dependencies, approved

#2786 Bump the storybooks to 6.4.18
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies, approved

#2761 Content pages: remove async
  packages/app-content-pages/package.json
  yarn.lock
Labels: dependencies, approved

#2800 Classifier: Refactor subject snapshots
  packages/lib-classifier/src/store/SubjectStore/Subject/Subject.js
  packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/TranscriptionReductions.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
Labels: bug, refactor, approved

#2711 lib-classifier: Refactor feedback component to use react-i18next
  packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.js
  packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.spec.js
  packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js
  packages/lib-classifier/src/components/Classifier/components/Feedback/locales/en.json
  packages/lib-classifier/src/translations/en/components.json
Labels: refactor, approved, translations

#2823 App-project: Use router locale for DailyClassificationsChart
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.stories.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsCarousel.js
Labels: refactor, approved

#2824 App-project: Translate Announcements components with next-i18next
  packages/app-project/.storybook/i18n.js
  packages/app-project/pages/[owner]/[project]/about/education.js
  packages/app-project/pages/[owner]/[project]/about/faq.js
  packages/app-project/pages/[owner]/[project]/about/research.js
  packages/app-project/pages/[owner]/[project]/about/results.js
  packages/app-project/pages/[owner]/[project]/about/team.js
  packages/app-project/pages/[owner]/[project]/classify/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject/[subjectID]/index.js
  packages/app-project/pages/[owner]/[project]/index.js
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationContainer.js
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationContainer.spec.js
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/locales/en.json
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.spec.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/locales/en.json
Labels: refactor, approved, translations

#2719 Remove @inject from subject viewers
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.spec.js
  packages/lib-classifier/src/helpers/index.js
  packages/lib-classifier/src/helpers/useJSONData/README.md
  packages/lib-classifier/src/helpers/useJSONData/index.js
  packages/lib-classifier/src/helpers/useJSONData/useJSONData.js
Labels: refactor, approved

#2833 Add suggested explanations to PR template
  docs/PULL_REQUEST_TEMPLATE.md
Labels: documentation, approved

#2827 App-project: Translate AuthModal components with next-i18next
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/components/AuthModal/components/LoginForm/LoginForm.js
  packages/app-project/src/components/AuthModal/components/LoginForm/LoginFormContainer.js
  packages/app-project/src/components/AuthModal/components/LoginForm/LoginFormContainer.spec.js
  packages/app-project/src/components/AuthModal/components/LoginForm/components/Form/Form.js
  packages/app-project/src/components/AuthModal/components/LoginForm/locales/en.json
  packages/app-project/src/components/AuthModal/components/RegisterForm/RegisterForm.js
  packages/app-project/src/components/AuthModal/components/RegisterForm/RegisterFormContainer.js
  packages/app-project/src/components/AuthModal/components/RegisterForm/RegisterFormContainer.spec.js
  packages/app-project/src/components/AuthModal/components/RegisterForm/components/Form/Form.js
  packages/app-project/src/components/AuthModal/components/RegisterForm/components/Form/Form.spec.js
  packages/app-project/src/components/AuthModal/components/RegisterForm/locales/en.json
Labels: refactor, approved, translations

#2832 App-project: Translate Head and ProjectHeader components with next-i18next
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/components/Head/Head.js
  packages/app-project/src/components/Head/locales/en.json
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js
  packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/ApprovedIcon.js
  packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/ApprovedIcon.spec.js
  packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/locales/en.json
  packages/app-project/src/components/ProjectHeader/components/Avatar/Avatar.js
  packages/app-project/src/components/ProjectHeader/components/Avatar/Avatar.spec.js
  packages/app-project/src/components/ProjectHeader/components/Avatar/locales/en.json
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
  packages/app-project/src/components/ProjectHeader/components/Nav/locales/en.json
  packages/app-project/src/components/ProjectHeader/components/UnderReviewLabel/UnderReviewLabel.js
  packages/app-project/src/components/ProjectHeader/components/UnderReviewLabel/locales/en.json
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.js
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/getNavLinks.spec.js
  packages/app-project/src/components/ProjectHeader/helpers/getNavLinks/index.js
  packages/app-project/src/components/ProjectHeader/locales/en.json
Labels: refactor, approved, translations

#2825 lib-classifier: MetaTools stories and refactor its component translations
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/CollectionsButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/CollectionsButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/HidePreviousMarksButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/HidePreviousMarksButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/HidePreviousMarksButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/HidePreviousTranscriptionsButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/HidePreviousTranscriptionsButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/HidePreviousTranscriptionsButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/MetadataButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/MetadataButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.stories.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/locales/en.json
  packages/lib-classifier/src/translations/en/components.json
Labels: refactor, storybook, approved, translations

#2848 Lib-classifier: Remove @inject from tutorial components and translate with react-i18next
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/locales/en.json
  packages/lib-classifier/src/translations/en/components.json
Labels: refactor, approved, translations

#2793 Classifier: Refactor ClassifierContainer hooks
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/components/Classifier/hooks/Readme.md
  packages/lib-classifier/src/components/Classifier/hooks/index.js
  packages/lib-classifier/src/components/Classifier/hooks/useHydratedStore.js
  packages/lib-classifier/src/components/Classifier/hooks/useStore.js
  packages/lib-classifier/src/components/Classifier/hooks/useWorkflowSnapshot.js
  packages/lib-classifier/src/store/RootStore.js
Labels: refactor, approved

#2861 Lib-classifier: Translate all SubjectViewer components with react-i18next
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ConfirmModal/ConfirmModal.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ConfirmModal/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/SaveButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/PeriodMultipleControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/PeriodMultipleControls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PhaseFocusControls/PhaseFocusControls.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/VideoController.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/components/Slider/Slider.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/locales/en.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ZoomControlButton/ZoomControlButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ZoomControlButton/ZoomControlButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ZoomControlButton/locales/en.json
  packages/lib-classifier/src/translations/en/components.json
Labels: refactor, approved, translations

#2872 Refactor LightCurveViewerContainer to return null if dataPoints has no length
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
Labels: bug, approved

#2866 Lib-classifier: Translate /plugins components with react-i18next
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.spec.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/locales/en.json
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/components/DataVisAnnotationTask.js
  packages/lib-classifier/src/plugins/tasks/DataVisAnnotationTask/components/locales/en.json
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/SimpleDropdownTask.js
  packages/lib-classifier/src/plugins/tasks/SimpleDropdownTask/components/locales/en.json
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/ConfusedWith.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/ConfusedWith.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/components/Confusion.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/components/Confusion.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/ConfusedWith/locales/en.json
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/locales/en.json
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.spec.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/ClearFilters/ClearFilters.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Chooser/components/CharacteristicsFilter/locales/en.json
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTagButtons/TextTagButtons.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/components/TextTagButtons/locales/en.json
  packages/lib-classifier/src/plugins/tasks/components/InputStatus/InputStatus.js
  packages/lib-classifier/src/plugins/tasks/components/InputStatus/InputStatus.spec.js
  packages/lib-classifier/src/plugins/tasks/components/InputStatus/locales/en.json
  packages/lib-classifier/src/translations/en/plugins.json
Labels: refactor, approved, translations

#2880 Classifier: Skip Choice component tests due to timeout
  packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js
Labels: approved

#2881 Classifier: Refactor FeedbackModal. Remove @inject.
  packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.js
  packages/lib-classifier/src/components/Classifier/components/Feedback/FeedbackModal.spec.js
  packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js
  packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.spec.js
Labels: bug, high priority, refactor, approved

#2882 Light Curve Viewer: stop Animation when new Subject loads
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
Labels: bug, approved

#2870 Classifier: refactor tutorial components to use `useState` hooks
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.spec.js
  packages/lib-classifier/src/store/Medium/Medium.js
  packages/lib-classifier/src/store/Medium/Medium.spec.js
  packages/lib-classifier/src/store/Medium/index.js
  packages/lib-classifier/src/store/TutorialStore.spec.js
  packages/lib-classifier/src/store/TutorialStore/Tutorial/Tutorial.js
  packages/lib-classifier/src/store/TutorialStore/Tutorial/Tutorial.spec.js
  packages/lib-classifier/src/store/TutorialStore/Tutorial/index.js
  packages/lib-classifier/src/store/TutorialStore/TutorialStore.js
  packages/lib-classifier/src/store/TutorialStore/TutorialStore.spec.js
  packages/lib-classifier/src/store/TutorialStore/index.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore/UserProjectPreferences/UserProjectPreferences.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore/UserProjectPreferences/UserProjectPreferences.spec.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore/UserProjectPreferences/index.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore/UserProjectPreferencesStore.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore/UserProjectPreferencesStore.spec.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore/index.js
Labels: bug, refactor, approved

#2888 Classifier: Filter prioritised subject queues
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
Labels: bug, enhancement, approved

#2878 App-project: Translate ThemeModeToggle with next-i18next and add its storybook
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/components/ThemeModeToggle/ThemeModeToggle.js
  packages/app-project/src/components/ThemeModeToggle/ThemeModeToggle.stories.js
  packages/app-project/src/components/ThemeModeToggle/locales/en.json
Labels: refactor, storybook, approved, translations

#2893 Refactor TutorialStore hasNotSeenTutorialBefore to return false if UPP or tutorial not determined
  packages/lib-classifier/src/store/TutorialStore/TutorialStore.js
Labels: approved

#2879 App-project: Refactor ProjectHomePage > AboutProject (translations, remove decorators, add story)
  packages/app-project/public/locales/en/screens.json
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProject.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProject.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProject.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProjectContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProjectContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/index.js
  packages/app-project/src/shared/components/AboutProject/AboutProjectContainer.js
  packages/app-project/src/shared/components/AboutProject/locales/en.json
Labels: refactor, storybook, approved, translations

#2895 Classifier: fix empty subject queue on load
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.spec.js
Labels: bug, approved
