Repository zooniverse/front-end-monorepo, pull requests merged in 2022-08, with the labels that each got.

#3543 Project: don't render Loader component during Server-Side Rendering
  packages/app-project/src/shared/components/Loader/Loader.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js
Labels: bug, approved

#3542 Add support for Turkish translations
  packages/app-project/next-i18next.config.js
  packages/app-project/public/locales/hi/screens.json
  packages/app-project/public/locales/ru/screens.json
  packages/app-project/public/locales/sv/screens.json
  packages/app-project/public/locales/tr/components.json
  packages/app-project/public/locales/tr/screens.json
  packages/app-project/src/helpers/localeMenu.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.js
  packages/lib-classifier/dev/components/App/localeMenu.js
  packages/lib-classifier/src/translations/i18n.js
  packages/lib-classifier/src/translations/tr/components.json
  packages/lib-classifier/src/translations/tr/plugins.json
  packages/lib-react-components/src/ZooHeader/components/NarrowMenu/NarrowMenu.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenuNavListItem/NarrowMenuNavListItem.js
  packages/lib-react-components/src/ZooHeader/components/UserMenu/UserMenu.js
  packages/lib-react-components/src/translations/i18n.js
  packages/lib-react-components/src/translations/tr.json
Labels: approved, translations

#3549 Classifier: assign unique IDs to transcribed lines
  packages/lib-classifier/src/store/SubjectStore/Subject/TranscriptionReductions/TranscriptionReductions.js
Labels: bug, approved

#3554 Add professional Spanish translations for all FEM packages
  packages/app-project/public/locales/es/components.json
  packages/app-project/public/locales/es/screens.json
  packages/lib-classifier/src/translations/es/components.json
  packages/lib-classifier/src/translations/es/plugins.json
  packages/lib-react-components/src/translations/es.json
Labels: approved, translations

#3533 Refactor StepNavigation and shared components
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/Banner.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.stories.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/shared/StepNavigation/StepNavigation.js
  packages/lib-classifier/src/components/Classifier/components/shared/StepNavigation/StepNavigation.spec.js
  packages/lib-classifier/src/components/Classifier/components/shared/StepNavigation/index.js
  packages/lib-classifier/src/translations/en/components.json
  packages/lib-classifier/src/translations/test/components.json
  packages/lib-classifier/webpack.dev.js
  packages/lib-classifier/webpack.dist.js
Labels: bug, approved, degraded-ux

#3446 Drawing tools: edit freehand lines
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
Labels: enhancement, experiment, approved

#2988 Classifier: refactor UPP data-fetching with hooks
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.spec.js
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.spec.js
  packages/lib-classifier/src/hooks/Readme.md
  packages/lib-classifier/src/hooks/index.js
  packages/lib-classifier/src/hooks/useProjectPreferences.js
  packages/lib-classifier/src/hooks/useProjectRoles.js
  packages/lib-classifier/src/store/TutorialStore/Tutorial/Tutorial.spec.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore/UserProjectPreferencesStore.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore/UserProjectPreferencesStore.spec.js
Labels: refactor, approved

#3294 Generalise Classifier workflow tests
  packages/lib-classifier/src/components/Classifier/Classifier.spec.js
  packages/lib-classifier/src/components/Classifier/Classifier.workflows.spec.js
  packages/lib-classifier/src/plugins/tasks/dataVisAnnotation/components/DataVisAnnotationTask.js
Labels: enhancement, approved

#3152 Project: Language middleware
  packages/app-project/pages/_middleware.js
  packages/app-project/server/dev-server.js
  packages/app-project/server/server.js
Labels: enhancement, approved, translations

#3457 Classifier: add forwardRef to withFeatureFlag
  packages/lib-classifier/src/helpers/withFeatureFlag/withFeatureFlag.js
Labels: refactor, approved

#3312 Project: withEnvironments(Component, environments)
  packages/app-project/src/components/ProjectHeader/components/LocaleSwitcher/LocaleSwitcher.js
  packages/app-project/src/helpers/index.js
  packages/app-project/src/helpers/withEnvironments/README.md
  packages/app-project/src/helpers/withEnvironments/index.js
  packages/app-project/src/helpers/withEnvironments/withEnvironments.js
  packages/app-project/src/helpers/withEnvironments/withEnvironments.spec.js
Labels: enhancement, refactor, approved

#3458 Classifier: add forwardRef to withStores
  packages/lib-classifier/src/helpers/withStores/withStores.js
Labels: refactor, approved

#3551 Maintenance: rebuild yarn.lock. Upgrade NextJS to 12.1.6
  packages/app-project/package.json
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.spec.js
  packages/app-project/src/helpers/addQueryParams/README.md
  packages/app-project/src/helpers/addQueryParams/addQueryParams.js
  packages/app-project/src/helpers/addQueryParams/addQueryParams.spec.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.spec.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartConnector.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink/AboutNavLink.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButtonContainer.js
  packages/app-project/src/shared/components/NavLink/NavLink.js
  packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayout.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayout.spec.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
  yarn.lock
Labels: approved

#3396 Add unread Messages count to ZooHeader, with sugar subscription
  packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js
  packages/app-project/stores/User/UserPersonalization/Notifications/Notifications.js
  packages/app-project/stores/User/UserPersonalization/Notifications/Notifications.spec.js
  packages/app-project/stores/User/UserPersonalization/Notifications/helpers/getTalkUnreadConversationsIds.js
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.spec.js
Labels: enhancement, approved

#3570 Fix SubTaskPopup tests
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
Labels: approved

#3569 Project: show workflow menu in stories
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.stories.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
Labels: bug, approved

#3568 fix modal-subtask buttons on touch devices
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js
Labels: approved

#3459 Classifier: Replace QuickTalk HOCs with hooks
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.spec.js
Labels: refactor, approved

#3536 Drawing tools: refactor active mark selection
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.js
  packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingTask.js
Labels: bug, refactor, approved

#3572 Project: Remove logger from exported helpers
  packages/app-project/src/helpers/index.js
Labels: bug, approved

#3535 Improved touch event handling for drawing tools
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
Labels: bug, approved

#3565 Project: Refactor data-fetching for favourites
  packages/app-project/pages/_app.js
  packages/app-project/src/hooks/index.js
  packages/app-project/src/hooks/usePanoptesAuth.js
  packages/app-project/src/hooks/useUserFavourites.js
  packages/app-project/stores/User/Collections/Collections.js
  packages/app-project/stores/User/Collections/Collections.spec.js
  packages/app-project/stores/User/User.js
  packages/lib-panoptes-js/src/resources/collections/rest.js
Labels: bug, approved, degraded-ux

#3583 Fixed accessibility issue: content filters are before the publications list in the tab order
  packages/app-content-pages/src/shared/components/TwoColumnLayout/TwoColumnLayout.js
Labels: accessibility, approved

#3586 Fix NextJS asset prefixes
  Jenkinsfile
Labels: ops, approved
