Repository zooniverse/front-end-monorepo, pull requests merged in 2022-12, with the labels that each got.

#3927 Classifier: Adjust Flipbook styling for small screens
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/components/FlipbookControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/components/theme.js
Labels: refactor, design, approved

#3942 Classifier: Skip some survey task tests
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
Labels: approved, tests

#3905 Install @next/bundle-analyzer
  packages/app-content-pages/README.md
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-project/README.md
  packages/app-project/next.config.js
  packages/app-project/package.json
  yarn.lock
Labels: dx, performance, approved

#3933 Classifier: Refactor survey task tests
  package.json
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/ClearFilters/ClearFilters.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js
Labels: experiment, approved, tests

#3971 Refactor survey task tests with beforeEach() hooks
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
Labels: performance, approved

#3960 Remove source maps from webpack builds
  packages/lib-classifier/webpack.dist.js
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/webpack.dist.js
Labels: enhancement, dependencies, performance, approved

#3959 Bump library packages
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/package.json
  packages/lib-panoptes-js/docs/CHANGELOG.md
  packages/lib-panoptes-js/package.json
Labels: dependencies, approved

#3976 Update PDBs to v1
  kubernetes/deployment-production.tmpl
Labels: approved

#3975 App-project: refactor when notifications requests called
  packages/app-project/stores/User/UserPersonalization/Notifications/Notifications.spec.js
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.js
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.spec.js
Labels: approved

#3974 Classifier: separate survey task tests to different files, skip filter interaction tests
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userKeystrokes.spec.js
Labels: performance, approved, tests

#3966 Remove query-string
  packages/lib-classifier/dev/index.js
  packages/lib-classifier/package.json
  yarn.lock
Labels: dependencies, approved

#3990 Refactor Done button queries
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js
Labels: refactor, approved

#3986 @zooniverse/panoptes-js v0.2.3
  packages/lib-panoptes-js/docs/CHANGELOG.md
  packages/lib-panoptes-js/package.json
Labels: security, approved

#3989 Refactor survey task choice button labels
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js
Labels: accessibility, refactor, approved

#3961 Restrict classifier width on wide displays
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
Labels: bug, approved

#3995 @zooniverse/react-components: fix installation on Custom Front Ends, bump to v1.3.2
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: bug, approved

#3928 Debounce resize observers
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
Labels: bug, refactor, approved

#4022 Project App: Remove max-width on Classify Page
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
Labels: approved, ui
