Repository zooniverse/front-end-monorepo, pull requests merged in 2022-03, with the labels that each got.

#2912 Refactor getStaticPageProps workflowID to project's single active workflow, if no query param
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.spec.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
Labels: bug, approved

#2892 Classifier: Remove counterpart from store
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/SubjectStore/Subject/StepHistory/StepHistory.js
  packages/lib-classifier/src/store/SubjectStore/Subject/StepHistory/locales/en.json
Labels: refactor, approved, translations

#2901 App-project: Translate Loader and ProjectStatistics with next-i18next
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/shared/components/Loader/Loader.js
  packages/app-project/src/shared/components/Loader/locales/en.json
  packages/app-project/src/shared/components/ProjectStatistics/ProjectStatistics.js
  packages/app-project/src/shared/components/ProjectStatistics/locales/en.json
Labels: refactor, approved, translations

#2900 App-project: Translate CollectionsModal and ConnectWithProject with next-i18next
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/shared/components/CollectionsModal/CollectionsModal.js
  packages/app-project/src/shared/components/CollectionsModal/components/CreateCollection/CreateCollection.js
  packages/app-project/src/shared/components/CollectionsModal/components/CreateCollection/locales/en.json
  packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.js
  packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/locales/en.json
  packages/app-project/src/shared/components/CollectionsModal/locales/en.json
  packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.js
  packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.stories.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/ProjectLink.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/helpers/formatUrlObject/formatUrlObject.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/locales/en.json
  packages/app-project/src/shared/components/ConnectWithProject/locales/en.json
Labels: refactor, approved, translations

#2905 App-project: Refactor withRequireUser and YourStatsContainer (remove inject, add i18next translations)
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStatsContainer.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStatsContainer.spec.js
  packages/app-project/src/shared/components/withRequireUser/locales/en.json
  packages/app-project/src/shared/components/withRequireUser/withRequireUser.js
  packages/app-project/src/shared/components/withRequireUser/withRequireUser.spec.js
Labels: refactor, approved, translations

#2902 App-project: Translate SubjectPicker and SubjectPreview with next-i18next
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.spec.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchStatuses.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchStatuses.spec.js
  packages/app-project/src/shared/components/SubjectPicker/locales/en.json
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/locales/en.json
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkLink.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/locales/en.json
  packages/app-project/src/shared/components/SubjectPreview/locales/en.json
Labels: refactor, approved, translations

#2903 App-project: Translate SubjectSetPicker and WorkflowSelector with next-i18next
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.spec.js
  packages/app-project/src/shared/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js
  packages/app-project/src/shared/components/SubjectSetPicker/components/SubjectSetCard/locales/en.json
  packages/app-project/src/shared/components/SubjectSetPicker/locales/en.json
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/locales/en.json
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/locales/en.json
  packages/app-project/src/shared/components/WorkflowSelector/locales/en.json
Labels: refactor, approved, translations

#2904 Classifier: record tutorials as completed when you click Get Started
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js
  packages/lib-classifier/src/store/TutorialStore/Tutorial/Tutorial.js
  packages/lib-classifier/src/store/TutorialStore/Tutorial/Tutorial.spec.js
  packages/lib-classifier/src/store/TutorialStore/TutorialStore.js
  packages/lib-classifier/src/store/TutorialStore/TutorialStore.spec.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore/UserProjectPreferencesStore.js
Labels: bug, refactor, approved

#2907 Panoptes-js Package: Bump url-parse
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-panoptes-js/docs/CHANGELOG.md
  packages/lib-panoptes-js/docs/CONTRIBUTING.md
  packages/lib-panoptes-js/package.json
  yarn.lock
Labels: documentation, security, approved

#2921 Uninstall counterpart from lib-classifier and app-project
  packages/app-project/package.json
  packages/lib-classifier/package.json
Labels: approved, translations

#2896 Classifier: Add SlideTutorial stories
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.stories.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/StepNavigation/StepNavigation.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/components/index.js
Labels: storybook, approved

#2929 App-project: Remove unused YourStats translation key
  packages/app-project/public/locales/en/screens.json
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.js
Labels: refactor, approved

#2928 Lokalise: Translations update
  packages/lib-react-components/src/translations/test.json
Labels: approved, translations

#2923 SingleTextViewer: remove implementation tests
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerContainer.spec.js
Labels: refactor, approved

#2933 Lib-React-Components: Add storybook-react-i18next config
  packages/lib-react-components/.storybook/i18n.js
  packages/lib-react-components/.storybook/main.js
  packages/lib-react-components/.storybook/preview.js
  packages/lib-react-components/package.json
  yarn.lock
Labels: storybook, approved, translations

#2930 Add activeTool validation on frame change to MultiFrameViewerContainer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js
Labels: bug, approved, degraded-ux

#2931 Lokalise: Add test language dictionaries for Classifier's storybook
  packages/lib-classifier/src/translations/test/components.json
  packages/lib-classifier/src/translations/test/plugins.json
Labels: approved, translations

#2932 Lokalise: Add test language dictionaries for App Project's storybook
  packages/app-project/public/locales/test/components.json
  packages/app-project/public/locales/test/screens.json
Labels: approved, translations

#2924 Classifier: Set ModalTutorial as complete on close
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/TaskArea.spec.js
Labels: enhancement, approved

#2890 Classifier: Remove @inject from SubjectViewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.spec.js
Labels: refactor, approved

#2951 Roll Grommet back to ~2.19.0
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: bug, approved

#2963 Reset the Classifier key after logging out
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapperConnector.js
Labels: bug, approved

#2808 Classifier: useSubjectImage hook
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/hooks/useSubjectImage.js
Labels: experiment, refactor, approved

#2922 Fix mark selectors in DrawingToolMarks tests
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
Labels: bug, dependencies, approved

#2968 Classifier: always check for a logged-in user on mount
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/store/ResourceStore/ResourceStore.js
  packages/lib-classifier/src/store/TutorialStore/Tutorial/Tutorial.js
Labels: bug, approved

#2947 app-project: Fix broken dark/light mode theme toggle
  packages/app-project/pages/_app.js
  packages/app-project/src/helpers/getCookie/getCookie.js
  packages/app-project/src/helpers/getCookie/getCookie.spec.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js
  packages/app-project/stores/UI.js
  packages/app-project/stores/UI.spec.js
  packages/app-project/stores/initStore.js
Labels: bug, approved

#2918 Add a showTutorial hint to the popup tutorial
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.spec.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
Labels: bug, approved

#2571 Upgrade builds to Node 16
  .github/workflows/ci-tests.yml
  Dockerfile
  README.md
  package.json
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-async-states/package.json
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js
  packages/lib-grommet-theme/package.json
  packages/lib-panoptes-js/package.json
  packages/lib-react-components/package.json
Labels: ops, approved

#2981 Added .eslintrc file
  packages/lib-classifier/.eslintrc
Labels: approved

#2961 Make mark.initialDrag optional
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
Labels: refactor, approved

#2941 webpack dev server: replace https with server
  packages/lib-classifier/webpack.dev.js
Labels: enhancement, approved

#2984 Classifier subject banners: Fix `stepHistory is undefined` on load
  packages/lib-classifier/src/components/Classifier/components/Banners/Banners.js
Labels: bug, approved

#2863 Classifier: Refactor and test useHydratedStore hook. Remove mst-persist
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/components/Classifier/hooks/Readme.md
  packages/lib-classifier/src/components/Classifier/hooks/useHydratedStore.js
  packages/lib-classifier/src/components/Classifier/hooks/useStore.js
  packages/lib-classifier/src/helpers/asyncSessionStorage/asyncSessionStorage.js
  packages/lib-classifier/src/helpers/asyncSessionStorage/index.js
  packages/lib-classifier/src/helpers/index.js
  packages/lib-classifier/src/hooks/Readme.md
  packages/lib-classifier/src/hooks/index.js
  packages/lib-classifier/src/hooks/useHydratedStore.js
  packages/lib-classifier/src/hooks/useHydratedStore.spec.js
  packages/lib-classifier/src/hooks/useWorkflowSnapshot.js
  packages/lib-classifier/webpack.dev.js
  packages/lib-classifier/webpack.dist.js
  yarn.lock
Labels: refactor, approved

#2946 ADR 42: record classifier store snapshots
  docs/arch/README.md
  docs/arch/adr-42.md
Labels: documentation, approved

#2949 New Checklist for PR Template
  docs/PULL_REQUEST_TEMPLATE.md
Labels: documentation, approved

#2790 Project: add allowedWorkflows to ClassifyPage
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
Labels: refactor, approved

#2989 Ellipse Refactor
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.js
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.stories.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Ellipse/Ellipse.js
Labels: refactor, approved

#2992 Refactor ClassifyPageContainer workflow ID for workflow assignment and complete workflows
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
Labels: bug, approved

#2993 Dev classifier workflow routing
  packages/lib-classifier/dev/components/App/App.js
Labels: enhancement, dx, approved

#2940 Classifier: Add support for inactive (private) workflows
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/helpers/index.js
  packages/lib-classifier/src/helpers/useStores/README.md
  packages/lib-classifier/src/helpers/useStores/index.js
  packages/lib-classifier/src/helpers/withStores/withStores.js
  packages/lib-classifier/src/hooks/Readme.md
  packages/lib-classifier/src/hooks/index.js
  packages/lib-classifier/src/hooks/usePanoptesAuth.js
  packages/lib-classifier/src/hooks/usePanoptesUser.js
  packages/lib-classifier/src/hooks/useProjectRoles.js
  packages/lib-classifier/src/hooks/useStores.js
  packages/lib-classifier/src/hooks/useStores.spec.js
  packages/lib-classifier/src/hooks/useWorkflowSnapshot.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
  packages/lib-classifier/test/factories/ProjectFactory.js
  packages/lib-classifier/webpack.dev.js
  packages/lib-classifier/webpack.dist.js
Labels: enhancement, approved
