Repository zooniverse/front-end-monorepo, pull requests merged in 2022-01, with the labels that each got.

#2589 babel config: remove deprecated useESModules
  packages/app-content-pages/.babelrc
  packages/app-project/.babelrc
Labels: dependencies, approved

#2598 Classifier: log malformed classifications
  packages/lib-classifier/package.json
  packages/lib-classifier/src/store/utils/ClassificationQueue.js
  yarn.lock
Labels: high priority, approved

#2586 Upgrade Sentry
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: dependencies, approved

#2584 Storybook 6.4
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies, approved

#2600 Classifier: Log dropped classifications to Sentry
  packages/lib-classifier/src/store/utils/ClassificationQueue.js
Labels: high priority, approved

#2605 Classifier: set classification.metadata.started_at when a classification is created
  packages/lib-classifier/src/store/Classification/ClassificationMetadata.js
  packages/lib-classifier/src/store/Classification/ClassificationMetadata.spec.js
  packages/lib-classifier/src/store/ClassificationStore.js
Labels: bug, approved

#2599 Classifier: toggle show/hide for transcribed lines
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.spec.js
Labels: bug, approved

#2601 [Security] Upgrade lerna
  package.json
  yarn.lock
Labels: dependencies, security, approved

#2612 Create dependabot.yml
  .github/dependabot.yml
Labels: dependencies, approved

#2587 Upgrade mobx and mobx-state-tree
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-project/stores/UI.spec.js
  packages/app-project/stores/User/Recents/Recents.spec.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js
  packages/lib-classifier/src/plugins/tasks/DrawingTask/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.spec.js
  packages/lib-classifier/src/store/AnnotationsStore.spec.js
  packages/lib-classifier/src/store/ClassificationStore.js
  packages/lib-classifier/src/store/ClassificationStore.spec.js
  packages/lib-classifier/src/store/FeedbackStore.spec.js
  packages/lib-classifier/src/store/FieldGuideStore.spec.js
  packages/lib-classifier/src/store/SubjectStore/SingleImageSubject/SingleImageSubject.spec.js
  packages/lib-classifier/src/store/SubjectStore/SingleVideoSubject/SingleVideoSubject.spec.js
  packages/lib-classifier/src/store/SubjectStore/Subject/Subject.spec.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.spec.js
  packages/lib-classifier/src/store/TutorialStore.spec.js
  packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore/Step/Step.spec.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.spec.js
  packages/lib-classifier/test/mockStore/mockStore.js
  yarn.lock
Labels: dependencies, approved

#2619 Add mockStore to classifier task stories
  packages/lib-classifier/src/stories/components/MockTask/MockTask.js
Labels: bug, storybook, approved

#2588 Upgrade visx and d3
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addRemoveAnnotationButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/preventDefaultAction.js
  yarn.lock
Labels: dependencies, approved

#2618 Upgrade webpack-dev-server to 4.7
  packages/lib-classifier/package.json
  yarn.lock
Labels: dependencies, security

#2626 Remove @babel/plugin-proposal-class-properties
  packages/lib-classifier/.babelrc
  packages/lib-classifier/package.json
  packages/lib-react-components/.babelrc
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies, ops, approved

#2609 Upgrade remark to 11
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies

#2289 Storybooks: build stories with webpack 5
  packages/app-project/.storybook/main.js
  packages/lib-classifier/.storybook/main.js
  packages/lib-react-components/.storybook/main.js
Labels: dependencies, security, approved

#2638 Remove require-control
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  yarn.lock
Labels: dependencies, approved

#2641 Bump test dependencies
  yarn.lock
Labels: dependencies, approved

#2645 Update NextJS ESLint to 12
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: dependencies, approved

#2627 Classifier: persist fetched data with mst-persist
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/helpers/asyncSessionStorage/asyncSessionStorage.js
  packages/lib-classifier/src/helpers/asyncSessionStorage/index.js
  packages/lib-classifier/src/helpers/index.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
  packages/lib-classifier/src/store/FieldGuideStore/FieldGuide/FieldGuide.js
  packages/lib-classifier/src/store/FieldGuideStore/FieldGuide/FieldGuide.spec.js
  packages/lib-classifier/src/store/FieldGuideStore/FieldGuide/index.js
  packages/lib-classifier/src/store/FieldGuideStore/FieldGuideStore.js
  packages/lib-classifier/src/store/FieldGuideStore/FieldGuideStore.spec.js
  packages/lib-classifier/src/store/FieldGuideStore/index.js
  packages/lib-classifier/src/store/ResourceStore/ResourceStore.js
  packages/lib-classifier/src/store/TutorialStore.js
  packages/lib-classifier/test/mockStore/mockStore.js
  yarn.lock
Labels: enhancement, experiment, performance, approved

#2644 Upgrade babel
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies, approved

#2640 Bump storybook to 6.4.13
  packages/app-project/.storybook/main.js
  packages/lib-classifier/.storybook/main.js
  packages/lib-react-components/.storybook/main.js
  yarn.lock
Labels: bug, dependencies, approved

#2550 Next.js Localization & i18next Config
  docs/arch/README.md
  docs/arch/adr-40.md
  docs/arch/adr-41.md
  packages/app-project/next-i18next.config.js
  packages/app-project/next.config.js
  packages/app-project/package.json
  packages/app-project/pages/_app.js
  packages/app-project/public/locales/en/common.json
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/components/LocaleSwitcher/LocaleLink.js
  packages/app-project/src/components/ProjectHeader/components/LocaleSwitcher/LocaleSwitcher.js
  packages/app-project/src/components/ProjectHeader/components/LocaleSwitcher/LocaleSwitcher.spec.js
  packages/app-project/src/components/ProjectHeader/components/LocaleSwitcher/LocaleSwitcher.stories.js
  packages/app-project/src/components/ProjectHeader/components/LocaleSwitcher/index.js
  packages/app-project/src/helpers/localeMenu.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.spec.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/RootStore.spec.js
  packages/lib-classifier/src/translations/en.json
  packages/lib-classifier/src/translations/i18n.js
  packages/lib-react-components/package.json
  packages/lib-react-components/src/ZooHeader/helpers/navListItems.js
  packages/lib-react-components/src/translations/en.json
  packages/lib-react-components/src/translations/i18n.js
  yarn.lock
Labels: enhancement, documentation, approved

#2663 fix subject fetchTranscriptionReductions
  packages/lib-classifier/src/store/SubjectStore/Subject/Subject.js
Labels: bug, approved

#2671 Add minZoom 0.1 to MultiFrameViewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
Labels: bug, high priority, approved

#2673 [Security] Projects: remove direct node-fetch dependency
  packages/app-project/package.json
  packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
  yarn.lock
Labels: dependencies, security, high priority, approved

#2678 [Security] Upgrade formik
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies, security, high priority, approved

#2686 [Security] upgrade graphql-request
  packages/app-project/package.json
  packages/app-project/test/create-global-document.js
  packages/lib-classifier/package.json
  packages/lib-classifier/test/setup.js
  yarn.lock
Labels: dependencies, security, approved

#2676 Classifier: add cachePanoptesData flag
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
Labels: enhancement, approved

#2677 Classifier: Refresh workflows with SWR (stale-while-revalidate)
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
  yarn.lock
Labels: bug, experiment, approved

#2693 [Security] remove node-fetch@2.6.1
  package.json
  yarn.lock
Labels: dependencies, security, high priority, approved

#2692 Bump babel-plugin-styled-components to 2.0.2
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: dependencies, approved

#2575 Add Notifications unread count to ZooHeader, with sugar subscription
  packages/app-project/package.json
  packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js
  packages/app-project/stores/User/UserPersonalization/Notifications/Notifications.js
  packages/app-project/stores/User/UserPersonalization/Notifications/Notifications.spec.js
  packages/app-project/stores/User/UserPersonalization/Notifications/index.js
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.js
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.spec.js
  packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.spec.js
  packages/app-project/stores/User/UserPersonalization/YourStats/YourStats.spec.js
  yarn.lock
Labels: enhancement

#2697 [Security] Bump next to 12.0.9
  package.json
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: dependencies, security, approved

#2685 Patch storybook to 6.4.14
  yarn.lock
Labels: dependencies
