Repository zooniverse/front-end-monorepo, pull requests merged in 2022-10, with the labels that each got.

#3731 Maintenance Week: add tests for RotateHandle
  packages/lib-classifier/src/plugins/drawingTools/components/RotateHandle/RotateHandle.js
  packages/lib-classifier/src/plugins/drawingTools/components/RotateHandle/RotateHandle.spec.js
  packages/lib-classifier/src/translations/en/components.json
Labels: approved

#3732 ZooFooter React Testing Library tests
  packages/lib-react-components/src/ZooFooter/ZooFooter.js
  packages/lib-react-components/src/ZooFooter/ZooFooter.spec.js
  packages/lib-react-components/src/ZooFooter/components/LinkList/LinkList.spec.js
  packages/lib-react-components/src/ZooFooter/components/LogoAndTagline/LogoAndTagline.spec.js
  packages/lib-react-components/src/ZooFooter/components/PolicyLinkSection/PolicyLinkSection.spec.js
  packages/lib-react-components/src/ZooFooter/components/SocialAnchor/SocialAnchor.spec.js
  packages/lib-react-components/src/ZooniverseLogotype/ZooniverseLogotype.js
  packages/lib-react-components/src/ZooniverseLogotype/ZooniverseLogotype.spec.js
Labels: refactor, approved

#3724 @zooniverse/grommet-theme v3.1.0
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/package.json
  packages/lib-react-components/package.json
Labels: dependencies, approved

#3722 @zooniverse/react-components v1.2.0
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: dependencies, approved

#3585 Project app: Refactor subject picker data fetching
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.spec.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.spec.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchStatuses.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchStatuses.spec.js
Labels: refactor, approved

#3737 Remove ProjectHomePageConnector
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.spec.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePageConnector.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePageConnector.spec.js
  packages/app-project/src/screens/ProjectHomePage/index.js
Labels: refactor, approved

#3715 Classifier: Reduce mock survey task, improve survey task tests performance
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/ConfusedWith.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/helpers/getQuestionIds.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.stories.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/helpers/getFilteredChoiceIds.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/mock-data/index.js
  packages/lib-classifier/src/plugins/tasks/survey/mock-data/task.js
Labels: approved

#3738 Remove StandardLayoutContainer
  packages/app-project/src/shared/components/StandardLayout/StandardLayout.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayout.spec.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayoutContainer.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayoutContainer.spec.js
  packages/app-project/src/shared/components/StandardLayout/index.js
Labels: refactor, approved

#3688 Admin mode: admins can load inactive workflows
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/Classifier.spec.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
Labels: enhancement, approved

#3716 Classifier: Refactor survey task Chooser to conditionally show filter components
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.spec.js
Labels: approved

#3684 Classifier: Custom Video Controls
  docs/arch/adr-45.md
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoController/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoController/VideoController.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoController/VideoController.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoController/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoController/theme.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/VideoController.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/components/FormattedTime/FormattedTime.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/components/FormattedTime/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/components/Slider/Slider.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VideoController/components/Slider/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getFixedNumber/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getFixedNumber/getFixedNumber.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getFixedNumber/getFixedNumber.spec.js
  packages/lib-classifier/src/helpers/formatTimeStamp/README.md
  packages/lib-classifier/src/helpers/formatTimeStamp/formatTimeStamp.js
  packages/lib-classifier/src/helpers/formatTimeStamp/formatTimeStamp.spec.js
  packages/lib-classifier/src/translations/en/components.json
  yarn.lock
Labels: refactor, approved, tests, video subject

#3765 Add GitHub Actions to dependabot
  .github/dependabot.yml
Labels: ops, approved

#3763 Bump GitHub v2 actions to v3
  .github/workflows/ci-build.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy_staging.yml
Labels: ops, approved

#3764 Update Sentry release actions
  .github/workflows/sentry-production-releases.yml
  .github/workflows/sentry-staging-releases.yml
Labels: ops, approved

#3771 Add projects to Sentry production releases
  .github/workflows/sentry-production-releases.yml
Labels: bug, approved

#3748 Admin Mode: check for logged-in admin user
  packages/app-project/src/hooks/useAdminMode.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.spec.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayout.js
Labels: bug, approved

#3777 Flipbook Viewer: Display this viewer for non-transcription multiple-image-subjects
  docs/arch/adr-46.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/Flipbook.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.js
  packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.js
  packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.spec.js
  packages/lib-classifier/src/store/SubjectStore/Subject/Subject.js
  packages/lib-classifier/src/store/SubjectStore/Subject/Subject.spec.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
Labels: enhancement, approved

#3736 Refactor ProjectHeader with hooks, stories and RTL tests
  packages/app-project/package.json
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.stories.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.js
  packages/app-project/src/components/ProjectHeader/ProjectHeaderContainer.spec.js
  packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/ApprovedIcon.js
  packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/ApprovedIcon.spec.js
  packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/ApprovedIconContainer.js
  packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/ApprovedIconContainer.spec.js
  packages/app-project/src/components/ProjectHeader/components/ApprovedIcon/index.js
  packages/app-project/src/components/ProjectHeader/components/Avatar/Avatar.js
  packages/app-project/src/components/ProjectHeader/components/Avatar/Avatar.spec.js
  packages/app-project/src/components/ProjectHeader/components/Avatar/AvatarContainer.js
  packages/app-project/src/components/ProjectHeader/components/Avatar/AvatarContainer.spec.js
  packages/app-project/src/components/ProjectHeader/components/Avatar/index.js
  packages/app-project/src/components/ProjectHeader/components/Background/Background.js
  packages/app-project/src/components/ProjectHeader/components/Background/Background.spec.js
  packages/app-project/src/components/ProjectHeader/components/Background/BackgroundContainer.js
  packages/app-project/src/components/ProjectHeader/components/Background/BackgroundContainer.spec.js
  packages/app-project/src/components/ProjectHeader/components/Background/index.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.spec.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.stories.js
  packages/app-project/src/components/ProjectHeader/components/LocaleSwitcher/LocaleSwitcher.js
  packages/app-project/src/components/ProjectHeader/components/LocaleSwitcher/LocaleSwitcher.spec.js
  packages/app-project/src/components/ProjectHeader/components/LocaleSwitcher/LocaleSwitcher.stories.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.spec.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.stories.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.spec.js
  packages/app-project/src/components/ProjectHeader/components/UnderReviewLabel/UnderReviewLabel.spec.js
  packages/app-project/src/components/ProjectHeader/components/index.js
  packages/app-project/src/components/ProjectHeader/hooks/index.js
  packages/app-project/src/components/ProjectHeader/hooks/useProjectNavigation.js
  packages/app-project/src/components/ProjectHeader/hooks/useStores.js
  packages/app-project/src/components/ProjectHeader/index.js
  packages/app-project/test/create-global-document.js
Labels: refactor, approved

#3703 Admin mode: Add admin flag to Zooniverse site header
  packages/app-content-pages/src/shared/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js
  packages/app-content-pages/src/shared/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.spec.js
  packages/app-content-pages/test/create-global-document.js
  packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js
  packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayout.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.spec.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.stories.js
  packages/lib-react-components/src/ZooHeader/ZooHeaderContainer.js
  packages/lib-react-components/src/ZooHeader/ZooHeaderContainer.spec.js
  packages/lib-react-components/src/ZooHeader/components/MainNavList/MainNavList.spec.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMainNavMenu/NarrowMainNavMenu.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMainNavMenu/NarrowMainNavMenu.spec.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenu/NarrowMenu.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenu/NarrowMenu.spec.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenuNavListItem/NarrowMenuNavListItem.spec.js
  packages/lib-react-components/src/ZooHeader/components/NavListItem/NavListItem.spec.js
  packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.spec.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/SignedOutUserNavigation.spec.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/components/NavButton/NavButton.spec.js
  packages/lib-react-components/src/ZooHeader/index.js
  packages/lib-react-components/test/setup.js
Labels: bug, enhancement, accessibility, refactor, approved

#3798 Update images in prod deploy template
  kubernetes/deployment-production.tmpl
Labels: approved

#3800 PR Template: Add new checklist item for translation keys
  docs/PULL_REQUEST_TEMPLATE.md
Labels: documentation, approved, translations

#3782 Classifier: Build basic flipbook viewer with thumbnail navigation
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/Flipbook.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/components/FlipbookControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/components/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoController/VideoController.spec.js
Labels: enhancement, documentation, approved

#3788 Remove @babel/polyfill
  packages/lib-classifier/package.json
  packages/lib-classifier/test/.mocharc.json
  packages/lib-classifier/webpack.dev.js
Labels: dependencies, approved

#3735 Classifier: Refactor Chooser and child components for focus and accessibility improvements
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTaskContainer.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTaskContainer.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterIcon.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/components/FilterButton.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.stories.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.stories.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/theme.js
  packages/lib-classifier/test/setup.js
Labels: approved
