Repository zooniverse/front-end-monorepo, pull requests merged in 2022-06, with the labels that each got.

#3178 Classifier: localise tutorials
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.stories.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js
Labels: enhancement, approved, translations

#3247 Remove unused auth from QuickTalk
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js
Labels: refactor, approved

#3250 Fix ImageAndTextViewer not calling onReady or onError
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewerContainer.js
Labels: bug, approved

#3133 Classifier: Remove `inject` from MetaTools
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.spec.js
Labels: refactor, approved

#3046 Test the Classifier
  packages/lib-classifier/src/components/Classifier/Classifier.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/translations/i18n.js
  packages/lib-classifier/test/mockStore/mockStore.js
Labels: approved

#3219 Classifier: more stringent workflow version checks
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/Classifier.spec.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBackgroundLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addBorderLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addDataLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/addInterfaceLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/d3/setDataPointStyle.spec.js
  packages/lib-classifier/src/store/ResourceStore/ResourceStore.spec.js
  packages/lib-classifier/test/mockStore/branchingWorkflow.js
Labels: bug, approved, translations

#3220 Classifier: Refactor WorkflowStepStore tests
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js
Labels: approved, translations

#3267 PR Template: Update VoiceOver Guide link
  docs/PULL_REQUEST_TEMPLATE.md
Labels: approved

#3144 Project About pages: accessibility fixes
  packages/app-project/public/locales/en/screens.json
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.js
Labels: bug, accessibility, refactor, approved

#3239 Classifier: Refactor workflow strings as a map
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/Classifier.spec.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
Labels: refactor, approved, translations

#3290 Set default APP_ENV to 'development'
  README.md
  kubernetes/deployment-production.tmpl
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-project/next.config.js
  packages/app-project/package.json
Labels: ops, approved

#3293 Classifier: better handling of invalid tasks
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.spec.js
  packages/lib-classifier/src/hooks/useHydratedStore.js
Labels: bug, approved, degraded-ux

#3193 Classifier: Localise workflow task text
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/Classifier.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js
  packages/lib-classifier/src/plugins/drawingTools/stories/helpers.js
  packages/lib-classifier/src/plugins/tasks/dataVisAnnotation/components/DataVisAnnotationTask.spec.js
  packages/lib-classifier/src/plugins/tasks/dataVisAnnotation/models/DataVisAnnotationTask.js
  packages/lib-classifier/src/plugins/tasks/drawing/components/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/drawing/components/DrawingTask.stories.js
  packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.spec.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.stories.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/SimpleDropdownTask.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/SimpleDropdownTask.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/textFromSubject/components/TextFromSubjectContainer.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/textFromSubject/components/TextFromSubjectTask.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/textFromSubject/components/TextFromSubjectTask.stories.js
  packages/lib-classifier/src/plugins/tasks/experimental/textFromSubject/models/TextFromSubjectTask.js
  packages/lib-classifier/src/plugins/tasks/experimental/textFromSubject/models/TextFromSubjectTask.spec.js
  packages/lib-classifier/src/plugins/tasks/models/Task.js
  packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.stories.js
  packages/lib-classifier/src/plugins/tasks/multiple/models/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/multiple/models/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.stories.js
  packages/lib-classifier/src/plugins/tasks/single/models/SingleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/single/models/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/subjectGroupComparison/components/SubjectGroupComparisonTask.spec.js
  packages/lib-classifier/src/plugins/tasks/subjectGroupComparison/models/SubjectGroupComparisonTask.js
  packages/lib-classifier/src/plugins/tasks/subjectGroupComparison/models/SubjectGroupComparisonTask.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/text/components/TextTask/TextTask.spec.js
  packages/lib-classifier/src/plugins/tasks/text/components/TextTask/TextTask.stories.js
  packages/lib-classifier/src/plugins/tasks/text/components/TextTask/components/DefaultTextTask/DefaultTextTask.js
  packages/lib-classifier/src/plugins/tasks/text/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.js
  packages/lib-classifier/src/plugins/tasks/text/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.spec.js
  packages/lib-classifier/src/plugins/tasks/text/models/TextTask.js
  packages/lib-classifier/src/plugins/tasks/text/models/TextTask.spec.js
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.spec.js
  packages/lib-classifier/src/stories/components/MockTask/MockTask.js
  packages/lib-classifier/test/factories/tasks/DrawingTaskFactory.js
  packages/lib-classifier/test/factories/tasks/MultipleChoiceTaskFactory.js
  packages/lib-classifier/test/factories/tasks/SingleChoiceTaskFactory.js
  packages/lib-classifier/test/factories/tasks/TextTaskFactory.js
  packages/lib-classifier/test/factories/tasks/TranscriptionTaskFactory.js
Labels: enhancement, approved, translations

#3283 Project header: show LocaleSwitcher in development
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
Labels: refactor, approved, translations

#3249 QuickTalk: data-fetching with SWR
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/helpers/postTalkComment.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/helpers/postTalkDiscussion.js
Labels: refactor, approved

#3282 Classifier: withFeatureFlag(Component, flag)
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js
  packages/lib-classifier/src/helpers/index.js
  packages/lib-classifier/src/helpers/withFeatureFlag/README.md
  packages/lib-classifier/src/helpers/withFeatureFlag/index.js
  packages/lib-classifier/src/helpers/withFeatureFlag/withFeatureFlag.js
  packages/lib-classifier/src/helpers/withFeatureFlag/withFeatureFlag.spec.js
  packages/lib-classifier/src/helpers/withStores/withStores.js
Labels: refactor, approved

#3047 Add invert button to image toolbar
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertIcon.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/index.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/index.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/WorkflowConfiguration/WorkflowConfiguration.spec.js
  packages/lib-classifier/src/translations/en/components.json
Labels: enhancement, approved

#3318 Project app pages: fix broken Array.find
  packages/app-project/pages/[owner]/[project]/classify/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js
  packages/app-project/pages/[owner]/[project]/classify/workflow/[workflowID]/subject/[subjectID]/index.js
Labels: bug, approved

#3223 Classifier: localise drawing subtasks
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Circle/Circle.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.stories.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js
  packages/lib-classifier/src/plugins/drawingTools/stories/helpers.js
  packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/transcription/TranscriptionTask.stories.js
Labels: enhancement, approved, translations

#3320 Transcription workflows: adjust subtask position
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/helpers/getDefaultPosition/getDefaultPosition.js
Labels: bug, approved, degraded-ux

#3324 Hide invert button
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButtonContainer.js
Labels: bug, approved

#3199 Classifier: localise drawing task tools
  packages/lib-classifier/src/plugins/tasks/drawing/components/DrawingTask.js
  packages/lib-classifier/src/plugins/tasks/drawing/components/DrawingTask.spec.js
  packages/lib-classifier/src/plugins/tasks/drawing/components/DrawingTask.stories.js
  packages/lib-classifier/src/plugins/tasks/experimental/transcription/TranscriptionTask.stories.js
Labels: enhancement, approved, translations

#3238 Classifier: localise dropdown task options
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.spec.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.stories.js
Labels: enhancement, approved, translations

#3332 Classifier: improved subtask positioning
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuideContainer.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuideContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/helpers/getDefaultPosition/getDefaultPosition.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/helpers/getDefaultPosition/getDefaultPosition.spec.js
  packages/lib-classifier/src/hooks/Readme.md
  packages/lib-classifier/src/hooks/index.js
  packages/lib-classifier/src/hooks/useClientRect.js
  packages/lib-react-components/src/MovableModal/MovableModal.js
  packages/lib-react-components/src/MovableModal/MovableModal.spec.js
  packages/lib-react-components/src/MovableModal/README.md
Labels: refactor, approved

#3124 Refactor SingleTextViewer tests with testing-library
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerContainer.spec.js
Labels: refactor, approved, tests

#3224 Classifier: localise survey tasks
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.stories.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/ConfusedWith.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/ConfusedWith.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/ConfusedWith.stories.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/Questions/Questions.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/Questions/Questions.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.stories.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/Characteristics.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.stories.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.stories.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.stories.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js
  packages/lib-classifier/src/plugins/tasks/survey/mock-data/task.js
Labels: enhancement, approved, translations

#3325 Fix invert button for multi-frame subjects and line color consistency
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGImage/SVGImage.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGImage/SVGImage.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGImage/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
Labels: bug, approved

#3346 Classifier: React strict mode
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
Labels: refactor, dx, approved

#3356 Reset invert on subject change
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.spec.js
Labels: bug, approved

#3273 Classifier: Refactor ClassifierContainer effect hooks
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/hooks/useHydratedStore.js
  packages/lib-classifier/src/hooks/useHydratedStore.spec.js
Labels: bug, refactor, approved
