Repository zooniverse/front-end-monorepo, pull requests merged in 2023-01, with the labels that each got.

#4003 Update README with better publishing instructions
  README.md
Labels: documentation, approved

#4020 Classifier: add survey task choice close/delete on Escape key
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userKeystrokes.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/Questions/Questions.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/Questions/components/InputGroup/InputGroup.js
Labels: approved

#4019 Classifier: Remove legacy +tab+ formatter from MetadataModal
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.spec.js
Labels: bug, approved

#4092 Update Turkish dictionaries in app-project via Lokalise
  packages/app-project/public/locales/tr/components.json
  packages/app-project/public/locales/tr/screens.json
Labels: approved, translations

#4090 Update Turkish library in lib-react-components via Lokalise
  packages/lib-react-components/src/translations/tr.json
Labels: approved, translations

#4056 Classifier: Specify no download for video subject viewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
Labels: approved, video subject

#4004 Add app-content-pages dev server with devcert
  packages/app-content-pages/README.md
  packages/app-content-pages/package.json
  packages/app-content-pages/server/dev-server.js
  packages/app-project/README.md
  yarn.lock
Labels: dx, approved

#4107 Maintenance Week: add tests for Tooltip
  packages/lib-react-components/src/Tooltip/Tooltip.spec.js
  packages/lib-react-components/test/setup.js
Labels: approved

#4093 [Security] Bump NextJS to 12.3.4
  yarn.lock
Labels: dependencies, security, approved

#4113 Survey task Choice, Chooser, and Confusion tests refactor
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userKeystrokes.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.spec.js
Labels: approved, tests

#4118 Refactor TextTaskWithSuggestions tests
  packages/lib-classifier/src/plugins/tasks/text/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.spec.js
Labels: approved, tests

#4058 Refactor SVGImage for dragMove warning
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGImage/SVGImage.js
Labels: dx, approved, low-priority

#4122 Maintenance Week: add tests for Tooltip's sub-components
  packages/lib-react-components/src/Tooltip/components/Label/Label.spec.js
  packages/lib-react-components/src/Tooltip/components/Triangle/Triangle.spec.js
Labels: approved

#4123 Maintenance Week: add tests & story for Zooniverse Logo & Logotype
  packages/lib-react-components/src/ZooniverseLogo/ZooniverseLogo.stories.js
  packages/lib-react-components/src/ZooniverseLogotype/ZooniverseLogo.stories.js
  packages/lib-react-components/src/ZooniverseLogotype/ZooniverseLogotype.spec.js
Labels: approved

#4112 Refactor Markdownz's handling of custom image dimensions
  packages/lib-react-components/src/Markdownz/Markdownz.js
  packages/lib-react-components/src/Markdownz/Markdownz.spec.js
  packages/lib-react-components/src/Markdownz/markdownGridExample.md
  packages/lib-react-components/src/Media/Media.stories.js
  packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js
Labels: bug, approved

#4008 Classifier: Revamp Image Toolbar with responsive styling
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideWrapper.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/HelpIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertIcon.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
  packages/lib-classifier/test/mockStore/mockStore.js
Labels: refactor, approved, ui

#4125 lib-react-components v1.3.3
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: approved

#4134 Instructions for debugging the production release
  README.md
Labels: documentation, approved

#4021 Classifier: Move MetaTools into same grid area as subject viewer
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.stories.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/HidePreviousMarksButton/HidePreviousTranscriptionsButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/Metadata.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/Metadata.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/InfoIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/MetadataButton.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataButton/MetadataButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.spec.js
Labels: refactor, approved, ui

#4064 Remove webpack builds
  .github/workflows/ci-build.yml
  .github/workflows/coverage.yml
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-classifier/.babelrc
  packages/lib-classifier/package.json
  packages/lib-classifier/webpack.dist.js
  packages/lib-react-components/.babelrc
  packages/lib-react-components/.storybook/main.js
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/webpack.dist.js
  yarn.lock
Labels: dependencies, ops, performance, approved

#4091 Update Turkish dictionaries in lib-classifier via Lokalise
  packages/lib-classifier/src/translations/tr/components.json
  packages/lib-classifier/src/translations/tr/plugins.json
Labels: approved, translations

#4114 Fix survey task Choice styling with forwardedAs
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js
Labels: bug, approved

#4108 Replace devcert with selfsigned
  packages/app-content-pages/README.md
  packages/app-content-pages/package.json
  packages/app-content-pages/server/dev-server.js
  packages/app-content-pages/server/server.js
  packages/app-project/README.md
  packages/app-project/package.json
  packages/app-project/server/dev-server.js
  packages/app-project/server/server.js
  yarn.lock
Labels: security, dx, approved

#4135 Fix data image viewer stories
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/mockData.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
Labels: bug, storybook, approved

#4010 Add app-content-pages notifications
  packages/app-content-pages/src/shared/stores/User/User.js
  packages/app-content-pages/src/shared/stores/User/User.spec.js
  packages/app-content-pages/src/shared/stores/User/UserPersonalization/Notifications/Notifications.js
  packages/app-content-pages/src/shared/stores/User/UserPersonalization/Notifications/Notifications.spec.js
  packages/app-content-pages/src/shared/stores/User/UserPersonalization/Notifications/helpers/getTalkUnreadConversationsIds.js
  packages/app-content-pages/src/shared/stores/User/UserPersonalization/Notifications/helpers/getTalkUnreadNotificationsCount.js
  packages/app-content-pages/src/shared/stores/User/UserPersonalization/Notifications/index.js
  packages/app-content-pages/src/shared/stores/User/UserPersonalization/UserPersonalization.js
  packages/app-content-pages/src/shared/stores/User/UserPersonalization/UserPersonalization.spec.js
  packages/app-content-pages/src/shared/stores/User/UserPersonalization/index.js
  packages/app-content-pages/src/shared/stores/User/index.js
Labels: approved

#4148 Require selfsigned in local development
  packages/app-content-pages/server/server.js
  packages/app-project/server/server.js
Labels: bug, ops, approved

#4145 Disable real HTTP requests in tests
  packages/app-content-pages/test/create-global-document.js
  packages/app-project/test/create-global-document.js
  packages/lib-classifier/test/setup.js
Labels: performance, approved

#4131 Refactor classifier user authentication
  packages/lib-classifier/src/hooks/usePanoptesUser.js
  packages/lib-classifier/test/mockStore/mockStore.js
Labels: bug, approved

#4154 Classifier: change Default Layout's breakpoint to 768px
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.spec.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.stories.js
Labels: design, approved, ui

#4177 Classifier: preload all images of a subject in flipbook viewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
Labels: enhancement, approved

#4089 Handle zh-CN and zh-TW language codes
  packages/app-project/next-i18next.config.js
  packages/app-project/public/locales/zh-CN/components.json
  packages/app-project/public/locales/zh-CN/screens.json
  packages/app-project/public/locales/zh-TW/components.json
  packages/app-project/public/locales/zh-TW/screens.json
  packages/app-project/src/components/ProjectHeader/hooks/useStores.js
  packages/app-project/src/helpers/fetchTranslations/fetchTranslations.js
  packages/app-project/src/helpers/fetchTranslations/fetchTranslations.spec.js
  packages/app-project/src/helpers/localeMenu.js
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/dev/components/App/localeMenu.js
  packages/lib-classifier/src/hooks/usePanoptesTranslations.js
  packages/lib-classifier/src/translations/i18n.js
  packages/lib-classifier/src/translations/zh-CN/components.json
  packages/lib-classifier/src/translations/zh-CN/plugins.json
  packages/lib-classifier/src/translations/zh-TW/components.json
  packages/lib-classifier/src/translations/zh-TW/plugins.json
  packages/lib-react-components/src/translations/i18n.js
  packages/lib-react-components/src/translations/zh-CN.json
  packages/lib-react-components/src/translations/zh-TW.json
Labels: approved, translations

#4189 Add storybook deployment notes to Readme
  README.md
Labels: documentation, approved

#4077 Translations: Update zh-cn, test language, and one Spanish key
  packages/app-project/public/locales/es/components.json
  packages/app-project/public/locales/test/components.json
  packages/app-project/public/locales/test/screens.json
  packages/app-project/public/locales/zh-CN/components.json
  packages/app-project/public/locales/zh-CN/screens.json
  packages/lib-classifier/src/translations/es/plugins.json
  packages/lib-classifier/src/translations/ja/plugins.json
  packages/lib-classifier/src/translations/sv/plugins.json
  packages/lib-classifier/src/translations/test/components.json
  packages/lib-classifier/src/translations/test/plugins.json
  packages/lib-classifier/src/translations/tr/plugins.json
  packages/lib-classifier/src/translations/ur/plugins.json
  packages/lib-classifier/src/translations/zh-CN/components.json
  packages/lib-classifier/src/translations/zh-CN/plugins.json
  packages/lib-react-components/src/translations/zh-CN.json
Labels: approved, translations

#4133 Field Guide refactor for scrolling bug and item icon thumbnails
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuide.stories.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuide.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuideContainer.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuideContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItem/FieldGuideItem.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemIcon/FieldGuideItemIcon.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemIcon/FieldGuideItemIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItems.js
Labels: bug, design, performance, approved

#4212 Add filters default value to MetadataModal
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.spec.js
Labels: bug, approved

#4190 Classifier Storybook: exclude the mockTask object as a story
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.stories.js
Labels: storybook, approved
