Repository zooniverse/front-end-monorepo, pull requests merged in 2023-03, with the labels that each got.

#4315 Restore continuous zoom in and out
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
Labels: bug, approved, degraded-ux

#4313 Classifier: Document layouts and consolidate getting a layout to the Workflow store
  packages/lib-classifier/src/components/Classifier/components/Layout/README.md
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.js
  packages/lib-classifier/src/helpers/index.js
  packages/lib-classifier/src/helpers/layouts/index.js
  packages/lib-classifier/src/helpers/layouts/layouts.js
  packages/lib-classifier/src/helpers/layouts/layouts.spec.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.spec.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.js
Labels: enhancement, approved

#3991 Refactor survey task filter button queries
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js
Labels: refactor, approved

#4285 Refactor DataImageViewer and validate JSON scatter plots
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/hooks/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/hooks/useDataImageSubject.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/helpers/mockData.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/hooks/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/hooks/useScatterPlotSubject.js
  packages/lib-classifier/src/hooks/Readme.md
  packages/lib-classifier/src/hooks/index.js
  packages/lib-classifier/src/hooks/useSubjectJSON.js
  packages/lib-classifier/src/store/JSONData/DataSeriesPlot.js
  packages/lib-classifier/src/store/JSONData/TESSLightCurve.js
  packages/lib-classifier/src/store/JSONData/index.js
Labels: enhancement, refactor, approved

#4340 Refactor hooks in JSON data viewers
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/README.md
  packages/lib-classifier/src/helpers/index.js
  packages/lib-classifier/src/helpers/useJSONData/README.md
  packages/lib-classifier/src/helpers/useJSONData/index.js
  packages/lib-classifier/src/helpers/useJSONData/useJSONData.js
  packages/lib-classifier/src/hooks/useSubjectJSON.js
  packages/lib-classifier/src/store/JSONData/BarChart.js
  packages/lib-classifier/src/store/JSONData/index.js
Labels: bug, refactor, storybook, approved

#4318 Update pt dictionaries for theme mode and Research page title
  packages/app-project/public/locales/pt/components.json
  packages/app-project/public/locales/pt/screens.json
Labels: approved, translations

#4274 Classifier: add useSubjectText hook and refactor subject viewers (1 of 3)
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerContainer.js
  packages/lib-classifier/src/hooks/Readme.md
  packages/lib-classifier/src/hooks/index.js
  packages/lib-classifier/src/hooks/useSubjectText.js
Labels: refactor, approved

#4352 Image toolbar: use pointer events
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.spec.js
Labels: bug, refactor, approved

#4375 Add Sentry Express middleware
  packages/app-content-pages/server/server.js
  packages/app-project/server/server.js
Labels: ops, approved

#4387 Quick and dirty script error logging
  packages/app-project/pages/_document.js
Labels: ops

#4388 Update Sentry logging
  packages/app-project/pages/_document.js
Labels: approved

#4338 Add workflow config to limit subject's height
  packages/lib-classifier/src/components/Classifier/components/Layout/Layout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/README.md
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.spec.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.stories.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/index.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.spec.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
Labels: enhancement, approved

#4394 Trace page performance with Sentry
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-content-pages/pages/publications.js
  packages/app-content-pages/pages/team.js
  packages/app-content-pages/src/helpers/logger/initializeSentry.js
  packages/app-content-pages/src/helpers/logger/logNodeError.js
  packages/app-content-pages/src/helpers/logger/logReactError.js
  packages/app-project/next.config.js
  packages/app-project/package.json
  packages/app-project/pages/_document.js
  packages/app-project/src/helpers/fetchProjectData/fetchProjectData.js
  packages/app-project/src/helpers/fetchProjectPage/fetchProjectPage.js
  packages/app-project/src/helpers/fetchProjectPageTitles/fetchProjectPageTitles.js
  packages/app-project/src/helpers/fetchSubjectSets/fetchSubjectSets.js
  packages/app-project/src/helpers/fetchTeam/fetchTeam.js
  packages/app-project/src/helpers/fetchTranslations/fetchTranslations.js
  packages/app-project/src/helpers/fetchWorkflowsHelper/fetchWorkflowsHelper.js
  packages/app-project/src/helpers/logger/initializeSentry.js
  packages/app-project/src/helpers/logger/logToSentry.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/checkRetiredStatus.js
  packages/app-project/stores/Store.js
  packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.js
  yarn.lock
Labels: ops

#4383 Add pull request branch to CodeQL workflow config
  .github/workflows/codeql-analysis.yml
Labels: ops, approved

#4405 lib-react-components: update .npmignore
  packages/lib-react-components/.npmignore
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: ops, approved
