Repository zooniverse/front-end-monorepo, pull requests merged in 2023-06, with the labels that each got.

#4751 app-project: Remove google+ link from Connect With Project
  packages/app-project/public/locales/en/components.json
  packages/app-project/public/locales/es/components.json
  packages/app-project/public/locales/test/components.json
  packages/app-project/public/locales/tr/components.json
  packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.stories.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/helpers/formatUrlObject/formatUrlObject.js
Labels: approved, ui

#4752 Default Sentry tag for classification errors
  packages/lib-classifier/src/store/utils/ClassificationQueue.js
Labels: refactor, approved

#4755 Remove unneeded test files for things like svg icons
  packages/app-content-pages/src/shared/components/AuthModal/shared/components/FieldLabel/FieldLabel.spec.js
  packages/app-project/src/components/AuthModal/shared/components/FieldLabel/FieldLabel.spec.js
  packages/app-project/src/helpers/GrommetWrapper/GrommetWrapperContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/components/MessageBox/MessageBox.spec.js
  packages/app-project/src/shared/components/CollectionsModal/CollectionsModal.spec.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/components/BitbucketIcon/BitbucketIcon.spec.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/components/WeiboIcon/WeiboIcon.spec.js
  packages/app-project/src/shared/components/ProjectStatistics/components/MainGrid/MainGrid.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsIcon.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/Banner/components/TooltipText/TooltipText.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/CollectionsButton/CollectionsIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/ResizeIcon/ResizeIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/TooltipIcon/TooltipIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/FlipIcon/FlipIcon.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptions.spec.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/components/TooltipIcon/TooltipIcon.spec.js
  packages/lib-classifier/src/plugins/tasks/components/InputIcon/InputIcon.spec.js
  packages/lib-classifier/src/plugins/tasks/dataVisAnnotation/components/components/Graph2dRangeXIcon.spec.js
  packages/lib-react-components/src/FavouritesButton/HeartIcon.spec.js
  packages/lib-react-components/src/MovableModal/components/ResizeIcon/ResizeIcon.spec.js
Labels: approved, tests

#4673 app-content-pages: Add stories and RTL unit tests to publications components
  packages/app-content-pages/.eslintrc
  packages/app-content-pages/pages/publications.js
  packages/app-content-pages/pages/team.js
  packages/app-content-pages/public/locales/en/components.json
  packages/app-content-pages/public/locales/test/components.json
  packages/app-content-pages/src/api/publications/publications.js
  packages/app-content-pages/src/api/team/team.js
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Publications/Publications.spec.js
  packages/app-content-pages/src/screens/Publications/Publications.stories.js
  packages/app-content-pages/src/screens/Publications/PublicationsContainer.js
  packages/app-content-pages/src/screens/Publications/PublicationsContainer.mock.json
  packages/app-content-pages/src/screens/Publications/PublicationsContainer.spec.js
  packages/app-content-pages/src/screens/Publications/components/Category/Category.js
  packages/app-content-pages/src/screens/Publications/components/Category/Category.spec.js
  packages/app-content-pages/src/screens/Publications/components/Category/Category.stories.js
  packages/app-content-pages/src/screens/Publications/components/Category/index.js
  packages/app-content-pages/src/screens/Publications/components/Project/Project.js
  packages/app-content-pages/src/screens/Publications/components/Project/Project.spec.js
  packages/app-content-pages/src/screens/Publications/components/Project/Project.stories.js
  packages/app-content-pages/src/screens/Publications/components/Project/index.js
  packages/app-content-pages/src/screens/Publications/components/Publication/Publication.js
  packages/app-content-pages/src/screens/Publications/components/Publication/Publication.spec.js
  packages/app-content-pages/src/screens/Publications/components/Publication/Publication.stories.js
  packages/app-content-pages/src/screens/Publications/components/Publication/index.js
  packages/app-content-pages/src/shared/components/AuthModal/theme.js
Labels: storybook, approved, tests

#4680 Test ScatterPlotViewer with React Testing Library
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Chart/Chart.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/Axes.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/Axis/Axis.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/Axes/components/InnerTickAxis/InnerTickAxis.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/ScatterPlotSeries/ScatterPlotPoint.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/ScatterPlotSeries/ScatterPlotSeries.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js
Labels: approved, tests

#4758 Fix Sentry build errors in Node
  packages/app-content-pages/src/helpers/logger/initializeSentry.js
  packages/app-project/src/helpers/logger/initializeSentry.js
Labels: bug, approved

#4692 app-content-pages: Add stories and RTL unit tests for Our Team page components
  packages/app-content-pages/pages/team.js
  packages/app-content-pages/src/screens/Team/Team.spec.js
  packages/app-content-pages/src/screens/Team/TeamContainer.spec.js
  packages/app-content-pages/src/screens/Team/components/Person/Person.spec.js
  packages/app-content-pages/src/screens/Team/components/Person/components/Avatar/Avatar.spec.js
  packages/app-content-pages/src/screens/Team/components/Person/components/Avatar/index.js
  packages/app-content-pages/src/screens/Team/components/Person/components/TwitterLink/TwitterLink.spec.js
  packages/app-content-pages/src/screens/Team/components/Person/components/TwitterLink/index.js
  packages/app-content-pages/src/screens/Team/components/Team/Team.spec.js
  packages/app-content-pages/src/screens/Team/components/Team/index.js
  packages/app-content-pages/src/screens/Team/index.js
  packages/app-content-pages/src/screens/Teams/Teams.js
  packages/app-content-pages/src/screens/Teams/Teams.stories.js
  packages/app-content-pages/src/screens/Teams/TeamsContainer.js
  packages/app-content-pages/src/screens/Teams/TeamsContainer.mock.json
  packages/app-content-pages/src/screens/Teams/TeamsContainer.spec.js
  packages/app-content-pages/src/screens/Teams/components/Person/Person.js
  packages/app-content-pages/src/screens/Teams/components/Person/Person.spec.js
  packages/app-content-pages/src/screens/Teams/components/Person/Person.stories.js
  packages/app-content-pages/src/screens/Teams/components/Person/components/Avatar/Avatar.js
  packages/app-content-pages/src/screens/Teams/components/Person/components/Avatar/index.js
  packages/app-content-pages/src/screens/Teams/components/Person/components/TwitterLink/TwitterLink.js
  packages/app-content-pages/src/screens/Teams/components/Person/components/TwitterLink/index.js
  packages/app-content-pages/src/screens/Teams/components/Person/index.js
  packages/app-content-pages/src/screens/Teams/components/Team/Team.js
  packages/app-content-pages/src/screens/Teams/components/Team/Team.spec.js
  packages/app-content-pages/src/screens/Teams/components/Team/Team.stories.js
  packages/app-content-pages/src/screens/Teams/components/Team/index.js
  packages/app-content-pages/src/screens/Teams/index.js
  packages/app-content-pages/test/team.spec.js
Labels: storybook, approved, tests

#4531 Remove TranscribedLinesConnector
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLinesConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/index.js
  packages/lib-classifier/src/hooks/useTranscriptionReductions.js
Labels: refactor, approved

#4753 Highlighter task: accessible text selections
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerContainer.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/components/Selection.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/components/Selection.spec.js
Labels: enhancement, accessibility, approved

#4594 lib-classifier: Add disableImageToolbar view to SubjectViewerStore, refactor toolbar buttons
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewerContainer.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.spec.js
Labels: approved

#4595 Add DataVisAnnotation task to scatter plot viewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/Selection.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/Selections.js
Labels: enhancement, approved

#4648 JSONData ADR
  docs/arch/README.md
  docs/arch/adr-48.md
Labels: documentation, approved

#4767 Defer Done & Talk until classification has saved
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.js
  packages/lib-classifier/src/store/ClassificationStore.js
Labels: bug, experiment, approved

#4776 Classifier: Disable both Done&Talk and Done buttons while classification is saving
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.js
Labels: approved, ui

#4782 Unit Test Conversion: Head components
  packages/app-content-pages/src/shared/components/Head/Head.spec.js
  packages/app-project/src/components/Head/Head.spec.js
  packages/app-project/src/components/Head/HeadContainer.spec.js
Labels: approved, tests

#4768 app-content-pages: resolve skipped unit tests
  packages/app-content-pages/public/locales/en/components.json
  packages/app-content-pages/public/locales/test/components.json
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Publications/PublicationsContainer.mock.json
  packages/app-content-pages/src/screens/Publications/PublicationsContainer.spec.js
  packages/app-content-pages/src/screens/Teams/Teams.js
  packages/app-content-pages/src/screens/Teams/TeamsContainer.spec.js
  packages/app-content-pages/src/shared/components/AuthModal/components/LoginForm/LoginFormContainer.js
  packages/app-content-pages/src/shared/components/AuthModal/components/LoginForm/LoginFormContainer.spec.js
  packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/RegisterFormContainer.js
  packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/RegisterFormContainer.spec.js
  packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/components/Form/Form.spec.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js
  packages/app-project/test/i18n-for-tests.js
Labels: accessibility, approved, tests

#4567 app-project: Add OrganizationLink to ProjectHeader and Hero components
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.stories.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.spec.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.stories.js
  packages/app-project/src/components/ProjectHeader/components/OrganizationLink/OrganizationLink.js
  packages/app-project/src/components/ProjectHeader/components/OrganizationLink/index.js
  packages/app-project/src/components/ProjectHeader/components/index.js
  packages/app-project/src/components/ProjectHeader/hooks/useStores.js
  packages/app-project/src/helpers/fetchOrganization/fetchOrganization.js
  packages/app-project/src/helpers/fetchOrganization/fetchOrganization.spec.js
  packages/app-project/src/helpers/fetchOrganization/index.js
  packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
  packages/app-project/src/helpers/index.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/NarrowLayout/NarrowLayout.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/OrganizationLink/OrganizationLink.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/OrganizationLink/OrganizationLink.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/OrganizationLink/index.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WideLayout/WideLayout.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayout.js
  packages/app-project/stores/Organization.js
  packages/app-project/stores/Organization.spec.js
  packages/app-project/stores/Store.js
  packages/app-project/stores/initStore.js
  packages/app-project/stores/initStore.spec.js
Labels: approved

#4801 Organisations: small fixes
  packages/app-project/src/helpers/fetchOrganization/fetchOrganization.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
  packages/app-project/stores/Organization.js
  packages/app-project/stores/Project.js
  packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.spec.js
Labels: refactor, approved

#4764 NextJS: migrate Sentry to @sentry/nextjs
  .github/workflows/deploy_branch.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  Dockerfile
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-content-pages/pages/_app.js
  packages/app-content-pages/pages/_error.js
  packages/app-content-pages/sentry.client.config.js
  packages/app-content-pages/sentry.edge.config.js
  packages/app-content-pages/sentry.server.config.js
  packages/app-content-pages/src/helpers/logger/index.js
  packages/app-content-pages/src/helpers/logger/initializeSentry.js
  packages/app-content-pages/src/helpers/logger/logNodeError.js
  packages/app-content-pages/src/helpers/logger/logReactError.js
  packages/app-project/next.config.js
  packages/app-project/package.json
  packages/app-project/pages/_app.js
  packages/app-project/pages/_error.js
  packages/app-project/sentry.client.config.js
  packages/app-project/sentry.edge.config.js
  packages/app-project/sentry.server.config.js
  packages/app-project/src/helpers/logger/addSentryUser.js
  packages/app-project/src/helpers/logger/index.js
  packages/app-project/src/helpers/logger/initializeSentry.js
  packages/app-project/src/helpers/logger/logToSentry.js
  yarn.lock
Labels: dependencies, refactor, approved

#4821 WorkflowSelector: prevent container from squeezing/overlapping content
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js
Labels: approved

#4839 lib-classifier: Edit field guide attached media request
  packages/lib-classifier/src/store/FieldGuideStore/FieldGuideStore.js
Labels: approved

#4840 Fix Workflow Assignment Modal Bugs
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/README.md
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.stories.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalConnector.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalContainer.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModalContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/index.js
Labels: bug, high priority, approved

#4754 ESLint: Add eslint-plugin-react
  packages/app-content-pages/.eslintrc
  packages/app-content-pages/package.json
  packages/app-content-pages/pages/_app.js
  packages/app-content-pages/src/api/publications/buildResponse.js
  packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/components/Form/Form.js
  packages/app-project/.eslintignore
  packages/app-project/.eslintrc
  packages/app-project/package.json
  packages/app-project/pages/_document.js
  packages/app-project/src/components/AuthModal/components/RegisterForm/components/Form/Form.js
  packages/app-project/src/helpers/fetchProjectPageTitles/fetchProjectPageTitles.js
  packages/app-project/src/hooks/useAdminMode.js
  packages/app-project/src/hooks/useSugarProject.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
  packages/lib-classifier/.eslintrc
  packages/lib-classifier/eslint.config.js
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
  packages/tools-standard/options.js
  packages/tools-standard/package.json
  yarn.lock
Labels: enhancement, dx, approved

#4861 Classifier: Fix build warning about workflow assignment modal
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
Labels: approved

#4802 lib-classifier: Refactor survey task ConfusedWith styling
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/ConfusedWith.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.js
Labels: approved

#4848 Wait before refreshing the subject queue
  packages/lib-classifier/src/store/RootStore.js
Labels: bug, high priority

#4870 Workflow Assignment Modal: check for session storage item on every render
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.js
Labels: bug, approved

#4846 Remove seenThisSession from ZooHeaderWrapper
  packages/app-content-pages/src/shared/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js
  packages/app-content-pages/src/shared/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.spec.js
  packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js
  packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.spec.js
Labels: refactor, approved

#4868 Set classification userLanguage from locale
  packages/lib-classifier/src/store/Classification/ClassificationMetadata.js
  packages/lib-classifier/src/store/Classification/ClassificationMetadata.spec.js
Labels: bug, approved

#4869 Disable previous drawing marks
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarksConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarksConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/index.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.spec.js
Labels: bug, approved

#4891 app-project: minor refactor of Hero tests
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.spec.js
Labels: approved, tests

#4867 Project: fix collections search
  packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.js
  packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.spec.js
Labels: bug, approved

#4876 Reduce metadata modal row spacing
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.js
Labels: approved, ui

#4798 Transcription task: catch duplicate subjects
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/hooks/useTranscriptionReductions.js
  packages/lib-classifier/src/store/subjects/Subject/TranscriptionReductions/TranscriptionReductions.js
Labels: enhancement, approved

#4820 Validate auth'ed subject queue requests
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
Labels: enhancement, approved

#4841 lib-classifier: Refactor survey task choices thumbnail sizing per task properties
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.js
  packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.js
Labels: approved

#4919 Restore drawing tool disabled state
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
Labels: bug, approved
