Repository zooniverse/front-end-monorepo, pull requests merged in 2023-07, with the labels that each got.

#4911 lib-classifier: Refactor survey task carousel control arrows and 3 column styling
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/carouselTheme.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js
Labels: approved

#4921 Enable Finished Project Banner
  packages/app-project/pages/[panoptesEnv]/[owner]/[project]/about/education.js
  packages/app-project/pages/[panoptesEnv]/[owner]/[project]/about/faq.js
  packages/app-project/pages/[panoptesEnv]/[owner]/[project]/about/research.js
  packages/app-project/pages/[panoptesEnv]/[owner]/[project]/about/results.js
  packages/app-project/pages/[panoptesEnv]/[owner]/[project]/about/team.js
  packages/app-project/pages/[panoptesEnv]/[owner]/[project]/index.js
  packages/app-project/src/components/Announcements/Announcements.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncement.stories.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.spec.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
  packages/app-project/stores/Project.js
Labels: enhancement, approved

#4866 App-project: Refactor collections modal and modify collection names
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
  packages/app-project/src/shared/components/CollectionsModal/CollectionsModal.js
  packages/app-project/src/shared/components/CollectionsModal/CollectionsModal.stories.js
  packages/app-project/src/shared/components/CollectionsModal/CollectionsModalContainer.js
  packages/app-project/src/shared/components/CollectionsModal/CollectionsModalContainer.spec.js
  packages/app-project/src/shared/components/CollectionsModal/components/CreateCollection/CreateCollection.js
  packages/app-project/src/shared/components/CollectionsModal/components/CreateCollection/CreateCollection.spec.js
  packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.js
  packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.spec.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.stories.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.stories.js
Labels: bug, approved

#4903 lib-classifier: Refactor drawing task to support dropdown subtask
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/models/marks/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.js
  packages/lib-classifier/src/plugins/drawingTools/models/tools/Tool/Tool.spec.js
  packages/lib-classifier/src/plugins/drawingTools/stories/helpers.js
Labels: approved

#4943 Specify dimensions for Media images
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.js
  packages/lib-react-components/src/Media/Media.js
  packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js
  packages/lib-react-components/src/Media/helpers/getThumbnailSrc.js
Labels: bug, approved

#4958 Debounce flipbook resize observer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/components/FlipbookControls.js
Labels: bug, dx, approved

#4970 Revert "build(deps): bump @sentry/nextjs from 7.56.0 to 7.57.0"
  packages/app-content-pages/package.json
  packages/app-project/next.config.js
  packages/app-project/package.json
  yarn.lock
Labels: bug, approved

#4803 Refactor Panoptes authentication in all packages
  packages/app-content-pages/package.json
  packages/app-content-pages/src/shared/stores/User/User.js
  packages/app-project/package.json
  packages/app-project/src/hooks/usePanoptesUser.js
  packages/app-project/stores/User/User.js
  packages/app-project/stores/User/User.spec.js
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/Classifier.spec.js
  packages/lib-classifier/src/components/Classifier/Classifier.workflows.spec.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js
  packages/lib-classifier/src/components/Classifier/hooks/usePanoptesUserSession.js
  packages/lib-classifier/src/hooks/Readme.md
  packages/lib-classifier/src/hooks/useHydratedStore.js
  packages/lib-classifier/src/hooks/useHydratedStore.spec.js
  packages/lib-classifier/src/hooks/usePanoptesAuth.js
  packages/lib-classifier/src/hooks/usePanoptesUser.js
  packages/lib-classifier/src/hooks/useProjectPreferences.js
  packages/lib-classifier/src/hooks/useProjectRoles.js
  packages/lib-classifier/src/store/RootStore.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js
  packages/lib-classifier/src/store/WorkflowStore/WorkflowStore.js
  packages/lib-panoptes-js/docs/CHANGELOG.md
  packages/lib-panoptes-js/package.json
  packages/lib-panoptes-js/src/auth.js
Labels: bug, refactor, performance, approved

#5010 Show modal tutorial for anonymous users
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.spec.js
  packages/lib-classifier/src/components/Classifier/hooks/usePanoptesUserSession.js
  packages/lib-classifier/src/hooks/useProjectPreferences.js
  packages/lib-classifier/src/hooks/useProjectRoles.js
Labels: bug, approved

#5014 Stronger checking for classifier data fetching
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/components/Classifier/hooks/usePanoptesUserSession.js
  packages/lib-classifier/src/hooks/useProjectPreferences.js
  packages/lib-classifier/src/hooks/useProjectRoles.js
Labels: bug, refactor, approved

#4979 Update classifier when callbacks change
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/app-project/src/shared/components/CollectionsModal/CollectionsModalContainer.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
Labels: bug, approved

#5038 Move workflow strings state to ClassifierContainer
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/Classifier.spec.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.spec.js
Labels: bug, approved

#5007 Project: set UPP loading state after refreshing from Panoptes
  packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.js
  packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.spec.js
Labels: bug, approved

#5051 Use constant callbacks in the dev classifier
  packages/lib-classifier/dev/components/App/App.js
Labels: bug, approved

#4978 Classifier: fix unobserve error in flipbook controls
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/components/FlipbookControls.js
Labels: dx, approved

#5042 Document the ClassifierContainer and Classifier with code comments
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
Labels: documentation, approved

#5037 Lint ClassifierWrapper callbacks
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
Labels: bug, approved

#5050 Continuous zooming in separate frames mode
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
Labels: bug, approved

#5077 Image Toolbar: change button callbacks to match zoom callback pattern
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/SeparateFramesViewer.js
Labels: dx, approved
