Repository zooniverse/front-end-monorepo, pull requests merged in 2023-04, with the labels that each got.

#4409 Standardize all component stories in lib-react-components
  packages/lib-react-components/.storybook/lib/backgrounds.js
  packages/lib-react-components/.storybook/lib/index.js
  packages/lib-react-components/.storybook/main.js
  packages/lib-react-components/.storybook/preview.js
  packages/lib-react-components/package.json
  packages/lib-react-components/src/AdminCheckbox/AdminCheckbox.stories.js
  packages/lib-react-components/src/CloseButton/CloseButton.stories.js
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.stories.js
  packages/lib-react-components/src/Markdownz/Markdownz.stories.js
  packages/lib-react-components/src/Media/Media.stories.js
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.stories.js
  packages/lib-react-components/src/Modal/Modal.stories.js
  packages/lib-react-components/src/MovableModal/MovableModal.stories.js
  packages/lib-react-components/src/PlainButton/PlainButton.stories.js
  packages/lib-react-components/src/PrimaryButton/PrimaryButton.stories.js
  packages/lib-react-components/src/SpacedHeading/SpacedHeading.stories.js
  packages/lib-react-components/src/SpacedText/SpacedText.stories.js
  packages/lib-react-components/src/Tabs/Tabs.stories.js
  packages/lib-react-components/src/Tooltip/Tooltip.stories.js
  packages/lib-react-components/src/Tooltip/components/Label/Label.stories.js
  packages/lib-react-components/src/Tooltip/components/Triangle/Triangle.stories.js
  packages/lib-react-components/src/ZooFooter/ZooFooter.stories.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.stories.js
  packages/lib-react-components/src/ZooniverseLogo/ZooniverseLogo.stories.js
  packages/lib-react-components/src/ZooniverseLogotype/ZooniverseLogo.stories.js
Labels: refactor, storybook, approved

#4417 app-project: Remove deprecated Storybook packages
  packages/app-project/.storybook/main.js
  packages/app-project/.storybook/preview.js
  packages/app-project/package.json
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitation.stories.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncement.stories.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/GenericAnnouncement.stories.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncement.stories.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.stories.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjects.stories.js
  packages/app-project/src/shared/components/ContentBox/ContentBox.stories.js
  packages/app-project/src/shared/components/Loader/Loader.stories.js
  packages/app-project/src/shared/components/Stat/Stat.stories.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.stories.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.stories.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.stories.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.stories.js
Labels: refactor, storybook, approved

#4428 lib-classifier: Remove deprecated Storybook packages
  packages/lib-classifier/.storybook/main.js
  packages/lib-classifier/.storybook/preview.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.stories.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.stories.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Circle/Circle.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Ellipse/Ellipse.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Line/Line.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Point/Point.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/Rectangle/Rectangle.stories.js
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.stories.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.stories.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/TranscriptionLine.stories.js
  packages/lib-classifier/src/plugins/tasks/dataVisAnnotation/components/DataVisAnnotationTask.stories.js
  packages/lib-classifier/src/plugins/tasks/drawing/components/DrawingTask.stories.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.stories.js
  packages/lib-classifier/src/plugins/tasks/experimental/transcription/TranscriptionTask.stories.js
  packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.stories.js
  packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.stories.js
  packages/lib-classifier/src/plugins/tasks/text/components/TextTask/TextTask.stories.js
Labels: refactor, storybook, approved

#4442 Revert Sentry packages to version 7.46.0
  packages/app-content-pages/package.json
  packages/app-project/package.json
  yarn.lock
Labels: bug, approved, degraded-ux

#4427 app-project: Create Storybook global decorator for Grommet theme
  packages/app-project/.storybook/lib/backgrounds.js
  packages/app-project/.storybook/lib/index.js
  packages/app-project/.storybook/preview.js
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitation.stories.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncement.stories.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/GenericAnnouncement.stories.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncement.stories.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.stories.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.stories.js
  packages/app-project/src/components/ProjectHeader/components/LocaleSwitcher/LocaleSwitcher.stories.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.stories.js
  packages/app-project/src/components/ThemeModeToggle/ThemeModeToggle.stories.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.stories.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.stories.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.stories.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink/AboutNavLink.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProject.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjects.stories.js
  packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.stories.js
  packages/app-project/src/shared/components/ContentBox/ContentBox.stories.js
  packages/app-project/src/shared/components/Loader/Loader.stories.js
  packages/app-project/src/shared/components/Stat/Stat.stories.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.stories.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.stories.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.stories.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.stories.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.stories.js
Labels: refactor, storybook

#4453 Fix Safari layout bug on /about pages
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
Labels: bug, approved

#4463 Deploy storybooks from production-release
  .github/workflows/deploy_storybook.yml
Labels: ops, approved

#4475 Add missing CI env to deploy_storybook workflow
  .github/workflows/deploy_storybook.yml
Labels: ops, approved

#4452 1 of 3 Separate Frames Viewer: Introduce SeparateFrame component
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/InvertButton/InvertButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/MoveButton/MoveButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ResetButton/ResetButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/RotateButton/RotateButtonContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js
  packages/lib-classifier/src/components/Classifier/components/Layout/Layout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.stories.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js
Labels: enhancement, approved

#4227 Add undo, redo, and tests to the freehand line tool.
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGImage/SVGImage.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/FreehandLine.stories.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/FreehandLine/README.md
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/LineControls/LineControls.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/LineControls/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/index.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/FreehandLineTool/FreehandLineTool.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/tools/FreehandLineTool/FreehandLineTool.spec.js
  packages/lib-classifier/src/translations/en/plugins.json
Labels: approved

#4470 Turn off NextJS gzip compression
  packages/app-content-pages/next.config.js
  packages/app-project/next.config.js
Labels: ops, approved

#4455 2 of 3 Separate Frames Viewer: Add View Mode Button to UI
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideConnector.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideWrapper.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/FullscreenButton/FullscreenButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.stories.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.stories.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/components/FlipbookControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/SeparateFramesViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/SeparateFramesViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/SeparateFramesViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/ViewModeButton/ViewModeButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/ViewModeButton/ViewModeButton.stories.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.stories.js
  packages/lib-classifier/src/translations/en/components.json
Labels: enhancement, approved

#4370 Add highlighter task
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewerContainer.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/README.md
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/HighlighterTask.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/HighlighterTask.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/HighlighterTask.stories.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/components/Selection.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/components/Selection.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/helpers/getOffset.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/helpers/selectableArea.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/index.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/models/HighlighterAnnotation.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/models/HighlighterAnnotation.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/models/HighlighterLabel.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/models/HighlighterLabel.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/models/HighlighterTask.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/models/HighlighterTask.spec.js
  packages/lib-classifier/src/plugins/tasks/index.js
  packages/lib-classifier/src/translations/en/plugins.json
Labels: enhancement, approved

#4506 Label approved pull requests
  .github/workflows/label_approved.yml
Labels: ops, approved

#4481 3 of 3 Separate Frames Viewer: Handle various frames layouts
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/SeparateFramesViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/SeparateFramesViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/ViewModeButton/ViewModeButton.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
Labels: enhancement, approved
