Repository zooniverse/front-end-monorepo, pull requests merged in 2023-02, with the labels that each got.

#4225 Bypass the CDN for /projects/_next/static
  packages/app-project/next.config.js
Labels: high priority, ops, approved

#4176 Remove @babel/plugin-proposal-decorators
  packages/lib-classifier/.babelrc
  packages/lib-classifier/package.json
  yarn.lock
Labels: dependencies, approved

#4238 Edit next app asset prefixes to bypass CDN on production, go through CDN on staging
  packages/app-content-pages/next.config.js
  packages/app-project/next.config.js
Labels: ops, approved

#4243 Correct the app-content-pages production assetPrefix to bypass CDN
  packages/app-content-pages/next.config.js
  packages/app-project/next.config.js
Labels: ops, approved

#4254 Classifier: mute liveliness warnings in tests
  packages/lib-classifier/src/store/RootStore.js
Labels: approved

#4240 Remove redundant asset prefixes
  packages/app-content-pages/next.config.js
  packages/app-project/next.config.js
Labels: ops, approved

#4206 Subscribe volunteers to a project's Sugar channel
  packages/app-project/pages/_app.js
  packages/app-project/src/hooks/index.js
  packages/app-project/src/hooks/useSugarProject.js
Labels: enhancement, approved

#4181 Classifier: enable autoplay config for flipbook viewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.spec.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
  packages/lib-classifier/test/setup.js
Labels: enhancement, approved

#4213 Remove drop-down icon from hamburger menu
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/src/ZooHeader/components/NarrowMainNavMenu/NarrowMainNavMenu.js
Labels: bug, approved

#4236 Build and deploy with Node 18
  .github/workflows/ci-build.yml
  .github/workflows/coverage.yml
  Dockerfile
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/lib-async-states/package.json
  packages/lib-classifier/package.json
  packages/lib-grommet-theme/package.json
  packages/lib-panoptes-js/package.json
  packages/lib-react-components/package.json
Labels: ops

#4282 Fix broken Docker builds
  Dockerfile
Labels: ops

#4292 Remove production assetPrefix from next.config
  packages/app-content-pages/next.config.js
  packages/app-project/next.config.js
Labels: ops

#4273 Log errors from prioritised subject queues
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
Labels: bug, approved

#4298 Fix privacy policy links
  packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/components/Form/Form.js
  packages/app-project/src/components/AuthModal/components/RegisterForm/components/Form/Form.js
Labels: bug, approved

#4281 Classifier: Refactor and document Caesar hooks
  packages/lib-classifier/src/hooks/Readme.md
  packages/lib-classifier/src/hooks/index.js
  packages/lib-classifier/src/hooks/useCaesarReductions.js
  packages/lib-classifier/src/hooks/useTranscriptionReductions.js
Labels: refactor, approved

#4244 Classifier: refactor survey task styling for varying screen sizes
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/Choices.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.spec.js
Labels: design, approved

#4247 Refactor TranscribedLines tests with RTL
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
Labels: refactor, approved

#4066 Classifier: limit subject width in extra-wide viewports
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.stories.js
  packages/lib-classifier/src/components/Classifier/components/Layout/Layout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/Layout.spec.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/index.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.spec.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.stories.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/index.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.spec.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.stories.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/index.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/index.js
  packages/lib-classifier/src/components/Classifier/components/Layout/helpers/getLayout/getLayout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/helpers/getLayout/getLayout.spec.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.js
  packages/lib-classifier/test/mockStore/mockStore.js
Labels: bug, accessibility, refactor, design, approved

#4295 Refactor useSubjectImage as a shared hook
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/hooks/useSubjectImage.js
  packages/lib-classifier/src/hooks/Readme.md
  packages/lib-classifier/src/hooks/index.js
  packages/lib-classifier/src/hooks/useSubjectImage.js
Labels: refactor, approved

#4260 Classifier: refactor image and text viewer controls
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/components/ImageAndTextControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/components/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/components/theme.js
  packages/lib-classifier/src/translations/en/components.json
Labels: refactor, approved

#4310 Refactor TextFromSubject task font
  packages/lib-classifier/src/plugins/tasks/experimental/textFromSubject/components/TextFromSubjectTask.js
Labels: design, approved

#4311 Refactor text viewer font
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.js
Labels: design, approved
