Repository zooniverse/front-end-monorepo, pull requests merged in 2023-09, with the labels that each got.

#5292 Enable the experimental data selection tools.
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/JSONDataViewer/JSONDataViewer.js
Labels: enhancement, approved

#5270 Clear LightCurveViewer on unmount
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
Labels: bug, approved

#5298 Generalise graph2dRangeFeedback for JSON subjects
  packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js
  packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
Labels: refactor, approved

#5306 Data selection: use window events for brushes
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/Selections.js
Labels: bug, approved

#5274 404 page: fix invalid HTML
  packages/app-project/pages/404.js
  packages/app-project/src/hooks/useSugarProject.js
Labels: bug, approved

#5271 Create wrapper function for running Stories in Specs
  packages/app-content-pages/.storybook/lib/i18n.js
  packages/app-content-pages/.storybook/specConfig.js
  packages/app-content-pages/package.json
  packages/app-content-pages/src/screens/Publications/PublicationsContainer.spec.js
  packages/app-content-pages/src/screens/Teams/TeamsContainer.spec.js
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.spec.js
  packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/components/Form/Form.spec.js
  packages/app-project/.storybook/lib/i18n.js
  packages/app-project/.storybook/specConfig.js
  packages/app-project/package.json
  packages/app-project/src/components/ProjectName/ProjectName.mock.js
  packages/app-project/src/components/ProjectName/ProjectName.spec.js
  packages/app-project/src/components/ProjectName/ProjectName.stories.js
  packages/lib-classifier/.storybook/specConfig.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.spec.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.spec.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/JSONDataViewer/JSONDataViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/HighlighterTask.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userKeystrokes.spec.js
  packages/lib-react-components/.storybook/specConfig.js
  packages/lib-react-components/package.json
Labels: storybook, approved, tests

#5219 AboutProject: Remove enzyme and convert tests to RTL
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProject.mock.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProject.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProject.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/AboutProject/AboutProjectContainer.spec.js
Labels: approved, tests

#5218 MessageFromResearcher: Remove enzyme and convert tests to RTL
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcher.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcher.mock.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcher.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcher.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcherContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcherContainer.spec.js
Labels: approved, tests

#5326 Restore image viewer drag performance
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
Labels: bug, approved

#5278 ZRC: Refactor ZooHeader to avoid hydration errors
  packages/app-project/pages/_app.js
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
  packages/lib-react-components/src/ZooHeader/components/NavListItem/NavListItem.js
  packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/SignedOutUserNavigation.js
Labels: bug, accessibility, approved

#5327 Fix missing padding in the logged-out user menu
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenu/NarrowMenu.js
  packages/lib-react-components/src/ZooHeader/components/UserMenu/UserMenu.js
Labels: bug, accessibility, approved

#5325 Modularise @zooniverse/react-components
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.js
  packages/app-content-pages/src/shared/components/AuthModal/AuthModal.js
  packages/app-content-pages/src/shared/components/AuthModal/components/LoginForm/components/Form/Form.js
  packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/components/Form/Form.js
  packages/app-project/next.config.js
  packages/app-project/package.json
  packages/app-project/src/components/AuthModal/AuthModal.js
  packages/app-project/src/components/AuthModal/components/LoginForm/components/Form/Form.js
  packages/app-project/src/components/AuthModal/components/RegisterForm/components/Form/Form.js
  packages/app-project/src/components/ProjectName/ProjectName.js
  packages/app-project/src/components/ThemeModeToggle/ThemeModeToggle.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutMarkdownz/AboutMarkdownz.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/ZooniverseTalk.js
  packages/app-project/src/shared/components/ProjectStatistics/components/Subtitle/Subtitle.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/theme.js
  packages/lib-classifier/.babelrc
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/components/SaveButton/SaveButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoController/VideoController.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/Controls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/components/Controls/components/PeriodMultipleControls/PeriodMultipleControls.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.js
  packages/lib-classifier/src/hooks/useSubjectImage.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.js
  packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/subjectGroupComparison/components/SubjectGroupComparisonTask.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/theme.js
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/src/helpers/pxToRem/index.js
  packages/lib-react-components/src/helpers/pxToRem/pxToRem.js
  packages/lib-react-components/src/index.js
Labels: dependencies, ops, approved

#5333 Add notes to ADR Template file
  docs/ADR_TEMPLATE.md
Labels: documentation, approved

#5339 ZRC: restore the package main entry point
  packages/lib-react-components/package.json
Labels: bug, ops, approved

#5305 Style SVG subjects with touch-action: pinch-zoom
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
Labels: bug, accessibility, approved

#5184 Upgrade app-content-pages to NextJS 13
  package.json
  packages/app-content-pages/package.json
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Teams/Teams.js
  packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.js
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies, ops, approved

#5361 ZRC: import @visx/vendor/d3-array
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/src/Media/components/Data/components/DataSeriesPlot/helpers/utils.js
Labels: bug, approved, ESM

#5349 lib-classifier: Refactor TaskHelp separators with multiple tasks
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.spec.js
Labels: bug, approved

#5341 Display Media images inline
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.spec.js
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/src/Markdownz/Markdownz.js
  packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js
  packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.spec.js
  yarn.lock
Labels: bug, approved

#5383 Add drop shadow to transcribed lines
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.js
Labels: enhancement

#4894 Implement Custom 404 page for project pages
  packages/app-project/pages/404.js
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/helpers/404theme.js
Labels: approved

#5416 Fix transcription task errors for async Caesar reductions
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/src/hooks/useCaesarReductions.js
  packages/lib-classifier/src/hooks/useTranscriptionReductions.js
Labels: bug, approved

#5421 Fix Field Guide movable modal on touch devices
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/FieldGuideContainer.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItems/FieldGuideItems.js
Labels: bug, approved

#5386 Fix SVG subject scaling
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGImage/SVGImage.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/TranscriptionLine/helpers/constants.js
Labels: bug, approved

#5427 Content pages: run with next start
  packages/app-content-pages/package.json
Labels: ops
