Repository zooniverse/front-end-monorepo, pull requests merged in 2023-12, with the labels that each got.

#5707 Classifier: Adjust video controller spacing for consistent timestamp style
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoController/VideoController.js
Labels: bug, approved

#5521 [Security] Upgrade app-project to next@13.5
  package.json
  packages/app-project/middleware.js
  packages/app-project/next.config.js
  packages/app-project/package.json
  packages/app-project/src/components/AdminContainer/AdminContainer.spec.js
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationContainer.spec.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncement.stories.js
  packages/app-project/src/components/AuthModal/components/LoginForm/components/Form/Form.js
  packages/app-project/src/components/ProjectHeader/ProjectHeader.stories.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.stories.js
  packages/app-project/src/components/ProjectHeader/components/LocaleSwitcher/LocaleSwitcher.stories.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.stories.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js
  packages/app-project/src/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowAssignmentModal/WorkflowAssignmentModal.stories.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.spec.js
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.stories.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.stories.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink/AboutNavLink.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink/AboutNavLink.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.stories.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.stories.js
  packages/app-project/src/screens/ProjectHomePage/ProjectHomePage.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButton.js
  packages/app-project/src/shared/components/ContentBox/ContentBox.stories.js
  packages/app-project/src/shared/components/NavLink/NavLink.js
  packages/app-project/src/shared/components/NavLink/NavLink.stories.js
  packages/app-project/src/shared/components/StandardLayout/StandardLayout.spec.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.js
  packages/app-project/src/shared/components/SubjectPicker/SubjectPicker.spec.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/columns.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/columns.spec.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.stories.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.spec.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.spec.js
  packages/app-project/stores/index.js
  yarn.lock
Labels: dependencies, security, ops, approved

#5740 Bump lib-react-components to v1.11.0
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-root/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: documentation, approved

#5582 lib-user: add user_group actions, related components for local dev
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/package.json
  packages/lib-user/src/components/GroupStats/DeleteGroup.js
  packages/lib-user/src/components/GroupStats/EditGroup.js
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/GroupStats.spec.js
  packages/lib-user/src/components/MyGroups/CreateGroup.js
  packages/lib-user/src/components/MyGroups/MyGroups.js
  packages/lib-user/src/components/MyGroups/helpers/convertActiveGroupsWithRoles.js
  packages/lib-user/src/components/MyGroups/helpers/convertActiveGroupsWithRoles.spec.js
  packages/lib-user/src/components/MyGroups/index.js
  packages/lib-user/src/components/UserStats/UserStats.js
  packages/lib-user/src/components/index.js
  packages/lib-user/src/hooks/index.js
  packages/lib-user/src/hooks/usePanoptesAuth.js
  packages/lib-user/src/hooks/usePanoptesMemberships.js
  packages/lib-user/src/hooks/usePanoptesUser.js
  packages/lib-user/src/hooks/usePanoptesUserGroup.js
  packages/lib-user/src/index.js
  packages/lib-user/src/utils/createPanoptesUserGroup.js
  packages/lib-user/src/utils/deletePanoptesUserGroup.js
  packages/lib-user/src/utils/getBearerToken.spec.js
  packages/lib-user/src/utils/index.js
  packages/lib-user/src/utils/updatePanoptesUserGroup.js
Labels: approved

#5665 lib-user: Add ProfileHeader component and story
  packages/lib-user/eslint.config.js
  packages/lib-user/package.json
  packages/lib-user/src/components/UserStats/components/ProfileHeader.js
  packages/lib-user/src/components/UserStats/components/ProfileHeader.spec.js
  packages/lib-user/src/components/UserStats/components/ProfileHeader.stories.js
  packages/lib-user/src/components/UserStats/components/index.js
  packages/lib-user/webpack.dev.js
  yarn.lock
Labels: approved

#5758 app-content-pages: return mock data if no contentful tokens
  packages/app-content-pages/src/api/publications/buildResponse.spec.js
  packages/app-content-pages/src/api/publications/mocks/contentfulResponse.mock.json
  packages/app-content-pages/src/api/publications/mocks/projectAvatarsMap.mock.json
  packages/app-content-pages/src/api/publications/mocks/response.mock.json
  packages/app-content-pages/src/api/publications/mocks/uniqueProjectIds.mock.json
  packages/app-content-pages/src/api/publications/publications.js
  packages/app-content-pages/src/api/shared/contentfulClient/contentfulClient.js
  packages/app-content-pages/src/api/team/processTeamData.mock.json
  packages/app-content-pages/src/api/team/processTeamData.result.json
  packages/app-content-pages/src/api/team/processTeamData.spec.js
  packages/app-content-pages/src/api/team/team.js
Labels: bug, approved

#5768 Check if subject exists for recent subjects on homepage
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/helpers/fetchRecentSubjects/fetchRecentSubjects.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/helpers/fetchRecentSubjects/fetchSubjectData.js
Labels: bug, approved, degraded-ux

#5776 Subject Set Selection bug fixes
  packages/app-project/pages/[panoptesEnv]/[owner]/[project]/classify/workflow/[workflowID]/subject-set/[subjectSetID]/subject/[subjectID]/index.js
  packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPage.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
Labels: bug, approved, degraded-ux

#5762 app-content-pages: Remove Sentry, New Relic, and Million.js
  packages/app-content-pages/.storybook/main.js
  packages/app-content-pages/README.md
  packages/app-content-pages/newrelic.js
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-content-pages/pages/_app.js
  packages/app-content-pages/pages/_document.js
  packages/app-content-pages/pages/_error.js
  packages/app-content-pages/pages/publications.js
  packages/app-content-pages/pages/team.js
  packages/app-content-pages/sentry.client.config.js
  packages/app-content-pages/sentry.edge.config.js
  packages/app-content-pages/sentry.server.config.js
  packages/app-content-pages/server/server.js
  packages/app-content-pages/server/set-cache-headers.js
  packages/app-content-pages/server/set-cache-headers.spec.js
  packages/app-content-pages/server/set-logging.js
  packages/app-content-pages/server/set-logging.spec.js
  packages/app-content-pages/src/helpers/logger/README.md
  packages/app-content-pages/src/helpers/logger/index.js
  packages/app-content-pages/src/helpers/logger/logNodeError.js
  packages/app-content-pages/src/helpers/logger/logReactError.js
  yarn.lock
Labels: refactor, approved

#5771 Start the new root About Zooniverse page
  packages/app-content-pages/.storybook/lib/i18n.js
  packages/app-content-pages/.storybook/preview.js
  packages/app-content-pages/next-i18next.config.js
  packages/app-content-pages/pages/about.js
  packages/app-content-pages/public/locales/en/components.json
  packages/app-content-pages/public/locales/test/components.json
  packages/app-content-pages/src/screens/About/About.js
  packages/app-content-pages/src/screens/About/components/OurMission.js
  packages/app-content-pages/src/screens/Publications/components/Category/Category.js
  packages/app-content-pages/src/screens/Teams/components/Team/Team.js
  packages/app-content-pages/src/shared/components/SharedStyledComponents/SharedStyledComponents.js
Labels: enhancement, approved

#5679 Fix WorkflowMenuModal stories
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.mock.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.spec.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.stories.js
Labels: bug, approved

#5769 Create check in SubjectViewer for whether to enable InteractionLayer.
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/SeparateFramesViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js
Labels: approved

#5761 lib-user: Add project card component
  packages/lib-classifier/package.json
  packages/lib-user/package.json
  packages/lib-user/src/components/GroupStats/GroupStats.stories.js
  packages/lib-user/src/components/UserStats/components/ProfileHeader.stories.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.spec.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.stories.js
  packages/lib-user/src/components/shared/ProfileHeader/index.js
  packages/lib-user/src/components/shared/ProjectCard/ProjectCard.js
  packages/lib-user/src/components/shared/ProjectCard/ProjectCard.spec.js
  packages/lib-user/src/components/shared/ProjectCard/ProjectCard.stories.js
  packages/lib-user/src/components/shared/ProjectCard/index.js
Labels: approved

#5682 Announce current project nav in screen readers
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutNavLink/AboutNavLink.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutSidebar/AboutSidebar.js
  packages/app-project/src/shared/components/NavLink/NavLink.js
  packages/app-project/src/shared/components/NavLink/NavLink.mock.js
  packages/app-project/src/shared/components/NavLink/NavLink.spec.js
Labels: bug, accessibility, approved
