Repository zooniverse/front-end-monorepo, pull requests merged in 2023-11, with the labels that each got.

#5352 Markdownz: replace remark with markdownz
  docs/arch/README.md
  docs/arch/adr-56.md
  package.json
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-content-pages/webpack.config.js
  packages/app-project/next.config.js
  packages/app-project/package.json
  packages/app-project/webpack.config.js
  packages/app-root/package.json
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.js
  packages/lib-classifier/webpack.dev.js
  packages/lib-react-components/.storybook/lib/example.md
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/src/Markdownz/Markdownz.js
  packages/lib-react-components/src/Markdownz/Markdownz.spec.js
  packages/lib-react-components/src/Markdownz/Markdownz.stories.js
  packages/lib-react-components/src/Markdownz/helpers/storybookExamples.js
  packages/lib-react-components/src/Markdownz/lib/ping.js
  packages/lib-react-components/src/Markdownz/lib/ping.spec.js
  packages/lib-react-components/src/Markdownz/markdownGridExample.md
  yarn.lock
Labels: refactor, approved, ESM

#5577 Fix #5575, allow sticky sidebar in About page to overflow/scroll
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Teams/Teams.js
Labels: accessibility, approved

#5583 Pass the size prop to SpacedHeading's child component
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-root/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/src/SpacedHeading/SpacedHeading.js
Labels: bug, approved, ui

#5544 Fix app-project linter errors
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/app-project/src/shared/components/Stat/Stat.mock.js
  packages/app-project/src/shared/components/Stat/Stat.spec.js
Labels: bug, approved

#5590 [Security] remove markdown-it 8.4.2
  package.json
  yarn.lock
Labels: dependencies, security, approved

#5603 SubjectPicker: slugify data property names
  packages/app-project/src/shared/components/SubjectPicker/helpers/columns.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchStatuses.spec.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/fetchSubjects.js
  packages/app-project/src/shared/components/SubjectPicker/helpers/slugify.js
Labels: bug, approved

#5605 FreehandLine LineControls: Add confirm or cancel to delete.
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/LineControls/LineControls.js
  packages/lib-classifier/src/translations/en/plugins.json
Labels: approved

#5382 Add search to SimpleDropdown.
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/README.md
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.mock.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.spec.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.stories.js
  packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/SimpleDropdownTask.js
Labels: approved

#5574 Add sign-in/register to root app
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-root/next.config.mjs
  packages/app-root/package.json
  packages/app-root/src/components/PageContextProviders.js
  packages/app-root/src/components/PageHeader.js
  packages/app-root/src/helpers/index.js
  packages/app-root/src/hooks/index.js
  packages/lib-classifier/package.json
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/src/AuthModal/AuthModal.js
  packages/lib-react-components/src/AuthModal/AuthModal.spec.js
  packages/lib-react-components/src/AuthModal/AuthModal.stories.js
  packages/lib-react-components/src/AuthModal/Readme.md
  packages/lib-react-components/src/AuthModal/components/LoginForm/LoginForm.js
  packages/lib-react-components/src/AuthModal/components/LoginForm/LoginFormContainer.js
  packages/lib-react-components/src/AuthModal/components/LoginForm/components/Form/Form.js
  packages/lib-react-components/src/AuthModal/components/LoginForm/components/Form/index.js
  packages/lib-react-components/src/AuthModal/components/LoginForm/index.js
  packages/lib-react-components/src/AuthModal/components/RegisterForm/RegisterForm.js
  packages/lib-react-components/src/AuthModal/components/RegisterForm/RegisterFormContainer.js
  packages/lib-react-components/src/AuthModal/components/RegisterForm/components/Form/Form.js
  packages/lib-react-components/src/AuthModal/components/RegisterForm/components/Form/index.js
  packages/lib-react-components/src/AuthModal/components/RegisterForm/index.js
  packages/lib-react-components/src/AuthModal/index.js
  packages/lib-react-components/src/AuthModal/shared/components/FieldLabel/FieldLabel.js
  packages/lib-react-components/src/AuthModal/shared/components/FieldLabel/index.js
  packages/lib-react-components/src/AuthModal/theme.js
  packages/lib-react-components/src/helpers/fetchPanoptesUser/fetchPanoptesUser.js
  packages/lib-react-components/src/helpers/fetchPanoptesUser/index.js
  packages/lib-react-components/src/helpers/withCustomFormik/withCustomFormik.js
  packages/lib-react-components/src/hooks/Readme.md
  packages/lib-react-components/src/hooks/index.js
  packages/lib-react-components/src/hooks/usePanoptesUser.js
  packages/lib-react-components/src/hooks/useUnreadMessages.js
  packages/lib-react-components/src/hooks/useUnreadNotifications.js
  packages/lib-react-components/src/index.js
  packages/lib-react-components/src/translations/en.json
  packages/lib-react-components/src/translations/test.json
Labels: enhancement, approved

#5578 app-content-pages: Responsive styling and mobile dropdown
  packages/app-content-pages/pages/publications.js
  packages/app-content-pages/pages/team.js
  packages/app-content-pages/public/locales/en/components.json
  packages/app-content-pages/public/locales/test/components.json
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Publications/Publications.spec.js
  packages/app-content-pages/src/screens/Publications/components/Category/Category.js
  packages/app-content-pages/src/screens/Publications/components/Project/Project.js
  packages/app-content-pages/src/screens/Publications/components/Project/Project.stories.js
  packages/app-content-pages/src/screens/Publications/components/Publication/Publication.js
  packages/app-content-pages/src/screens/Publications/components/Publication/Publication.stories.js
  packages/app-content-pages/src/screens/Teams/Teams.js
  packages/app-content-pages/src/screens/Teams/Teams.spec.js
  packages/app-content-pages/src/screens/Teams/components/Person/Person.js
  packages/app-content-pages/src/screens/Teams/components/Person/components/Avatar/Avatar.js
  packages/app-content-pages/src/screens/Teams/components/Person/components/TwitterLink/TwitterLink.js
  packages/app-content-pages/src/screens/Teams/components/Team/Team.js
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.js
  packages/app-content-pages/src/shared/components/DropdownNav/DropdownNav.js
  packages/app-content-pages/src/shared/components/DropdownNav/DropdownNav.spec.js
  packages/app-content-pages/src/shared/components/DropdownNav/DropdownNav.stories.js
  packages/app-content-pages/src/shared/components/MaxWidthContent/MaxWidthContent.js
  packages/app-content-pages/src/shared/components/PageLayout/layout.js
  packages/app-content-pages/src/shared/components/SharedStyledComponents/SharedStyledComponents.js
  packages/app-content-pages/src/shared/components/Sidebar/Sidebar.js
  packages/app-content-pages/src/shared/components/Sidebar/Sidebar.spec.js
  packages/app-content-pages/test/create-global-document.js
Labels: refactor, design, approved

#5659 Lazy-load ZooHeader's and ZooFooter's user-specific navigation and admin feature
  packages/lib-react-components/src/ZooFooter/ZooFooter.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
  packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/index.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/SignedOutUserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/components/NavButton/index.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/index.js
  packages/lib-react-components/src/ZooHeader/components/UserNavigation/UserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/UserNavigation/components/NavButton/NavButton.js
  packages/lib-react-components/src/hooks/Readme.md
  packages/lib-react-components/src/hooks/index.js
  packages/lib-react-components/src/hooks/useHasMounted.js
Labels: bug, refactor

#5648 Bugfix: missing SWR package
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: bug, dependencies, approved

#5588 Background refresh project Talk recent subjects
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjectsContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/helpers/fetchRecentSubjects/fetchRecentSubjects.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/helpers/fetchRecentSubjects/fetchRecentSubjects.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/helpers/fetchRecentSubjects/fetchSubjectData.js
Labels: refactor, approved, ux

#5614 Add preview for subject with text location
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.mock.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/RecentSubjects.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/components/SubjectThumbnail/SubjectThumbnail.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/components/SubjectThumbnail/SubjectThumbnail.spec.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.mock.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.spec.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.stories.js
  packages/lib-react-components/src/Media/Media.js
  packages/lib-react-components/src/Media/Media.spec.js
  packages/lib-react-components/src/Media/Media.stories.js
  packages/lib-react-components/src/Media/components/Text/Text.js
  packages/lib-react-components/src/Media/components/Text/Text.spec.js
  packages/lib-react-components/src/Media/components/Text/index.js
  packages/lib-react-components/src/Media/components/index.js
  packages/lib-react-components/src/hooks/index.js
  packages/lib-react-components/src/hooks/useTextData.js
Labels: enhancement, approved

#5228 ContentBox: Remove enzyme and convert tests to RTL
  packages/app-project/src/shared/components/ContentBox/ContentBox.mock.js
  packages/app-project/src/shared/components/ContentBox/ContentBox.spec.js
  packages/app-project/src/shared/components/ContentBox/ContentBox.stories.js
Labels: approved, tests

#5674 Fix missing dependency in lib-react-components
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-root/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: approved

#5675 Bump @zooniverse/panoptes-js to 0.5.1
  packages/lib-panoptes-js/docs/CHANGELOG.md
  packages/lib-panoptes-js/package.json
Labels: dependencies, approved

#5658 Clean up ZooHeader defaultProps and standard horizontal padding
  packages/lib-react-components/src/ZooFooter/ZooFooter.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.spec.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.stories.js
  packages/lib-react-components/src/ZooHeader/components/MainNavList/MainNavList.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMainNavMenu/NarrowMainNavMenu.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenu/NarrowMenu.js
  packages/lib-react-components/src/ZooHeader/components/NarrowMenuNavListItem/NarrowMenuNavListItem.js
  packages/lib-react-components/src/ZooHeader/components/NavListItem/NavListItem.js
  packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/SignedInUserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/SignedInUserNavigation/index.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/SignedOutUserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/components/NavButton/index.js
  packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/index.js
  packages/lib-react-components/src/ZooHeader/components/UserMenu/UserMenu.js
  packages/lib-react-components/src/ZooHeader/components/UserMenu/UserMenu.spec.js
  packages/lib-react-components/src/ZooHeader/components/UserNavigation/UserNavigation.js
  packages/lib-react-components/src/ZooHeader/components/UserNavigation/components/NavButton/NavButton.js
  packages/lib-react-components/src/hooks/Readme.md
  packages/lib-react-components/src/hooks/index.js
  packages/lib-react-components/src/hooks/useHasMounted.js
Labels: refactor

#5264 Render the NextJS apps with Million.js
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-project/next.config.js
  packages/app-project/package.json
  packages/lib-classifier/package.json
  packages/lib-classifier/webpack.dev.js
  yarn.lock
Labels: performance

#5681 Project: Fix user.recents.toggleFavourite
  packages/app-project/stores/User/Recents/Recents.js
Labels: bug, approved

#5680 Add tabindex to content page link targets
  packages/app-content-pages/src/screens/Publications/components/Category/Category.js
  packages/app-content-pages/src/screens/Teams/components/Team/Team.js
Labels: bug, accessibility, approved
