Repository zooniverse/front-end-monorepo, pull requests merged in 2023-10, with the labels that each got.

#5342 @zooniverse/react-components: remove require
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/PrimaryButton/helpers/getGradientShade.js
  packages/lib-react-components/src/translations/i18n.js
  packages/lib-react-components/test/setup.js
Labels: refactor, approved, ESM

#5436 Replace subject placeholder with background image
  packages/app-project/src/components/Head/Head.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGImage/SVGImage.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/hooks/useSubjectImage.js
Labels: refactor, approved

#5253 FavouritesButton: Remove enzyme and convert to RTL
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.mock.js
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.spec.js
  packages/lib-react-components/src/FavouritesButton/FavouritesButton.stories.js
Labels: approved, tests

#5241 MetaToolsButton: Remove enzyme and convert to RTL
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.js
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.mock.js
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.spec.js
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.stories.js
Labels: approved, tests

#5229 NavLink: Remove enzyme and convert tests to RTL
  packages/app-project/src/shared/components/NavLink/NavLink.mock.js
  packages/app-project/src/shared/components/NavLink/NavLink.spec.js
  packages/app-project/src/shared/components/NavLink/NavLink.stories.js
Labels: approved, tests

#5447 Revert "@zooniverse/react-components: remove require"
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/translations/i18n.js
Labels: approved

#5316 Add user group stats page, user stats page, and logged-in user homepage ADRs
  docs/arch/README.md
  docs/arch/adr-51.md
  docs/arch/adr-52.md
  docs/arch/adr-53.md
Labels: documentation, approved

#5423 Introduce app-root
  bin/bootstrap.sh
  bin/bootstrap:es6.sh
  docs/arch/README.md
  docs/arch/adr-54.md
  packages/app-root/.gitignore
  packages/app-root/README.md
  packages/app-root/jsconfig.json
  packages/app-root/next.config.mjs
  packages/app-root/package.json
  packages/app-root/src/app/about/page.js
  packages/app-root/src/app/groups/page.js
  packages/app-root/src/app/layout.js
  packages/app-root/src/app/loading.js
  packages/app-root/src/app/page.js
  packages/app-root/src/app/projects/page.js
  packages/app-root/src/app/style-registry.js
  packages/app-root/src/app/users/page.js
  packages/app-root/src/components/RootLayout.js
  yarn.lock
Labels: approved

#5450 @zooniverse/react-components v1.6.4
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: bug, approved

#5411 Fix Next.js build warnings and errors
  package.json
  packages/app-content-pages/next.config.js
  packages/app-project/src/components/Head/Head.js
  yarn.lock
Labels: bug, dependencies

#5245 Build libraries with 'npm prepare'
  bin/bootstrap.sh
  packages/lib-classifier/package.json
  packages/lib-react-components/package.json
Labels: ops, dx, approved

#5431 Fix keyboard autofocus for question tasks
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/TaskInput.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/TaskInput.spec.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/components/TaskInputLabel/TaskInputLabel.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/components/TaskInputLabel/TaskInputLabel.spec.js
  packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.stories.js
  packages/lib-classifier/src/plugins/tasks/multiple/components/mockTask.js
  packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.spec.js
  packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.stories.js
  packages/lib-classifier/src/plugins/tasks/single/components/mockTask.js
Labels: bug, accessibility, refactor, approved

#5468 Remove legacy next/link components
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Teams/Teams.js
  packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.js
Labels: refactor, approved

#5494 Revert: build(deps-dev): bump sinon from 16.1.0 to 16.1.1 (#5490)
  yarn.lock
Labels: approved

#5424 lib-user: Create user library
  bin/bootstrap.sh
  bin/bootstrap:es6.sh
  docs/arch/README.md
  docs/arch/adr-51.md
  docs/arch/adr-52.md
  docs/arch/adr-53.md
  docs/arch/adr-55.md
  packages/lib-user/.babelrc
  packages/lib-user/.gitignore
  packages/lib-user/README.md
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/dev/components/App/index.js
  packages/lib-user/dev/index.html
  packages/lib-user/dev/index.js
  packages/lib-user/package.json
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/index.js
  packages/lib-user/src/components/UserStats/UserStats.js
  packages/lib-user/src/components/UserStats/index.js
  packages/lib-user/src/components/index.js
  packages/lib-user/src/hooks/index.js
  packages/lib-user/src/hooks/useGroupStats.js
  packages/lib-user/src/hooks/usePanoptesUser.js
  packages/lib-user/src/hooks/usePanoptesUserGroup.js
  packages/lib-user/src/hooks/useUserStats.js
  packages/lib-user/src/index.js
  packages/lib-user/src/utils/getBearerToken.js
  packages/lib-user/src/utils/index.js
  packages/lib-user/webpack.dev.js
Labels: approved

#5500 [Security] Ignore post-install scripts
  .github/workflows/ci-build.yml
  .github/workflows/coverage.yml
  Dockerfile
Labels: security, approved

#5492 Specify flipbook viewer ADR titles
  docs/arch/README.md
  docs/arch/adr-46.md
  docs/arch/adr-49.md
Labels: documentation, approved

#5522 Restore newrelic monitoring for app-content-pages
  packages/app-content-pages/next.config.js
  packages/app-project/next.config.js
Labels: bug, ops, approved

#5525 Refactor URLs in subject metadata
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.spec.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/components/Metadata/components/MetadataModal/MetadataModal.stories.js
Labels: refactor, approved

#5531 Bump inline Sentry to 7.75.1
  packages/app-project/pages/_document.js
Labels: dependencies, approved

#5534 Fix Not Found responses for project About pages
  packages/app-project/src/helpers/fetchProjectPage/fetchProjectPage.js
  packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.js
Labels: bug, approved

#5546 Clean up Sentry config
  packages/app-content-pages/server/server.js
  packages/app-project/server/server.js
  packages/app-project/webpack.config.test.js
Labels: dependencies, approved

#5535 Build and deploy with Node 20 (lts/iron)
  .github/workflows/ci-build.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy_storybook.yml
  Dockerfile
  README.md
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-root/package.json
  packages/lib-async-states/package.json
  packages/lib-classifier/package.json
  packages/lib-grommet-theme/CHANGELOG.md
  packages/lib-grommet-theme/package.json
  packages/lib-panoptes-js/docs/CHANGELOG.md
  packages/lib-panoptes-js/package.json
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-user/package.json
Labels: ops, approved

#5459 Add Panoptes auth to app-root
  packages/app-root/.eslintrc.json
  packages/app-root/next.config.mjs
  packages/app-root/package.json
  packages/app-root/server/server.js
  packages/app-root/src/app/about/page.js
  packages/app-root/src/app/projects/page.js
  packages/app-root/src/components/PageContextProviders.js
  packages/app-root/src/components/PageFooter.js
  packages/app-root/src/components/PageHeader.js
  packages/app-root/src/components/RootLayout.js
  packages/app-root/src/contexts/PanoptesAuthContext.js
  packages/app-root/src/contexts/index.js
  packages/app-root/src/helpers/fetchPanoptesUser.js
  packages/app-root/src/helpers/index.js
  packages/app-root/src/hooks/index.js
  packages/app-root/src/hooks/useAdminMode.js
  packages/app-root/src/hooks/usePanoptesUser.js
  packages/app-root/src/hooks/useUnreadMessages.js
  packages/app-root/src/hooks/useUnreadNotifications.js
  yarn.lock
Labels: approved

#5475 lib-user: add Grommet, zooTheme, storybook, and testing setup
  packages/lib-user/.babelrc
  packages/lib-user/.storybook/main.js
  packages/lib-user/.storybook/manager.js
  packages/lib-user/.storybook/preview.js
  packages/lib-user/.storybook/specConfig.js
  packages/lib-user/README.md
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/eslint.config.js
  packages/lib-user/package.json
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/GroupStats.spec.js
  packages/lib-user/src/components/GroupStats/GroupStats.stories.js
  packages/lib-user/src/hooks/useGroupStats.js
  packages/lib-user/src/hooks/usePanoptesUserGroup.js
  packages/lib-user/src/hooks/useUserStats.js
  packages/lib-user/test/.mocharc.json
  packages/lib-user/test/setup.js
  yarn.lock
Labels: approved

#5488 app-content-pages: Style AboutHeader and move it to a general layout.js file
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Teams/Teams.js
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.js
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.spec.js
  packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.js
  packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.spec.js
  packages/app-content-pages/src/shared/components/AboutHeader/theme.js
  packages/app-content-pages/src/shared/components/PageLayout/layout.js
  packages/app-content-pages/src/shared/components/TwoColumnLayout/TwoColumnLayout.js
Labels: refactor, design, approved

#5551 app-content-pages: Add max width and elevation elements
  packages/app-content-pages/pages/_app.js
  packages/app-content-pages/src/shared/components/PageLayout/layout.js
  packages/app-root/src/app/about/page.js
  packages/app-root/src/app/projects/page.js
Labels: design, approved

#5552 app-content-pages: Built a shared sticky side bar component
  packages/app-content-pages/pages/publications.js
  packages/app-content-pages/pages/team.js
  packages/app-content-pages/public/locales/en/components.json
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Publications/Publications.mock.json
  packages/app-content-pages/src/screens/Publications/Publications.spec.js
  packages/app-content-pages/src/screens/Publications/Publications.stories.js
  packages/app-content-pages/src/screens/Publications/PublicationsContainer.js
  packages/app-content-pages/src/screens/Publications/components/Category/Category.js
  packages/app-content-pages/src/screens/Publications/components/Project/Project.js
  packages/app-content-pages/src/screens/Publications/index.js
  packages/app-content-pages/src/screens/Teams/Teams.js
  packages/app-content-pages/src/screens/Teams/Teams.mock.json
  packages/app-content-pages/src/screens/Teams/Teams.spec.js
  packages/app-content-pages/src/screens/Teams/Teams.stories.js
  packages/app-content-pages/src/screens/Teams/TeamsContainer.js
  packages/app-content-pages/src/screens/Teams/index.js
  packages/app-content-pages/src/shared/components/PageLayout/layout.js
  packages/app-content-pages/src/shared/components/Sidebar/Sidebar.js
  packages/app-content-pages/src/shared/components/Sidebar/Sidebar.spec.js
  packages/app-content-pages/src/shared/components/Sidebar/Sidebar.stories.js
  packages/app-content-pages/src/shared/components/TwoColumnLayout/TwoColumnLayout.js
  packages/app-content-pages/src/shared/components/TwoColumnLayout/index.js
  packages/app-content-pages/test/publications.spec.js
  packages/app-content-pages/test/team.spec.js
Labels: refactor, design, approved
