Repository zooniverse/front-end-monorepo, pull requests merged in 2023-08, with the labels that each got.

#5082 Refactor daily classification counts
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.js
  packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.js
  packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.spec.js
  packages/app-project/stores/User/UserPersonalization/YourStats/YourStats.js
Labels: bug, refactor, approved

#5123 Fix docker builds
  Dockerfile
  docker-compose.yml
  packages/app-content-pages/server/server.js
  packages/app-project/server/server.js
Labels: security, ops, approved

#4959 Refactor Finished For the Day component
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.spec.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDay.stories.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/FinishedForTheDayContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.spec.js
  packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/index.js
Labels: refactor, approved

#5149 Updated design system links
  packages/lib-grommet-theme/README.md
Labels: approved

#5150 Fix for allowing multiple marks when using the FreehandLine tool conn…
  packages/lib-classifier/src/hooks/useFreehandLineReductions.js
  packages/lib-classifier/src/store/subjects/Subject/FreehandLineReductions/FreehandLineReductions.js
  packages/lib-classifier/src/store/subjects/Subject/FreehandLineReductions/FreehandLineReductions.spec.js
  packages/lib-classifier/src/store/subjects/Subject/FreehandLineReductions/mocks/reducedSubject.js
Labels: approved

#5179 Update Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request--data-store--ops--etc.md
  .github/ISSUE_TEMPLATE/feature-request--ux--ui--accessibility--design--etc.md
Labels: documentation, approved

#5080 Fixes for tests and SSR errors
  packages/app-content-pages/pages/_app.js
  packages/app-project/pages/_app.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.spec.js
Labels: refactor, approved

#5185 Add ADR template
  docs/ADR_TEMPLATE.md
Labels: documentation, approved

#5186 Mark ZRC as free of side effects
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: enhancement, performance, approved

#5140 Base 404
  packages/app-project/pages/404.js
  packages/app-project/public/assets/background1.jpg
  packages/app-project/public/assets/background2.jpg
  packages/app-project/public/assets/background3.jpg
  packages/app-project/public/assets/background4.jpg
  packages/app-project/public/assets/background5.jpg
  packages/app-project/public/assets/background6.jpg
  packages/app-project/public/assets/background7.jpg
  packages/app-project/public/assets/background8.jpg
  packages/app-project/public/assets/background9.jpg
  packages/app-project/public/assets/logoBlack404.png
  packages/app-project/public/assets/logoWhite404.png
  packages/app-project/public/locales/en/components.json
  packages/app-project/public/locales/test/components.json
Labels: approved

#5206 GenericAnnouncement: Remove enzyme and convert tests to RTL.
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/GenericAnnouncement.mock.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/GenericAnnouncement.spec.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/GenericAnnouncement.stories.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/components/NarrowGenericAnnouncement/NarrowGenericAnnouncement.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/components/NarrowGenericAnnouncement/NarrowGenericAnnouncement.spec.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/components/WideGenericAnnouncement/WideGenericAnnouncement.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/components/WideGenericAnnouncement/WideGenericAnnouncement.spec.js
Labels: approved

#5164 Refactor draggable with functional components
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.js
  packages/lib-classifier/src/plugins/drawingTools/components/draggable/draggable.spec.js
Labels: refactor, approved

#5217 Panoptes client: match project slugs more strictly
  packages/lib-panoptes-js/docs/CHANGELOG.md
  packages/lib-panoptes-js/package.json
  packages/lib-panoptes-js/src/resources/projects/commonRequests.js
  packages/lib-panoptes-js/src/resources/projects/commonRequests.spec.js
Labels: bug, approved

#5216 SubjectPreview: Remove enzyme and convert tests to RTL
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.mock.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.spec.js
  packages/app-project/src/shared/components/SubjectPreview/SubjectPreview.stories.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/CollectionsButton/CollectionsButton.stories.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkIcon.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkLink.spec.js
  packages/app-project/src/shared/components/SubjectPreview/components/TalkLink/TalkLink.stories.js
Labels: approved

#5165 Refactor SVGPanZoom
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
Labels: refactor, approved

#5210 YourStats: Remove enzyme and convert tests to RTL.
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.mock.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.spec.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStats.stories.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/YourStatsContainer.spec.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.spec.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChart.stories.js
  packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.spec.js
  packages/app-project/src/screens/ProjectAboutPage/ProjectAboutPage.spec.js
  packages/app-project/src/screens/ProjectAboutPage/components/AboutDropdownNav/AboutDropdownNav.spec.js
Labels: approved

#5057 Refactor ClassifierContainer to use snapshots and fix broken tests
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.spec.js
  packages/lib-classifier/src/store/Project/Project.js
  packages/lib-classifier/src/store/Project/Project.spec.js
Labels: refactor, approved, tests

#5231 SubjectSetPicker: Remove enzyme and convert tests to RTL
  packages/app-project/src/screens/ClassifyPage/components/WorkflowMenuModal/WorkflowMenuModal.stories.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.mock.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.spec.js
  packages/app-project/src/shared/components/SubjectSetPicker/SubjectSetPicker.stories.js
  packages/app-project/src/shared/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js
  packages/app-project/src/shared/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.spec.js
  packages/app-project/src/shared/components/SubjectSetPicker/helpers/index.js
Labels: approved

#5209 RecentSubjects: Remove enzyme and convert tests to RTL.
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/CollectionsStoreMock.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.mock.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.spec.js
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/components/SubjectThumbnail/SubjectThumbnail.js
Labels: approved

#5211 withRequireUser: Remove enzyme and convert tests to RTL
  packages/app-project/src/shared/components/withRequireUser/withRequireUser.mock.js
  packages/app-project/src/shared/components/withRequireUser/withRequireUser.spec.js
  packages/app-project/src/shared/components/withRequireUser/withRequireUser.stories.js
Labels: approved

#3887 Upgrade to React 18
  packages/app-content-pages/.storybook/preview.js
  packages/app-content-pages/package.json
  packages/app-project/.storybook/preview.js
  packages/app-project/package.json
  packages/lib-classifier/.storybook/preview.js
  packages/lib-classifier/dev/components/App/App.js
  packages/lib-classifier/dev/index.js
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/Classifier.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.js
  packages/lib-classifier/src/components/Classifier/ClassifierContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
  packages/lib-classifier/src/hooks/useHydratedStore.spec.js
  packages/lib-classifier/src/hooks/useStores.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.spec.js
  packages/lib-classifier/src/plugins/tasks/text/components/TextTask/components/TextTaskWithSuggestions/TextTaskWithSuggestions.spec.js
  packages/lib-react-components/.storybook/preview.js
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies, approved
