Repository zooniverse/front-end-monorepo, pull requests merged in 2023-05, with the labels that each got.

#4525 Classifier: add onTouch handler for Highlighter task button
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/HighlighterTask.js
Labels: bug, approved

#4524 Lokalise: Classifier Translations update
  packages/lib-classifier/src/translations/test/components.json
  packages/lib-classifier/src/translations/test/plugins.json
Labels: approved, translations

#4544 Classifier: refactor text viewer with labeled text story
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.stories.js
Labels: storybook, approved

#4503 Refactor ScatterPlot components
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/Background.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/Background/Background.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/ScatterPlotSeries/ScatterPlotPoint.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/ScatterPlotSeries/ScatterPlotSeries.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/ScatterPlotSeries/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/index.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js
  packages/lib-classifier/src/hooks/Readme.md
  packages/lib-classifier/src/hooks/index.js
  packages/lib-classifier/src/hooks/useKeyZoom.js
Labels: refactor

#4550 Remove refs from withKeyZoom
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.spec.js
Labels: refactor, approved

#4568 Restore survey task focus tests
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userKeystrokes.spec.js
Labels: refactor, approved, tests

#4482 Scatter plot viewer: add x-range selection
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/DeleteButton.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/Selection.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/Selections.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/Selections/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/index.js
  packages/lib-classifier/src/translations/en/components.json
  yarn.lock
Labels: enhancement, approved

#4538 Add a SubjectLocation type
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/hooks/useDataImageSubject.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/components/FlipbookControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/components/ImageAndTextControls.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/FrameCarousel.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/SeparateFramesViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/locationValidator/locationValidator.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/locationValidator/locationValidator.spec.js
  packages/lib-classifier/src/helpers/findLocationsByMediaType/findLocationsByMediaType.js
  packages/lib-classifier/src/helpers/findLocationsByMediaType/findLocationsByMediaType.spec.js
  packages/lib-classifier/src/helpers/findLocationsByMediaType/index.js
  packages/lib-classifier/src/helpers/index.js
  packages/lib-classifier/src/helpers/validateSubjectLocations/index.js
  packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.js
  packages/lib-classifier/src/helpers/validateSubjectLocations/validateSubjectLocations.spec.js
  packages/lib-classifier/src/hooks/useSubjectJSON.js
  packages/lib-classifier/src/hooks/useSubjectText.js
  packages/lib-classifier/src/plugins/tasks/experimental/textFromSubject/components/TextFromSubjectTask.spec.js
  packages/lib-classifier/src/store/subjects/ImageAndTextSubject/ImageAndTextSubject.spec.js
  packages/lib-classifier/src/store/subjects/ImageSubject/ImageSubject.spec.js
  packages/lib-classifier/src/store/subjects/SingleImageSubject/SingleImageSubject.spec.js
  packages/lib-classifier/src/store/subjects/SingleJSONSubject/SIngleJSONSubject.spec.js
  packages/lib-classifier/src/store/subjects/SingleTextSubject/SingleTextSubject.spec.js
  packages/lib-classifier/src/store/subjects/SingleVideoSubject/SingleVideoSubject.spec.js
  packages/lib-classifier/src/store/subjects/Subject/Subject.js
  packages/lib-classifier/src/store/subjects/Subject/Subject.spec.js
  packages/lib-classifier/src/store/subjects/Subject/SubjectLocation/SubjectLocation.js
  packages/lib-classifier/src/store/subjects/Subject/SubjectLocation/index.js
  packages/lib-classifier/src/store/subjects/TextSubject/TextSubject.spec.js
Labels: refactor, approved

#4333 lib-classifier: Add survey task instruction
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.stories.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userKeystrokes.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.js
  packages/lib-classifier/src/plugins/tasks/survey/mock-data/task.js
Labels: enhancement, approved

#4640 Run update-browserslist-db@latest
  yarn.lock
Labels: dependencies, dx, approved

#4634 lib-classifier: Refactor styling for text viewer, highlighter task selection, and TextFromSubject task
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleTextViewer/SingleTextViewer.js
  packages/lib-classifier/src/plugins/tasks/experimental/highlighter/components/components/Selection.js
  packages/lib-classifier/src/plugins/tasks/experimental/textFromSubject/components/TextFromSubjectTask.js
Labels: approved

#4638 lib-classifier: Add fallback url false to dev webpack
  packages/lib-classifier/webpack.dev.js
Labels: dx, approved

#4610 New subject viewer: JSONDataViewer
  packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js
  packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/JSONDataViewer/JSONDataViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/JSONDataViewer/JSONDataViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/JSONDataViewer/JSONDataViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/JSONDataViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/ScatterPlotViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/components/ScatterPlotSeries/ScatterPlotSeries.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/hooks/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/hooks/useScatterPlotSubject.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VariableStarViewer/VariableStarViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.spec.js
  packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.js
  packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.spec.js
  packages/lib-classifier/src/hooks/useSubjectJSON.js
  packages/lib-classifier/src/store/JSONData/BarChart.js
  packages/lib-classifier/src/store/JSONData/DataSeriesPlot.js
  packages/lib-classifier/src/store/JSONData/TESSLightCurve.js
  packages/lib-classifier/src/store/JSONData/VariableStarPlots.js
  packages/lib-classifier/src/store/JSONData/index.js
  packages/lib-classifier/src/store/JSONData/index.spec.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/WorkflowConfiguration/WorkflowConfiguration.js
  packages/lib-classifier/src/store/subjects/Subject/Subject.js
  packages/lib-classifier/src/store/subjects/Subject/Subject.spec.js
  packages/lib-classifier/test/setup.js
Labels: enhancement, approved

#4609 app-project: Fix Hero and TeamMember stories
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
Labels: storybook, approved, tests

#4639 Add the git ref to page metadata
  .github/workflows/deploy_branch.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  Dockerfile
  kubernetes/deployment-branch.tmpl
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
  packages/app-project/next.config.js
  packages/app-project/src/components/Head/Head.js
Labels: ops, approved

#4656 Use Coveralls action v2
  .github/workflows/coverage.yml
Labels: ops, approved

#4650 Remove withKeyZoom from the classifier
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/ZoomEventLayer/ZoomEventLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/ZoomEventLayer/ZoomEventLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/SubjectGroupViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/README.md
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/index.js
  packages/lib-classifier/src/components/Classifier/components/withKeyZoom/withKeyZoom.js
  packages/lib-classifier/src/hooks/useKeyZoom.spec.js
Labels: refactor, approved

#4667 Remove @zeit/next-source-maps
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-project/next.config.js
  packages/app-project/package.json
  yarn.lock
Labels: dependencies, approved

#4526 Fetch FreehandLine Tool reductions from Caesar POC.
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarksConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/index.js
  packages/lib-classifier/src/hooks/index.js
  packages/lib-classifier/src/hooks/useCaesarReductions.js
  packages/lib-classifier/src/hooks/useFreehandLineReductions.js
  packages/lib-classifier/src/hooks/useTranscriptionReductions.js
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/LineControls/LineControls.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.js
  packages/lib-classifier/src/store/subjects/Subject/FreehandLineReductions/FreehandLineReductions.js
  packages/lib-classifier/src/store/subjects/Subject/FreehandLineReductions/FreehandLineReductions.spec.js
  packages/lib-classifier/src/store/subjects/Subject/FreehandLineReductions/index.js
  packages/lib-classifier/src/store/subjects/Subject/FreehandLineReductions/mocks/index.js
  packages/lib-classifier/src/store/subjects/Subject/FreehandLineReductions/mocks/reducedSubject.js
  packages/lib-classifier/src/store/subjects/Subject/Subject.js
  packages/lib-classifier/src/store/subjects/Subject/TranscriptionReductions/TranscriptionReductions.js
Labels: approved

#4643 app-content-pages: Replace counterpart with i18next
  packages/app-content-pages/.storybook/lib/i18n.js
  packages/app-content-pages/next-i18next.config.js
  packages/app-content-pages/next.config.js
  packages/app-content-pages/package.json
  packages/app-content-pages/pages/_app.js
  packages/app-content-pages/pages/publications.js
  packages/app-content-pages/pages/team.js
  packages/app-content-pages/public/locales/README.md
  packages/app-content-pages/public/locales/en/components.json
  packages/app-content-pages/public/locales/test/components.json
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Publications/PublicationsContainer.js
  packages/app-content-pages/src/screens/Publications/locales/en.json
  packages/app-content-pages/src/screens/Team/Team.js
  packages/app-content-pages/src/screens/Team/TeamContainer.js
  packages/app-content-pages/src/screens/Team/components/Person/components/Avatar/locales/en.json
  packages/app-content-pages/src/screens/Team/locales/en.json
  packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.js
  packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/locales/en.json
  packages/app-content-pages/src/shared/components/AuthModal/components/LoginForm/LoginForm.js
  packages/app-content-pages/src/shared/components/AuthModal/components/LoginForm/LoginFormContainer.js
  packages/app-content-pages/src/shared/components/AuthModal/components/LoginForm/LoginFormContainer.spec.js
  packages/app-content-pages/src/shared/components/AuthModal/components/LoginForm/components/Form/Form.js
  packages/app-content-pages/src/shared/components/AuthModal/components/LoginForm/locales/en.json
  packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/RegisterForm.js
  packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/RegisterFormContainer.js
  packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/RegisterFormContainer.spec.js
  packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/components/Form/Form.js
  packages/app-content-pages/src/shared/components/AuthModal/components/RegisterForm/components/Form/Form.spec.js
  packages/app-content-pages/src/shared/components/Head/Head.js
  packages/app-content-pages/src/shared/components/Head/locales/en.json
  packages/app-content-pages/test/publications.spec.js
  packages/app-content-pages/test/team.spec.js
  yarn.lock
Labels: refactor, translations

#4681 lib-react-components: Refactor SpacedText prop margin when object
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/src/SpacedText/README.md
  packages/lib-react-components/src/SpacedText/SpacedText.js
  packages/lib-react-components/src/SpacedText/SpacedText.stories.js
Labels: approved

#4608 Increase popup tutorial size
  packages/lib-classifier/src/components/Classifier/components/ModalTutorial/ModalTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.spec.js
  packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorialContainer.js
Labels: refactor, approved

#4706 Remove @babel/plugin-proposal-logical-assignment-operators
  packages/lib-classifier/.babelrc
  packages/lib-classifier/package.json
  yarn.lock
Labels: dependencies, approved

#4701 app-content-pages: Add stories and RTL unit tests for AboutHeader
  packages/app-content-pages/.storybook/lib/i18n.js
  packages/app-content-pages/.storybook/main.js
  packages/app-content-pages/.storybook/preview.js
  packages/app-content-pages/public/locales/en/components.json
  packages/app-content-pages/public/locales/test/components.json
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.js
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.spec.js
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.stories.js
  packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.js
  packages/app-content-pages/src/shared/components/AboutHeader/components/NavLink/NavLink.spec.js
  packages/app-content-pages/src/shared/components/TwoColumnLayout/TwoColumnLayout.js
  packages/app-content-pages/src/shared/components/TwoColumnLayout/TwoColumnLayout.spec.js
Labels: storybook, approved, tests

#4736 Classifier: preserve pending classifications
  packages/lib-classifier/src/store/Classification/Classification.js
  packages/lib-classifier/src/store/Classification/Classification.spec.js
  packages/lib-classifier/src/store/utils/ClassificationQueue.js
  packages/lib-classifier/src/store/utils/ClassificationQueue.spec.js
Labels: bug, refactor

#4741 Classifier: updated Readme for store utils
  packages/lib-classifier/src/store/utils/README.md
Labels: documentation, approved

#4661 Transcription task: RTL tests
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/ConsensusPopup/ConsensusPopup.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/components/TooltipIcon/TooltipIcon.spec.js
Labels: approved, tests
