Repository zooniverse/front-end-monorepo, pull requests merged in 2024-07, with the labels that each got.

#6141 lib-user: Refactor usePanoptesMemberships hook and createMembership with useSWRMutation
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/components/GroupUpdateFormContainer/GroupUpdateFormContainer.js
  packages/lib-user/src/components/GroupStats/components/MembersList/MembersListContainer.js
  packages/lib-user/src/components/GroupStats/helpers/getHeaderItems.js
  packages/lib-user/src/components/shared/GroupContainer/GroupContainer.js
  packages/lib-user/src/components/shared/GroupContainer/helpers/getUserGroupStatus.js
  packages/lib-user/src/components/shared/GroupContainer/helpers/getUserGroupStatus.spec.js
  packages/lib-user/src/hooks/usePanoptesMemberships.js
  packages/lib-user/src/hooks/usePanoptesUserGroup.js
  packages/lib-user/src/utils/createPanoptesMembership.js
Labels: approved

#6139 lib-user: Add responsive design for user stats and group stats
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/components/TopContributors/TopContributors.js
  packages/lib-user/src/components/MyGroups/components/GroupCard/GroupCard.js
  packages/lib-user/src/components/MyGroups/components/PreviewLayout/PreviewLayout.js
  packages/lib-user/src/components/UserHome/UserHome.js
  packages/lib-user/src/components/shared/ContentBox/ContentBox.js
  packages/lib-user/src/components/shared/MainContent/MainContent.js
  packages/lib-user/src/components/shared/MainContent/MainContent.stories.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.js
  packages/lib-user/src/components/shared/Select/Select.js
  packages/lib-user/src/components/shared/Select/theme.js
  packages/lib-user/src/components/shared/Tabs/Tabs.js
  packages/lib-user/src/components/shared/Tabs/Tabs.spec.js
  packages/lib-user/src/components/shared/Tabs/Tabs.stories.js
  packages/lib-user/src/components/shared/Tabs/index.js
  packages/lib-user/src/components/shared/Tabs/theme.js
  packages/lib-user/src/components/shared/index.js
  packages/lib-user/src/index.js
Labels: approved

#6149 Homepages: Use Community component in both DefaultHome and UserHome
  packages/app-root/src/components/HomePageContainer.js
  packages/lib-content/src/screens/Home/Community/Community.js
  packages/lib-content/src/screens/Home/Community/CommunityContainer.js
  packages/lib-content/src/screens/Home/Community/blogPosts.mock.json
  packages/lib-content/src/screens/Home/DefaultHome/DefaultHome.js
  packages/lib-content/src/screens/Home/DefaultHome/DefaultHome.stories.js
  packages/lib-user/src/components/UserHome/UserHome.js
Labels: bug, approved

#6157 lib-user: Fix BarChart console error, conditionally define gradient per data
  packages/lib-user/src/components/shared/BarChart/BarChart.js
Labels: approved

#6160 app-root, lib-user: Use url search param for stats date range and project state
  packages/app-root/src/app/groups/[groupId]/GroupStatsContainer.js
  packages/app-root/src/app/groups/[groupId]/page.js
  packages/app-root/src/app/users/[login]/stats/UserStatsContainer.js
  packages/app-root/src/app/users/[login]/stats/certificate/CertificateContainer.js
  packages/app-root/src/app/users/[login]/stats/certificate/page.js
  packages/app-root/src/app/users/[login]/stats/layout.js
  packages/app-root/src/app/users/[login]/stats/page.js
  packages/app-root/src/components/UserStatsContextProvider.js
  packages/app-root/src/contexts/UserStatsContext.js
  packages/app-root/src/contexts/index.js
  packages/app-root/src/hooks/index.js
  packages/app-root/src/hooks/useStatsDateRange.js
  packages/app-root/src/hooks/useStatsProject.js
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/dev/index.js
  packages/lib-user/src/components/Certificate/Certificate.js
  packages/lib-user/src/components/Certificate/Certificate.stories.js
  packages/lib-user/src/components/Certificate/CertificateContainer.js
  packages/lib-user/src/components/Certificate/helpers/formatDateRange.js
  packages/lib-user/src/components/Certificate/helpers/formatDateRange.spec.js
  packages/lib-user/src/components/Contributors/helpers/generateExport.spec.js
  packages/lib-user/src/components/Contributors/helpers/getExportData.spec.js
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/GroupStatsContainer.js
  packages/lib-user/src/components/GroupStats/helpers/getHeaderItems.js
  packages/lib-user/src/components/UserHome/components/Dashboard/components/StatsTabs/StatsTabsContainer.js
  packages/lib-user/src/components/UserStats/UserStats.js
  packages/lib-user/src/components/UserStats/UserStatsContainer.js
  packages/lib-user/src/components/shared/BarChart/BarChart.js
  packages/lib-user/src/components/shared/BarChart/BarChart.spec.js
  packages/lib-user/src/components/shared/BarChart/BarChart.stories.js
  packages/lib-user/src/components/shared/BarChart/helpers/getCompleteData.js
  packages/lib-user/src/components/shared/BarChart/helpers/getDateRangeLabel.js
  packages/lib-user/src/components/shared/BarChart/helpers/getDateRangeLabel.spec.js
  packages/lib-user/src/components/shared/MainContent/MainContent.js
  packages/lib-user/src/components/shared/MainContent/MainContent.spec.js
  packages/lib-user/src/components/shared/MainContent/MainContent.stories.js
  packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.js
  packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.spec.js
  packages/lib-user/src/components/shared/Select/Select.spec.js
  packages/lib-user/src/components/shared/Select/Select.stories.js
  packages/lib-user/src/index.js
  packages/lib-user/src/utils/convertStatsSecondsToHours.spec.js
  packages/lib-user/src/utils/dateRanges.js
  packages/lib-user/src/utils/dateRanges.spec.js
  packages/lib-user/src/utils/getDateInterval.js
  packages/lib-user/src/utils/getDateInterval.spec.js
  packages/lib-user/src/utils/index.js
Labels: approved

#6163 Bug fix: groups roles on logged-in homepage
  packages/lib-user/src/components/MyGroups/components/PreviewLayout/PreviewLayout.js
Labels: bug, approved

#6156 Build the user homepage welcome modal
  packages/lib-user/src/components/UserHome/UserHome.js
  packages/lib-user/src/components/UserHome/components/Dashboard/Dashboard.js
  packages/lib-user/src/components/UserHome/components/WelcomeModal/README.md
  packages/lib-user/src/components/UserHome/components/WelcomeModal/WelcomeModal.js
  packages/lib-user/src/components/UserHome/components/WelcomeModal/WelcomeModal.stories.js
Labels: approved

#6145 lib-user: Certificate, change link label, center name, fix font color on dark mode print
  packages/lib-user/src/components/Certificate/Certificate.js
Labels: approved

#6172 Community section styling updates
  packages/lib-content/src/components/Article/Article.js
  packages/lib-content/src/screens/Home/Community/Community.js
Labels: design, approved

#6165 app-root: Add Loader to full pages
  packages/app-root/src/app/groups/[groupId]/GroupStatsContainer.js
  packages/app-root/src/app/groups/[groupId]/contributors/GroupContributorsContainer.js
  packages/app-root/src/app/loading.js
  packages/app-root/src/components/AuthenticatedUsersPageContainer.js
Labels: enhancement, approved

#6169 lib-user: Add Pagination component to MyGroups and MembersList
  packages/lib-user/src/components/GroupStats/components/MembersList/MembersList.js
  packages/lib-user/src/components/GroupStats/components/MembersList/MembersListContainer.js
  packages/lib-user/src/components/MyGroups/MyGroupsContainer.js
  packages/lib-user/src/components/MyGroups/components/PreviewLayout/PreviewLayout.js
  packages/lib-user/src/components/shared/GroupModal/GroupModal.stories.js
  packages/lib-user/src/components/shared/Pagination/Pagination.js
  packages/lib-user/src/components/shared/Pagination/index.js
  packages/lib-user/src/components/shared/Pagination/theme.js
  packages/lib-user/src/components/shared/index.js
  packages/lib-user/src/index.js
Labels: approved

#6173 Quick fix for 404 page links
  packages/app-project/pages/404.js
  packages/lib-content/src/screens/404/Default404.js
Labels: bug, approved

#6170 lib-user: Refactor Contributors with Pagination, data export with all users
  packages/lib-user/package.json
  packages/lib-user/src/components/Contributors/Contributors.js
  packages/lib-user/src/components/Contributors/components/ContributorsList/ContributorsList.js
  packages/lib-user/src/components/Contributors/helpers/generateExport.js
  packages/lib-user/src/components/Contributors/helpers/generateExport.spec.js
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/hooks/index.js
  packages/lib-user/src/hooks/usePanoptesUser.js
  packages/lib-user/src/hooks/usePanoptesUsers.js
  packages/lib-user/src/index.js
  packages/lib-user/src/utils/fetchPanoptesUsers.js
  packages/lib-user/src/utils/index.js
Labels: approved

#6166 Logged-out Homepage Hero copy update
  packages/app-root/public/assets/home-video-placeholder.jpg
  packages/lib-content/src/components/Mobile/Mobile.js
  packages/lib-content/src/screens/Home/DefaultHome/DefaultHome.js
  packages/lib-content/src/screens/Home/DefaultHome/components/Hero.js
  packages/lib-content/src/screens/Home/DefaultHome/components/Introduction.js
  packages/lib-content/src/translations/en.json
Labels: design, approved

#6179 Logged-in Homepage styling updates
  packages/lib-content/src/screens/Home/Community/Community.js
  packages/lib-user/src/components/UserHome/UserHome.js
  packages/lib-user/src/components/UserHome/components/Dashboard/Dashboard.js
  packages/lib-user/src/components/UserHome/components/Dashboard/components/DashboardLink.js
  packages/lib-user/src/components/UserHome/components/Dashboard/components/StatsTabs/StatsTabs.js
  packages/lib-user/src/components/UserHome/components/Dashboard/components/StatsTabs/tabsTheme.js
  packages/lib-user/src/components/UserHome/components/UserHomeLayout/README.md
  packages/lib-user/src/components/UserHome/components/UserHomeLayout/UserHomeLayout.js
  packages/lib-user/src/components/UserHome/components/WelcomeModal/WelcomeModal.js
Labels: design, approved

#6180 Quick fix for signed-in homepage mobile layout
  packages/lib-user/src/components/UserHome/components/Dashboard/Dashboard.js
  packages/lib-user/src/components/UserHome/components/Dashboard/components/DashboardLink.js
  packages/lib-user/src/components/UserHome/components/UserHomeLayout/UserHomeLayout.js
Labels: bug

#6186 lib-user: Add getDateRangeSelectOptions tests before and after UTC
  packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.js
  packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.spec.js
Labels: approved
