Repository zooniverse/front-end-monorepo, pull requests merged in 2024-04, with the labels that each got.

#5989 lib-user: Refactor MyGroups with GroupCards
  packages/lib-user/src/components/MyGroups/MyGroups.js
  packages/lib-user/src/components/MyGroups/MyGroups.stories.js
  packages/lib-user/src/components/MyGroups/MyGroupsContainer.js
  packages/lib-user/src/components/MyGroups/components/GroupCard.js
  packages/lib-user/src/components/MyGroups/components/GroupCard/GroupCard.js
  packages/lib-user/src/components/MyGroups/components/GroupCard/GroupCard.mock.js
  packages/lib-user/src/components/MyGroups/components/GroupCard/GroupCard.spec.js
  packages/lib-user/src/components/MyGroups/components/GroupCard/GroupCard.stories.js
  packages/lib-user/src/components/MyGroups/components/GroupCard/GroupCardContainer.js
  packages/lib-user/src/components/MyGroups/components/GroupCard/index.js
  packages/lib-user/src/components/MyGroups/components/GroupCardList/GroupCardList.js
  packages/lib-user/src/components/MyGroups/components/GroupCardList/index.js
  packages/lib-user/src/components/UserStats/components/MainContent/MainContent.spec.js
  packages/lib-user/src/components/UserStats/components/MainContent/MainContent.stories.js
  packages/lib-user/src/components/UserStats/components/TopProjects/TopProjects.spec.js
  packages/lib-user/src/components/UserStats/components/TopProjects/TopProjects.stories.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.spec.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.stories.js
  packages/lib-user/src/components/shared/TitledStat/TitledStat.js
  packages/lib-user/test/mocks/panoptes/index.js
  packages/lib-user/test/mocks/panoptes/memberships.js
  packages/lib-user/test/mocks/panoptes/projects.js
  packages/lib-user/test/mocks/panoptes/user_groups.js
  packages/lib-user/test/mocks/panoptes/users.js
Labels: approved

#6016 Handle partial translated project-specific translation strings
  packages/app-project/src/helpers/fetchTranslations/fetchTranslations.js
  packages/lib-classifier/src/hooks/usePanoptesTranslations.js
Labels: bug, approved, translations

#5992 lib-user: Refactor dev App to use PJC auth client
  packages/lib-user/dev/components/App/App.js
Labels: approved

#6009 lib-user: Add group create modal
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/Modal/Modal.js
  packages/lib-react-components/src/Modal/README.md
  packages/lib-react-components/src/Modal/components/ModalBody/ModalBody.js
  packages/lib-user/package.json
  packages/lib-user/src/components/MyGroups/CreateGroup.js
  packages/lib-user/src/components/MyGroups/MyGroups.js
  packages/lib-user/src/components/MyGroups/MyGroups.stories.js
  packages/lib-user/src/components/MyGroups/MyGroupsContainer.js
  packages/lib-user/src/components/MyGroups/components/CreateButton/AddIcon.js
  packages/lib-user/src/components/MyGroups/components/CreateButton/CreateButton.js
  packages/lib-user/src/components/MyGroups/components/CreateButton/CreateButton.stories.js
  packages/lib-user/src/components/MyGroups/components/CreateButton/index.js
  packages/lib-user/src/components/MyGroups/components/GroupCard/GroupCard.stories.js
  packages/lib-user/src/components/MyGroups/components/GroupForm/GroupForm.js
  packages/lib-user/src/components/MyGroups/components/GroupForm/GroupForm.spec.js
  packages/lib-user/src/components/MyGroups/components/GroupForm/GroupForm.stories.js
  packages/lib-user/src/components/MyGroups/components/GroupForm/GroupFormContainer.js
  packages/lib-user/src/components/MyGroups/components/GroupForm/index.js
  packages/lib-user/src/components/MyGroups/components/GroupModal/GroupModal.js
  packages/lib-user/src/components/MyGroups/components/GroupModal/GroupModal.stories.js
  packages/lib-user/src/components/MyGroups/components/GroupModal/index.js
  yarn.lock
Labels: approved

#6014 lib-user: Refactor GroupStats with existing MainContent, ContentBox, and ProjectCard components
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/GroupStatsContainer.js
  packages/lib-user/src/components/UserStats/UserStats.js
  packages/lib-user/src/components/UserStats/components/MainContent/index.js
  packages/lib-user/src/components/shared/Layout/Layout.js
  packages/lib-user/src/components/shared/MainContent/MainContent.js
  packages/lib-user/src/components/shared/MainContent/MainContent.spec.js
  packages/lib-user/src/components/shared/MainContent/MainContent.stories.js
  packages/lib-user/src/components/shared/MainContent/index.js
  packages/lib-user/src/components/shared/index.js
  packages/lib-user/src/utils/getDateInterval.js
Labels: approved

#6020 Remove @fortawesome and use grommet-icons in ZooHeader
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/src/ZooHeader/components/UserNavigation/UserNavigation.js
  yarn.lock
Labels: refactor, approved

#5963 Update YourStats to callout to Eras instead of Zoo-stats-graphql
  packages/app-project/stores/User/Recents/Recents.spec.js
  packages/app-project/stores/User/User.spec.js
  packages/app-project/stores/User/UserPersonalization/Notifications/Notifications.spec.js
  packages/app-project/stores/User/UserPersonalization/UserPersonalization.spec.js
  packages/app-project/stores/User/UserPersonalization/UserProjectPreferences/UserProjectPreferences.spec.js
  packages/app-project/stores/User/UserPersonalization/YourStats/YourStats.js
  packages/app-project/stores/User/UserPersonalization/YourStats/YourStats.spec.js
  packages/app-project/test/create-global-document.js
Labels: approved

#6030 Pass ProjectCard component a size prop
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/UserStats/components/TopProjects/TopProjects.js
  packages/lib-user/src/components/shared/ContentBox/ContentBox.stories.js
  packages/lib-user/src/components/shared/ProjectCard/ProjectCard.js
  packages/lib-user/src/components/shared/ProjectCard/ProjectCard.spec.js
  packages/lib-user/src/components/shared/ProjectCard/ProjectCard.stories.js
Labels: refactor, approved

#6032 Add app-root / fe-root to GitHub Actions workflows and kubernetes staging deployment
  .github/workflows/ci-build.yml
  .github/workflows/coverage.yml
  kubernetes/deployment-staging.tmpl
Labels: ops, approved

#6046 Refactor app-root probes path
  kubernetes/deployment-staging.tmpl
  packages/app-root/server/server.js
Labels: ops, approved

#6044 Move ProjectCard to lib-react-components
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/ProjectCard/ProjectCard.js
  packages/lib-react-components/src/ProjectCard/ProjectCard.spec.js
  packages/lib-react-components/src/ProjectCard/ProjectCard.stories.js
  packages/lib-react-components/src/ProjectCard/README.md
  packages/lib-react-components/src/ProjectCard/index.js
  packages/lib-react-components/src/index.js
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/UserStats/components/TopProjects/TopProjects.js
  packages/lib-user/src/components/shared/ContentBox/ContentBox.stories.js
  packages/lib-user/src/components/shared/ProjectCard/ProjectCard.stories.js
  packages/lib-user/src/components/shared/index.js
  packages/lib-user/src/index.js
Labels: refactor, approved

#6051 Make sure the array of points gets added for a closed path
  packages/lib-classifier/src/plugins/drawingTools/experimental/models/marks/FreehandLine/FreehandLine.js
Labels: approved

#6054 Add lib-content to the Dockerfile
  Dockerfile
Labels: ops, approved

#4436 Classifier: change Annotate Button icon to "edit/pencil"
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/AnnotateButton.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/EditIcon.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/AnnotateButton/PointerIcon.js
Labels: design, approved, ui

#6045 Move root About Zooniverse page to lib-content
  packages/app-root/public/assets/adler.png
  packages/app-root/public/assets/app-store.png
  packages/app-root/public/assets/exoplanet.jpg
  packages/app-root/public/assets/google-play.png
  packages/app-root/public/assets/green-pea.jpg
  packages/app-root/public/assets/into-the-zooniverse1.jpg
  packages/app-root/public/assets/into-the-zooniverse2.png
  packages/app-root/public/assets/into-the-zooniverse3.jpg
  packages/app-root/public/assets/minnesota.png
  packages/app-root/public/assets/oxford.jpg
  packages/app-root/public/assets/phone.png
  packages/app-root/public/assets/star.jpg
  packages/app-root/public/assets/transcription.jpg
  packages/app-root/src/app/about/page.js
  packages/lib-content/src/components/HorizontalRuleLogo/HorizontalRuleLogo.js
  packages/lib-content/src/components/HorizontalRuleLogo/HorizontalRuleLogo.stories.js
  packages/lib-content/src/components/Mobile/Mobile.js
  packages/lib-content/src/components/Mobile/Mobile.stories.js
  packages/lib-content/src/components/Stats/Stats.js
  packages/lib-content/src/components/Stats/Stats.stories.js
  packages/lib-content/src/components/Stats/hooks.js
  packages/lib-content/src/index.js
  packages/lib-content/src/screens/About/About.js
  packages/lib-content/src/screens/About/About.stories.js
  packages/lib-content/src/screens/About/components/Contact.js
  packages/lib-content/src/screens/About/components/Highlights.js
  packages/lib-content/src/screens/About/components/HowItWorks.js
  packages/lib-content/src/screens/About/components/OurMission.js
  packages/lib-content/src/screens/About/components/SubHeading.js
Labels: refactor, approved

#6042 Move Resources and FAQ pages into lib-content
  packages/app-root/public/assets/adler.png
  packages/app-root/public/assets/app-store.png
  packages/app-root/public/assets/brand-links-four.png
  packages/app-root/public/assets/brand-links-three.png
  packages/app-root/public/assets/brand-links-two.png
  packages/app-root/public/assets/exoplanet.jpg
  packages/app-root/public/assets/google-play.png
  packages/app-root/public/assets/green-pea.jpg
  packages/app-root/public/assets/into-the-zooniverse1.jpg
  packages/app-root/public/assets/into-the-zooniverse2.png
  packages/app-root/public/assets/into-the-zooniverse3.jpg
  packages/app-root/public/assets/minnesota.png
  packages/app-root/public/assets/oxford.jpg
  packages/app-root/public/assets/phone.png
  packages/app-root/public/assets/star.jpg
  packages/app-root/public/assets/transcription.jpg
  packages/app-root/src/app/about/faq/page.js
  packages/app-root/src/app/about/page.js
  packages/app-root/src/app/about/resources/page.js
  packages/app-root/src/app/layout.js
  packages/lib-content/src/components/AboutHeader/AboutHeader.js
  packages/lib-content/src/components/AboutHeader/components/NavLink/NavLink.js
  packages/lib-content/src/components/HorizontalRuleLogo/HorizontalRuleLogo.js
  packages/lib-content/src/components/HorizontalRuleLogo/HorizontalRuleLogo.stories.js
  packages/lib-content/src/components/Mobile/Mobile.js
  packages/lib-content/src/components/Mobile/Mobile.stories.js
  packages/lib-content/src/components/Stats/Stats.js
  packages/lib-content/src/components/Stats/Stats.stories.js
  packages/lib-content/src/components/Stats/hooks.js
  packages/lib-content/src/index.js
  packages/lib-content/src/screens/About/About.js
  packages/lib-content/src/screens/About/About.stories.js
  packages/lib-content/src/screens/About/components/Contact.js
  packages/lib-content/src/screens/About/components/Highlights.js
  packages/lib-content/src/screens/About/components/HowItWorks.js
  packages/lib-content/src/screens/About/components/OurMission.js
  packages/lib-content/src/screens/About/components/SubHeading.js
  packages/lib-content/src/screens/FAQ/FAQ.js
  packages/lib-content/src/screens/FAQ/FAQ.stories.js
  packages/lib-content/src/screens/Resources/Resources.js
  packages/lib-content/src/screens/Resources/Resources.stories.js
  packages/lib-content/src/translations/README.md
  packages/lib-content/src/translations/i18n.js
  packages/lib-react-components/src/translations/i18n.js
Labels: refactor, approved
