Repository zooniverse/front-end-monorepo, pull requests merged in 2024-03, with the labels that each got.

#5254 CloseButton: Remove enzyme and convert to RTL
  packages/lib-react-components/src/CloseButton/CloseButton.spec.js
  packages/lib-react-components/src/CloseButton/CloseButton.stories.js
Labels: approved, tests

#5227 ConnectWithProject: Remove enzyme and convert tests to RTL
  packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.js
  packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.mock.js
  packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.spec.js
  packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.stories.js
  packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProjectContainer.spec.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/ProjectLink.spec.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/components/BitbucketIcon/BitbucketIcon.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/components/WeiboIcon/WeiboIcon.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/helpers/formatUrlObject/formatUrlObject.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/helpers/formatUrlObject/formatUrlObject.spec.js
Labels: approved, tests

#5952 Use local state for Flipbook Viewer's frame to avoid MST re-renders
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
Labels: bug, high priority, approved

#5935 Content Pages: Build root About page's highlights and mobile sections
  packages/app-content-pages/public/assets/app-store.png
  packages/app-content-pages/public/assets/google-play.png
  packages/app-content-pages/public/assets/into-the-zooniverse1.jpg
  packages/app-content-pages/public/assets/into-the-zooniverse2.png
  packages/app-content-pages/public/assets/into-the-zooniverse3.jpg
  packages/app-content-pages/public/assets/phone.png
  packages/app-content-pages/public/locales/en/components.json
  packages/app-content-pages/src/screens/About/About.js
  packages/app-content-pages/src/screens/About/components/Highlights.js
  packages/app-content-pages/src/screens/About/components/HowItWorks.js
  packages/app-content-pages/src/screens/About/components/Mobile.js
Labels: enhancement, approved

#5956 Bump lib-react-components to v1.12.0
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-root/package.json
  packages/lib-classifier/package.json
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
Labels: dependencies, approved

#5936 lib-user: Add TopProjects section, refactor imports
  packages/app-root/package.json
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/dev/index.js
  packages/lib-user/package.json
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/MyGroups/MyGroups.js
  packages/lib-user/src/components/UserStats/UserStats.js
  packages/lib-user/src/components/UserStats/components/MainContent/MainContent.js
  packages/lib-user/src/components/UserStats/components/MainContent/MainContent.spec.js
  packages/lib-user/src/components/UserStats/components/MainContent/MainContent.stories.js
  packages/lib-user/src/components/UserStats/components/MainContent/index.js
  packages/lib-user/src/components/UserStats/components/TopProjects/TopProjects.js
  packages/lib-user/src/components/UserStats/components/TopProjects/TopProjects.spec.js
  packages/lib-user/src/components/UserStats/components/TopProjects/TopProjects.stories.js
  packages/lib-user/src/components/UserStats/components/TopProjects/index.js
  packages/lib-user/src/components/index.js
  packages/lib-user/src/components/shared/BarChart/BarChart.stories.js
  packages/lib-user/src/components/shared/BarChart/index.js
  packages/lib-user/src/components/shared/ContentBox/index.js
  packages/lib-user/src/components/shared/Layout/index.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.stories.js
  packages/lib-user/src/components/shared/ProfileHeader/index.js
  packages/lib-user/src/components/shared/ProjectCard/ProjectCard.spec.js
  packages/lib-user/src/components/shared/ProjectCard/ProjectCard.stories.js
  packages/lib-user/src/components/shared/ProjectCard/index.js
  packages/lib-user/src/components/shared/Select/index.js
  packages/lib-user/src/components/shared/Tabs/index.js
  packages/lib-user/src/components/shared/index.js
  packages/lib-user/src/hooks/index.js
  packages/lib-user/src/hooks/useGroupStats.js
  packages/lib-user/src/hooks/usePanoptesAuth.js
  packages/lib-user/src/hooks/usePanoptesMemberships.js
  packages/lib-user/src/hooks/usePanoptesProjects.js
  packages/lib-user/src/hooks/usePanoptesUser.js
  packages/lib-user/src/hooks/usePanoptesUserGroup.js
  packages/lib-user/src/hooks/useUserStats.js
  packages/lib-user/src/index.js
  packages/lib-user/src/utils/createPanoptesUserGroup.js
  packages/lib-user/src/utils/dateRanges.js
  packages/lib-user/src/utils/dateRanges.spec.js
  packages/lib-user/src/utils/deletePanoptesUserGroup.js
  packages/lib-user/src/utils/getBearerToken.js
  packages/lib-user/src/utils/getBearerToken.spec.js
  packages/lib-user/src/utils/getDateInterval.js
  packages/lib-user/src/utils/getDateInterval.spec.js
  packages/lib-user/src/utils/index.js
  packages/lib-user/src/utils/updatePanoptesUserGroup.js
  packages/lib-user/test/mocks/panoptes.mock.js
  packages/lib-user/test/mocks/stats.mock.js
Labels: approved

#5943 lib-user: Add GroupCard
  packages/lib-user/src/components/MyGroups/components/GroupCard.js
  packages/lib-user/src/components/MyGroups/components/GroupCard.mock.js
  packages/lib-user/src/components/MyGroups/components/GroupCard.spec.js
  packages/lib-user/src/components/MyGroups/components/GroupCard.stories.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.js
  packages/lib-user/src/components/shared/TitledStat/TitledStat.js
  packages/lib-user/src/components/shared/TitledStat/TitledStat.spec.js
  packages/lib-user/src/components/shared/TitledStat/TitledStat.stories.js
  packages/lib-user/src/components/shared/TitledStat/index.js
Labels: approved

#5974 Animated Number bug fix - handle update of value prop
  packages/lib-react-components/src/AnimatedNumber/AnimatedNumber.js
  packages/lib-react-components/src/AnimatedNumber/AnimatedNumber.stories.js
Labels: bug, approved

#5948 lib-user: Add usePanoptesAuthUser, refactor related hooks and components
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/index.js
  packages/lib-user/src/components/MyGroups/MyGroups.js
  packages/lib-user/src/components/MyGroups/helpers/getActiveGroupsWithRoles.js
  packages/lib-user/src/components/MyGroups/helpers/getActiveGroupsWithRoles.spec.js
  packages/lib-user/src/components/MyGroups/index.js
  packages/lib-user/src/components/UserStats/UserStats.js
  packages/lib-user/src/components/UserStats/index.js
  packages/lib-user/src/components/shared/index.js
  packages/lib-user/src/hooks/index.js
  packages/lib-user/src/hooks/useGroupStats.js
  packages/lib-user/src/hooks/usePanoptesAuth.js
  packages/lib-user/src/hooks/usePanoptesAuthUser.js
  packages/lib-user/src/hooks/usePanoptesMemberships.js
  packages/lib-user/src/hooks/usePanoptesUser.js
  packages/lib-user/src/hooks/usePanoptesUserGroup.js
  packages/lib-user/src/hooks/useStats.js
  packages/lib-user/src/index.js
  packages/lib-user/src/utils/getBearerToken.js
  packages/lib-user/src/utils/getBearerToken.spec.js
Labels: approved

#5980 app-root: Add login param as prop to lib-user UserStats and MyGroups components
  packages/app-root/src/app/users/[login]/groups/page.js
  packages/app-root/src/app/users/[login]/stats/page.js
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/src/components/MyGroups/MyGroups.js
  packages/lib-user/src/components/UserStats/UserStats.js
Labels: approved

#5987 AnimatedNumber : Fix missing dependency and handling of prefers reduced motion
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-react-components/src/AnimatedNumber/AnimatedNumber.js
Labels: bug, approved

#5950 Build the Zooniverse Works section with stats in root About Page
  packages/app-content-pages/public/assets/exoplanet.jpg
  packages/app-content-pages/public/assets/green-pea.jpg
  packages/app-content-pages/public/assets/star.jpg
  packages/app-content-pages/public/assets/transcription.jpg
  packages/app-content-pages/public/locales/en/components.json
  packages/app-content-pages/src/screens/About/About.js
  packages/app-content-pages/src/screens/About/components/OurMission.js
  packages/app-content-pages/src/screens/About/components/Stats/Stats.js
  packages/app-content-pages/src/screens/About/components/Stats/Stats.stories.js
  packages/app-content-pages/src/screens/About/components/Stats/hooks.js
Labels: enhancement, approved

#5984 Content Pages: Use Intersection Observer for sidebar nav
  packages/app-content-pages/src/screens/About/About.js
  packages/app-content-pages/src/screens/About/components/AboutLogo.js
  packages/app-content-pages/src/screens/About/components/Contact.js
  packages/app-content-pages/src/screens/About/components/Highlights.js
  packages/app-content-pages/src/screens/About/components/HowItWorks.js
  packages/app-content-pages/src/screens/About/components/Mobile.js
  packages/app-content-pages/src/screens/About/components/OurMission.js
  packages/app-content-pages/src/screens/About/components/Stats/Stats.js
  packages/app-content-pages/src/screens/FAQ/FAQ.js
  packages/app-content-pages/src/screens/Publications/Publications.js
  packages/app-content-pages/src/screens/Publications/components/Category/Category.js
  packages/app-content-pages/src/screens/Publications/components/Project/Project.js
  packages/app-content-pages/src/screens/Resources/Resources.js
  packages/app-content-pages/src/screens/Teams/Teams.js
  packages/app-content-pages/src/screens/Teams/components/Team/Team.js
  packages/app-content-pages/src/shared/components/AboutHeader/AboutHeader.js
  packages/app-content-pages/src/shared/components/DropdownNav/DropdownNav.js
  packages/app-content-pages/src/shared/components/DropdownNav/DropdownNav.stories.js
  packages/app-content-pages/src/shared/components/HeadingForAboutNav/HeadingForAboutNav.js
  packages/app-content-pages/src/shared/components/SharedStyledComponents/SharedStyledComponents.js
  packages/app-content-pages/src/shared/components/Sidebar/Sidebar.js
  packages/app-content-pages/src/shared/components/Sidebar/Sidebar.stories.js
  packages/app-content-pages/test/create-global-document.js
Labels: enhancement, approved

#5985 lib-user: Refactor UseStats, MyGroups, and GroupStats with containers
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/GroupStatsContainer.js
  packages/lib-user/src/components/GroupStats/index.js
  packages/lib-user/src/components/MyGroups/MyGroups.js
  packages/lib-user/src/components/MyGroups/MyGroupsContainer.js
  packages/lib-user/src/components/MyGroups/index.js
  packages/lib-user/src/components/UserStats/UserStats.js
  packages/lib-user/src/components/UserStats/UserStatsContainer.js
  packages/lib-user/src/components/UserStats/index.js
Labels: approved
