Repository zooniverse/front-end-monorepo, pull requests merged in 2024-09, with the labels that each got.

#6227 AuthModal: style register form as one column for small widths
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/AuthModal/components/RegisterForm/components/Form/Form.js
Labels: accessibility, approved

#6256 lib-user: Add DeactivatedGroup component for active membership with deactivated group
  packages/lib-user/src/components/shared/GroupContainer/GroupContainer.js
  packages/lib-user/src/components/shared/GroupContainer/components/DeactivatedGroup.js
Labels: approved

#6242 Create `lib-subject-viewers` & make importable for `lib-classifier`
  .github/workflows/ci-build.yml
  .github/workflows/coverage.yml
  Dockerfile
  bin/bootstrap.sh
  bin/bootstrap:es6.sh
  packages/lib-classifier/package.json
  packages/lib-subject-viewers/.babelrc
  packages/lib-subject-viewers/.gitignore
  packages/lib-subject-viewers/.storybook/main.js
  packages/lib-subject-viewers/.storybook/manager.js
  packages/lib-subject-viewers/.storybook/preview.js
  packages/lib-subject-viewers/.storybook/specConfig.js
  packages/lib-subject-viewers/LICENSE
  packages/lib-subject-viewers/README.md
  packages/lib-subject-viewers/package.json
  packages/lib-subject-viewers/src/components/ProtoViewer/ProtoViewer.js
  packages/lib-subject-viewers/src/components/ProtoViewer/ProtoViewer.spec.js
  packages/lib-subject-viewers/src/components/ProtoViewer/ProtoViewer.stories.js
  packages/lib-subject-viewers/src/components/ProtoViewer/README.md
  packages/lib-subject-viewers/src/index.js
  packages/lib-subject-viewers/test/.mocharc.json
  packages/lib-subject-viewers/test/setup.js
Labels: approved

#6262 Use absolute urls for static image assets
  packages/app-project/pages/404.js
  packages/app-project/public/assets/README.md
  packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.js
  packages/app-project/src/screens/ProjectHomePage/components/MessageFromResearcher/MessageFromResearcher.mock.js
  packages/app-project/src/shared/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js
  packages/app-root/public/assets/README.md
  packages/app-root/src/app/about/team/response.mock.json
  packages/lib-classifier/src/components/Classifier/components/Banners/components/AlreadySeenBanner/AlreadySeenBanner.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/RetiredBanner/RetiredBanner.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/SubjectSetProgressBanner/SubjectSetProgressBanner.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/UserHasFinishedWorkflowBanner/UserHasFinishedWorkflowBanner.stories.js
  packages/lib-classifier/src/components/Classifier/components/Banners/components/WorkflowIsFinishedBanner/WorkflowIsFinishedBanner.stories.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/Comment.spec.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/UserAvatar.js
  packages/lib-classifier/src/components/Classifier/components/QuickTalk/components/UserAvatar.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
  packages/lib-content/src/components/Mobile/Mobile.js
  packages/lib-content/src/screens/404/Default404.js
  packages/lib-content/src/screens/About/components/Highlights.js
  packages/lib-content/src/screens/About/components/HowItWorks.js
  packages/lib-content/src/screens/About/components/OurMission.js
  packages/lib-content/src/screens/Collaborate/Logos.js
  packages/lib-content/src/screens/Donate/Donate.js
  packages/lib-content/src/screens/Educate/Educate.js
  packages/lib-content/src/screens/Home/DefaultHome/components/Hero.js
  packages/lib-content/src/screens/Resources/Resources.js
  packages/lib-panoptes-js/src/resources/subjects/helpers.js
  packages/lib-panoptes-js/src/resources/subjects/mocks.js
  packages/lib-react-components/src/Markdownz/helpers/storybookExamples.js
  packages/lib-react-components/src/Markdownz/helpers/testExamples.js
  packages/lib-react-components/src/Markdownz/markdownGridExample.md
  packages/lib-react-components/src/Media/Media.stories.js
  packages/lib-react-components/src/Media/components/Video/Video.spec.js
  packages/lib-user/src/components/Certificate/Certificate.js
  packages/lib-user/src/components/Contributors/components/MemberStats/MemberStats.js
  packages/lib-user/src/components/GroupStats/components/MemberCard/MemberCard.js
  packages/lib-user/src/components/UserHome/components/Dashboard/Dashboard.js
Labels: approved

#6270 Update platform-wide classification and user count offsets
  packages/app-content-pages/src/screens/About/components/Stats/Stats.js
  packages/lib-content/src/components/Stats/Stats.js
Labels: approved

#6267 lib-classifier: Fix survey task Confusion drop positioning
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/ConfusedWith.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/components/Confusion.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/Characteristics/components/CharacteristicSection.js
  packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.js
Labels: approved

#6273 Add fe-root resources to production k8s template
  kubernetes/deployment-production.tmpl
Labels: approved

#6225 Update ZooFooter links to reflect new FEM pages
  packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.mock.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/helpers/formatUrlObject/formatUrlObject.js
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/ZooFooter/ZooFooter.js
  packages/lib-react-components/src/ZooFooter/ZooFooter.spec.js
  packages/lib-react-components/src/ZooFooter/components/SocialAnchor/SocialAnchor.js
  packages/lib-react-components/src/translations/cs.json
  packages/lib-react-components/src/translations/de.json
  packages/lib-react-components/src/translations/en.json
  packages/lib-react-components/src/translations/es.json
  packages/lib-react-components/src/translations/fr.json
  packages/lib-react-components/src/translations/hr.json
  packages/lib-react-components/src/translations/it.json
  packages/lib-react-components/src/translations/pt.json
  packages/lib-react-components/src/translations/ru.json
  packages/lib-react-components/src/translations/sv.json
  packages/lib-react-components/src/translations/test.json
  packages/lib-react-components/src/translations/tr.json
  packages/lib-react-components/src/translations/ur.json
Labels: approved

#6274 Retry revalidating wordpress fetch every hour
  packages/app-root/src/app/page.js
Labels: approved

#6281 Update publications page metadata
  packages/app-root/src/app/about/publications/page.js
Labels: approved

#6303 app-root: Add morgan for logging on production server
  packages/app-root/package.json
  packages/app-root/server/server.js
  yarn.lock
Labels: approved

#6291 app-project: Refactor Announcement banners styling and remove artsy/fresnel
  packages/app-project/package.json
  packages/app-project/pages/_app.js
  packages/app-project/pages/_document.js
  packages/app-project/src/components/Announcements/components/FinishedAnnouncement/FinishedAnnouncementConnector.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/GenericAnnouncement.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/GenericAnnouncement.mock.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/GenericAnnouncement.spec.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/GenericAnnouncement.stories.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/README.md
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/components/NarrowGenericAnnouncement/NarrowGenericAnnouncement.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/components/NarrowGenericAnnouncement/index.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/components/WideGenericAnnouncement/WideGenericAnnouncement.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/components/WideGenericAnnouncement/index.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/helpers/markdownzComponents/index.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/markdownzComponents.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncement.stories.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncementConnector.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/Hero/Hero.stories.js
  packages/app-project/src/shared/components/Media/Media.js
  packages/app-project/src/shared/components/Media/README.md
  packages/app-project/src/shared/components/Media/index.js
  yarn.lock
Labels: approved

#6306 lib-content: Remove integrity hash from contact widget
  packages/lib-content/src/screens/About/About.js
Labels: bug, approved

#6304 Reveal links to user stats + groups blog post
  packages/lib-content/src/screens/Educate/Educate.js
  packages/lib-content/src/screens/FAQ/FAQ.js
  packages/lib-content/src/translations/en.json
  packages/lib-user/src/components/MyGroups/MyGroupsContainer.js
  packages/lib-user/src/components/MyGroups/components/PreviewLayout/PreviewLayout.js
Labels: approved

#6309 lib-user: Fix default page positioning for Certificate save or print
  packages/lib-user/src/components/Certificate/Certificate.js
Labels: approved

#6310 Add favicon files to app-root and app-project
  packages/app-project/public/assets/apple-icon.png
  packages/app-project/public/assets/favicon.ico
  packages/app-project/public/assets/icon.svg
  packages/app-project/src/components/Head/Head.js
  packages/app-root/public/apple-icon.png
  packages/app-root/public/favicon.ico
  packages/app-root/public/icon.svg
  packages/app-root/src/app/layout.js
Labels: approved

#6308 app-project: Announcements markdown direction
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/GenericAnnouncement.js
  packages/app-project/src/components/Announcements/components/GenericAnnouncement/markdownzComponents.js
  packages/app-project/src/components/Announcements/components/ProjectAnnouncement/ProjectAnnouncement.stories.js
Labels: design, approved

#6317 lib-user: Refactor TopProjects with up to 20 items
  packages/lib-user/src/components/shared/TopProjects/TopProjects.js
  packages/lib-user/src/components/shared/TopProjects/TopProjects.stories.js
  packages/lib-user/test/mocks/panoptes/projects.js
  packages/lib-user/test/mocks/stats.mock.js
Labels: approved

#6311 Remove fe-content-pages from ci builds and deployment
  .github/workflows/ci-build.yml
  Dockerfile
  bin/bootstrap.sh
  bin/bootstrap:es6.sh
  docker-compose.yml
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
Labels: ops, approved

#6325 Homepage: Remove filter logic from Recent Projects section
  packages/lib-react-components/src/ProjectCard/ProjectCard.js
  packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjects.js
  packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjectsContainer.js
Labels: approved

#6321 lib-user: Refactor MainContent total projects and bar chart projects select
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/UserStats/UserStats.js
  packages/lib-user/src/components/shared/MainContent/MainContent.js
  packages/lib-user/src/components/shared/MainContent/helpers/getProjectSelectOptions.js
Labels: approved

#6326 lib-user: Add classification count to ProjectCard badge in TopProjects
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/ProjectCard/ProjectCard.js
  packages/lib-react-components/src/ProjectCard/ProjectCard.stories.js
  packages/lib-user/src/components/shared/TopProjects/TopProjects.js
Labels: approved

#6318 app-project: Refactor JoinInButton without next/link
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/ZooniverseTalk.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/ZooniverseTalk.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButton.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButton.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButton.stories.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButtonContainer.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/JoinInButtonContainer.spec.js
  packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/JoinInButton/index.js
Labels: approved

#6320 app-project: Refactor NavLink to handle internal vs external route
  packages/app-project/src/components/ProjectHeader/ProjectHeader.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
  packages/app-project/src/components/ProjectHeader/hooks/useProjectNavigation.js
  packages/app-project/src/screens/ProjectAboutPage/components/TeamMember/TeamMember.js
  packages/app-project/src/shared/components/ContentBox/README.md
  packages/app-project/src/shared/components/NavLink/NavLink.js
  packages/app-project/src/shared/components/NavLink/NavLink.spec.js
  packages/app-project/src/shared/components/NavLink/NavLink.stories.js
  packages/app-project/src/shared/components/ProjectStatistics/ProjectStatisticsContainer.js
Labels: approved

#6297 Refactor classifier layout per survey task
  packages/lib-classifier/src/components/Classifier/components/Layout/Layout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.stories.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.stories.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.stories.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.js
  packages/lib-classifier/src/store/WorkflowStore/Workflow/Workflow.spec.js
Labels: approved

#6339 Styling adjustments for Tabs and AuthModal
  packages/lib-classifier/src/plugins/tasks/multiple/components/MultipleChoiceTask.js
  packages/lib-classifier/src/plugins/tasks/single/components/SingleChoiceTask.js
  packages/lib-react-components/src/AuthModal/AuthModal.js
  packages/lib-react-components/src/Modal/Modal.js
  packages/lib-react-components/src/Tabs/Tabs.stories.js
  packages/lib-react-components/src/Tabs/theme.js
Labels: approved

#6342 app-project: add /projects to useProjectNavigation external links
  packages/app-project/src/components/ProjectHeader/ProjectHeader.spec.js
  packages/app-project/src/components/ProjectHeader/components/DropdownNav/DropdownNav.spec.js
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.spec.js
  packages/app-project/src/components/ProjectHeader/hooks/useProjectNavigation.js
Labels: bug, approved

#6340 app-root: Remove stub routes
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
  packages/app-root/src/app/groups/page.js
  packages/app-root/src/app/projects/page.js
  packages/app-root/src/app/robots.txt
  packages/app-root/src/app/users/[login]/page.js
  packages/app-root/src/app/users/page.js
Labels: approved
