Repository zooniverse/front-end-monorepo, pull requests merged in 2024-05, with the labels that each got.

#6050 [2 of 2] Remove defaultProps from MetaToolsButton and refactor Tooltip's Stories and specs
  packages/lib-react-components/src/AuthModal/components/RegisterForm/RegisterForm.js
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.js
  packages/lib-react-components/src/MetaToolsButton/MetaToolsButton.stories.js
  packages/lib-react-components/src/Modal/components/ModalHeading/ModalHeading.js
  packages/lib-react-components/src/MovableModal/components/ResizeIcon/ResizeIcon.js
  packages/lib-react-components/src/Tooltip/Tooltip.spec.js
  packages/lib-react-components/src/Tooltip/Tooltip.stories.js
  packages/lib-react-components/src/Tooltip/components/Label/Label.js
  packages/lib-react-components/src/Tooltip/components/Label/Label.spec.js
  packages/lib-react-components/src/Tooltip/components/Label/Label.stories.js
  packages/lib-react-components/src/Tooltip/components/Triangle/Triangle.js
  packages/lib-react-components/src/Tooltip/components/Triangle/Triangle.spec.js
  packages/lib-react-components/src/Tooltip/components/Triangle/Triangle.stories.js
Labels: refactor, approved

#6075 lib-user: Add MemberCard
  packages/lib-user/src/components/GroupStats/components/MemberCard/MemberCard.js
  packages/lib-user/src/components/GroupStats/components/MemberCard/MemberCard.spec.js
  packages/lib-user/src/components/GroupStats/components/MemberCard/MemberCard.stories.js
  packages/lib-user/src/components/GroupStats/components/MemberCard/index.js
  packages/lib-user/src/components/shared/Avatar/Avatar.js
  packages/lib-user/src/components/shared/Avatar/index.js
  packages/lib-user/src/components/shared/ContentBox/ContentBox.stories.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.spec.js
  packages/lib-user/src/components/shared/index.js
  packages/lib-user/src/index.js
  packages/lib-user/test/mocks/panoptes/index.js
  packages/lib-user/test/mocks/panoptes/users.js
Labels: approved

#6052 lib-user: Add HeaderLink, HeaderToast, and refactor Layout
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/SpacedText/SpacedText.js
  packages/lib-user/package.json
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/GroupStatsContainer.js
  packages/lib-user/src/components/MyGroups/components/CreateButton/AddIcon.js
  packages/lib-user/src/components/MyGroups/components/CreateButton/CreateButton.js
  packages/lib-user/src/components/MyGroups/components/GroupCard/GroupCard.js
  packages/lib-user/src/components/UserStats/UserStats.js
  packages/lib-user/src/components/shared/HeaderButton/HeaderButton.js
  packages/lib-user/src/components/shared/HeaderButton/index.js
  packages/lib-user/src/components/shared/HeaderLink/HeaderLink.js
  packages/lib-user/src/components/shared/HeaderLink/HeaderLink.spec.js
  packages/lib-user/src/components/shared/HeaderLink/HeaderLink.stories.js
  packages/lib-user/src/components/shared/HeaderLink/index.js
  packages/lib-user/src/components/shared/HeaderToast/HeaderToast.js
  packages/lib-user/src/components/shared/HeaderToast/HeaderToast.spec.js
  packages/lib-user/src/components/shared/HeaderToast/HeaderToast.stories.js
  packages/lib-user/src/components/shared/HeaderToast/index.js
  packages/lib-user/src/components/shared/Layout/Layout.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.js
  packages/lib-user/src/components/shared/Select/Select.spec.js
  packages/lib-user/src/components/shared/index.js
  packages/lib-user/test/setup.js
Labels: approved

#6069 lib-user: Refactor GroupStats for user, group, and join states
  packages/app-root/src/app/groups/[groupId]/page.js
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/dev/index.js
  packages/lib-user/package.json
  packages/lib-user/src/components/GroupStats/EditGroup.js
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/GroupStatsContainer.js
  packages/lib-user/src/components/GroupStats/helpers/getUserGroupStatus.js
  packages/lib-user/src/components/GroupStats/helpers/getUserGroupStatus.spec.js
  packages/lib-user/src/components/MyGroups/components/GroupForm/GroupFormContainer.js
  packages/lib-user/src/hooks/usePanoptesMemberships.js
  packages/lib-user/src/hooks/usePanoptesUserGroup.js
  packages/lib-user/src/index.js
  packages/lib-user/src/utils/createPanoptesMembership.js
  packages/lib-user/src/utils/createPanoptesUserGroup.js
  packages/lib-user/src/utils/index.js
  packages/lib-user/src/utils/updatePanoptesUserGroup.js
Labels: approved

#6081 app-root: Fix group join issue
  packages/app-root/src/app/groups/[groupId]/GroupStatsContainer.js
  packages/lib-user/src/components/GroupStats/GroupStatsContainer.js
Labels: bug, approved

#6078 Move components for Our Team and Publications pages to lib-content
  packages/app-root/README.md
  packages/app-root/package.json
  packages/app-root/src/app/about/publications/page.js
  packages/app-root/src/app/about/publications/processPublicationData.js
  packages/app-root/src/app/about/publications/response.mock.json
  packages/app-root/src/app/about/team/page.js
  packages/app-root/src/app/about/team/processTeamData.js
  packages/app-root/src/app/about/team/response.mock.json
  packages/app-root/src/utils/contentfulClient.js
  packages/lib-content/src/index.js
  packages/lib-content/src/screens/OurTeam/OurTeam.js
  packages/lib-content/src/screens/OurTeam/OurTeam.spec.js
  packages/lib-content/src/screens/OurTeam/OurTeam.stories.js
  packages/lib-content/src/screens/OurTeam/components/Institution/Institution.js
  packages/lib-content/src/screens/OurTeam/components/Institution/Institution.spec.js
  packages/lib-content/src/screens/OurTeam/components/Institution/Institution.stories.js
  packages/lib-content/src/screens/OurTeam/components/Institution/index.js
  packages/lib-content/src/screens/OurTeam/components/Person/Person.js
  packages/lib-content/src/screens/OurTeam/components/Person/Person.spec.js
  packages/lib-content/src/screens/OurTeam/components/Person/Person.stories.js
  packages/lib-content/src/screens/OurTeam/components/Person/components/Avatar/Avatar.js
  packages/lib-content/src/screens/OurTeam/components/Person/components/Avatar/index.js
  packages/lib-content/src/screens/OurTeam/components/Person/components/TwitterLink/TwitterLink.js
  packages/lib-content/src/screens/OurTeam/components/Person/components/TwitterLink/index.js
  packages/lib-content/src/screens/OurTeam/components/Person/index.js
  packages/lib-content/src/screens/OurTeam/teamData.mock.json
  packages/lib-content/src/screens/Publications/Publications.js
  packages/lib-content/src/screens/Publications/Publications.spec.js
  packages/lib-content/src/screens/Publications/Publications.stories.js
  packages/lib-content/src/screens/Publications/components/Discipline/Discipline.js
  packages/lib-content/src/screens/Publications/components/Discipline/Discipline.spec.js
  packages/lib-content/src/screens/Publications/components/Discipline/Discipline.stories.js
  packages/lib-content/src/screens/Publications/components/Project/Project.js
  packages/lib-content/src/screens/Publications/components/Project/Project.spec.js
  packages/lib-content/src/screens/Publications/components/Project/Project.stories.js
  packages/lib-content/src/screens/Publications/components/Publication/Publication.js
  packages/lib-content/src/screens/Publications/components/Publication/Publication.spec.js
  packages/lib-content/src/screens/Publications/components/Publication/Publication.stories.js
  packages/lib-content/src/screens/Publications/publicationsData.mock.json
  packages/lib-content/src/translations/en.json
  yarn.lock
Labels: refactor, approved

#6082 lib-user: List top contributors in GroupStats
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/components/MemberCard/MemberCard.js
  packages/lib-user/src/hooks/usePanoptesMemberships.js
  packages/lib-user/src/hooks/usePanoptesProjects.js
  packages/lib-user/src/hooks/usePanoptesUser.js
  packages/lib-user/src/hooks/usePanoptesUserGroup.js
  packages/lib-user/src/hooks/useStats.js
Labels: approved

#6089 Handle homepage UI based on signed-in user or no user
  packages/app-root/src/app/page.js
  packages/app-root/src/components/HomePageContainer.js
Labels: enhancement, approved

#6090 Move Loader component to lib-react-components
  packages/app-project/package.json
  packages/app-project/public/locales/ar/components.json
  packages/app-project/public/locales/cs/components.json
  packages/app-project/public/locales/de/components.json
  packages/app-project/public/locales/en/components.json
  packages/app-project/public/locales/es/components.json
  packages/app-project/public/locales/fr/components.json
  packages/app-project/public/locales/he/components.json
  packages/app-project/public/locales/hi/components.json
  packages/app-project/public/locales/hr/components.json
  packages/app-project/public/locales/it/components.json
  packages/app-project/public/locales/ja/components.json
  packages/app-project/public/locales/nl/components.json
  packages/app-project/public/locales/pt/components.json
  packages/app-project/public/locales/ru/components.json
  packages/app-project/public/locales/sv/components.json
  packages/app-project/public/locales/test/components.json
  packages/app-project/public/locales/tr/components.json
  packages/app-project/public/locales/ur/components.json
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
  packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.spec.js
  packages/app-project/src/shared/components/Loader/Loader.js
  packages/app-project/src/shared/components/Loader/Loader.spec.js
  packages/app-project/src/shared/components/Loader/Loader.stories.js
  packages/app-project/src/shared/components/Loader/README.md
  packages/app-project/src/shared/components/WorkflowSelector/WorkflowSelector.js
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/Loader/Loader.js
  packages/lib-react-components/src/Loader/Loader.spec.js
  packages/lib-react-components/src/Loader/Loader.stories.js
  packages/lib-react-components/src/Loader/README.md
  packages/lib-react-components/src/Loader/index.js
  packages/lib-react-components/src/index.js
  packages/lib-react-components/src/translations/ar.json
  packages/lib-react-components/src/translations/cs.json
  packages/lib-react-components/src/translations/de.json
  packages/lib-react-components/src/translations/en.json
  packages/lib-react-components/src/translations/es.json
  packages/lib-react-components/src/translations/fr.json
  packages/lib-react-components/src/translations/he.json
  packages/lib-react-components/src/translations/hi.json
  packages/lib-react-components/src/translations/hr.json
  packages/lib-react-components/src/translations/it.json
  packages/lib-react-components/src/translations/ja.json
  packages/lib-react-components/src/translations/nl.json
  packages/lib-react-components/src/translations/pt.json
  packages/lib-react-components/src/translations/ru.json
  packages/lib-react-components/src/translations/sv.json
  packages/lib-react-components/src/translations/test.json
  packages/lib-react-components/src/translations/tr.json
  packages/lib-react-components/src/translations/ur.json
  yarn.lock
Labels: refactor, approved

#6099 Add Contentful keys to fe-root env
  kubernetes/deployment-staging.tmpl
Labels: approved

#6097 Bump lib-react-components to 1.13.0
  packages/app-content-pages/package.json
  packages/app-project/package.json
  packages/app-root/package.json
  packages/lib-classifier/package.json
  packages/lib-content/package.json
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/package.json
  packages/lib-user/package.json
Labels: dependencies, approved

#6096 Build the Community section for new homepages
  packages/app-project/package.json
  packages/app-root/src/app/page.js
  packages/app-root/src/components/HomePageContainer.js
  packages/lib-content/package.json
  packages/lib-content/src/components/Article/Article.js
  packages/lib-content/src/components/Article/Article.stories.js
  packages/lib-content/src/components/HeadingForAboutNav/SubHeading.js
  packages/lib-content/src/index.js
  packages/lib-content/src/screens/About/About.js
  packages/lib-content/src/screens/Home/Community/Community.js
  packages/lib-content/src/screens/Home/Community/Community.stories.js
  packages/lib-content/src/screens/Home/Community/CommunityContainer.js
  packages/lib-content/src/screens/Home/Community/dailyZooPosts.mock.json
  packages/lib-content/src/screens/Home/Community/index.js
  packages/lib-content/src/screens/Home/Community/zooBlogPosts.mock.json
  packages/lib-content/src/translations/en.json
  yarn.lock
Labels: enhancement, approved

#6095 lib-user: refactor group stats page header items and content per group, user, and membership
  packages/app-root/src/app/groups/[groupId]/GroupStatsContainer.js
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/src/components/GroupStats/DeleteGroup.js
  packages/lib-user/src/components/GroupStats/EditGroup.js
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/GroupStatsContainer.js
  packages/lib-user/src/components/GroupStats/components/TopContributors/TopContributors.js
  packages/lib-user/src/components/GroupStats/components/TopContributors/TopContributors.spec.js
  packages/lib-user/src/components/GroupStats/components/TopContributors/TopContributors.stories.js
  packages/lib-user/src/components/GroupStats/components/TopContributors/index.js
  packages/lib-user/src/components/GroupStats/helpers/getHeaderItems.js
  packages/lib-user/src/components/GroupStats/helpers/getHeaderItems.spec.js
  packages/lib-user/src/components/MyGroups/MyGroupsContainer.js
  packages/lib-user/src/components/MyGroups/components/GroupCardList/GroupCardList.js
  packages/lib-user/src/components/UserStats/UserStats.js
  packages/lib-user/src/components/UserStats/components/TopProjects/TopProjects.js
  packages/lib-user/src/components/shared/BarChart/BarChart.js
  packages/lib-user/src/components/shared/ContentBox/ContentBox.stories.js
  packages/lib-user/src/components/shared/Layout/Layout.js
  packages/lib-user/src/components/shared/MainContent/MainContent.js
  packages/lib-user/src/components/shared/MainContent/MainContent.stories.js
  packages/lib-user/src/components/shared/TopProjects/TopProjects.js
  packages/lib-user/src/components/shared/TopProjects/TopProjects.spec.js
  packages/lib-user/src/components/shared/TopProjects/TopProjects.stories.js
  packages/lib-user/src/components/shared/TopProjects/index.js
  packages/lib-user/src/components/shared/index.js
  packages/lib-user/src/hooks/usePanoptesUserGroup.js
  packages/lib-user/src/index.js
  packages/lib-user/src/utils/deletePanoptesMembership.js
  packages/lib-user/src/utils/deletePanoptesUserGroup.js
  packages/lib-user/src/utils/index.js
  packages/lib-user/src/utils/updatePanoptesUserGroup.js
  packages/lib-user/test/mocks/panoptes/memberships.js
  packages/lib-user/test/mocks/panoptes/users.js
  packages/lib-user/test/mocks/stats.mock.js
Labels: approved

#6104 Classifier: use Text for field guide anchors
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuide/components/FieldGuideItemAnchor/FieldGuideItemAnchor.spec.js
Labels: design, approved

#6103 Make the classifier's subject viewer sticky
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.js
  packages/lib-classifier/src/components/Classifier/components/Layout/helpers/getLayout/getLayout.js
Labels: enhancement, approved

#6109 Update breakpoints and brand documentation in lib-grommet-theme
  packages/lib-grommet-theme/src/index.js
Labels: documentation, approved
