Repository zooniverse/front-end-monorepo, pull requests merged in 2024-08, with the labels that each got.

#6175 lib-user: Refactor convertStatsSecondsToHours to include one decimal place
  packages/lib-user/src/components/Certificate/Certificate.stories.js
  packages/lib-user/src/components/Contributors/components/ContributorsList/ContributorsList.spec.js
  packages/lib-user/src/components/Contributors/components/MemberStats/MemberStats.js
  packages/lib-user/src/components/Contributors/components/ProjectStats/ProjectStats.js
  packages/lib-user/src/components/Contributors/helpers/getExportData.spec.js
  packages/lib-user/src/components/GroupStats/components/MemberCard/MemberCard.js
  packages/lib-user/src/components/shared/BarChart/BarChart.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.spec.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.stories.js
  packages/lib-user/src/components/shared/TitledStat/TitledStat.js
  packages/lib-user/src/utils/convertStatsSecondsToHours.js
  packages/lib-user/src/utils/convertStatsSecondsToHours.spec.js
Labels: approved

#6176 lib-user: Refactor BarChart and getCompleteData to show x-axis labels as intended
  packages/lib-user/src/components/shared/BarChart/BarChart.js
  packages/lib-user/src/components/shared/BarChart/BarChart.spec.js
  packages/lib-user/src/components/shared/BarChart/BarChart.stories.js
  packages/lib-user/src/components/shared/BarChart/helpers/getCompleteData.js
  packages/lib-user/src/components/shared/BarChart/helpers/getCompleteData.spec.js
Labels: approved

#6161 lib-user: Add stats custom date range with Calendar
  packages/app-root/src/app/groups/[groupId]/GroupStatsContainer.js
  packages/app-root/src/app/users/[login]/stats/UserStatsContainer.js
  packages/app-root/src/app/users/[login]/stats/certificate/CertificateContainer.js
  packages/lib-user/src/components/Certificate/Certificate.stories.js
  packages/lib-user/src/components/UserHome/components/Dashboard/components/StatsTabs/StatsTabsContainer.js
  packages/lib-user/src/components/shared/MainContent/MainContent.js
  packages/lib-user/src/components/shared/MainContent/MainContent.spec.js
  packages/lib-user/src/components/shared/MainContent/MainContent.stories.js
  packages/lib-user/src/components/shared/MainContent/components/StyledCalendarButton.js
  packages/lib-user/src/components/shared/MainContent/components/StyledCertificateButton.js
  packages/lib-user/src/components/shared/MainContent/components/StyledTab.js
  packages/lib-user/src/components/shared/MainContent/components/index.js
  packages/lib-user/src/components/shared/MainContent/helpers/formatSelectOptionDateLabel.js
  packages/lib-user/src/components/shared/MainContent/helpers/formatSelectOptionDateLabel.spec.js
  packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.js
  packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.spec.js
  packages/lib-user/src/components/shared/MainContent/helpers/getProjectSelectOptions.js
  packages/lib-user/src/components/shared/MainContent/helpers/index.js
  packages/lib-user/src/components/shared/Select/Select.spec.js
  packages/lib-user/src/components/shared/Select/Select.stories.js
  packages/lib-user/src/index.js
  packages/lib-user/src/utils/getDateInterval.js
  packages/lib-user/src/utils/getStatsDateString.js
  packages/lib-user/src/utils/getStatsDateString.spec.js
  packages/lib-user/src/utils/index.js
Labels: approved

#6174 Underline PlainButton on link hover
  packages/lib-react-components/CHANGELOG.md
  packages/lib-react-components/src/PlainButton/PlainButton.js
Labels: design, approved

#6196 Fix homepage dashboard links and minor logged-out copy update
  packages/lib-content/src/translations/en.json
  packages/lib-react-components/src/PlainButton/PlainButton.js
  packages/lib-user/src/components/UserHome/components/Dashboard/components/DashboardLink.js
Labels: approved

#6195 lib-user: Add MainContent tooltip about hours stats calculation
  packages/lib-user/src/components/shared/MainContent/MainContent.js
Labels: approved

#6191 lib-user: Refactor Certificate with credited_name and info Tip
  packages/lib-user/src/components/Certificate/Certificate.js
  packages/lib-user/src/components/Certificate/Certificate.stories.js
  packages/lib-user/src/components/Certificate/CertificateContainer.js
  packages/lib-user/src/components/UserStats/UserStatsContainer.js
  packages/lib-user/src/components/shared/Tip/Tip.js
  packages/lib-user/src/hooks/usePanoptesUser.js
Labels: approved

#6197 User stats and groups styling updates
  packages/lib-user/src/components/MyGroups/MyGroups.js
  packages/lib-user/src/components/UserHome/UserHome.js
  packages/lib-user/src/components/shared/GroupForm/GroupForm.js
  packages/lib-user/src/components/shared/GroupModal/GroupModal.js
  packages/lib-user/src/components/shared/Layout/components/PageHeader.js
  packages/lib-user/src/components/shared/MainContent/MainContent.js
  packages/lib-user/src/components/shared/MainContent/components/StyledTab.js
  packages/lib-user/src/components/shared/ProfileHeader/ProfileHeader.js
Labels: approved

#6200 Homepages: Adjust mobile styling of Article in Community section
  packages/app-root/src/app/page.js
  packages/lib-content/src/components/Article/Article.js
Labels: bug, approved

#6201 Refactor Workflow Select Buttons for leveling up retirement bug
  packages/app-project/src/hooks/useAssignedLevel.js
  packages/app-project/src/screens/ClassifyPage/ClassifyPageContainer.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/LevelingUpButtons.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.js
  packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButtons/WorkflowSelectButtons.spec.js
Labels: bug, approved

#6215 app-root: Remove revalidate param from home page
  packages/app-root/src/app/page.js
Labels: approved

#6204 lib-user: Add max character group name validation to group form
  packages/lib-user/src/components/shared/GroupForm/GroupForm.js
  packages/lib-user/src/components/shared/GroupForm/GroupForm.spec.js
Labels: approved

#6205 Get Involved pages navigation
  packages/app-root/src/app/get-involved/collaborate/page.js
  packages/app-root/src/app/get-involved/donate/page.js
  packages/app-root/src/app/get-involved/educate/page.js
  packages/app-root/src/app/get-involved/volunteer/page.js
  packages/lib-content/src/components/AboutHeader/AboutHeader.js
  packages/lib-content/src/components/AboutHeader/AboutHeader.stories.js
  packages/lib-content/src/components/PageLayout/AboutLayout.js
  packages/lib-content/src/components/PageLayout/GetInvolvedLayout.js
  packages/lib-content/src/index.js
  packages/lib-content/src/screens/About/About.stories.js
  packages/lib-content/src/screens/Collaborate/Collaborate.js
  packages/lib-content/src/screens/Collaborate/Collaborate.stories.js
  packages/lib-content/src/screens/Donate/Donate.js
  packages/lib-content/src/screens/Donate/Donate.stories.js
  packages/lib-content/src/screens/Educate/Educate.js
  packages/lib-content/src/screens/Educate/Educate.stories.js
  packages/lib-content/src/screens/FAQ/FAQ.stories.js
  packages/lib-content/src/screens/Home/Community/Community.stories.js
  packages/lib-content/src/screens/Home/DefaultHome/DefaultHome.stories.js
  packages/lib-content/src/screens/Home/DefaultHome/components/FeaturedProjects.stories.js
  packages/lib-content/src/screens/OurTeam/OurTeam.stories.js
  packages/lib-content/src/screens/OurTeam/components/Institution/Institution.stories.js
  packages/lib-content/src/screens/OurTeam/components/Person/Person.stories.js
  packages/lib-content/src/screens/Publications/Publications.stories.js
  packages/lib-content/src/screens/Publications/components/Discipline/Discipline.stories.js
  packages/lib-content/src/screens/Publications/components/Project/Project.stories.js
  packages/lib-content/src/screens/Publications/components/Publication/Publication.stories.js
  packages/lib-content/src/screens/Resources/Resources.stories.js
  packages/lib-content/src/screens/Volunteer/Volunteer.js
  packages/lib-content/src/screens/Volunteer/Volunteer.stories.js
  packages/lib-content/src/translations/en.json
Labels: enhancement, approved

#6220 Add middleware for redirects in app-root
  packages/app-root/src/middleware.js
Labels: enhancement, approved

#6206 Build the Get Involved > Volunteer page content
  packages/lib-content/src/screens/Volunteer/Volunteer.js
  packages/lib-content/src/translations/en.json
Labels: enhancement

#6207 Build the Get Involved > Donate page content
  packages/app-root/public/assets/donate-page.jpeg
  packages/lib-content/src/screens/Donate/Donate.js
  packages/lib-content/src/translations/en.json
Labels: enhancement

#6213 Build the Get Involved > Educate page
  packages/app-root/public/assets/educate-btn1.jpg
  packages/app-root/public/assets/educate-btn2.jpg
  packages/app-root/public/assets/educate-btn3.jpg
  packages/lib-content/src/components/Article/Article.js
  packages/lib-content/src/screens/Educate/Educate.js
  packages/lib-content/src/translations/en.json
Labels: enhancement

#6214 Build the Get Involved > Collaborate page
  packages/app-root/public/assets/collaborate/acls.png
  packages/app-root/public/assets/collaborate/brlib.png
  packages/app-root/public/assets/collaborate/coram.jpg
  packages/app-root/public/assets/collaborate/crick.png
  packages/app-root/public/assets/collaborate/dupage.jpg
  packages/app-root/public/assets/collaborate/google.png
  packages/app-root/public/assets/collaborate/gorongosa.png
  packages/app-root/public/assets/collaborate/imls.jpeg
  packages/app-root/public/assets/collaborate/lancaster.jpg
  packages/app-root/public/assets/collaborate/lpo.jpg
  packages/app-root/public/assets/collaborate/lpzoo.jpg
  packages/app-root/public/assets/collaborate/maxplanck.jpg
  packages/app-root/public/assets/collaborate/mio.jpg
  packages/app-root/public/assets/collaborate/nasa.png
  packages/app-root/public/assets/collaborate/neh.jpeg
  packages/app-root/public/assets/collaborate/nhm.jpeg
  packages/app-root/public/assets/collaborate/nih.png
  packages/app-root/public/assets/collaborate/nmk.jpg
  packages/app-root/public/assets/collaborate/noaa.png
  packages/app-root/public/assets/collaborate/nsf.jpg
  packages/app-root/public/assets/collaborate/nwu.jpg
  packages/app-root/public/assets/collaborate/saskatchawan.jpeg
  packages/app-root/public/assets/collaborate/simons.jpg
  packages/app-root/public/assets/collaborate/sloan-foundation.jpg
  packages/app-root/public/assets/collaborate/tsinghua.jpg
  packages/app-root/public/assets/collaborate/ukri.jpg
  packages/app-root/public/assets/collaborate/upenn.jpg
  packages/app-root/public/assets/collaborate/usfws.png
  packages/app-root/public/assets/collaborate/uts.jpg
  packages/lib-content/src/screens/Collaborate/Collaborate.js
  packages/lib-content/src/screens/Collaborate/Logos.js
  packages/lib-content/src/screens/Donate/Donate.js
  packages/lib-content/src/screens/Educate/Educate.js
  packages/lib-content/src/screens/Volunteer/Volunteer.js
  packages/lib-content/src/translations/en.json
Labels: enhancement

#6202 app-root, lib-user: Add search param validation for stats project_id, start_date, and end_date
  packages/app-root/src/app/groups/[groupId]/GroupStatsContainer.js
  packages/app-root/src/app/groups/[groupId]/page.js
  packages/app-root/src/app/users/[login]/stats/UserStatsContainer.js
  packages/app-root/src/app/users/[login]/stats/certificate/CertificateContainer.js
  packages/app-root/src/app/users/[login]/stats/certificate/page.js
  packages/app-root/src/app/users/[login]/stats/page.js
  packages/app-root/src/utils/validateDateRangeParams.js
  packages/app-root/src/utils/validateProjectIdParam.js
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/src/components/Certificate/Certificate.js
  packages/lib-user/src/components/Certificate/Certificate.stories.js
  packages/lib-user/src/components/Certificate/CertificateContainer.js
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/GroupStatsContainer.js
  packages/lib-user/src/components/UserStats/UserStats.js
  packages/lib-user/src/components/UserStats/UserStatsContainer.js
  packages/lib-user/src/components/shared/MainContent/MainContent.js
  packages/lib-user/src/components/shared/MainContent/MainContent.spec.js
  packages/lib-user/src/components/shared/MainContent/MainContent.stories.js
  packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.js
  packages/lib-user/src/components/shared/MainContent/helpers/getProjectSelectOptions.js
  packages/lib-user/src/components/shared/Select/Select.stories.js
Labels: approved

#6223 SubjectGroupComparison tool not allowing Annotating
  packages/lib-classifier/src/store/WorkflowStepStore/WorkflowStepStore.js
Labels: approved

#6222 Use relative paths for any links with /about or /get-involved or sharing groups
  packages/lib-content/src/screens/About/components/Contact.js
  packages/lib-content/src/screens/About/components/Highlights.js
  packages/lib-content/src/screens/Collaborate/Collaborate.js
  packages/lib-content/src/screens/Collaborate/Logos.js
  packages/lib-content/src/screens/FAQ/FAQ.js
  packages/lib-content/src/screens/Resources/Resources.js
  packages/lib-content/src/translations/en.json
  packages/lib-user/src/components/GroupStats/helpers/getHeaderItems.js
  packages/lib-user/src/components/UserHome/components/WelcomeModal/WelcomeModal.js
Labels: approved

#6221 Homepages: Revalidate wordpress fetch every hour
  packages/app-root/src/app/page.js
Labels: approved

#6226 app-root, lib-user: Remove stats date constraint
  packages/app-root/src/app/users/[login]/stats/certificate/CertificateContainer.js
  packages/lib-user/src/components/Certificate/Certificate.js
  packages/lib-user/src/components/Certificate/Certificate.stories.js
  packages/lib-user/src/components/Certificate/CertificateContainer.js
  packages/lib-user/src/components/shared/MainContent/MainContent.js
  packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.js
  packages/lib-user/src/components/shared/MainContent/helpers/getDateRangeSelectOptions.spec.js
  packages/lib-user/src/index.js
  packages/lib-user/src/utils/getStatsDateString.js
  packages/lib-user/src/utils/getStatsDateString.spec.js
  packages/lib-user/src/utils/index.js
Labels: approved

#6230 lib-user: Refactor UserStatsContainer to request user with created_at
  packages/lib-user/src/components/UserStats/UserStatsContainer.js
Labels: bug, approved

#6233 Signed-out homepage Hero video - autoplay only once screen size is detected
  packages/lib-content/src/screens/Home/DefaultHome/components/Hero.js
  packages/lib-react-components/src/hooks/Readme.md
Labels: bug, accessibility, approved

#6234 Upgrade to Next.js 14 and latest i18next
  packages/app-content-pages/package.json
  packages/app-content-pages/src/api/team/processTeamData.mock.json
  packages/app-content-pages/src/api/team/processTeamData.result.json
  packages/app-content-pages/src/screens/Publications/Publications.spec.js
  packages/app-content-pages/src/screens/Teams/Teams.spec.js
  packages/app-project/package.json
  packages/app-root/next.config.mjs
  packages/app-root/package.json
  packages/app-root/server/server.js
  packages/lib-content/package.json
  packages/lib-react-components/package.json
  yarn.lock
Labels: dependencies, approved

#6253 app-root: Refactor setting stats startDate param with router.replace
  packages/app-root/src/app/groups/[groupId]/GroupStatsContainer.js
  packages/app-root/src/app/users/[login]/stats/UserStatsContainer.js
  packages/app-root/src/app/users/[login]/stats/certificate/CertificateContainer.js
Labels: bug, approved

#6199 Add ADR 60: Enabling Aggregations (Caesar Reducers) on Workflows
  docs/arch/README.md
  docs/arch/adr-60.md
Labels: approved

#6228 lib-user: Add loading, empty, and error states to UserStats, MyGroups, Certificate, GroupStats, and Contributors
  packages/app-root/src/components/AuthenticatedUsersPageContainer.js
  packages/lib-user/src/components/Certificate/Certificate.js
  packages/lib-user/src/components/Certificate/CertificateContainer.js
  packages/lib-user/src/components/Contributors/Contributors.js
  packages/lib-user/src/components/GroupStats/GroupStats.js
  packages/lib-user/src/components/GroupStats/components/TopContributors/TopContributors.js
  packages/lib-user/src/components/MyGroups/MyGroups.js
  packages/lib-user/src/components/MyGroups/MyGroups.stories.js
  packages/lib-user/src/components/MyGroups/MyGroupsContainer.js
  packages/lib-user/src/components/UserStats/UserStats.js
  packages/lib-user/src/components/UserStats/UserStatsContainer.js
  packages/lib-user/src/components/shared/ContentBox/components/ContentLink.js
  packages/lib-user/src/components/shared/GroupContainer/GroupContainer.js
  packages/lib-user/src/components/shared/GroupContainer/helpers/getUserGroupStatus.js
  packages/lib-user/src/components/shared/GroupContainer/helpers/getUserGroupStatus.spec.js
  packages/lib-user/src/components/shared/MainContent/MainContent.js
  packages/lib-user/src/components/shared/TopProjects/TopProjects.js
  packages/lib-user/src/components/shared/TopProjects/TopProjects.stories.js
  packages/lib-user/src/hooks/usePanoptesMemberships.js
  packages/lib-user/src/hooks/usePanoptesProjects.js
  packages/lib-user/src/hooks/usePanoptesUser.js
  packages/lib-user/src/hooks/usePanoptesUserGroup.js
  packages/lib-user/src/hooks/useStats.js
  packages/lib-user/src/utils/fetchPanoptesUsers.js
Labels: approved
