Repository zooniverse/front-end-monorepo, pull requests merged in 2024-12, with the labels that each got.

#6512 lib-classifier: Fix survey task FilterStatus images not showing
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
Labels: bug, approved

#6524 app-project: Refactor useYourProjectStats fetchUserCreatedAt panoptes request
  packages/app-project/src/screens/ClassifyPage/components/YourProjectStats/useYourProjectStats.js
Labels: approved

#6511 VV - Implement Classifier Tool/Task
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/components/TaskInputLabel/TaskInputLabel.js
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/README.md
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/components/VolumetricTask.js
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/components/VolumetricTask.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/components/VolumetricTask.stories.js
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/index.js
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricAnnotation.js
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricTask.js
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricTask.spec.js
  packages/lib-classifier/src/plugins/tasks/index.js
  packages/lib-classifier/src/store/Project/Project.js
Labels: approved

#6510 Upgrade to styled-components v6
  package.json
  packages/app-project/.babelrc
  packages/app-project/package.json
  packages/app-project/src/helpers/theme/README.md
  packages/app-project/src/screens/ProjectHomePage/components/Hero/components/Background/Background.js
  packages/app-root/next.config.mjs
  packages/app-root/package.json
  packages/app-root/src/app/style-registry.js
  packages/lib-classifier/.babelrc
  packages/lib-classifier/package.json
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/DrawingToolMarks/DrawingToolMarks.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/PreviousMarks/PreviousMarks.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/TranscribedLines/TranscribedLines.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/ZoomEventLayer/ZoomEventLayer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SubjectGroupViewer/components/SGVGridCell/SGVGridCell.spec.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.js
  packages/lib-classifier/src/plugins/drawingTools/components/Mark/Mark.spec.js
  packages/lib-classifier/test/.mocharc.json
  packages/lib-content/package.json
  packages/lib-content/test/.mocharc.json
  packages/lib-react-components/package.json
  packages/lib-react-components/src/Markdownz/Markdownz.js
  packages/lib-react-components/src/Markdownz/Markdownz.stories.js
  packages/lib-react-components/src/Media/components/Text/Text.spec.js
  packages/lib-react-components/test/.mocharc.json
  packages/lib-subject-viewers/test/.mocharc.json
  packages/lib-user/.babelrc
  packages/lib-user/package.json
  packages/lib-user/test/.mocharc.json
  yarn.lock
Labels: approved

#6499 Classifier: Remove the faulty session id code
  packages/lib-classifier/src/store/utils/README.md
  packages/lib-classifier/src/store/utils/session.js
  packages/lib-classifier/src/store/utils/session.spec.js
Labels: approved

#6532 Classifier: Clean up TaskInput styling
  packages/lib-classifier/src/plugins/tasks/components/InputIcon/InputIcon.js
  packages/lib-classifier/src/plugins/tasks/components/InputStatus/InputStatus.js
  packages/lib-classifier/src/plugins/tasks/components/InputStatus/InputStatus.spec.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/TaskInput.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/TaskInput.stories.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/components/TaskInputLabel/TaskInputLabel.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/components/TaskInputLabel/TaskInputLabel.spec.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/helpers/doesTheLabelHaveAnImage.js
  packages/lib-classifier/src/plugins/tasks/components/TaskInput/helpers/index.js
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/components/VolumetricTask.js
Labels: refactor, approved

#6478 lib-classifier: Refactor survey task Choice and Questions styling
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userKeystrokes.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.stories.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/ConfusedWith/ConfusedWith.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/Questions/Questions.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/components/Questions/components/InputGroup/components/QuestionInput.js
  packages/lib-classifier/src/translations/en/plugins.json
Labels: approved

#6568 VV - Implement Classifier Annotation Model
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/SubjectViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VolumetricViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VolumetricViewer/VolumetricMockSubject.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VolumetricViewer/VolumetricViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VolumetricViewer/VolumetricViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/VolumetricViewer/VolumetricViewerWrapper.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getViewer/getViewer.js
  packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.js
  packages/lib-classifier/src/helpers/subjectViewers/subjectViewers.spec.js
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/components/VolumetricTask.js
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricAnnotation.js
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricTask.spec.js
  packages/lib-classifier/src/store/subjects/Subject/Subject.js
  packages/lib-subject-viewers/src/VolumetricViewer/VolumetricViewer.js
  packages/lib-subject-viewers/src/VolumetricViewer/models/ModelAnnotations.js
  packages/lib-subject-viewers/src/VolumetricViewer/tests/ModelAnnotations.spec.js
Labels: approved
