Repository zooniverse/front-end-monorepo, pull requests merged in 2024-10, with the labels that each got.

#6159 Classifier README updates
  packages/lib-classifier/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/README.md
  packages/lib-classifier/src/plugins/tasks/readme.md
  packages/lib-classifier/src/store/README.md
  packages/lib-classifier/src/store/feedback/README.md
Labels: documentation, approved

#6348 lib-user: Fix usePanoptesProjects request error return
  packages/lib-user/src/hooks/usePanoptesProjects.js
Labels: bug, approved

#6353 Add Google Tag Manager to app-root's layout
  packages/app-root/package.json
  packages/app-root/src/app/layout.js
Labels: approved

#6338 app-project: Add MastodonIcon and BlueSkyIcon
  packages/app-project/public/locales/en/components.json
  packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProject.mock.js
  packages/app-project/src/shared/components/ConnectWithProject/ConnectWithProjectContainer.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/components/BitbucketIcon.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/components/BitbucketIcon/index.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/components/BlueSkyIcon.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/components/MastodonIcon.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/components/WeiboIcon.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/components/WeiboIcon/index.js
  packages/app-project/src/shared/components/ConnectWithProject/components/ProjectLink/helpers/formatUrlObject/formatUrlObject.js
Labels: approved

#6352 app-root: add COMMIT_ID to head element
  packages/app-root/next.config.mjs
  packages/app-root/src/app/layout.js
Labels: approved

#6349 VV: Add VolumetricViewer to `lib-subject-viewers`
  packages/lib-subject-viewers/README.md
  packages/lib-subject-viewers/package.json
  packages/lib-subject-viewers/src/components/ProtoViewer/ProtoViewer.js
  packages/lib-subject-viewers/src/components/ProtoViewer/ProtoViewer.spec.js
  packages/lib-subject-viewers/src/components/ProtoViewer/ProtoViewer.stories.js
  packages/lib-subject-viewers/src/components/ProtoViewer/README.md
  packages/lib-subject-viewers/src/components/VolumetricViewer/README.md
  packages/lib-subject-viewers/src/components/VolumetricViewer/VolumetricViewer.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/components/AnnotationView.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/components/ComponentViewer.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/components/Config.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/components/Cube.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/components/Histogram.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/components/InputRange.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/components/InputRangeDual.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/components/Plane.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/css/globals.css
  packages/lib-subject-viewers/src/components/VolumetricViewer/data/4x4x4.json
  packages/lib-subject-viewers/src/components/VolumetricViewer/helpers/AlgorithmAStar.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/helpers/SortedSet.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/helpers/pointColor.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/models/ModelAnnotations.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/models/ModelTool.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/models/ModelViewer.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/tests/AlgorithmAStar.spec.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/tests/ModelAnnotations.spec.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/tests/ModelTool.spec.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/tests/ModelViewer.spec.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/tests/SortedSet.spec.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/tests/VolumetricViewer.spec.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/tests/VolumetricViewer.stories.js
  packages/lib-subject-viewers/src/components/VolumetricViewer/tests/pointColor.spec.js
  packages/lib-subject-viewers/src/index.js
  yarn.lock
Labels: approved

#6364 Add cache purging to staging deploy
  .github/workflows/deploy_staging.yml
Labels: approved

#6365 Add cache purge step to production deploy
  .github/workflows/deploy_production.yml
Labels: approved

#6388 Remove SENTRY_CONTENT_APP
  .github/workflows/sentry-production-releases.yml
  .github/workflows/sentry-staging-releases.yml
Labels: approved

#6356 Remove set-cache-headers from app-project
  kubernetes/deployment-branch.tmpl
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
  packages/app-project/server/server.js
  packages/app-project/server/set-cache-headers.js
  packages/app-project/server/set-cache-headers.spec.js
Labels: ops, approved

#6371 lib-user: Fix MembersList paginationProps property assignment
  packages/lib-user/src/components/GroupStats/components/MembersList/MembersListContainer.js
  packages/lib-user/src/hooks/usePanoptesMemberships.js
Labels: bug, approved

#6387 Migrate Sentry packages to v8
  packages/app-project/instrumentation.js
  packages/app-project/next.config.js
  packages/app-project/package.json
  packages/app-project/pages/_document.js
  packages/app-project/sentry.client.config.js
  packages/app-project/sentry.server.config.js
  packages/app-project/server/server.js
  packages/lib-classifier/package.json
  yarn.lock
Labels: dependencies, approved

#6397 Refactor homepage recent projects to use ERAS
  packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjects.js
  packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjectsContainer.js
  packages/lib-user/src/components/shared/ContentBox/components/ContentLink.js
Labels: refactor, approved

#6396 Upgrade Grommet to v2.41.0
  packages/app-project/package.json
  packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js
  packages/app-root/package.json
  packages/lib-classifier/package.json
  packages/lib-content/src/screens/About/components/HowItWorks.js
  packages/lib-content/src/screens/Donate/Donate.js
  packages/lib-content/src/screens/Home/DefaultHome/components/Hero.js
  packages/lib-content/src/screens/Home/DefaultHome/components/Researchers.js
  packages/lib-content/src/screens/Volunteer/Volunteer.js
  packages/lib-react-components/package.json
  packages/lib-react-components/src/ZooFooter/components/LogoAndTagline/LogoAndTagline.js
  packages/lib-react-components/src/ZooHeader/ZooHeader.js
  packages/lib-react-components/src/ZooHeader/components/NavListItem/NavListItem.js
  packages/lib-react-components/src/ZooHeader/components/UserNavigation/UserNavigation.js
  yarn.lock
Labels: dependencies, approved

#6409 Revert: Refactor homepage recent projects to use ERAS
  packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjects.js
  packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjectsContainer.js
Labels: approved
