Repository zooniverse/front-end-monorepo, pull requests merged in 2025-04, with the labels that each got.

#6752 Classifier: Open new tab on Done & Talk button and cleanup TaskNavButtons
  packages/lib-classifier/src/components/Classifier/Classifier.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskHelp/TaskHelp.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.stories.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/BackButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/BackButton/theme.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneButton/DoneButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptions.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptionsConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptionsConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptionsContainer.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/ExpertOptionsContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/DemoModeToggle.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/DemoModeToggle.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/DemoModeToggleConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/ExpertOptions/components/DemoModeToggle/DemoModeToggleConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/NextButtonConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/NextButton/theme.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/mocks/mockWorkflow.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
  packages/lib-classifier/src/store/subjects/Subject/Subject.js
  packages/lib-classifier/src/store/subjects/Subject/Subject.spec.js
  packages/lib-classifier/src/translations/en/components.json
Labels: enhancement, refactor, approved

#6812 Update the VV annotation to only send active and connected points.
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/README.md
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricAnnotation.js
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricTask.spec.js
  packages/lib-subject-viewers/src/VolumetricViewer/components/Plane.js
  packages/lib-subject-viewers/src/VolumetricViewer/models/ModelAnnotations.js
  packages/lib-subject-viewers/src/VolumetricViewer/tests/ModelAnnotations.spec.js
Labels: approved

#6811 Fix LineControls bug with zoom refactor
  packages/lib-classifier/src/plugins/drawingTools/experimental/components/LineControls/LineControls.js
Labels: approved

#6805 lib-classifier: Add scroll to zoom overlay message to SingleImageViewer
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/components/ZoomHelperOverlay.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/components/ZoomHelperOverlay.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/components/ZoomHelperOverlay.stories.js
  packages/lib-classifier/src/translations/en/components.json
Labels: approved

#6819 Change the Done & Talk button to a new-tab link with no context menu
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/TaskNavButtons.spec.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButton.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.js
  packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/TaskNavButtons/components/DoneAndTalkButton/DoneAndTalkButtonConnector.spec.js
  packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.userClicks.spec.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.js
  packages/lib-classifier/src/store/SubjectStore/SubjectStore.spec.js
  packages/lib-classifier/src/store/subjects/Subject/Subject.js
Labels: bug, approved

#6753 lib-user: Refactor group stats data export
  packages/lib-user/src/components/Contributors/Contributors.js
  packages/lib-user/src/components/Contributors/components/ExportStats/ExportStats.js
  packages/lib-user/src/components/Contributors/components/ExportStats/ExportStats.spec.js
  packages/lib-user/src/components/Contributors/components/ExportStats/ExportStats.stories.js
  packages/lib-user/src/components/Contributors/components/ExportStats/ExportStatsContainer.js
  packages/lib-user/src/components/Contributors/components/ExportStats/index.js
  packages/lib-user/src/components/Contributors/helpers/generateExport.js
  packages/lib-user/src/components/Contributors/helpers/generateExport.spec.js
  packages/lib-user/src/components/Contributors/helpers/generateExport.worker.js
  packages/lib-user/src/components/Contributors/helpers/getAllUsers.js
  packages/lib-user/src/components/Contributors/helpers/getAllUsers.spec.js
  packages/lib-user/src/components/Contributors/helpers/handleGenerateExport.js
  packages/lib-user/src/translations/en.json
Labels: approved

#6800 Remove pluralization names in lib-content translation keys
  packages/lib-content/src/components/Stats/Stats.js
  packages/lib-content/src/screens/About/About.js
  packages/lib-content/src/screens/About/components/Contact.js
  packages/lib-content/src/screens/About/components/Highlights.js
  packages/lib-content/src/screens/About/components/HowItWorks.js
  packages/lib-content/src/screens/About/components/OurMission.js
  packages/lib-content/src/screens/Collaborate/Collaborate.js
  packages/lib-content/src/screens/Donate/Donate.js
  packages/lib-content/src/screens/Educate/Educate.js
  packages/lib-content/src/screens/Home/DefaultHome/DefaultHome.js
  packages/lib-content/src/screens/Home/DefaultHome/components/Introduction.js
  packages/lib-content/src/screens/Home/DefaultHome/components/Researchers.js
  packages/lib-content/src/screens/Resources/Resources.js
  packages/lib-content/src/screens/Volunteer/Volunteer.js
  packages/lib-content/src/translations/en.json
  packages/lib-content/src/translations/test.json
Labels: approved, translations

#6816 Create an All Projects page for user groups
  packages/app-root/src/app/groups/[groupId]/projects/GroupAllProjectsContainer.js
  packages/app-root/src/app/groups/[groupId]/projects/page.js
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/src/components/GroupAllProjects/GroupAllProjects.js
  packages/lib-user/src/components/GroupAllProjects/GroupAllProjectsContainer.js
  packages/lib-user/src/components/GroupAllProjects/index.js
  packages/lib-user/src/components/index.js
  packages/lib-user/src/components/shared/AllProjects/AllProjects.js
  packages/lib-user/src/components/shared/AllProjects/AllProjects.stories.js
  packages/lib-user/src/components/shared/AllProjects/index.js
  packages/lib-user/src/components/shared/index.js
  packages/lib-user/src/index.js
  packages/lib-user/src/translations/en.json
Labels: approved

#6822 lib-classifier: Refactor VisXZoom onFirstScroll and hasScrolledRef per initial CTRL + scroll event
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js
Labels: bug, approved

#6830 lib-content: Fix aria-label in Sidebar in OurTeam and Publications
  packages/lib-content/src/screens/About/About.js
  packages/lib-content/src/screens/OurTeam/OurTeam.js
  packages/lib-content/src/screens/OurTeam/OurTeam.spec.js
  packages/lib-content/src/screens/Publications/Publications.js
  packages/lib-content/src/screens/Publications/Publications.spec.js
Labels: accessibility, approved

#6836 lib-user: Refactor lists with a11y name, tabindex, and scroll-snap
  packages/lib-user/src/components/Contributors/components/ContributorsList/ContributorsList.js
  packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjects.js
  packages/lib-user/src/components/UserHome/components/RecentSubjects/RecentSubjects.js
  packages/lib-user/src/components/shared/ContentBox/ContentBox.js
  packages/lib-user/src/components/shared/ContentBox/components/ContentHeading.js
  packages/lib-user/src/components/shared/TopProjects/TopProjects.js
  packages/lib-user/src/translations/en.json
Labels: approved

#6827 build(deps): bump superagent from v8 to v10
  package.json
  packages/app-root/next.config.mjs
  packages/lib-panoptes-js/package.json
  yarn.lock
Labels: security

#6838 lib-user: Build Pagination in All Projects sorted by classification count
  packages/app-root/src/app/users/[login]/stats/projects/AllProjectsContainer.js
  packages/app-root/src/app/users/[login]/stats/projects/page.js
  packages/lib-user/.storybook/main.js
  packages/lib-user/.storybook/preview.js
  packages/lib-user/dev/components/App/App.js
  packages/lib-user/package.json
  packages/lib-user/src/components/GroupAllProjects/GroupAllProjects.js
  packages/lib-user/src/components/UserHome/components/Dashboard/components/StatsTabs/StatsTabsContainer.js
  packages/lib-user/src/components/UserStatsAllProjects/UserStatsAllProjects.js
  packages/lib-user/src/components/UserStatsAllProjects/index.js
  packages/lib-user/src/components/index.js
  packages/lib-user/src/components/shared/AllProjects/AllProjects.js
  packages/lib-user/src/components/shared/AllProjects/AllProjects.mocks.js
  packages/lib-user/src/components/shared/AllProjects/AllProjects.stories.js
  packages/lib-user/src/components/shared/AllProjects/AllProjectsByCount/AllProjectsByCount.js
  packages/lib-user/src/components/shared/AllProjects/AllProjectsByCount/AllProjectsByCount.stories.js
  packages/lib-user/src/components/shared/AllProjects/AllProjectsByCount/index.js
  packages/lib-user/src/components/shared/AllProjects/Projects/Projects.js
  packages/lib-user/src/components/shared/AllProjects/Projects/Projects.spec.js
  packages/lib-user/src/components/shared/AllProjects/README.md
  packages/lib-user/src/components/shared/index.js
  packages/lib-user/src/hooks/usePanoptesProjects.js
  packages/lib-user/src/index.js
  packages/lib-user/src/translations/en.json
  packages/lib-user/storybook-public/mockServiceWorker.js
Labels: approved

#6813 Convert AuthenticationInvitation components from enzyme to RTL
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationConnector.spec.js
  packages/app-project/src/components/Announcements/components/AuthenticationInvitation/AuthenticationInvitationContainer.spec.js
Labels: approved, tests

#6864 lib-classifier: Use a Grid for subject viewer container in CenteredLayout
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
Labels: bug, approved

#6860 lib-user: Refactor horizontal lists scroll-snap-align to start
  packages/lib-user/src/components/Contributors/components/ContributorsList/ContributorsList.js
  packages/lib-user/src/components/UserHome/components/RecentProjects/RecentProjects.js
  packages/lib-user/src/components/UserHome/components/RecentSubjects/RecentSubjects.js
  packages/lib-user/src/components/shared/TopProjects/TopProjects.js
Labels: approved
