Repository zooniverse/front-end-monorepo, pull requests merged in 2025-03, with the labels that each got.

#6721 Project Team Page: remove manual reverse of teamArray
  packages/app-project/pages/[panoptesEnv]/[owner]/[project]/about/team.js
Labels: approved

#6734 lib-classifier: adjust spacing around survey filter button
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/Chooser.js
  packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js
Labels: approved, ui

#6733 app-project: Edit revalidate options in useYourProjectStats
  packages/app-project/src/screens/ClassifyPage/components/YourProjectStats/useYourProjectStats.js
Labels: bug, approved

#6655 Separate default video viewer from custom controls and improve accessibility
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoController/VideoController.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoController/VideoController.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoController/theme.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoViewer/VideoViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoWithDrawing/VideoWithDrawing.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/helpers/getFixedNumber/README.md
  packages/lib-classifier/src/helpers/formatTimeStamp/README.md
  packages/lib-classifier/src/helpers/formatTimeStamp/formatTimeStamp.js
Labels: accessibility, refactor, approved, video subject

#6709 Finish styles for Volumetric Viewer
  packages/lib-subject-viewers/src/VolumetricViewer/components/ComponentViewer.js
  packages/lib-subject-viewers/src/VolumetricViewer/components/Cube.js
  packages/lib-subject-viewers/src/VolumetricViewer/components/MarkButtons.js
  packages/lib-subject-viewers/src/VolumetricViewer/components/Plane.js
  packages/lib-subject-viewers/src/VolumetricViewer/components/Slider.js
Labels: approved

#6668 Persist video volume + playback speed between classifications
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/SingleVideoViewerContainer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleVideoViewer/components/VideoWithDrawing/VideoWithDrawing.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.spec.js
Labels: enhancement, approved, video subject

#6390 lib-classifier: refactor single image viewer with VisXZoom
  packages/lib-classifier/src/components/Classifier/Classifier.spec.js
  packages/lib-classifier/src/components/Classifier/components/ImageToolbar/ImageToolbar.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/CenteredLayout/CenteredLayout.spec.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/MaxWidth/MaxWidth.spec.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/NoMaxWidth/NoMaxWidth.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/DataImageViewer/DataImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/FlipbookViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/FlipbookViewer/README.md
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ImageAndTextViewer/ImageAndTextViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/MultiFrameViewer/MultiFrameViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/SVGPanZoom.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/SVGPanZoom/index.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/ZoomEventLayer/ZoomEventLayer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/SeparateFramesViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SeparateFramesViewer/components/SeparateFrame/SeparateFrame.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageCanvas.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageCanvas.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerConnector.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/components/PlaceholderSVG.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/components/PlaceholderSVG.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/components/PlaceholderSVG.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/index.js
  packages/lib-classifier/src/hooks/useKeyZoom.js
  packages/lib-classifier/src/hooks/useKeyZoom.spec.js
  packages/lib-classifier/src/hooks/useSubjectImage.js
  packages/lib-classifier/src/store/SubjectViewerStore/SubjectViewerStore.js
Labels: approved

#6741 Create Volumetric Layout
  packages/lib-classifier/src/components/Classifier/components/Layout/Layout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/Volumetric/VolumetricLayout.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/Volumetric/VolumetricLayout.stories.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/Volumetric/index.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/index.js
  packages/lib-classifier/src/components/Classifier/components/MetaTools/MetaTools.js
  packages/lib-subject-viewers/src/VolumetricViewer/components/ComponentViewer.js
Labels: approved

#6750 lib-user: Refactor usePanoptesUserGroup for signed-out user access to public group
  packages/lib-user/src/hooks/usePanoptesProjects.js
  packages/lib-user/src/hooks/usePanoptesUserGroup.js
  packages/lib-user/src/hooks/useStats.js
Labels: bug, approved

#6755 Filter Volumetric Project Research Team to only show the Project Owner.
  packages/app-project/pages/[panoptesEnv]/[owner]/[project]/about/team.js
Labels: approved

#6773 Edit GitHub Actions workflow ymls to node v20.18 with .nvmrc
  .github/workflows/ci-build.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy_storybook.yml
  .nvmrc
  package.json
  packages/app-project/package.json
  packages/app-root/package.json
  packages/lib-async-states/package.json
  packages/lib-classifier/package.json
  packages/lib-content/package.json
  packages/lib-grommet-theme/package.json
  packages/lib-panoptes-js/package.json
  packages/lib-react-components/package.json
  packages/lib-subject-viewers/package.json
  packages/lib-user/package.json
Labels: approved, github_actions

#6776 Pin Docker image to node version 20.18
  Dockerfile
Labels: approved

#6761 Classifier: Use container queries for various layouts of the field guide button
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideConnector.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideConnector.spec.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideWrapper.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.js
  packages/lib-classifier/src/components/Classifier/components/FieldGuide/components/FieldGuideButton/FieldGuideButton.spec.js
  packages/lib-classifier/src/components/Classifier/components/Layout/components/Volumetric/VolumetricLayout.js
Labels: refactor, approved

#6775 fix(lib-classifier): SingleImageViewer stories
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.spec.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.stories.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/constants.js
Labels: storybook, approved

#6781 lib-classifier: Refactor SingleImageViewer and VisXZoom back to component props
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js
  packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js
Labels: approved

#6794 Security: update Node.JS to v14.2.26
  packages/app-project/package.json
  packages/app-root/package.json
  packages/lib-content/package.json
  packages/lib-user/package.json
  yarn.lock
Labels: approved

#6743 About pages and Get Involved pages minor adjustments
  packages/lib-content/src/components/Mobile/Mobile.js
  packages/lib-content/src/components/PageLayout/AboutLayout.js
  packages/lib-content/src/components/PageLayout/GetInvolvedLayout.js
  packages/lib-content/src/screens/About/components/Contact.js
  packages/lib-content/src/screens/About/components/Highlights.js
  packages/lib-content/src/screens/About/components/OurMission.js
  packages/lib-content/src/screens/Collaborate/Logos.js
  packages/lib-content/src/screens/Educate/Educate.js
  packages/lib-content/src/screens/OurTeam/components/Person/Person.js
  packages/lib-content/src/screens/Publications/Publications.js
  packages/lib-content/src/screens/Resources/Resources.js
  packages/lib-content/src/screens/Volunteer/Volunteer.js
  packages/lib-content/src/translations/en.json
  packages/lib-user/src/components/UserHome/components/Dashboard/components/DashboardLink.js
  packages/lib-user/src/translations/en.json
Labels: approved

#6754 Remove unused dependencies from VV.
  packages/lib-subject-viewers/package.json
  yarn.lock
Labels: approved

#6799 Tutorial: fix navigation breaking when too many steps
  packages/lib-classifier/src/components/Classifier/components/shared/StepNavigation/StepNavigation.js
Labels: approved

#6769 VV: fix bug that limits the max number of marks.
  packages/lib-subject-viewers/src/VolumetricViewer/helpers/pointColor.js
  packages/lib-subject-viewers/src/VolumetricViewer/tests/pointColor.spec.js
Labels: approved

#6801 Implement ARIA recommendation for the Accordion pattern for the VV Planes view
  packages/lib-subject-viewers/src/VolumetricViewer/components/Plane.js
Labels: approved

#6803 Fix bug where the VV planar view wouldn't show an annotation if the histogram had removed its underlying color's voxel
  packages/lib-subject-viewers/src/VolumetricViewer/components/Plane.js
Labels: approved

#6802 Update VV classification export to match the FreehandLine tool
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/README.md
  packages/lib-classifier/src/plugins/tasks/experimental/volumetric/models/VolumetricAnnotation.js
  packages/lib-subject-viewers/src/VolumetricViewer/models/ModelAnnotations.js
  packages/lib-subject-viewers/src/VolumetricViewer/tests/ModelAnnotations.spec.js
Labels: approved
